### ISSUE TITLE
Support audio panning

### ISSUE THREAD

**Issue by adinapoli** [jwplayer/jwplayer#100]
Hello folks,

first of all thanks for all the hard work on this fantastic player.

Me and my company are commercial users of JWPlayer, and as part of our core business, we have the need of panning the audio of a video (by panning I mean, obviously, the ability to adjust the levels of the right and left audio channels, mute the left, mute the right, etc). There is a "hack" going around in internet which expose two new API calls to the flash version of the player, as described here:

http://www.kokozo.net/jwplayer_pannable/

The API change seems to be minimal.
Do you think you could start from this as a base and provide audio panning for RTMP videos?

A fantastic bonus would be also to allow skinning of the player exposing two new "ouleft" for adjusting the panning directly from the player.

As regards the mobile world, since the WebAudio API is still not yet so richful, even a partial solution would be better than nothing. As inspiration you could take a look at this plugin for video.js:

https://github.com/cladera/videojs-stereopanner

It doesn't work on mobile, but it seems to leverage a full-html5 API :)

Thanks in advance!
Alfredo

**Comment by robwalch** [comment]
The solution here was to create a custom Flash provider based on or SDK docs and the Video or RTMPMediaProvider classes in our open source project:

https://github.com/jwplayer/jwplayer-sdks/

https://github.com/jwplayer/jwplayer/blob/master/src/flash/com/longtailvideo/jwplayer/media/VideoMediaProvider.as

We don't provide a way to add custom methods to our API. ExternalInterface will allow you to add methods to the swf which you can call directly in JavaScript.

Please refer to Adobe's ActionScript docs for more info on ExternalInterface:

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/external/ExternalInterface.html


So in Flash:

```ActionScript
ExternalInterface.addCallback("pan", panFromJs); 

private function panFromJs(panValue:Number):void {
  // pan the soundTransform and apply it back to media.soundTransform
}
```

From javascript:

```javascript
var swf = jwplayer().getContainer().getElementsByTagName('object')[0];
swf.pan(-1);
```

If you want to go the extra mile you could add pan to the player instance `jwplayer().pan = swf.pan`.

If you're interested in how we wrap ExternalInterface in jw7, have a look at how we use SwfEventRouter in the open source project.


From ActionScript:
```ActionScript
SwfEventRouter.on('pan', panFromJs);
```

From javascript:

```javascript
var swf = jwplayer().getContainer().getElementsByTagName('object')[0];
swf.triggerFLash('pan', -1);
```
