### ISSUE TITLE
Flash HLS provider does not set state to "buffering" with discontinuity in stream

### ISSUE THREAD

**Issue by shaharmor** [jwplayer/jwplayer#1001]
Hi,

Not sure if its a bug or a feature, but when the player is buffering when there is DVR enabled the spinning wheel won't show, and the playback would just "pause".

You can test it in the following links by using the Chrome network panel in the dev-tools to mimic a slow connection

With DVR:
http://demo.jwplayer.com/stream-tester/?config=%7Bfile%3A%20%22https%3A%2F%2Flivestream.peer5.com%2Fvideo%2Fkite%2Findex.m3u8%22%2Cwidth%3A%20%22580%22%2Cheight%3A%20%22370%22%2Cprimary%3A%20%22flash%22%2Candroidhls%3Atrue%7D

Without DVR:
http://demo.jwplayer.com/stream-tester/?config=%7Bfile%3A%20%22http%3A%2F%2Fwowza.peer5.com%2Flive%2Fsmil%3Aclock.smil%2Fplaylist.m3u8%22%2Cwidth%3A%20%22580%22%2Cheight%3A%20%22370%22%2Cprimary%3A%20%22flash%22%2Candroidhls%3Atrue%7D

**Comment by robwalch** [comment]
Yep. That's a bug. The player state does not change to "buffering" in DVR mode when the stream is under-buffered.

**Comment by robwalch** [comment]
Looking into it, it doesn't have anything to do with DVR streams as a whole. This particular stream has discontinuities, which introduce a side effect where the streaming engine sets a seeking flag that prevents a buffering event from being sent when under-buffering is detected.

**Comment by shaharmor** [comment]
Btw i think it also happens with the html5 player, but didn't verify

**Comment by robwalch** [comment]
We don't have any code to detect under-buffered state in html5 - for example compare currentTime to video.buffered TimeRanges. The video tag "stalled" and "waiting" events historically have proved useless for this purpose so we don't use them.

**Comment by shaharmor** [comment]
Got it. Did you check streams without doscontinuity? Im not near a computer

**Comment by robwalch** [comment]
Yeah that was the first thing I did. Then I pulled up your stream and did a little AS3 debugging. It a flag that gets set when appending bytes at the point of discontinuity - it's meant to prevent the spinning wheel from showing up because the buffer get's cleared. The flag never gets reset however.

**Comment by shaharmor** [comment]
Hey @robwalch, any update on this?

**Comment by robwalch** [comment]
Priority on this is low because it's Flash HLS playback for a small subset of streams. No updates on when we might fix. We're focusing our efforts on JS HLS playback.

**Comment by mkozlov1** [comment]
@robwalch 
>We're focusing our efforts on JS HLS playback.

when do you plan to release for testing this feature?

**Comment by robwalch** [comment]
Default HLS HLTML5 has been out since v7.8.1. Discontinuity support should be solid in v7.10 when you're stream implements it properly. Let us know if you still have any issues.
