### ISSUE TITLE
HLS support on Firefox (43.0.4)

### ISSUE THREAD

**Issue by mihai** [jwplayer/jwplayer#1008]
I've been testing the player (v7.2.4) on the latest version of Firefox (43.0.4) and for HLS video sources it doesn't work, shows the error: `Error loading player: No playable sources found`, probably because it tries to use Flash (which ~~doesn't come with Firefox any longer~~ [Firefox blocks](https://twitter.com/MarkSchmidty/status/620783674561327104)). However, setting the `primary` to `html5` in the configuration ([demo page example](http://demo.jwplayer.com/stream-tester/?config={file%3A%20%22https%3A%2F%2Fplayertest.longtailvideo.com%2Fadaptive%2Fbbbfull%2Fbbbfull.m3u8%22%2Cwidth%3A%20%22580%22%2Cheight%3A%20%22370%22%2Cprimary%3A%20%22html5%22})) still doesn't work.

**Comment by mattcoz** [comment]
Flash has never come with Firefox, and Firefox doesn't support HLS in HTML5.

**Comment by mihai** [comment]
Thanks for the clarification @mattcoz
 
> Flash has never come with Firefox

Unfortunate choice of words on my side, I meant it is blocked in Firefox -- updated the description.

> and Firefox doesn't support HLS in HTML5.

Good point, for future reference [Bug 577084](https://bugzilla.mozilla.org/show_bug.cgi?id=577084) tracks that, and [this page](http://www.jwplayer.com/html5/hls/) lists the browser support for HLS.

What would have helped is the player having a more meaningful error message than `No playable sources found`, like `browser not supported`.

**Comment by mattcoz** [comment]
The current version of Flash is not blocked, that post was from 6 months ago.
