### ISSUE TITLE
More robust error objects

### ISSUE THREAD

**Issue by deltafactory** [jwplayer/jwplayer#1027]
When catching the error event, it would be great to see more detail about the reason. For example, 4xx error, unsupported media, etc. This would allow for more customized error handling experiences.

The HTML5 provider logs some of these details to the console which only helps during development.

**Comment by robwalch** [comment]
We'd like to do an overhaul of errors in the player. Errors should include a code, message, the original Error or Exception object if present.

Are there any specific examples or modules that you need more detail from? I'm not sure if your examples refer to setup errors or errors from the media provider, but I'm guessing the latter:

https://github.com/jwplayer/jwplayer/blob/master/src/js/controller/setup-steps.js#L152

https://github.com/jwplayer/jwplayer/blob/master/src/js/providers/html5.js#L356

**Comment by deltafactory** [comment]
I was thinking in terms of the latter, media provider errors. The second link is exactly what I was looking at.

**Comment by deltafactory** [comment]
Curious to know if there's been any work on this. I don't see anything new in source. Would you accept pull requests as I find relevant code?

**Comment by johnBartos** [comment]
@deltafactory Of course! We have our own ideas on what we want our error objects to look like but we always welcome PRs

**Comment by deltafactory** [comment]
Looking mainly at the html5.js provider, exposing the HTML5 error object as evt.nativeError would let developers handle the variety of cases and still allow you to create a normalized error object alongside the evt.message.

Along with that, it would be great to optionally intercept the standard player "reaction" for customization purposes.

As originally proposed, I'm thinking along the lines of detecting HTTP 403 errors ("Session expired: please log in." or auto-refresh an expired URL), stream interruptions ("Please wait ... reconnecting"), etc.

I'm at the early stages of learning what's actually reported by the media elements and might be too optimistic about what information is available.

**Comment by robwalch** [comment]
This has been implemented in v8.4. Errors now all have an error `code` and `sourceError` property. Documentation https://developer.jwplayer.com/jw-player/docs/developer-guide/api/errors-reference/
