### ISSUE TITLE
Add JSON mime to Accept: header in Related plugin

### ISSUE THREAD

**Issue by deltafactory** [jwplayer/jwplayer#1028]
Following new JSON playlist support for the related plugin, please consider adding it to the Accept header of the AJAX request.

**Comment by robwalch** [comment]
Do you have an example of where this is a problem? Our playlist loader and ajax util are naive in that they don't know the type of data being loaded. It means we need to load plain text or let ajax try to parse the result as xml first, but it handles all cases without trying to guess based on file extension.

**Comment by deltafactory** [comment]
No problem that I'm aware of. Feel free to close.
