### ISSUE TITLE
RTMP (flash) through file://some_file.html crashes the flash player

### ISSUE THREAD

**Issue by eigilsagafos** [jwplayer/jwplayer#1030]
I get a `Flash plugin failed to load` error when trying to use JW Player from a local html file in Chrome on a mac. I have set the `flashplayer` option to `http://ssl.p.jwpcdn.com/player/v/7.2.4/jwplayer.flash.swf`, so there are no network or console errors.

If I serve the same file through a local webserver everything works fine. Flowplayer works fine on both file:// and http://.

**Comment by robwalch** [comment]
We don't support local playback using the file protocol.

**Comment by eigilsagafos** [comment]
It's not the video file that is hosted on file:// just the html file. The file below works if i access it through `http://localhost/index.html`, when i open the file in the browser `file://path/to/index.html` i get the flash error. Playing videos that don't require flash works fine.

I'm trying to use JW player in an electron environment, where the url scheme will always be based on file://.

```html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://content.jwplatform.com/libraries/vEHv1DZn.js"></script>
  </head>
  <body>
    <div id="player"></div>
    <script>
      var playerInstance = jwplayer("player");
      playerInstance.setup({
        file: "rtmp://example.org/live/stream.flv",
        flashplayer: "http://ssl.p.jwpcdn.com/player/v/7.2.4/jwplayer.flash.swf",
        rtmp: {
            bufferlength: 0.1
        }
      });
    </script>
  </body>
</html>
```
