### ISSUE TITLE
Support HLS metadata in Microsoft Edge

### ISSUE THREAD

**Issue by IsaacSchemm** [jwplayer/jwplayer#1037]
EdgeHTML (not including the launch version 12.10240, but including the current version 13.10586) supports HLS metadata, but the format is different than in Safari. On my repository I have a branch (https://github.com/IsaacSchemm/jwplayer/commit/a03faeb01b5dd1e1d27d148170e83b96b17e6a6f) that adds code into JW Player to convert the Edge format to Safari's format before doing further processing.

Let me know if you want me to make a pull request, but do note that I've only tested this with my own streams so far.

Here are a couple of examples of the data Edge exposes through the ArrayBuffer - a number in parentheses means that hex code appears instead of a printable character:
ID3(4)(0)(0)(0)(0)(0)(30)TIT2(0)(0)(0)(20)(0)(0)(3)some ID3 meta data(0)
ID3(4)(0)(0)(0)(0)(0)(16)TIT2(0)(0)(0)(6)(0)(0)(3)test(0)

Also note that I've assumed UTF-8 - this may not always be the case.

**Comment by robwalch** [comment]
Thanks @IsaacSchemm,

Really we'd like to get Microsoft Edge to implement an extension of DataCues of ID3 metadata the way WebKit has for ID3 data; a WebKitDataCue with type: "org.id3" and a value object containing the ID3 key and data fields. It looks like they've stopped at implementing the DataCue interface https://www.w3.org/html/wg/drafts/html/master/semantics.html#datacue and I haven't found a ID3Cue extension spec.

Thanks for the reference to the commit. It would great if you could submit this as a PR.
