### ISSUE TITLE
Support HLS redundant streams

### ISSUE THREAD

**Issue by konradpietrzkiewicz** [jwplayer/jwplayer#1040]
Hi,

This topic was mentioned several times on support.jwplayer.com. 
One of the support cases: https://support.jwplayer.com/customer/en/portal/questions/16135688-hls-primary-and-backup-bitrates-show-up-in-selection-list

The issue is JW don't support redundant stream info and duplicates HLS labels. What is more it is not supporting automatic switching to backup when primary source will break.

You can check this stream:
http://vgtvlive-f.akamaihd.net/i/20130514x64502_01@28597/master.m3u8 

jw stream tester page: 
http://demo.jwplayer.com/stream-tester/?config=%7Bfile%3A%20"http%3A%2F%2Fvgtvlive-f.akamaihd.net%2Fi%2F20130514x64502_01%4028597%2Fmaster.m3u8%20"%2Cwidth%3A%20"580"%2Cheight%3A%20"370"%2Cprimary%3A%20"flash"%2Candroidhls%3Atrue%7D

On this event primary encoder broke and we stream the rest of the event on backup encoder. You can check that duration of video changes when you switch bitrates and how player behaves on seeking e.g.:

![image](https://cloud.githubusercontent.com/assets/1742524/12711501/cf19ace0-c8c0-11e5-9801-494d7868a705.png)

Example stream with JW player 7 and Akamai live stream contains  redundant stream (which contains not broken streams on all the duration of video):
http://demo.jwplayer.com/stream-tester/?config=%7Bfile%3A%20"http%3A%2F%2Faftonbladetlive-lh.akamaihd.net%2Fi%2Flivestream01_1%40182509%2Fmaster.m3u8"%2Cwidth%3A%20"580"%2Cheight%3A%20"370"%2Cprimary%3A%20"flash"%2Candroidhls%3Atrue%7D

hls live url: http://aftonbladetlive-lh.akamaihd.net/i/livestream01_1@182509/master.m3u8

**Comment by robwalch** [comment]
Hi @konradpietrzkiewicz,

Thanks for the example. We'll take a look. This is a good candidate to add to our list of enhancements for live stream support.

**Comment by robwalch** [comment]
**Update:**

In 7.4, in "Caterpillar" our HLS js provider (not in Flash), redundant streams are filtered. Redundancy in manifest requests will be implemented in 7.5.

I haven't yet looked into why there are issues with the position and duration in Flash. This stream appears to switch and seek correctly using Caterpillar.

**Comment by johnBartos** [comment]
Supported in 7.5.0!

**Comment by citosid** [comment]
@johnBartos we have a commercial version of JW Player, we have version 7.6.1, and we are seeing the quality selector duplicated in SWF.

![screen shot 2016-10-11 at 1 35 08 pm](https://cloud.githubusercontent.com/assets/201430/19281285/8fba32d6-8fb7-11e6-93a5-db5d6b4b4094.png)

Is this working ok in HLS JS?
