### ISSUE TITLE
Global plugins

### ISSUE THREAD

**Issue by shaharmor** [jwplayer/jwplayer#1042]
Hi,

Is it possible to register a global plugin that will be injected to all players created afterwards?

For example, instead of doing this:
```javascript
// first
jwplayer.api.registerPlugin('someplugin', '6.0', plugin);

// and then
var player = jwplayer('player').setup({
   plugins: {
      someplugin: {}
   }
});
```

do this:
```javascript
// first
jwplayer.api.registerPlugin('someplugin', '6.0', plugin);

// and then
var player = jwplayer('player').setup({});
```

and the plugin will be injected to the newly created player

**Comment by robwalch** [comment]
No, but you could modify `setup` so that your second example always executes your first example.
