### ISSUE TITLE
JW Player 7 does not reload HLS file when going from display:none to display:block

### ISSUE THREAD

**Issue by TRoZZNL** [jwplayer/jwplayer#1047]
The situation is as follows : 2 players are loaded, one with FLV as source and one with HLS as source.
When i set display:none on the parent container of the FLV loaded player and i set it to display:block again, it will play just fine.
Whenever i so this with the HLS player, it displays a **no playable source** error.

I created a request on Stackoverflow containing a plunkr :
[https://stackoverflow.com/questions/35061237/jw-player-7-loads-hls-file-only-once-in-a-tabbed-container-with-flv-all-goes-we](https://stackoverflow.com/questions/35061237/jw-player-7-loads-hls-file-only-once-in-a-tabbed-container-with-flv-all-goes-we)

And also a support ticket on the JW Player site :
[https://support.jwplayer.com/customer/portal/questions/16136442-switching-players-with-a-hls-manifest-fails](https://support.jwplayer.com/customer/portal/questions/16136442-switching-players-with-a-hls-manifest-fails)

**Comment by pixelchutes** [comment]
Came here to file this same bug, thanks for posting this. I have confirmed in both JW <kbd>7.2.4</kbd> and <kbd>7.3.0-beta</kbd> in Chrome / Firefox stable.

Not reproducible on Android / iOS or Safari with _native_ HLS support.

**Comment by pixelchutes** [comment]
Here's some additional detail:

**Toggle the player (or parent container) to hide then re-show**
* Video playback no longer works:
    * If video was previously started, player will be black and cannot be started again.
    * If video was never started, player will be black, and errors upon playback:

    > Error loading media: File not found.

    * If using `preload = none`, errors upon playback:

    > no playable source

**Comment by slavah** [comment]
Same behavior for RTMP streams as well.
This is a show stopper bug for us to update from 6.12 to 7.xxx

**Comment by pixelchutes** [comment]
My understanding is that when toggled, the flash object is completely removed from memory.

What would be ideal is if when restored it came back in a playable state.

**Comment by slavah** [comment]
if its completely removed then all event subscriptions would be gone as well. That would be a bad behavior. I have not looked into code, but hopefully that's not the case.

**Comment by pixelchutes** [comment]
FYI -- this is the quote from @robwalch on the linked SO post:

>When you set display:none on the player and it's using Flash to render the video (it is for both HLS and FLV in this case), the Flash app is unloaded from memory and then reloaded again once it's visible again in the DOM. You could work around this by setting visible:hidden and using the api to pause and resume playback. I think you'll find this to be a lot faster than loading and unloading the swf from memory each time. Let me know.
> If you file an issue in gihtub we can see when the flv player in Flash is able to recover while the hls player is not. The code is very different and was not designed to handle the kind of resets caused by removing the plugin from the DOM or setting display to none.

The JW Player team also provided [a possible work around](http://qa.jwplayer.com/~george/resize.html), which leverages the player's `resize()` method, but it's use case if pretty limited:

```javascript
function shrink(){
    if(playerone.getState()=="playing"){
        playerone.pause();
    }
    playerone.resize(0,0);
}
function expand(){
    playerone.resize(320,180);
}	 
```

**Comment by robwalch** [comment]
In 7.4 if you do not set primary to flash, HLS will run in html5 on Chrome. So the impact will be reduced. We do not have plans to handle reloading the Flash player. Using visibility:hidden should be an acceptable workaround.

**Comment by slavah** [comment]
Ok thank you for work around!  I will test it out.
