### ISSUE TITLE
Cookies volume

### ISSUE THREAD

**Issue by campones** [jwplayer/jwplayer#1077]
### Expected Behavior

*Describe expected behavior*

User volume is kept between sessions

### Actual Behavior

Since your last release, I don't have any cookies created to store user side volume. 

*Describe actual behavior*

### Steps to reproduce

1. lower volume to 10
2. refresh
3. observe that volume goes to maximum

### Environment

- *hardware | device*
- *operating system | version*
- *JW Player version | url*

win7 64 tested on chrome 48, ff 44, last opera .
----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by dannyfinks** [comment]
Thank you @campones I was able to reproduce this issue and we will follow up on our end. A change to honor volume from the player configuration over local storage may have impacted this.
