### ISSUE TITLE
Provider example cannot be registered with JW player 7

### ISSUE THREAD

**Issue by miguelcb84** [jwplayer/jwplayer#1078]
### Expected Behavior

Being able to properly register a provider with  JW player 7.
### Actual Behavior

When trying to register a new provider using the example from https://github.com/jwplayer/jwplayer-sdks/blob/master/providers/timer.js, it throws the exception `"Uncaught TypeError: events.eventdispatcher is not a function"`. I believe, this is due to incompatibilities in the way former versions of the player handle events.

It would be nice that you provide a working example of provider skeleton.
### Steps to reproduce
1. Follow the steps to embed the jwplayer using Option 2 from: https://support.jwplayer.com/customer/portal/articles/1406723-basic-video-embed
2. Include a script with the provider
   
   `<script src="/timer.js"></script>`
3. Check console log using the browser inspector
### Environment
- JW Player version: "7.3.3+commercial_v7-3-3.77.commercial.7b0247.jwplayer.f229ea.analytics.5a0154.vast.0300bb.googima.e8ba93.plugin-sharing.08a279.plugin-related.909f55.plugin-gapro.0374cd"

(as given by jwplayer.version)

**Comment by robwalch** [comment]
This should address the issue:
https://github.com/jwplayer/jwplayer-sdks/commit/a396e0cabe84dbe7781cf927d5deb5b366f18fbc
