### ISSUE TITLE
Playlist Item 'start' offset inconsistencies

### ISSUE THREAD

**Issue by pixelchutes** [jwplayer/jwplayer#1079]
### Expected Behavior

When defining a `start` offset on a playlist item _(including RTMP)_, player automatically seeks to the defined offset on `play` event, audio/video plays as expected.
### Actual Behavior

For some browsers (Chrome 50 / Firefox 44), player automatically seeks to the defined offset on `play` event, but player is black _(no video/audio)_, esp. for large RTMP streams _(2-3 hour+)_.

**RTMP (Chrome 50)**
`start: 20` _(plus few seconds for screen grab)_
![large_rtmp_start_offset_black](https://cloud.githubusercontent.com/assets/352182/13330020/2bb8cd36-dbb4-11e5-9773-f4b31e794033.jpg)

For Safari, player does not automatically seek to the defined offset on `play` event (for HLS), but playback does begin (at `00:00`).

**HLS (Safari 9.0.2)**
`start: 10`
![safari_start_offset_hls_from_zero](https://cloud.githubusercontent.com/assets/352182/13330046/4e62f7b2-dbb4-11e5-94ff-c397e9aef6a2.jpg)
### Steps to reproduce
1. Create a JW Player v7.3.3 with a 2-item playlist.
2. Define a valid `start` offset on each playlist item:
   - Item 1 = HLS media
   - Item 2 = RTMP media
3. Play playlist item 1 (in Chrome/Firefox), watch automatic seek on playback: _(HLS video working)_.
4. Play playlist item 2 (in Chrome/Firefox), watch automatic seek on playback: _(RTMP video **not working**, just black.)_.
5. Play playlist item 1 (in Safari), **no automatic seek** on playback: _(HLS video working)_.
6. Play playlist item 2 (in Safari), watch automatic seek on playback: _(RTMP video working)_.
### Code to reproduce

``` html
<div id="player"></div>
```

``` javascript
// Demo Playlist
var demoPlaylist = [{
    title: 'Video 1 (HLS)',
    start: 10,
    description: 'Start offset not working in Safari',
    file: 'https://content.jwplatform.com/manifests/IMUjQRAB.m3u8',
    image: 'https://assets-jpcust.jwpsrv.com/thumbs/IMUjQRAB-720.jpg'
}, {
    title: 'Video 2 (RTMP)',
    start: 20,
    description: 'Start offset not working in Chrome/Firefox',
    file: 'rtmp://example.com/application/mp4:myVideo.mp4', // substitute with valid, RTMP stream.
    image: 'https://support.jwplayer.com/customer/portal/attachments/238181'
}];
var playerInstance = jwplayer('player');
playerInstance.setup({
    primary: 'html5',
    playlist: demoPlaylist,
    width: '100%',
    aspectratio: '16:9',
    preload: 'none',
    visualplaylist: true,
    displaytitle: true,
    repeat: false
});
```
### Environment
- MacBook Pro
- OS X 10.11.2 / Chrome 50.0.2657.0 dev (64-bit) / Firefox 44.0 / Safari 9.0.2
- JW Player 7.3.3

**Comment by esboyd** [comment]
Thanks for this detailed report @pixelchutes. The start param actually only works right now with the RTMP provider and is not a feature of the other video providers. We do have a feature in our backlog though to extend start to video and HLS providers.

**Comment by pixelchutes** [comment]
Good to know, @esboyd 

We've actually been using `start` param for quite a few years_ (homegrown solution)_ and noticed it stopped working upon upgrading to 7.3.3. Turns out, we both landed on the same naming convention for defining the start offset! :smile:

I can say that for RTMP (like described above), the built-in solution is running into issues on some browsers where the seek occurs, but player is black w/ **no **video**.

For now, our work around has been to rename our internal parameter to `offset`, and rely on our previous handling. Having this eventually baked-in will be really nice.

**Comment by robwalch** [comment]
The player supports playlist item `startTime`. `start` and RTMP have been deprecated.
