### ISSUE TITLE
EXT-X-DISCONTINUITY tag support

### ISSUE THREAD

**Issue by osztrovszky** [jwplayer/jwplayer#1081]
### Expected Behavior

Hi,
I’d like to insert an ad in my HLS live stream.
As far as I know I can do it with EXT-X-DISCONTINUITY tag.

Here is my manifest for one profile.

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:3363523
#EXTINF:4, no desc
#EXT-X-PROGRAM-DATE-TIME:2016-02-26T09:00:15Z
20160224T182112-01-3363523.ts
#EXTINF:4, no desc
#EXT-X-PROGRAM-DATE-TIME:2016-02-26T09:00:19Z
20160224T182112-01-3363524.ts
#EXTINF:4, no desc
#EXT-X-PROGRAM-DATE-TIME:2016-02-26T09:00:23Z
20160224T182112-01-3363525.ts
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2016-02-26T09:00:27Z
#EXTINF:4, no desc
/8001/tablo/20160224T173827-01-3328099.ts
#EXT-X-PROGRAM-DATE-TIME:2016-02-26T09:00:31Z
#EXTINF:4, no desc
/8001/tablo/20160224T173827-01-3328100.ts
#EXT-X-PROGRAM-DATE-TIME:2016-02-26T09:00:35Z
#EXTINF:4, no desc
/8001/tablo/20160224T173827-01-3328101.ts
#EXT-X-DISCONTINUITY
#EXTINF:4, no desc
#EXT-X-PROGRAM-DATE-TIME:2016-02-26T09:00:39Z
20160224T182112-01-3363529.ts
#EXTINF:4, no desc
#EXT-X-PROGRAM-DATE-TIME:2016-02-26T09:00:43Z
20160224T182112-01-3363530.ts
#EXTINF:4, no desc
#EXT-X-PROGRAM-DATE-TIME:2016-02-26T09:00:47Z
20160224T182112-01-3363531.ts
#EXTINF:4, no desc
#EXT-X-PROGRAM-DATE-TIME:2016-02-26T09:00:51Z
20160224T182112-01-3363532.ts
```

I’m running a script that inserts the 12sec long ad (/8001/tablo/*.ts) then removes it, repeating in 30 seconds.

### Actual Behavior

In Safari OSX, if I open the stream without player, it works fine, no buffering, no lagging.
In JWplayer iOS (html5 based) it works also fine.

However if I open it in JWplayer in OSX Safari (flash based), or Windows Chrome (flash based), it sometimes lagging or buffering, even freezes and stops the stream.

### Steps to reproduce

1. Create a JW Player v7 or v6.
2. Insert one of these links: http://dev.cdn.connectmedia.hu/8001/index.m3u8 or http://dev.cdn.connectmedia.hu/8002/index.m3u8
3. Play it in OSX/Safari, Windows/Chrome and compare it to iOS/Safari.

### Environment

- OS X Safari 9.0.3 / Windows 7/8 Chrome 50 dev, Firefox 44
- JWPlayer 6/7

**Comment by donato** [comment]
Hi @osztrovszky - these streams are dead, feel free to reopen with working streams

**Comment by esboyd** [comment]
@donato, @androoP has a downloaded copy from when @osztrovszky wrote into support@

**Comment by osztrovszky** [comment]
Hi Guys,
Here are the streams, AES and noAES:
http://109.199.57.76:8080/8001/index.m3u8
http://109.199.57.76:8080/8002/index.m3u8

Please check this AD insertion problem.

**Comment by donato** [comment]
Awesome, thanks, adding it into our test suite now.
