### ISSUE TITLE
JWPlay v7 seek does not work with rtmp 

### ISSUE THREAD

**Issue by PrimeObjects** [jwplayer/jwplayer#1087]
### Expected Behavior

suppose to jump to the 5 second of the video (rtmp)
### Actual Behavior

The load icon circling with a black screen. The seek event never trigger
### Steps to reproduce

Please try the code below

var playerInstance = jwplayer("_video");
        playerInstance.setup({
            file: "rtmp://szq3gh4wlzgxg.cloudfront.net/cfx/st/kb.20131113.mp4",
            width: "100%",
            aspectratio: "4:3"
        });

```
    playerInstance.on('play', function() { 
        console.log("play");
    });
    playerInstance.on('seek', function() { 
        console.log("seeked");
    });
    playerInstance.on('time', function() { 
        console.log("time");
    });

    playerInstance.on('ready', function() { 
        console.log("ready");
        playerInstance.seek(5);
    });
```
### Environment

Latest Chrome
JW Player 7.3.4

**Comment by robwalch** [comment]
Hi Prime. We're tracking this issue internally now. It's not on the slate for fixing in v7.4.0 right now. We'd have to troubleshoot if the command is getting queued in flash.js and then what happens in Player.as and RTMPMediaProvider.as if it get's that far. 

In the mean time it looks like there is still code in there for supporting `item.start`:
https://github.com/jwplayer/jwplayer/blob/master/src/flash/com/longtailvideo/jwplayer/media/RTMPMediaProvider.as#L290

So you may try this as an alternative even though it's not officially supported:

```js
jwplayer("_video").setup({
  playlist[{
    file: "rtmp://szq3gh4wlzgxg.cloudfront.net/cfx/st/kb.20131113.mp4",
    start: 5
  }],
  width: "100%",
  aspectratio: "4:3"
});
```

**Comment by PrimeObjects** [comment]
Thank you Rob, will it be officially supported anytime soon?

**Comment by robwalch** [comment]
We won't remove that code in case folks are using it. But because it's not supported across all types of playback, it remains undocumented. If you're really set on using RTMP this might be the way to go. Our focus now is on HLS and DASH support.
