### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by luciano-masuero** [jwplayer/jwplayer#1088]
###Compatibility

I am trying to use this on a Linux server environment. Now, I am checking on steps and there is one that requires to install "Adobe AIR SDK"

Currently on the linked page there is no source for Linux based OS. I search and find that they provide for version 2.6 - https://helpx.adobe.com/air/kb/archived-air-sdk-version.html#main_Adobe_AIR_2_6_runtime_downloads

My question is if this is compatible with the current version? Do you know anyone trying to integrate this to linux OS?

By the way: CentOS 7.0

**Comment by robwalch** [comment]
You can use the FLEX SDK in place of AIR:

http://www.adobe.com/devnet/flex/flex-sdk-download.html

or

http://flex.apache.org/
