### ISSUE TITLE
Palo Alto content filters detects use of data URI as threat

### ISSUE THREAD

**Issue by deltafactory** [jwplayer/jwplayer#1095]
Detailed description here: https://live.paloaltonetworks.com/t5/Threat-Articles/Threat-ID-30419-RFC2397-data-URL-scheme-usage-detected/ta-p/71389

### Environment
 - Any network environment using a content filter from Palo Alto Networks - especially schools
 - JW Player 7.x

**Comment by deltafactory** [comment]
Another report found online: http://stackoverflow.com/questions/33874636/jwplayer-7-vulnerability

We've had 3-4 incidents of this reported within 2 weeks of rolling out v7, most of which have come from schools that use the Palo Alto filter..

**Comment by robwalch** [comment]
Thanks for reporting this here @deltafactory. We don't have any plans to remove the data urls and load CSS and webfonts externally at this time. We've tried to work with Palo Alto on this. Our own @brentewood has written a response regarding our stance on this:

> Thanks for reaching out. We take inquiries like this very seriously.
> 
> For background, after we release new software, firewalls and virus protectors on occasion falsely characterize certain strings as potential threats. Within the realm of JW Player's vast footprint across the Internet, we see these occurrences very rarely. However, when they do occur, we are proactive in notifying firewall and virus protection vendors to white list our URLs (or certain patterns) to prevent false positives. Most of the time, these vendors act expeditiously to fix (override) their own false positives. 
> 
> Our methodology for embedding fonts is a well-established best practice based upon open standards. Therefore we don’t see the need to remedy the situation with a code change. 
> 
> This particular problem can be resolved by either having your vendor whitelist the URL to work around their false positive, or by having your staff configure your firewall software to whitelist the particular URL in question.  I would recommend tuning your own firewall. 
> 
> On your behalf, we have reached out to Palo Alto already and have attempted to get this resolved without your involvement. However, they informed us that they will need you to contact them to resolve this particular issue. 
> 
> For what it is worth, we have not received any other complaints regarding this issue from any of our thousands of global customers.Therefore at this time we don’t see this issues as systemic or wide-spread. 
> 
> I recognize this may not be the answer you wanted, so if you need assistance with your firewall, I will use my resources as best possible to help resolve your problem.  

Do you download and host the player on your site or use customer embed urls from our platform?

**Comment by deltafactory** [comment]
We download and host. I agree that you're using an established, standard practice and while I understand the potential for abuse, feel that it's a bit much to flag outright.

**Comment by robwalch** [comment]
@deltafactory we're starting to actively look at an alternative to include icons that does not add base64 data urls to the player.

**Comment by deltafactory** [comment]
Can you click on Debug Log and save it to a text file? I have a feeling 
the error message that would be most helpful is up above. The debug log 
should contain everything.

  - Jeff

**Comment by deltafactory** [comment]
Please excuse that accidental reply. Thanks for the update, I'm interested in the result.

**Comment by robwalch** [comment]
Hi @deltafactory,

We've updated our beta channel to v7.4.1-rc.1 to test externally loaded web fonts. The changes in this release removes all base64 data urls from jwplayer.js to remedy the issue with Palo Alto firewalls. Would you be able to help us test the player behind a firewall?

You can configure a player to [use the beta release channel in a JW Player account](https://support.jwplayer.com/customer/en/portal/articles/2149561-using-player-release-channels), or use the player library on our CDN:

//ssl.p.jwpcdn.com/player/v/7.4.1-rc.1/jwplayer.js

**Comment by deltafactory** [comment]
We didn't experience the blocks firsthand. It was reported by a number of schools who use PAF and one of them involved the IT staff who pinpointed the exact rule being triggered. Any reported instance was resolved by a domain-specific whitelist entry.

Since you have had contact with Palo Alto as noted earlier, is it possible to reach out to them with a test case and see if it passes their standard filters?

**Comment by androoP** [comment]
We've had two separate users with Palo Alto firewalls confirm that the issue is resolved with 7.4.1. Marking this as closed.
