### ISSUE TITLE
VTT file containing "WEBVTT" as the first line throws "Invalid SRT file"

### ISSUE THREAD

**Issue by isiryder** [jwplayer/jwplayer#1098]
### Expected Behavior

A VTT file with only "WEBVTT" to the first line of the file, is a valid one.

So I think it shouldn't throw such error (and why SRT btw?).

I would expect it just to return, as if no file was added, without any error.

In the worst case return a significant error as "No captions in VTT file" or "Empty VTT files not allowed"

### Actual Behavior

Throws "Invalid SRT file" when passing as caption a VTT file that only contains "WEBVTT" as the first line.

NOTE: A VTT file that only contains "WEBVTT" as the first line should be valid. There is an online VTT  validator: https://quuz.org/webvtt/

### Steps to reproduce

1. Create VTT file with one line only containing "WEBVTT".
2. Using setup add that file as a track (I tested thumbnails and captions).
3. Check the console and see the error.

### Environment

- iMac
- OSX Yosemite
- JW Player version 7

**Comment by robwalch** [comment]
Hi @isiryder,

Do you have a test page that reproduces this issue, or at least a url linking to the file in question? Also what type of media are you attempting to play in which browser?

Thanks in advance!

**Comment by isiryder** [comment]
Hi @robwalch,

Unfortunately I don't have a visible test page right now. But I've uploaded the file in question: http://filebin.ca/2ZWuSubgCkFZ/empty.vtt

I am trying to play a simple mp4 video file using Chrome v48.0.2564.116 (64-bit).

Thanks!

**Comment by johnBartos** [comment]
I'm trying to recreate this, but I'm not seeing any error thrown. Are you still having this issue @isiryder?

**Comment by isiryder** [comment]
Yes, I am still having this issue. Testing with Chrome 50 and JWPlayer 7.4.2 (HTML version).
