### ISSUE TITLE
jwplayer VPAID player doesn't handle AdClickThru correctly

### ISSUE THREAD

**Issue by cloudxu** [jwplayer/jwplayer#1100]
### Expected Behavior

Click on VPAID Ad, one window will be opened.

*Click through URL defined in the VAST will be opened in a new window.*

### Actual Behavior

Due to the implementation of JWPlayer, two windows will be open after click the VPAID ad.

*JWPlayer Ad Tester (http://demo.jwplayer.com/ad-tester/) handles AdClickThru VPAID event this way:
AdClickThru:function(a,b,c){c&&window.open(a),f("click",{id:b})}*

*In our VPAID ad, we are passing (null, null, true) to the event. We basically want the player to handle the window open event by loading the click through URL from the enclosed VAST tag. However, because of JWPlayer is not checking value of a, it will open a blank window.*

### Steps to reproduce

1. Go to the test AD player: http://demo.jwplayer.com/ad-tester/. And choose HTML 5
2. Paste the VAST tag with VPAID: https://ad.atdmt.com/d/a.vast;p=11002203177070
3. Play the Ad and click on the window.

### Environment

- *JW Player version | url: http://demo.jwplayer.com/ad-tester/*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Hi @cloudxu. I believe we are handling the event correctly. The VPAID spec does not say that the player needs to check for a valid url. If you do not want the player to open a new window then you should pass `false` with the third parameter _(null, null, false)_ .

From the VPAID2 spec:

> 4.9.10 AdClickThru
> The AdClickThru event is sent by the ad when a click thru occurs. Parameters can be
> included to give the player the option for handling the event. Three parameters are
> included with the event, String url, String id and Boolean playerHandles. If
> playerHandles is true, the player must handle the event by opening a new browser
> window to the url, false, the ad will handle the event...

**Comment by cloudxu** [comment]
@robwalch, Thanks for the quick response.

The problem is if I pass in (null, null, false), the behavior is still not right. According to the spec, (null, null, false) means the VPAID ad shall open a new window. And the spec didn't say if VPAID shall not fire AdClickThru event. To make third party tracking work, we will need to fire AdClickThru event. But in the case JWPlayer will catch the event and open a click thru url window. So again there will be two windows.

I feel from code logic point of view, there is no point for JWPlayer to open the window if the url parameter is null, correct? Google's ad player handled this case.

**Comment by federicoghedinastailamedia** [comment]
Same here, 10 months after the issue has been closed.... ! uh!!

**Comment by contobob** [comment]
Sorry @robwalch but this issue should not be closed.

Both @cloudxu and @federicoghedinastailamedia are right.

jwplayer incorrectly opens a new tab regardless of whether `playerHandles` is set to `true` or `false`. The behaviour in jwplayer is exactly the same in both cases but it's obvious from your quoted spec text that `playerHandles: false` means you should not be opening anything. As it currently stands, `('', '', false)` opens two tabs: one by the ad (good) and another by the player (bad). This makes for a grave user experience.

Please consider re-opening this issue.

**Comment by robwalch** [comment]
We don't address ads features in this repo. Please report your issue to support@jwplayer.com
