### ISSUE TITLE
Interactions with controls are susceptible to being broken by other code on the page.

### ISSUE THREAD

**Issue by joineral32** [jwplayer/jwplayer#1103]
### Expected Behavior

Video controls should work even if mouseup handlers on ancestor elements stop event propagation further up in the document. Examples:

When I drag the video play head, the playhead should stop being dragged once I let go of the mouse button.

When I drag the volume slider, the slider should stop being dragged once I let go of the mouse button.
### Actual Behavior

If an ancestor of the jwplayer stops event propagation of a mouseup event, interactions with controls will never stop. Examples:

When I drag the video play head, the playhead continues to follow the mouse movements even once the mouse button has been released.

When I drag the volume slider, the slider continues to follow the mouse movements even once the mouse button has been released.
### Steps to reproduce
1. Create an environment where an ancestor of the jwplayer is stopping event propagation of a mouseup event. Simplified example:

<div id="video-ancestor">
    <div class="jwplayer">
        
    <div>
<div>

<script>
    document.querySelector('#video-ancestor').addEventListener('mouseup', function (ev) {
        ev.stopPropagation();
    });
</script>

1. Click play on the jwplayer.
2. Attempt to adjust the volume or the playhead position.
3. Notice that the control cannot be released.

The 'click' behavior of jwplayer should not be impacted by its ancestors. The apparent cause of the problem seems to be due to the way interactions are handled. On mousedown events, the jwplayer attaches a document-level mouseup event listener to listen for the end of the interaction. However, this event listener is using event bubbling rather than event capturing. 

An example of where this is happening can be found here:
https://github.com/jwplayer/jwplayer/blob/1ade10b7bd86271bd8137f6a9920f9a75b4e471b/src/js/utils/ui.js#L152
It is my opinion that this needs to be switched to use event capturing rather than event bubbling, so that it receives the mouseup event before ancestors have a chance to stop the event from propagating.
See the useCapturing option for addEventListener:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Comment by robwalch** [comment]
Thanks @joineral32,

Do you want to submit a PR that changes the ui.js event listeners to use capture?

**Comment by joineral32** [comment]
@robwalch I have been planning on doing so. I have been very busy lately and not yet had a chance to get a dev environment set up and get jwplayer building. If somebody beats me to it, I will not hold it against them though.

**Comment by robwalch** [comment]
We should switch to using event bubbling as well as attach listeners to the ui element's ownerDocument, rather than the global document.
