### ISSUE TITLE
Compiled Flash Binary Does Not Playback Using Provider

### ISSUE THREAD

**Issue by stuartflanagan** [jwplayer/jwplayer#1111]
### Expected Behavior

Compiled flash binary to be the same size and functionality of downloaded player's flash binary.

### Actual Behavior

Flash binary is a lot smaller in filesize. The compiled flash binary does Not load in the AkamaiHD provider for playing an Akamai delivered HDS stream.

### Steps to reproduce

1. Clone repository
2. Check out tag of version 7.3.4
3. Compile

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by stuartflanagan** [comment]
Sorry this is not really a bug or an issue but more a question. Should the flash binary compiled from this source perform identically to the one supplied for download from our JWPlayer dashboard?

**Comment by robwalch** [comment]
The swf downloaded from your account is compiled from our commercial project. The commercial project extends this project with additional functionality - mainly support for HLS and loading of external providers like the AkamaiHD provider you mentioned. The commercial project is not public or open-source.

jwplayer.flash.swf compiled from this project can play mp4, flv, rtmp and audio media.
