### ISSUE TITLE
Playlist selector menu disappear

### ISSUE THREAD

**Issue by Jno21** [jwplayer/jwplayer#1119]
### Expected Behavior

The playlist selector menu should always be there (except when an ad is played).

### Actual Behavior

On JW 7.3.4 standalone, on the following playlist (with ads), after a while the playlist selector menu may disappear without any user action. 

### Steps to reproduce

I did not found a pattern to how to reproduce this. It is not systematic.
Screen: http://prntscr.com/ai1v6p

### Environment

- MacBook Pro
- OS X 10.11.3
- 7.3.4
- Test page: http://streamroot.test.s3.amazonaws.com/QATesting/v3/qatest21-03-16_JWonly.html

**Comment by waxidiotic** [comment]
I was able to reproduce this one time. It just happened without any interaction. I checked DevTools and It looks like `.jw-flag-compact-player` got added to the player when it was still 420px wide.

**Comment by robwalch** [comment]
Thanks! This is likely due to the compact player controls logic. We plan to replace that logic with set CSS classes that behave similar to responsive page break points (just using player size instead).

**Comment by johnBartos** [comment]
Since the playlist is being removed in 7.7 this bug no longer applies
