### ISSUE TITLE
[7.4.0-beta.2] Handling https status error codes without CORS headers

### ISSUE THREAD

**Issue by pixelchutes** [jwplayer/jwplayer#1121]
### Actual Behavior

Initial testing of HTML5 HLS in `7.4.0-beta.2`, I attempted to load an HLS stream from a playlist _(e.g. index = 10)_ as the first actual media playback event.

NOTE: The first playlist item is simply a poster image, tied to an audio file, but `stop()`'d in `beforePlay` event. (Used to render images in the player out-of-the-box.)

Upon attempting to `play()` the HLS playlist item, the following error is logged in the console:
**Console Error:**

> jwplayer.js:2 Uncaught Error: No suitable provider found

There is **no error** displayed in the JW 7.4.0 player itself. (Just black)

However, when the _first_ playlist item is the same HLS stream, I receive _different_ behavior:

**JW Player Error:**

> Cannot load M3U8: Crossdomain access denied

**Console Error:**

> Fetch API cannot load https://cdn.com/hls/playlist.m3u8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://domain.com' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
### Expected Behavior

I suspect the error is related to the same underlying issue _(missing proper CORS configuration)_. However, if so, I would expect more consistent handling (e.g. A JW Player error displayed in the player, the same CORS console error logged, etc).

If it's somehow _not_ related, then I am confused about these two different experiences when testing the exact same stream (one as the 1st playlist item, another further down the list).
### Steps to reproduce
1. Setup `7.4.0-beta.2` test instance on HTTPS domain.
2. Configure a playlist containing HLS streams to be tested in HTML5 on Chrome.
3. Attempt playing HLS playlist item > 1 (ensure 1st playlist item is not HLS, or ever played)
### Environment
- Chrome 51.0.2700.0 dev (64-bit)
- OS X 10.11.4
- build: commercial_v7-4-0-beta-2.82

**Comment by pixelchutes** [comment]
**UPDATE:**

Once our CORS configuration was straightened out, playback was possible. _(NOTE: Confirmed Limelight Networks [CDN support](https://developer.jwplayer.com/jw-player/docs/developer-guide/beta/html5_hls_beta/) for HLS VOD.)_

However, the following console error was still reproducible, suggesting it is potentially unrelated to CORS as I originally thought:

**Console Error:**
> jwplayer.js:2 Uncaught Error: No suitable provider found

**Comment by robwalch** [comment]
Yep. This happens on servers that return https status error codes without cors headers. We're unable to handle this using the fetch api - we catch a promise exception and no response is available to check the http status code. It's likely we'll fix this by using XHR instead of fetch - before or shortly after release.

**Comment by pixelchutes** [comment]
Good to know it's already on your radar. I am still somewhat confused by how the position in the playlist is somehow a factor. In the first position, the exact same stream plays fine...

**Comment by dligthart** [comment]
HI All, Could you tell me when this will be fixed? As I am also implementing handling this specific type of error.

**Comment by robwalch** [comment]
This issue was specific to the Caterpillar HLS provider using fetch. We've been using hls.js since v7.8.0 which should forward status codes correctly.
