### ISSUE TITLE
JW Player seeking problem

### ISSUE THREAD

**Issue by akopper** [jwplayer/jwplayer#1127]
JW Player seems to have problems with a video of mine. I noticed that sometimes 
when seeking in the stream, the playback does not start. Instead the player
is loading a lot of segments in the background.

Could you please take a look at this issue?

How to reproduce:
0. Enable developer console in your browser.
1. Open the JW-Test site at [2]
2. Load the manifest from [1]
3. Start the video playback.
4. Seek at random positions in the file and wait for it to continue playback.
5. Notice that sometimes the playback will not start. Instead the player will download segments from the server.

My setup:
* `uname -a` -> Linux akopper-ThinkPad-T540p 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* JW Tester: http://demo.jwplayer.com/stream-tester/ | Flash version 21 | JW Player 7.3.6
* Google Chrome Version 49.0.2623.112 (64-bit)

Best Regards,
Alexander Kopper

===============================
[1] https://eu-storage-bitcodin.storage.googleapis.com/bitStorage/7875_9ef90fef446ac887e6b9a16185086713/191640_7cc1d8535960fed4acf0a1f9edd51dc4/191640.mpd
[2] http://demo.jwplayer.com/stream-tester/

**Comment by robwalch** [comment]
Hi @akopper,

Can you provide more detail on step 4? Are you seeking more than once? Can you provide a break down of specific seek commands and timing that reproduce the issue?

**Comment by robwalch** [comment]
This stream appears to work and is seek-able in Shaka 2:

http://shaka-player-demo.appspot.com/demo/

The issue can be duplicated but is recoverable by seeking again or hitting play. Sometimes shaka pauses when under-buffered until the buffer is full.
