### ISSUE TITLE
status of cc button

### ISSUE THREAD

**Issue by madjarian** [jwplayer/jwplayer#1131]
### Expected Behavior
when we have multiple subtitles files for one video and choose one, the cc button is activated

### Actual Behavior

1. actually when we have multiple subtitles files for one video and choosed one, the cc button is disabled (grey)
2. when we have only one subtitle with a video file, the button work normally

### Steps to reproduce
1. add several subtitle to one video
2. choose one
3. check the status of the cc button, it is deactivated (grey)

### Environment
- *JW Player version | url* jwplayer 7.3.4 premium registered

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by donato** [comment]
@madjarian - Thank you for identifying this, we will definitely look to fix it.

Internal tracking: https://jwplayer.atlassian.net/browse/JW7-1017

**Comment by johnBartos** [comment]
Resolved in 7.5.0!
