### ISSUE TITLE
Container should not always require an id attribute

### ISSUE THREAD

**Issue by coulson84** [jwplayer/jwplayer#1136]
### Expected Behavior

If I pass the jwplayer() factory a reference to a node instead of an id string everything should work no problem.
### Actual Behavior

If no id is on the node reference passed to the jwplayer() creator then VAST ads fail to display because the initial video element that is inserted in to the DOM cannot be found
### Steps to reproduce

``` javascript
let videoPlayer = document.createElement('div');
document.body.appendChild(videoPlayer);

jwplayer(videoPlayer).setup({
            file: 'http://content.jwplatform.com/videos/Wf8BfcSt-kNspJqnJ.mp4',
            image: 'http://content.jwplatform.com/thumbs/Wf8BfcSt-640.jpg',
            width: 580,
            height: 370,
            autostart: false,
            advertising: {
                client: 'vast',
                schedule: {
                    'myAds': {
                        'offset': 'pre',
                        'tag': `http://www.adotube.com/php/services/player/OMLService.php?avpid=oRYYzvQ&platform_version=vast20&ad_type=linear&groupbypass=1&HTTP_REFERER=http://www.longtailvideo.com&video_identifier=longtailvideo.com,test`
                    }
                }
            }
        });
```
### Environment
- Browser: Chrome 49.0.2623
- OS: Ubuntu 15.04
- JW Player version: 7.3.6

---

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text _in italics_ with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
You can work around this issue by adding an id to the element:

```
let videoPlayer = document.createElement('div');
videoPlayer.id = 'video-player-1';
document.body.appendChild(videoPlayer);
```

**Comment by coulson84** [comment]
This is already how I worked around the issue. I just think it is pretty pointless being able to pass a reference to a node instead of an id string if the node you pass still has to have an id on anyway.

**Comment by donato** [comment]
Agreed that it sucks, but it's an age-old decision. The issue is communication between Flash and the player, as seen here https://github.com/jwplayer/jwplayer/blob/2d59678c4cc70fb8c98b05dfcea24e8a95d0dab0/src/flash/com/longtailvideo/jwplayer/player/SwfEventRouter.as#L67

Would it better suit your needs if we just generated a random id when none is given?

**Comment by ithcy** [comment]
Is there a target date for removing Flash from the player library? Seems to me like you could sunset it and retire it into a deprecated branch or tag to concentrate on HTML5 development. 

I agree that it's silly to require an ID. I would like to be able to instantiate the player with a reference to the raw Element, or better yet just allow me to construct a new JWPlayer() with no ties to the DOM and just inject the UI into the DOM when and where I need it. For example, maybe I don't need the UI at all, but just want to be able to manipulate the player for programmatic reasons. Allowing this kind of abstraction would make advanced usage so much easier.

**Comment by robwalch** [comment]
We still require an ID in a few places, but the changes here in #1929 should help.

Note that the player's view always creates a new element so the element you pass to setup is always replaced and only restored to DOM with `jwplayer().remove()`.

**Comment by smohadjer** [comment]
Any plan to release an stable version that contains this fix? I see on github that version 7.8.0 from Nov 2016 is still considered as the latest release!

**Comment by robwalch** [comment]
@smohadjer,

This ticket is marked with milestone v7.10.2 which indicates that is the version this issue was fixed in.

You will notice many tagged versions since the notes I added to v7.8.0. I no longer maintain release notes in this project by turning tags into "releases".

Official JW Player release notes can be found here https://developer.jwplayer.com/release-notes/jw-player/

**Comment by smohadjer** [comment]
Thanks Rob. Do you know which version is the latest stable (production ready) version? I'm having a hard time to figure that out. v8.0 seem to be in beta still, right?

**Comment by robwalch** [comment]
7.12.6
