### ISSUE TITLE
Allow jwplayer to setup inside of a friendly iframe

### ISSUE THREAD

**Issue by coulson84** [jwplayer/jwplayer#1138]
### Expected Behavior

I should be able to pass a node in to the factory function and have the video be inserted there and work as normal
### Actual Behavior

If the node passed in is not in the same window that the JW Player code was loaded in then no video player is added.

This should be possible by using element.ownerDocument.defaultView to get the window that the element belongs to for setting up the rest of the video player.
### Steps to reproduce

var ifr = document.createElement('iframe');
var holder = ifr.contentWindow.createElement('div');

document.body.appendChild(ifr);
ifr.contentDocument.body.appendChild(holder);

jwplayer(holder).setup(...);
### Environment
- All devices
- all OS
- JW Player version | 7.3.6

**Comment by donato** [comment]
Hi @coulson84, thanks for the great reproduction steps and example of the use case.

I had to tinker with your steps to see your issue in Chrome, I changed it to this:
```js

    var ifr = document.createElement('iframe');
    document.body.appendChild(ifr);

    var holder = ifr.contentDocument.createElement('div');
    ifr.contentDocument.body.appendChild(holder);
```

We believe that to fix this, we would need to replace all references in the player to "document" to references to the the ```ownerDocument``` of the container div.

Right now we are heads down on v7.4, but we would of course welcome open source contributions!

**Comment by adamk33n3r** [comment]
@donato I was going to take a look at this because it's something that I want but I cannot get it to even error. Running the four lines of code you posted along with a basic setup config produces no javascript errors but also doesn't initialize a player. It's just an empty iframe. Any ideas?

**Comment by FernandoMichelEnroute** [comment]
Hi @coulson84 I was taking a look in the issue and I found an error message on the steps to duplicate code (Uncaught TypeError: Cannot read property 'createElement' of null) so I tried this: 

var ifr = document.createElement('iframe');
var holder = document.createElement('div');
            
ifr.setAttribute("id","video-container");
    
document.body.appendChild(ifr);
ifr.contentDocument.body.appendChild(holder);
var jwp = jwplayer('video-container').setup(config);

The player actually works when the id is on the iframe but if is on the div inside the iframe it doesn't, this is the issue?

**Comment by coulson84** [comment]
Hi @FernandoMichelEnroute ,

The steps were typed out off the top of my head (a long time ago :) ) so I think there is an issue with them as mentioned by donato. If you follow his steps to reproduce code instead then you should still see the issue if it is not yet fixed.

To answer your question though, no. That was not the issue. The issue was that I should be able to pass a DOM node reference in to jwplayer instead of string that relates a DOM node's id. It's been a long time since I opened this issue but if I remember rightly you could pass a DOM node reference in but not if it is in a friendly iframe. This is specifically because the code referenced window directly during the setup but if, instead of referencing window directly, it accessed the window via node.ownerDocument.defaultView then the setup code should work.

Like I said - it has been a long time since I opened the ticket and it was for some integration I was making at a previous position so I am not up-to-date on any of this but I think I am recollecting things correctly - just don't hold me to it 😄

**Comment by robwalch** [comment]
We support player setup from elements. The element passed to the player is replaced with a div. If you want to setup the player in an iframe, your Javascript should be part of the iframe document, not the parent window.
