### ISSUE TITLE
Question: Timestamps in live stream

### ISSUE THREAD

**Issue by neilRGS** [jwplayer/jwplayer#1145]
We have a strategic requirement to be able to read the timestamps in a live stream.
Our application synchronises slides with video output, so we need to be able to tell how long the stream has been running for. It doesn't matter what format the time is in, so long as it can be read by the player.  At that point, we would fire an event to load the necessary slide.

Does JWPlayer have the capability to read timestamps from a live stream? If so, how do I retrieve the data?
If not, are there any plans for it to be able to do that?
Finally, if there are no plans for that, can anyone suggest a player which can do it?

It would need to be the actual timestamps in the media segments that are read. The idea being to mitigate buffering and latency, so that when the player receives the timestamp as a piece of meta data perhaps, then we can display the relevant slide for that time.

**Comment by robwalch** [comment]
Hi @neilRGS,

What format are your live streams in?

Getting media timestamps, or timed metadata with the program date-time is possible. There are ways to do this with our player but a lot depends on what type of media you have in which browser.

**Comment by neilRGS** [comment]
Hi @robwalch 
We are not tied to the type of stream we send out.  Currently, we are using Streamcoders Media Suite and are streaming through Wowza.
The (very limited) StreamCoders documentation shows that an RTP timestamp goes out with the stream, but that might not be exactly right, as their documentation is very poorly limited and assumes the user has an in-depth knowledge of how it all works; which I do not. :-)

If you can tell me the format you recommend we stream out and how to get the data from that, that would be a great help.

Many thanks,
Neil.

**Comment by neilRGS** [comment]
Hi @robwalch 
Have you had any further thoughts about the timestamp retrieval?

Thanks,

Neil.

**Comment by robwalch** [comment]
Hi @neilRGS,

Time events from our Flash HLS provider include the stream's MPEG timestamp (PTS):

```js
{
  "type":"time",
  "position": 0,
  "duration": 3513.964
  "metadata":{
    "mpegts": 90000.0
  }
}
```

We also expose [EXT-X-PROGRAM-DATE-TIME](https://datatracker.ietf.org/doc/draft-pantos-http-live-streaming/?include_text=1) in "meta" events. EXT-X-PROGRAM-DATE-TIME defines the absolute clock date/time for the first sample of some segments in streams:

```js
{
  "type":"meta",
  "metadata": {
    "programdatetime": "2013-06-17T18:32:00Z",
    "duration":115
  }
}
```

We'll be adding this event data to caterpillar, our html5 HLS implementation soon. This data is not available with native html5 hls playback in iOS, Safari, Android Chrome or MS Edge. I'd love it if there were standards for accessing MPEGTS and PROGRAM-DATE-TIME from HLS streams. This is certainly something we will pursue with the w3c.

What you can do is embed your own timed metadata in HLS streams. JW Player exposes ID3 timed metadata from HLS streams in all browsers. A "meta" event is emitted at the time in the stream that the data is embedded. This data could contain a date/time value that you could sync on. Wowza supports timed metadata in streams.

**Comment by neilRGS** [comment]
Thanks for getting back to me, Rob.

Our customer has a no-flash policy, so that isn't going to work for us, unfortunately.

However, I have discovered that I can send an additional track out with the video and audio tracks, from the encoder itself.  We are able to add data to this track.
What can JWPlayer do in terms of accessing the additional track data?  Would it appear as an event or a property, through the on.('meta') listener?

Thanks in advance,

Neil.

**Comment by robwalch** [comment]
Hi Neil. Yes, metadata tracks in HLS streams emit meta events for each cue point. The event object passed to the on('meta') listener will contain a `metadataTime` property and a `metadata` object that contains all fields in the data cue:

```
{
  "type": "meta",
  "metadataTime": 3.294,
  "metadata":{
    "PRIV":{
      "com.unified-streaming.sei_rbsp": (String or ArrayBuffer data)
    }
  }
}
```

**Comment by neilRGS** [comment]
Hi @robwalch 
I'm closing this as we made a java class for Wowza which injects the data we need, into the stream, without the need for Flash. JW can then read this as meta data.

Cheers

Neil.

**Comment by robwalch** [comment]
That's great @neilRGS!

I wish Wowza had a simpler way of doing this. I've seen some info on injecting metadata in their forum and on github, but I haven't found a comprehensive walkthrough. Are there any resources you could share?

Thanks!
Rob

**Comment by drakunov** [comment]
@robwalch https://github.com/WowzaMediaSystems/wse-example-ad-insertion

**Comment by mgw-sbic** [comment]
Wowza has a module for this: https://www.wowza.com/docs/how-to-control-display-of-program-date-and-time-headers-in-apple-hls-chunklists-for-live-streams-ext-x-program-date-time

**Comment by VincentCharpentier** [comment]
@robwalch Hi,

is this still true today ? With jwplayer 8.8.0-beta2 I can't find any relevant info in meta or time events ("PRIV", "mpegts" or "programdatetime") using an HLS stream

**Comment by mgw-sbic** [comment]
We are also interested if this timestamp workflow is documented somewhere in JW Player docs. It would be ideal if this documentation is not lumped into metadata of all kinds, but instead calls out timestamp processing individually and specifically.

**Comment by robwalch** [comment]
@mgw-sbic When JW Player is playing HLS content via hls.js (all browsers except Safari and IE11 Win7), the player fires "metadataCueParsed" events when parsing these tags in the manifest, and "meta" events when the playhead enters the time range where these tags were found:

#EXT-X-PROGRAM-DATE-TIME
#EXT-X-DATERANGE
#EXT-X-CUE-OUT
#EXT-X-CUE-IN
https://developer.jwplayer.com/jw-player/docs/javascript-api-reference/#jwplayeronmeta

We also still support "meta" events for ID3 metadata in all browser. 

Safari does not expose DATERANGE or CUE tags, and we do not yet support PROGRAM-DATE-TIME in Safari, but be adding support for it by using `MediaElement.getStartTime()`. Only streams with manifests that include a PROGRAM-DATE-TIME tag before segements will correctly output a date via `MediaElement.getStartTime()`. `MediaElement.getStartTime()` + `currentTime` should return the clock time for live streams.

**Comment by mgw-sbic** [comment]
@robwalch Thank you for this explanation! In the documentation, it refers to the various "time" values as "in seconds." I'm guessing that is misleading, as it must support fractions of a second for all values of a time related meta event, correct ?

Also, the documentation doesn't mention the ID and value attribute pair, how are those to be generated or understood?

{
        "name": "ID",
        "value": "309726842"
      },

Regarding Safari, are we saying there is no way to currently get the precise time within the media?

**Comment by robwalch** [comment]
> In the documentation, it refers to the various "time" values as "in seconds." I'm guessing that is misleading, as it must support fractions of a second for all values of a time related meta event, correct?

Seconds can mean "fractional seconds" unless we pointed out that the value is an integer.


> the documentation doesn't mention the ID and value attribute pair, how are those to be generated or understood?

Attribute pairs are parsed from the manifest. We don't generate these, they are just parsed from the manifest. Refer to the HLS spec or the documentation of your video provider in terms what is in the manifest.

> Regarding Safari, are we saying there is no way to currently get the precise time within the media?

Currently you can only get the current time, and need to access the video tag to get a PDT relevant date. Other manifest data is unavailable.
