### ISSUE TITLE
Increase Ahead Buffering of the video

### ISSUE THREAD

**Issue by De-M-oN** [jwplayer/jwplayer#1150]
### Expected Behavior

Playback like at Youtube - enough seconds buffered ahead to actually be able to playback the video

### Actual Behavior

A lot of Buffering, because the player only buffers like 5 seconds ahead of the video and stops then.

I even wonder about this behavior. Shouldnt it buffer the entire video while not using dash??
It buffers like dash streaming only these about 5 seconds ahead and stops buffering. Result: very much buffering which wouldnt occur if the player would buffer much more seconds.
For my own server I would prioritize that it buffers the entire video (meaning no dash loading) so that I can pause the video, watch it later and have it buffered all the way through.
I can only reach this behavior with flash at the moment.

### Steps to reproduce
Just watch this video:
http://killerinstinct.ath.cx:2000/Video/NFS6/2013/Raceday-(08_05_2013)-[NFS6]-part2__2048_html5.html

### Environment
- *hardware | device*

should be of no relevance

- *operating system | version*

on the root is windows server 2008 64bit
- *JW Player version | url*

7.36 free

My webbrowser is Google Chrome.

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by donato** [comment]
Hi there @De-M-oN - good point, we thought about that as well. Should it buffer while paused? For now, the answer is no, because it is the most conservative of bandwidth. This means the least amount of wasted $$$ on clients who pause a video because they don't want to watch it.

This could certainly be tweaked and improved, maybe it should buffer 30 seconds or so when paused and then stop.

**Comment by robwalch** [comment]
@De-M-oN 

JW Player doesn't control the buffer in your example. When you provide our player with an mp4, the browser buffers as much as it can. The reason it is not buffering enough in this example is because the bitrate of the video is much higher than it needs to be, and the server can't deliver it fast enough to play on the client requesting the mp4.

You should consider encoding your video at a lower bitrate, and putting it on a CDN, or uploading you mp4 to account.jwplayer.com so that we can re-encode and host DASH/HLS streams for you.

**Comment by De-M-oN** [comment]
The server can deliver the video perfectly fine. It is a 100 mbit server.
Its just the problem, that it stops buffering - yes also with a mp4.
When I set it to flash mode it buffers without stopping like a dash stream would - and you know what? I can watch the stream then.
But I cant watch it at html5 mode if it buffers there like up to 2 seconds or whatever it is.
Believe me I observe what it does. And what happens is:

Flash = entire video buffers, also if paused.
HTML5 = video buffers like 2 to 5 seconds at playback, server delivers data fast enough and data upload stops until I reach the next moment where it decides to load the next ~2seconds and so on.
Of course no full buffering at pause mode as well.


So please reopen it and dont tell me the bitrate being too high or the server too slow when it actually would work if it would work like at flash mode..

**Comment by robwalch** [comment]
Like I said, we don't control the buffering. When we set video.src to your mp4, the browser controls the loading of your content.

**Comment by De-M-oN** [comment]
And why youtube can do it? Even the non-dash streams dont do that behavior at youtube.

But on this case, jwplayer is unusable at html5 and I have to revert to flash.
Thats a bit pity, because I prefer html5 :-/

**Comment by robwalch** [comment]
This is not a Youtube video. The video in your example is a 5 minutes long 1.3GB file http://killerinstinct.ath.cx:2000/Video/NFS6/2013/Raceday-(08_05_2013)-%5BNFS6%5D-part2__2048.mp4. There's your problem.

Let's look at the output from ffprobe:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'http://killerinstinct.ath.cx:2000/Video/NFS6/2013/Raceday-(08_05_2013)-%5BNFS6%5D-part2__2048.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1
    creation_time   : 2013-05-09 21:44:32
  Duration: 00:07:32.88, start: 0.000000, bitrate: 25080 kb/s
    Stream #0:0(und): Video: h264 (High 4:2:2) (avc1 / 0x31637661), yuv422p, 2048x1152 [SAR 1:1 DAR 16:9], 24564 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2013-05-09 21:44:32
      handler_name    : 264#trackID=1:fps=30@GPAC0.5.1-DEV-rev4283
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 516 kb/s (default)
    Metadata:
      creation_time   : 2013-05-09 19:50:00
      handler_name    : Sound Media Handler
```

24564 kb/s video + 516 kb/s audio is excessive. I understand you would like the player to load the video and fill the buffer while the player is paused. Browsers do that on their own with html5 video, but there are limits to how much memory or disk cache a browser will use. I'm surprised there aren't with Flash in this case. 

A reasonable bitrate for a video of this resolution would be 800 kb/s for the video and 96 kb/s for the audio. Re-encode the video and it very likely the browser and our player will operate exactly as you'd like it to.

I encourage you to try our video platform for uploading and encoding your video. You're welcome to compare the service to Youtube. Tell us what you think and use what works best for you.

**Comment by De-M-oN** [comment]
if I would encode it into 800 kbit video it would look like garbage.
The CRF value of 17.5 is a low one and thus a high bitrate as result and a lower one with still good quality would be possible, but for the love of god - 800 kbit would look god awful.
And also: Thats not of a problem for a 100 mbit dedicated root combined with my 100 mbit internet. And flash shows perfectly fine that it actually is not of a problem at all. Because I can run the video with flash even without preloading it, I can watch it directly (which makes sense. 100 mbit/s is 4-times more than 25 mbit).
A reasonable bitrate for 2048x1152 at even high complexity video material is in your eyes 800 kbit? come on. Thats not going to work without macroblocks everywhere. Even not with vp9 2pass this just isnt going to work.
________
Youtube's 1440p60 videos have max average bitrate on vp9 codec of 15000 kbit and run fine at html5.
Youtube's 4k60 videos have often even more than 25 mbit average bitrate with high complexity codec vp9 and 60fps - runs fine
I have on youtube a video with resolution of 2800x1750 and has 50fps and it was very hard to compress, youtube gave it an average bitrate of 40 mbit (!) and that with VP9 - but it runs perfectly fine and smooth.

So youtube runs a 4k60 file with insane bitrate fine at html5 and vp9 and you want me to say the browser is overloaded with a 25mbit 2k 30fps h.264 file?

No its the buffering only buffering 2 seconds and then stops downloading. And that are only some mbytes for the first seconds on the car selection menu phase
Thats not an overload, thats just stopping downloading the video / loading the video in extremely small chunks.
It behaves like dash streaming with 2 second buffer.

**Comment by robwalch** [comment]
Yes. That is how Chrome behaves with your video. Create a page with a video tag, set src to your video and report the issue to Crome https://support.google.com/chrome/answer/95315?hl=en

**Comment by TheAncientDragon** [comment]
> if I would encode it into 800 kbit video it would look like garbage.
> The CRF value of 17.5 is a low one and thus a high bitrate as result and a lower bitrate (higher CRF) would still look good, but for the love of god - 800 kbit would look god awful.
> And also: Thats not of a problem for a 100 mbit dedicated root combined with my 100 mbit internet. And flash shows perfectly fine that it actually is not of a problem at all. Because I can run the video with flash even without preloading it, I can watch it directly (which makes sense. 100 mbit/s is 4-times more than 25 mbit).
> A reasonable bitrate for 2048x1152 at even high complexity video material is in your eyes 800 kbit? come on. Thats not going to work without macroblocks everywhere. Even not with vp9 2pass this just isnt going to work. I hope it was just a typo and you meant 8000 kbit at least.
> 
> Youtube's 1440p60 videos have max average bitrate on vp9 codec of 15000 kbit and run fine at html5.
> Youtube's 4k60 videos have often even more than 25 mbit average bitrate with high complexity codec vp9 and 60fps - runs fine
> I have on youtube a video with resolution of 2800x1750 and has 50fps and it was very hard to compress, youtube gave it an average bitrate of 40 mbit (!) and that with VP9 - but it runs perfectly fine and smooth.
> 
> So youtube runs a 4k60 file with insane bitrate fine at html5 and vp9 and you want me to say the browser is overloaded with a 25mbit 2k 30fps h.264 file?
> 
> No its the buffering only buffering 2 seconds and then stops downloading. And that are only some mbytes for the first seconds on the car selection menu phase
> Thats not an overload, thats just stopping downloading the video / loading the video in extremely small chunks.
> It behaves like dash streaming with 2 second buffer.

THey dont know how to do it.. 2021 and player still not buffering if you stop the video.. just some few seconds and done.. 
sadly we have to hang on such shame and porly made video player that almost anyone is using nowadays
