### ISSUE TITLE
no flash fallback for HE-AAC audio

### ISSUE THREAD

**Issue by fdambrosio** [jwplayer/jwplayer#1151]
JwPlayer 7.4 RC-2 have html5 support for audio HE-AAC in Chrome 50, but if I use Chrome < 50 jwplayer doesn't fallback to flash player, but return error. 
If I have video or audio with HE-AAC track, using Chrome 49 return error "HE-AAC not supported" instead of flash player. 

MAC OS 10.11.4 
Chrome 49.0.2623.112 (64-bit)
JwPlayer 7.4.0-RC-2 (CDN)

P.S. with Firefox 45 the player works in flash mode 

![jwplayer-heaac-error](https://cloud.githubusercontent.com/assets/2962823/14822322/85303c6a-0bce-11e6-826a-aea583e67435.png)

**Comment by esboyd** [comment]
Hi @fdambrosio! In order to to for the player to use flash, we would need reset the player and force the primary to flash. We do not actually know if HE-AAC is being used until after we try to play the media. What percentage of your streams use HE-AAC?

Thanks,
Eric

**Comment by robwalch** [comment]
Potentially we could fallback ahead of playing the stream if playlistItem.mediaType included the codecs. This would be similar to what we do for VP9 only DASH streams, but with a special case for skipping caterpillar in Chrome 49 or lower.

**Comment by fdambrosio** [comment]
We don't  know percentage of HE-AAC, but I expect that the player fallback to flash when needed

**Comment by fdambrosio** [comment]
there's news about this problem?

**Comment by fdambrosio** [comment]
@robwalch this will be fixed or we'll be unable to use jwplayer 7? (if we use jwplayer 7.2.4 return "Setup error")

**Comment by robwalch** [comment]
HE-AAC is supported in the latest version of Chrome 50.0.2661.94. There will not be a fallback feature for this. Updating Chrome resolves the issue.
