### ISSUE TITLE
Wrong mediaType reported

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#1153]
### Expected Behavior

Event mediaType should return `video` when HLS is video stream.

### Actual Behavior
On load mediaType reporting `audio` even tough video stream is provided. I found code which may causing this: https://github.com/jwplayer/jwplayer/blob/e7d8db4ff2664d2d67e4998694e535763e0efdcb/src/js/providers/html5.js#L1187

### Steps to reproduce

1. Create basic jwplayer instance
2. Add this playlist:
```"playlist": [{
            "file": "http://svpvod-vh.akamaized.net/i/2015/11/20151116_56499f1987e6d_vg01/,1280_720_3500,960_540_1500,640_360_800,480_270_500,.mp4.csmil/master.m3u8",
            "mediaid": 121031,
            "image": "http://imbo.vgtv.no/users/vgtv/images/87fe9113c19eb74ded9364611f298e58.jpg?t[]=904x508q50"
        }],```
3. Add logging for all events
```player.on('all', function() {
        console.log(arguments)
    });```
4. Check console results (screen):

![image](https://cloud.githubusercontent.com/assets/2443904/14849275/59370108-0c72-11e6-8ed0-5aad95bfc83f.png)

### Environment

- *iPhone 6, iPad, Macbook*
- *iOS, Safari OSX and other which plays HLS*
- *JW Player version | 7.3.4*

----------------------------------------------------------------------------------------

**Comment by robwalch** [comment]
Hi @artur-michalak. Are you setting preload to something in your setup as well? Is there a second mediaType event that reports video?

You can probably reproduce this behavior in 7.3.6 but have you tries 7.4.0? It's available in our beta and staging channels and is up on our CDN.

The videoHeight should be known by the time 'canplay' is emitted from the video tag. Maybe that's not the case with this stream on the version of iOS your testing with. We found it true on all browsers and devices except for Android.

**Comment by artur-michalak** [comment]
@robwalch preload is not set - we use default config there. I'll post whole configuration (expect key - pls provide your one). Main issue with this is that you're adding 'jw-flag-media-audio' which forces poster to always show.

Regarding JW 7.4 -> i'll test it but when will you release production version? It's quite important due to our internal release (i can't use beta on prod)

```html
<style>
    .wrapper {
        /*max-width: 640px;*/
        margin: 0 auto;
    }
    .responsive {
        margin-top: 40px; width: 100%; padding-bottom: 56.25%; height: 0;
        position: relative;
    }

    .responsive > div {
        position: absolute;
        left: 0; top: 0;
        width: 100%;
        height: 100%;
    }
</style>
<div class="embed-container responsive">
        <div id="player1"></div>
    </div>
<script src="//cdn.svp.schibsted.io/jw/7.3.4/player.min.js"></script>
<script type="text/javascript">
    jwplayer("player1").setup({
        "playlist": [{
            "file": "http://svpvod-vh.akamaized.net/i/2015/11/20151116_56499f1987e6d_vg01/,1280_720_3500,960_540_1500,640_360_800,480_270_500,.mp4.csmil/master.m3u8",
            "mediaid": 121031,
            "image": "http://imbo.vgtv.no/users/vgtv/images/87fe9113c19eb74ded9364611f298e58.jpg?t[]=904x508q50"
        }],
        "primary": "flash",
        "androidhls": true,
        "flashplayer": "//cdn.svp.schibsted.io/jw/7.3.4/player.flash.swf",
        "wmode": "transparent",
        "autostart": false,
        "width": "100%",
        "mute": true,
        "height": "100%"
    });
</script>
```
Here you can see how events are triggered (iPad iOS 9.3 - pressed play and paused after few seconds, other events are filtered out)
![image](https://cloud.githubusercontent.com/assets/2443904/14911322/011ad7d6-0df5-11e6-98b8-1a5e0ed97a13.png)

**Comment by robwalch** [comment]
7.4.0 has been released, it's in our staging channel. It will be available for download on May 10th once it's been promoted to the production channel. We have a patch in the work which will likely be the build that makes it to production by then.

For now you can test against 7.4.0 using the CDN url:
//ssl.p.jwpcdn.com/player/v/7.4.0/jwplayer.js

**Comment by artur-michalak** [comment]
Works well in 7.4.0 👍  We can use it on production then. 
Problem solved for me.
