### ISSUE TITLE
Question: how to hard code the "rtmp://xxx.cloudfront.com/live" into player and leave the filename in the "file" variable on the html

### ISSUE THREAD

**Issue by streamliveinfo** [jwplayer/jwplayer#1159]
I am trying to hard code the RTMP URL into the player. I only want to hard code the part "rtmp://xxx.cloudfront.com/live" into the player. Where should I make the modification? I want to keep the filename in the "file" variable on the html page

I am trying to edit this file: RTMPMediaProvider.as

        // Connect to RTMP server
        try {
            _connection.connect(application);
            sendMediaEvent(MediaEvent.JWPLAYER_MEDIA_LOADED);
        } catch (e:Error) {
            error("Error loading stream: Could not connect to server");
        }

to

        // Connect to RTMP server
        try {
            "rtmp://xxx.cloudfront.com/live";
            sendMediaEvent(MediaEvent.JWPLAYER_MEDIA_LOADED);
        } catch (e:Error) {
            error("Error loading stream: Could not connect to server");
        }

But it is not working.

your help is appreciated.

**Comment by robwalch** [comment]
The file comes from the PlaylistItem passed to the load() method. 

https://github.com/jwplayer/jwplayer/blob/master/src/flash/com/longtailvideo/jwplayer/model/PlaylistItem.as#L17

After hard coding the item are you still going to call "setup" to start the player? You'll still need to set "type" to "rtmp" for the rtmp provider to be selected.

**Comment by streamliveinfo** [comment]
I harcoded like you suggest but it does not seem to work

        if (!obj.levels && obj.file) {
            var singleLevel:Object = {
                file: "rtmp://xxx.cloudfront.com/live/",
                type: obj.type,
                label: obj.label
            };
            obj.levels = [singleLevel];
        }


My embed code is like this

<script type="text/javascript" src="./jwplayer.js" ></script>
<div id="myElement">Loading the player ...</div>
<script type="text/javascript">
    jwplayer("myElement").setup({

	playlist: [{
	image: "/assets/myVideo.jpg",
	sources: [{ 
			file: "espn"
		}]
	}],
height: 360,
primary: "flash",
width: 640,
autostart:true,
 rtmp: {
        bufferlength: 0.1
    },
    });
</script>

It is still loading the file: "espn" completely without using the rtmp in the hardcode

**Comment by robwalch** [comment]
If you don't care what's being passed in setup, why not just replace the entire constructor?

```as3
    public function PlaylistItem(obj:Object = null) {
        this.file = "rtmp://xxx.cloudfront.com/live/";
    }
```

I think that's all you need.

**Comment by robwalch** [comment]
Closing as this is not an issue with the player, but a general question about hacking the code base.
