### ISSUE TITLE
Question for play m3u8

### ISSUE THREAD

**Issue by prospdragon** [jwplayer/jwplayer#1179]
I have premium account of jwplayer.
And when I play m3u8 in my webpage using http://p.jwpcdn.com/6/11/jwplayer.js , it works well.
I build jwplayer as instructions and succeed to get jwplayer.js and jwplayer.flash.swf, and I replaced it with http://p.jwpcdn.com/6/11/jwplayer.js.

In other words, I replaced from 
`<script src="http://p.jwpcdn.com/6/11/jwplayer.js" type="text/javascript"></script>`
to
`<script src="jwplayer.js" type="text/javascript"></script>`

But video does not play anymore.
I've tried with mp4 instead of m3u8, it works well.

For fix this, please let me know what I have to do more.

**Comment by waxidiotic** [comment]
@prospdragon Since HLS playback is a feature that requires a [paid subscription](http://www.jwplayer.com/pricing) to JW Player, it is not supported in the open source version on this repo. It should work in browsers that natively support HLS, such as Safari and Edge, but will not work in Chrome, Firefox or IE.

**Comment by prospdragon** [comment]
I have a premium key;

<script src="MY COMPILED_jwplayer.js" type="text/javascript"></script>
<script>jwplayer.key="MY KEY"</script>

Is it impossible above code for play m3u8 ?

**Comment by waxidiotic** [comment]
@prospdragon The version of the player that you are compiling from this repo does not contain commercial functionality, such as HLS playback. You would need to either use a cloud-hosted player from your account dashboard, or download the production version from your dashboard and self-host it.

**Comment by prospdragon** [comment]
I understand.
Thank you so much!
