### ISSUE TITLE
Add Custom Buttons in Controlbar

### ISSUE THREAD

**Issue by noman720** [jwplayer/jwplayer#1182]
**UI** : 
- Add a repeat button in right of next button in controlbar

**Functionality** : 
- First click - single (current track) repeat
- Second click - playlist (all track) repeat
- Third Click - no repeat
- For every click on this button a callback should fired with repeat status and change the repeat icon.

**Comment by Snowbell92** [comment]
+1 on this. I'd like to add a resize player button (like youtube), and possible, seek controllers.

**Comment by johnBartos** [comment]
@msiddique Don't you have a plugin example for adding a button?

**Comment by robwalch** [comment]
See `addButton` documentation https://developer.jwplayer.com/jw-player/docs/javascript-api-reference/#jwplayeraddbuttonimg-tooltip-callback-id-btnclass
