### ISSUE TITLE
HLS Key request does not forward domain cookies

### ISSUE THREAD

**Issue by rdhunna** [jwplayer/jwplayer#1185]
### Expected Behavior

The key request should forward cookies set for the domain while using hls on chrome
### Actual Behavior

The Key request does not forwards cookies set for domain while using hls on chrome
### Steps to reproduce

Could not find a way to set withCredentials on XHR request for AES key. Is there a way to set this variable. Could you please expose it if there is none.
### Environment
- Windows/ Mac OS Chrome Browser

**Comment by robwalch** [comment]
Which version of JW Player are you using?

This is not supported with our Flash HLS renderer in 7.3. In 7.4 you can enable HTML5 playback of HLS in Chrome with a new "hlshtml" setup option. We do not attempt a request for the key with credentials. We can add that to the default request.

**Comment by rdhunna** [comment]
I was evaluating the 7.4 beta player and encountered this issue. I did reach out to support and was told to raise a issue here. It will be very helpful if you could add that as a configurable flag in the settings somewhere.

**Comment by rdhunna** [comment]
Hi @robwalch any resolution on this issue?

**Comment by robwalch** [comment]
There will be an option in 7.5 that adds "withCredentials" to HLS key requests.

A couple of questions:
1. Would you ever need credentials sent with manifest or segment requests?
2. Should requests that fail withCredentials be attempted again without?

**Comment by rdhunna** [comment]
Hi @robwalch  

As of now we do not need credentials sent with manifest or segment requests but this will be a good option to have; primarily to correlate CDN logs with the service (many CDN's allow you to log cookies that can be used for a variety of purposes). As far as re attempting requests that failed with withCredentials be attempted without credentials is concerned I don't think that would be a necessary use case for us.

**Comment by robsonrobi** [comment]
I am getting the same error, upgrading from 7.2.4 to 7.4.3 using hlshtml : true.
Trying to fetch the URL the error Cannot load M3U8 : 401 Unauthorized appears.
How can i handle that inside the provider.caterpillar.js ?

A Quickfix is needed.

**Comment by boryane** [comment]
I am also testing v7.4.3 in Chrome using Amazon Cloudfront signed cookies for private content distribution.

Currently, I am setting the cookies when the playlist loads, but those cookies are not passed in the Request header when individual segments are loaded.

For this to work correctly, I need a setting (or default behavior) to pass cookies to individual hls segment requests.

Presumably, a "withCredentials" property would suffice assuming that all cookies are sent on segment requests.

Is this the planned feature in v7.5?

**Comment by robwalch** [comment]
Yes. Adding credentials to requests is part of the plan for 7.5. For those who want to disable this behavior they will be able to set `withCredentials` to `false` on their video / playlist item.

**Comment by Apophenian** [comment]
Is there a timeline for 7.5?

**Comment by Apophenian** [comment]
Also, will this fix apply to the html5 and flash players?

**Comment by stoshniwal** [comment]
Saw the mention of "withCredentials" fix on 7.5 beta (7/8/2016) [release notes](https://developer.jwplayer.com/jw-player/docs/developer-guide/release_notes/release_notes_7/#version75). Is this fixed in that release for the html5 player?

**Comment by johnBartos** [comment]
@Apophenian The feature went in for our HLS HTML5 provider - Flash may already work but I'm not certain about that. Doesn't affect non-hls HTML5 videos

@stoshniwal Yeah its in! Just for HTML5 HLS, which is just on Chrome right now. Browsers which handle HLS natively (Safari, Edge) should do it already. Firefox will have support when we release HLS for it

**Comment by Apophenian** [comment]
Hi there, it looks like credentials aren't being set for DASH.  Is this something that will be looked into?

**Comment by parmarsanjay** [comment]
I am running into similar issue. What does "withCredentials" do? I don't see any documentation around that other than brief mention in releases notes of 7.5.x.

**Comment by robwalch** [comment]
For DASH, we only accept "withCredentials" as part of the drm config for license server authentication.

**Comment by parmarsanjay** [comment]
Thanks, Rob. Does this mean that for now, JW player doesn't work with CloudFront HLS content with signed cookies? I have to have HLS content on Cloud front as public URLS?

**Comment by robwalch** [comment]
@parmarsanjay no. That is for DASH, not HLS. With HLS when you specify "withCredentials" in the config, withCredentials should be set to true for all xhr requests.

**Comment by parmarsanjay** [comment]
Thanks, @robwalch.

**Comment by RafalLukawiecki** [comment]
I have the same or very similar issue with JW Player 7.9.3 Premium. Using CloudFront signed cookies, all works in Safari with HLS, but Chrome and Firefox DASH do not include the cookie when requesting the files in the playlist. Could you point me in the right direction, please? Thank you, very much.

**Comment by robwalch** [comment]
Playlist items or item sources must include `withCredentials: true` for the requests to be made with cookies. Please direct issues with this feature to support at jwplayer.com.

**Comment by RafalLukawiecki** [comment]
Thank you, @robwalch.

**Comment by RafalLukawiecki** [comment]
@robwalch I have contacted support and got a reply correcting my placement of "withCredentials": true to a position in the root of the player set-up. This made it work for HLS but it still does *not* work for DASH. Browser sends the signed cookie with HLS but it sends *no* cookies when requesting an .mpd file. On 1swt Dec 2016 you wrote, on this thread:

> @Apophenian For DASH, we only accept "withCredentials" as part of the drm config for license server authentication.

Does this mean that this functionality is not supported for any purposes other than DRM set-up? If so, it makes it impossible to use signed cookies with DASH videos. I would be very grateful if you comment on this and your earlier comment. Thank you very much for your help and my regards from Ireland.

**Comment by robwalch** [comment]
@RafalLukawiecki
Our shaka provider will apply `allowCrossSiteCredentials` to all requests when `withCredentials` is on the playlist item or globally in the top of the config.
