### ISSUE TITLE
IE8 not support

### ISSUE THREAD

**Issue by zjxcdut** [jwplayer/jwplayer#1192]
### Expected Behavior

Hope JW 7.4.2 can work in IE8.

### Actual Behavior

When I use IE8, the JWPlayer can not work and show a error ：Object does not support "bind" property or method. 

Is there anyway to solve this problem ?

THX

### Environment

- *Win 10 IE8*
- *JW 7.4.2*

**Comment by cpeterso** [comment]
HLS.js had a similar issue with IE8 when using a reserved keyword (in that case, `default`) as an unquoted property name: dailymotion/hls.js#422

**Comment by johnBartos** [comment]
Sorry, we don't support IE8! IE9 is the lowest we go in IE-land
