### ISSUE TITLE
no playable source found 

### ISSUE THREAD

**Issue by linminglu** [jwplayer/jwplayer#1193]
### Expected Behavior
it can not support on wechat browse .  and safari on the iphone。  test link。  www.uniit.com.cn/testrtmp/test.html
*Describe expected behavior*

### Actual Behavior

*Describe actual behavior*

### Steps to reproduce

1.
2.
3.

### Environment

- *hardware | device*
- *operating system | version*
- *JW Player version | url*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by linminglu** [comment]
sorry。link is www.uniit.com.cn/rtmptest/test.html

**Comment by esboyd** [comment]
@linminglu RTMP is not supported on mobile devices because it requires Flash. I suggest updating to JW7 and grabbing a Premium license key so you can use HLS everywhere. https://support.jwplayer.com/customer/portal/articles/1430189-about-hls-streaming

**Comment by linminglu** [comment]
@esboyd esboyd . how do I  get the premium license . Can U give me the link? tks

**Comment by esboyd** [comment]
@linminglu https://www.jwplayer.com/pricing/
