### ISSUE TITLE
Event hijacking - prevent postMessage

### ISSUE THREAD

**Issue by neilRGS** [jwplayer/jwplayer#1197]
I am experiencing a strange issue and one which did not happen when we were using JW Player v6.
This started after upgrading to JW Player version 7
Firefox and Chrome are showing same behaviour.

postMessage from sender to receiver (listener.html)  should be picked up by a window.eventListener.
postMessage sent a string which looks like this: "{ prop: 'cmi.suspend_data', value: 1567 }"

Instead, this is the event text which is showing in the console:
```
10:04:28.905 event data :  listener.html:70:4
10:04:28.905 {"type":"jwpsrv_position","playerId":"myPlayer","rect":{"top":248,"left":25,"width":376,"height":212},"iframeDepth":0,"coords":{"top":354,"left":25},"responseChain":"80632226101"} listener.html:71:4
```
The **type: jwpsrv_position**  suggests that jwplayer may be sending events which are preventing any others from getting through.
Communication from the listener (on the SCO LMS) to the webinar platform (sender) using postMessage does work

**Comment by robwalch** [comment]
JW Player 7 analytics use postMessage when the player is in an iFrame. The message is a JSON object with type "jwpsrv_position_response". This is used in conjunction with the position-companion.js script in the downloads zip that when added to the parent document allow tracking of player visibility.

As far as I know we are not preventing you from posting your own messages, or hijacking the event listener (especially if you are not using position-companion.js).

If you can provide a isolated example where your post message is not received by your listener with the player in the iFrame, we can investigate. It may be that you simply need to filter "jwpsrv_position_response" messages.

**Comment by neilRGS** [comment]
Hi Rob.  Thanks for getting back to me on this.
That is useful info.
As it turns out, my concern over what that was, was redirecting my focus from another area of my code which was not working properly.  I am communicating with a SCORM provision and there was an issue with the protocol.  I'd love to say 'customer' error, but I didn't check thoroughly enough :-)

You can close this one off now.

Cheers

Neil.
