### ISSUE TITLE
Uppercase HTTP in HLS playlist are breaking the stream

### ISSUE THREAD

**Issue by konradpietrzkiewicz** [jwplayer/jwplayer#1199]
### Expected Behavior

This issue is connected with the latest Akamai CDN update on HTTPS streams.
https://community.akamai.com/community/media-delivery/blog/2016/04/19/media-services-on-demand-33-release-preview

After updating some test properties in Akamai we noticed that they use "HTTP/HTTPS" with captial letters in playlist file:

example stream:
https://svpgeoswevod-vh.akamaihd.net/i/2014/10/20141022_5447a9fd681be_vg01/,1280_720_3500,960_540_1500,640_360_800,480_270_500,.mp4.csmil/master.m3u8

or

http://svpgeoswevod-vh.akamaihd.net/i/2014/10/20141022_5447a9fd681be_vg01/,1280_720_3500,960_540_1500,640_360_800,480_270_500,.mp4.csmil/master.m3u8

part of master file:

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3577000,RESOLUTION=1280x720,CODECS="avc1.64001f, mp4a.40.2",CLOSED-CAPTIONS=NONE
HTTPS://svpgeoswevod-vh.akamaihd.net/i/2014/10/20141022_5447a9fd681be_vg01/,1280_720_3500,960_540_1500,640_360_800,480_270_500,.mp4.csmil/index_0_av.m3u8?null=0

according to RFC this is allowed in uri scheme: http://tools.ietf.org/html/rfc3986#section-3.1

This could be cause of using indexOf("http") in JWPlayer for detecting streams which is case sensitive:

https://github.com/jwplayer/jwplayer/search?utf8=✓&q=indexof%28"http"%29

### Actual Behavior

cause of capital HTTP JWPlayer is requesting wrong url to playlist like:

Request URL:http://svpgeoswevod-vh.akamaihd.net/i/2014/10/20141022_5447a9fd681be_vg01/,1280_720_3500,960_540_1500,640_360_800,480_270_500,.mp4.csmil/HTTP://svpgeoswevod-vh.akamaihd.net/i/2014/10/20141022_5447a9fd681be_vg01/,1280_720_3500,960_540_1500,640_360_800,480_270_500,.mp4.csmil/index_0_av.m3u8?null=0 which is breaking the stream.

This is happening both for flash and HTML5 renderer.

Native HLS renderers (IE11, iOS, Andriod) are handling those streams correctly.

### Steps to reproduce

1. go to: http://demo.jwplayer.com/stream-tester/
2. use  as exmaple stream: http://svpgeoswevod-vh.akamaihd.net/i/2014/10/20141022_5447a9fd681be_vg01/,1280_720_3500,960_540_1500,640_360_800,480_270_500,.mp4.csmil/master.m3u8

### Environment

-  Desktop / Chrome/
- Windows
- 7.4.X

**Comment by cpeterso** [comment]
btw, these streams play correctly in the [HLS.js demo player](http://dailymotion.github.io/hls.js/demo/?src=http%3A%2F%2Fsvpgeoswevod-vh.akamaihd.net%2Fi%2F2014%2F10%2F20141022_5447a9fd681be_vg01%2F%2C1280_720_3500%2C960_540_1500%2C640_360_800%2C480_270_500%2C.mp4.csmil%2Fmaster.m3u8) but they hang iTunes.

**Comment by robwalch** [comment]
@pajong is looking in to it and will let you know if the fix makes it in to our next patch or minor rev.

**Comment by robwalch** [comment]
I have a fix for this that will go into our next patch. Thanks!

**Comment by robwalch** [comment]
The fix for this is in v7.4.3. It's on our beta and staging player channels, will go to production channel on Tuesday, and is available on the CDN at //ssl.p.jwpcdn.com/player/v/7.4.3/jwplayer.js

**Comment by johnBartos** [comment]
Closed since 7.4.3 is now live https://developer.jwplayer.com/jw-player/docs/developer-guide/release_notes/release_notes_7/#additional-74-releases
