### ISSUE TITLE
Player activation through iframe

### ISSUE THREAD

**Issue by neilRGS** [jwplayer/jwplayer#1225]
Hi.
When loading the player through an iframe (as one often does in a SCORM environment), the player will not autoplay in Chrome (or Canary). Instead, the user must click twice on the player, in order to activate it.

In Firefox, Opera and MS Edge, this behaviour is not present and autoplay works.

This points at the issue being with Chrome, but I'd appreciate confirmation of that.

Other pointers as that are that the status of the player is shown as 'playing', and it clearly isn't.

As you can imagine, from a usability perspective, this is horrendous behaviour, not least as it occurs is the browser most used.

I'll look forward to hearing back.

Neil.

**Comment by neilRGS** [comment]
The more I look at this, the more I am convinced that this is a Chrome issue, not a JW one.
This is not the same issue as the JW player size problem.
When loading through an iframe (as we would in SCORM applications), Chrome overlays the flash player with a layer requiring 2 clicks to start.

The two clicks business is present if autoplay is set to true.  The state of the player is set as 'playing' but the overlay stops that from happening - nothing is actually playing.  the first click changes state to 'paused' and the second sets to 'playing' and removes the overlay.

Iit only happens in Chromium-based browsers. Firefox, MS Edge, IE and Opera all autoplay without an issue.

Does anyone at JW have contacts on the Chromium team to whom this can be asked about?

Many thanks,

Neil.

**Comment by dannyfinks** [comment]
Hi @neilRGS - Chrome rolled out a feature a few versions ago that causes flash to be "throttled." This was a first step of them deprecating the flash plugin. You can read more about it here https://chrome.googleblog.com/2015/06/better-battery-life-for-your-laptop.html and there is a blog post that we followed up with on how the player handles flash throttling - https://www.jwplayer.com/blog/chrome-power-saving/

**Comment by neilRGS** [comment]
Hi Danny.
Thanks for getting back to me and providing that info.
It is much appreciated.

Very best regards,

Neil.

Neil McLeish
Software Development Engineer
 [cid:1566FC3F-4D22-4289-BFFF-0270C30D656C]
T:            +44 845 855 0550
M:           +44 785 400 2559
F:            +44 161 929 9055
E:            neil.mcleish@rgsit.com<mailto:neil.mcleish@rgsit.com>
            www.rgsit.com<applewebdata://E1548B09-C0ED-45A3-87B7-BC347B4F5B05/www.rgsit.com>

CONFIDENTIAL
The information contained in this email and any attachment is confidential. It is intended only for the named addressee(s). If you are not the named addressee please notify the sender immediately and do not disclose, copy or distribute the contents to any other person other than the intended addressee(s).

________________________________

**Comment by dannyfinks** [comment]
Anytime!
