### ISSUE TITLE
Errors thrown in event handlers are swallowed.

### ISSUE THREAD

**Issue by Guuz** [jwplayer/jwplayer#1226]
### Expected Behavior

The error is thrown as an uncaught exception, or at least logged by JW Player.

### Actual Behavior

The error is swallowed and there is no way to find out that an error occurred.

### Steps to reproduce

Run this code on a page with a licensed JW Player:
```js
const el = document.createElement('div');
el.id = 'myDiv';
document.body.appendChild(el);

jwplayer('myDiv').setup({
  file: 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4',
}).on('ready', e => {
  console.info('We will now throw an error...');
  // This error won't show up as an uncaught exception.
  throw new Error('Something has gone wrong.');
}).on('error', err => {
  // Nor will it show up here.
  console.warn('Some error has occured:', err);
});
```

### Environment

- Any browser
- Any OS
- JW Player version 7.2.4

**Comment by johnBartos** [comment]
Hey! Going to try and reproduce this. Btw you can set chrome dev tools to break on caught exceptions [like so](https://i.stack.imgur.com/ItvZj.png)

**Comment by robwalch** [comment]
Thanks. This bugs us too. @johnBartos's tip is great, but breaking on caught exceptions can be annoying when you're using libraries that throw exceptions on purpose, as part of a test for example.

This is by design - something we've had since v6. We need to execute callbacks safely in a try catch block to prevent user error from interrupting execution of our plugins. It hurts I know...

This behavior can be disables by setting a flag on the global `jwplayer` object:
```js
jwplayer.debug = true;
```

https://github.com/jwplayer/jwplayer/blob/master/src/js/utils/trycatch.js#L10

**Comment by robwalch** [comment]
As part of our follow up, this information should go in https://developer.jwplayer.com/jw-player/docs/developer-guide/api/javascript_api_introduction/

**Comment by Guuz** [comment]
Thanks for the feedback.
How about logging a warning when an error is swallowed? This makes it more developer friendly. Also I wouldn't want to run `debug` in production but i would still like to see my error logged there.

**Comment by johnBartos** [comment]
@Guuz I see your point - however, `console.warn` [isn't a standard](https://developer.mozilla.org/en-US/docs/Web/API/Console/warn) and I'd bet that most of our users do a lot of testing beforehand and don't plan on looking at the console in prod. I'll bring it up at standup today

**Comment by johnBartos** [comment]
Ok we talked it over, not going to `warn` because players in production are geared towards end-users, not developers. We don't want people to be concerned that jwplayer is tossing a bunch of warnings on their site despite everything functioning smoothly.
