### ISSUE TITLE
Captions move up when hovering video even when controls are disabled

### ISSUE THREAD

**Issue by andreasmcd** [jwplayer/jwplayer#1232]
### Expected Behavior

I've built my own controls and disabled the jwplayer controls (using api call setControls(false)).
When captions are enabled I'd expect them to always be rendered as if the built-in controls were hidden.

### Actual Behavior

When enabling captions, they are rendered as if the built-in controls are still active. So when I move the mouse off the video the captions move down (as if the built-in controls are hidden). When I move my mouse over the video the captions move up (as if the built-in controls are displayed). 

### Steps to reproduce

1. Create a jwplayer instance where controls are disabled.
2. Turn on captions.
3. Move mouse over video player and then off again and observe behavior.

See example:
http://codepen.io/andreasmcdermott/pen/EyVPzN

### Environment

- https://content.jwplatform.com/libraries/1vdCj5zH.js

**Comment by dannyfinks** [comment]
Hi @andreasmcd - thanks for providing this great example. We will investigate this issue and give you an update when we will prioritize it to be resolved.

**Comment by egreaves** [comment]
Resolved in https://github.com/jwplayer/jwplayer/pull/1337
