### ISSUE TITLE
possible 508 issues with textareas inside of sharing overlay

### ISSUE THREAD

**Issue by mrandrewmills** [jwplayer/jwplayer#1244]
Good afternoon, JWPlayer Developers

I would like to ask your advice and assistance in resolving potential 508 issues within the Sharing overlay, please.

According to HTML_CodeSniffer, a 508 scanning browser bookmarklet, there are four issues with the two textareas inside of the sharing overlay (i.e. the same two issues for both textareas).

1) This textarea element does not have a name available to an accessibility API. Valid names are: label element, title attribute. 

2) This form field should be labelled in some way. Use the label element (either with a "for" attribute or wrapped around the form field), or "title", "aria-label" or "aria-labelledby" attributes as appropriate.
### Expected Behavior

I expect the two textareas within the sharing overlay to have title attributes (e.g. title="sharing link", title="embedded iframe") to pass 508 compliance scan.
### Actual Behavior

The two textareas within the sharing overlay do not appear to have title attributes, labels, or aria-\* attributes that would help them pass a 508 compliance check.

`<div class="jw-sharing-row jw-sharing-link jw-reset">
  <span class="jw-sharing-cell jw-reset">
    <span class="jw-sharing-svg-row-icon jw-sharing-icon-link jw-reset"></span>
  </span>
  <textarea class="jw-sharing-text jw-reset" readonly="true">
    http://content.jwplatform.com/previews/BLZfMjbK-zUOz0EEv
  </textarea>
</div>
<div class="jw-sharing-row jw-sharing-embed jw-reset">
  <span class="jw-sharing-cell jw-reset">
    <span class="jw-sharing-svg-row-icon jw-sharing-icon-embed jw-reset"></span>
  </span>
  <textarea class="jw-sharing-text jw-reset" readonly="true">
    &lt;iframe src="http://content.jwplatform.com/players/BLZfMjbK-zUOz0EEv.html" width="320" height="260" frameborder="0" scrolling="auto"&gt;&lt;/iframe&gt;
  </textarea>
</div>`

Example output from https://support.jwplayer.com/customer/portal/articles/1409823-social-sharing-overlay#fndtn-code, directly under "Here is the overlay in action:" text.
### Steps to reproduce
1. Go to https://support.jwplayer.com/customer/portal/articles/1409823-social-sharing-overlay#fndtn-code.
2. Click on the Sharing button to reveal the Sharing overlay.
3. Use Inspect Element to examine the two textareas within the Sharing overlay.
### Environment
- \* JWPlayer 7.4.3 | https://support.jwplayer.com/customer/portal/articles/1409823-social-sharing-overlay#fndtn-code*

I've read the documentation re: customizing the Sharing Overlay, and although it looks possible to add new sharing sites through the Sharing API, I can't figure out how to modify the output of the two textareas to include a title attribute, label element, or aria attributes.

Am I missing something obvious, or is there a different approach I should take to resolve this issue?

Thank you,

Andrew

**Comment by johnBartos** [comment]
Great report, we'll be taking a look at this soon. I don't believe the API supports adding titles and labels - aria is on our roadmap but won't happen for a while

**Comment by mrandrewmills** [comment]
Good afternoon, JWPlayer Developers

I had time to dig into this issue more today, and have a _rough_ idea for a fix.  Since I can't find sharing.js in the plugins folder for this repo, I am unable to do the usual fork/fix/pull request approach.

Would presenting my idea here instead be acceptable?

Thank you,

Andrew

**Comment by johnBartos** [comment]
@mrandrewmills Go for it! Our sharing plugin repo is private so you can't do it yourself.

**Comment by mrandrewmills** [comment]
When I look at sharing.js, with pretty-print on, I see a function k(a).
 
~line 111 I read this line: 

e.setAttribute("readonly","true"), // this puts readonly="true" in the textarea output

Would it be possible to add this directly beneath that line:

	e.setAttribute("title",a),

If so, calling this: z = k("link"); gets you a textarea with a title attribute of "link".
And calling this: A = k("embed"); gets you a textarea with a title attribute of "embed".

I know it's crude, but I think it would suffice. Acceptable?

**Comment by mrandrewmills** [comment]
Perhaps this gist will it explain it better than my previous attempt?

https://gist.github.com/mrandrewmills/59730be0725c03cf340fef4e822a684d

**Comment by johnBartos** [comment]
Sorry for the delay! I'll see what we can do with this

**Comment by mrandrewmills** [comment]
Good morning, @johnBartos 

Any news?

**Comment by johnBartos** [comment]
@mrandrewmills We're busy testing our 7.5 release which has a lot of captions changes, we'll be looking at this afterwards

**Comment by mrandrewmills** [comment]
Good afternoon, @johnBartos and @egreaves 

I see 7.5.2 is available for download now, so I'm inferring that means testing has gone well.

Can you give me a ballpark idea when you will have time to look into this issue? My client is keen to put these 508 alerts behind them. Thank you.

**Comment by mrandrewmills** [comment]
May I please have an update on the status of this issue, gentlemen?

**Comment by johnBartos** [comment]
@mrandrewmills Yikes, forgot about this. We'll be implementing this within the next few weeks.

**Comment by johnBartos** [comment]
Resolved
