### ISSUE TITLE
Controls stay hidden on Windows RT devices

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/jwplayer#1247]
### Expected Behavior

As a user I want the controls to become visible after tapping a playing video.
### Actual Behavior

On a Microsoft Surface tablet the controls stay hidden and the only way to stop/pause playback is to reload the page.
### Steps to reproduce
1. Go to http://jwplayer.com/products/jwplayer
2. Start playback by clicking the play icon
3. Wait for the controls to disappear
4. Tap the video
### Environment
- Microsoft Surface II
- Windows RT 8.1
- 7.4.3

**Comment by dannyfinks** [comment]
@ChristiaanScheermeijer which browser were you able to reproduce this issue in? Was the Surface Tablet on desktop mode or surface mode?

**Comment by ChristiaanScheermeijer** [comment]
Hi @dannyfinks,

**which browser were you able to reproduce this issue in?**
Internet Explorer 11

**Was the Surface Tablet on desktop mode or surface mode?**
In both tablet and desktop mode.

**Comment by ChristiaanScheermeijer** [comment]
I've discovered this issue only occurs when JW Player uses Flash to render the video. Using the manual debug page I couldn't reproduce this issue in the first player, but in the `FLV Single with repeat:true` player I could.

I have a debug line in the tap callback and it seems this event is not triggered from video layer.

**Comment by dannyfinks** [comment]
Thank you for the additional information. We have an existing internal bug ticket opened surrounding this issue with pointer events with the flash provider (occurs in Edge on Win10 as well for surface tablets). I will provide you an update when I have more details on prioritization/fix of this issue.

**Comment by johnluther** [comment]
Hi, @dannyfinks. Is there any update on this bug?

Thanks--JL

**Comment by dannyfinks** [comment]
@johnluther no updates as of now, but I will sync up with @esboyd to discuss further

**Comment by ydelwiche** [comment]
This bug was still present in 7.10.7.

**Comment by Poopooracoocoo** [comment]
I have a Windows 10 laptop with a touchscreen and I sometimes use both. This gets annoying.
