### ISSUE TITLE
JW7 : Exactfit does not work when going fullscreen in flash mode

### ISSUE THREAD

**Issue by einthusan** [jwplayer/jwplayer#1251]
This has been extensively discussed and documented on the JW thread page @ https://support.jwplayer.com/customer/portal/questions/15985938-exactfit-does-not-work-when-going-fullscreen-in-flash-mode

I have created the issue in Github to reference this since I do not see a fix or bug report regarding this issue. However, a JW rep has said this will be fixed in 7.5 and has confirmed this from the engineering team at JW Player.

> I have just received word from our Engineering team that this issue is tentatively scheduled to be resolved in the next major release of our player, 7.5. Currently, we are expecting pre-release versions of 7.5 to be available for testing sometime this month.

**Comment by pajong** [comment]
@einthusan There will be a fix in 7.5. The work to fix this is in PR: https://github.com/jwplayer/jwplayer/pull/1252
