### ISSUE TITLE
CC button show on iPhone without setting Closed Captions (HLS)

### ISSUE THREAD

**Issue by Ultra7girl** [jwplayer/jwplayer#1254]
### Expected Behavior
CC button must be shown when setting Closed Captions only.

### Actual Behavior
CC button show on iPhone without setting Closed Captions. It's work when media file are .mp4 but not worked with m3u8

### Environment
iPhone 5/6
iOS 9.x
JW Player version 7.4.3: http://myaday.net/c/captions.php

----------------------------------------------------------------------------------------
I found same problem on you demo page
https://support.jwplayer.com/customer/portal/articles/1430240-hls-adaptive-streaming

**Comment by johnBartos** [comment]
Thanks for the report! We'll see if we can reproduce it

**Comment by Ultra7girl** [comment]
Hi @johnBartos  thanks for you answer.
