### ISSUE TITLE
Top-right button dock absorbs clicks to video

### ISSUE THREAD

**Issue by radium-v** [jwplayer/jwplayer#1256]
### Expected Behavior

The video should be clickable at the top of the container.
### Actual Behavior

The cursor changes from pointer to default and click events don't pass through to the video.
### Steps to reproduce
1. Load a player with a default skin.
2. Hover over and click on the upper quarter of the player.
### Environment
- Macbook Pro w/Retina
- OSX 10.11.5
- https://www.jwplayer.com/solutions/publishers-broadcasters/

![screen shot 2016-06-22 at 11 16 04 am](https://cloud.githubusercontent.com/assets/863023/16273288/0381c936-386f-11e6-8abd-e7cec37f6df1.png)

**Comment by johnBartos** [comment]
@radium-v what browser?

**Comment by radium-v** [comment]
I'm able to reproduce it in Chrome 51 and Firefox 47. The issue is present on Safari, but the cursor doesn't change so it's not as obvious where the deadzone is.

**Comment by dannyfinks** [comment]
Thanks. We have identified the issue and will update when we have prioritized a fix.
