### ISSUE TITLE
Video rewind is not working in chrome

### ISSUE THREAD

**Issue by tautvydasr** [jwplayer/jwplayer#1261]
I faced problem, what video rewind is not working on Chromium (Version 50.0.2661.102 Ubuntu 14.04 (64-bit)).  

### Expected Behavior

Then I press on progress bar it should rewind video to expected position.

### Actual Behavior

Then I press on progress bar the video starts from begining.

### Steps to reproduce

I faced this problem on livecodind.tv, for example: https://www.livecoding.tv/piotrpasich/videos/E7eVM-simple-registration-website-for-mentors-2

**Comment by johnBartos** [comment]
@tautvydasr I couldn't repro this on Chrome Version 51.0.2704.103 (64-bit) on OSX. It looks like Chrome has been updated - can you give this another go?

**Comment by johnBartos** [comment]
Feel free to reopen if you find this issue again
