### ISSUE TITLE
About jwplayer fullscreen

### ISSUE THREAD

**Issue by yizhigui** [jwplayer/jwplayer#1264]
my website have some webpage,jwplayer alse is used in some page,but have a webpage can't use fullscreen ,other webpage is ok,I think jquery's resize event affect it，but I‘m not sure, who can tell me,jwplayer'fullscreen will be affected  in which of the situations。

**Comment by waxidiotic** [comment]
I would suggest contacting our Support Team whom will be able to better assist you and your embed on your site.

If you are a customer of our Premium, Ads or Enterprise subscriptions, you can create a ticket by logging into your [Account Dashboard](https://account.jwplayer.com) and clicking on **Contact Support** in the _Support_ menu on the upper, right-hand corner of the page.

If you are a free customer, you can post to our [community forums](https://support.jwplayer.com/customer/portal/questions/new) and either one of our Support Engineers or a member of our developer community will be able to assist you.
