### ISSUE TITLE
Error loading media: File could not be played iOS

### ISSUE THREAD

**Issue by chihung93** [jwplayer/jwplayer#1275]
Using JWPlatform 7,Users are getting the error "Error loading media: File could not be played" on iOS ( but works fine in Android w/ HTML5). . Here is an my code : 

```

<html>
<head>
<script src="http://tv.tuoitre.vn/assets/c947721e/js/jwplayer7/jwplayer.js"></script>
<script>jwplayer.key="yl/yqfTaFkHTZsvJEK6NtJYZZujiAxc3knwh";</script>
</head>

<body>
<div id="container"></div>
<script>
jwplayer("container").setup({
file: "http://d28xjrpu39bs0f.cloudfront.net/bunny.mp4"
});
</script>
</body>
</html>
```
1. JWplayer 7 
2. Chrome 
3. iOS  8.0 , 9.0 ..vv all version

**Comment by fdambrosio** [comment]
Hi,
it works for me with 5S + ios 9.1 
http://codepen.io/fdambrosio/pen/XKRdgz

**Comment by trihung93** [comment]
I think this bug of version > 7.0 , because it works for me on  version 7.0

**Comment by johnBartos** [comment]
@trihung93 We'll look into this soon, but we currently have no issues with playback on iOS

**Comment by klouskingsley** [comment]
same on chrome 61.0.3163.98 android 6.0

**Comment by ajayadglobal360** [comment]
Hi i am facing same issue on safari desktop browser Version 12.0. it is working on chrome and all mobile device. but in safari, video will play first time if i refresh page then video will not play it is will show a error "Error loading media: File could not be played". and if i delete history of browser then refresh page again it will play. so i do not know why video play on history deleting. my jwplayer version is 7.10.7
here is my setup:
jwplayer("video-block-popup").setup({
			file: "<?php echo site_url(); ?>iffco.mp4",
			image: "<?php echo $this->data['themes_url']; ?>customize_theme/images/iffco-yuva-home-video-pupup.jpg",
			width: '100%',
			aspectratio: '14:9',
			stretching: "exactfit",
			events: {
				onTime: function (object) {
					if (object.position > object.duration - 1) {
						this.pause();
					}
				}
			}
		});
plz find screenshot for your reference 
![screen shot 2018-10-09 at 12 45 50 pm](https://user-images.githubusercontent.com/33024593/46652645-5598bd00-cbc1-11e8-847a-fd7980a14053.png)
