### ISSUE TITLE
Gracefully end live video on html5 with akamai CDN

### ISSUE THREAD

**Issue by konradpietrzkiewicz** [jwplayer/jwplayer#1279]
### Expected Behavior

Handle js error when live event is ended and child play lists are not available (returning HTTP 404)

### Actual Behavior

When playlist is no longer available html5 provider is causing js error:
(provider.caterpillar.js:1 Uncaught (in promise) TypeError: Cannot read property '0' of undefined(…))

console.log:
![image](https://cloud.githubusercontent.com/assets/1742524/16442937/13c09388-3dd6-11e6-9b14-4441139e7988.png)

network log:
![image](https://cloud.githubusercontent.com/assets/1742524/16442960/35d0752e-3dd6-11e6-8ffa-012967a48b3d.png)

HAR attached
[endofliveAkamaiCDN.zip](https://github.com/jwplayer/jwplayer/files/338679/endofliveAkamaiCDN.zip)

### Steps to reproduce

1. go to demo.jwplayer.com/stream-tester/
2. start live stream on akamai cdn
3. past stream url to stream tester
4. stop the live encoder
5. wait until akamai will start to send HTTP 404 on child playlist

### Environment

- opera / chrome
- Windows 10
-  7.4.4 / 7.4.3 HLS live on html5 provider

**Comment by johnBartos** [comment]
@konradpietrzkiewicz We're planning on more gracefully terminating streams in a future release when we perform some overhauls on our HLS implementation

**Comment by konradpietrzkiewicz** [comment]
I see on today beta 7.5 behavior is much better and I don't get js error in console/player error message.

**Comment by johnBartos** [comment]
Great! Expect some more improvements in the near future
