### ISSUE TITLE
Auto start don't work in Firefox

### ISSUE THREAD

**Issue by CodeMaschineX** [jwplayer/jwplayer#1284]
### Expected Behavior

Auto start audio stream.
### Actual Behavior

Auto play don't work in Firefox (v47.0.1), Windows 10 x64, you need to click on play button.
With JWplayer v7.3.6 auto start work as expected.
### Steps to reproduce

Run this code in Firefox:
`<div id="audioplayer">Loading...</div>
    <script type="text/javascript">
        var playerInstance = jwplayer("audioplayer");
        playerInstance.setup({
            file: 'http://stream.rtvbn.com:8522/;',
            width: 300,
            height: 40,
            type: 'mp3',
            autostart: 'true'
        });
        jwplayer().setVolume(40);
        jwplayer().on('play', function () {
            setTimeout(function () { var textAlt = document.querySelectorAll('#' + jwplayer().id + ' .jw-controlbar-center-group .jw-text-alt')[0]; if (textAlt) textAlt.innerHTML = 'Test'; }, 300);
        }); </script>`
### Environment
- Windows 10 x64 and Firefox 47.0.1 also x64
- JW Player version 7.4.4

**Comment by johnBartos** [comment]
@CodeMaschineX Thanks for the report, we'll take look and see if we can reproduce it

**Comment by johnBartos** [comment]
@CodeMaschineX We found a quick fix for you : set `preload: 'auto'` in your configuration. We'll be looking into the underlying issue for a real fix. What kind of stream is this? I don't believe we have seen this type before - any info on out would be a big help. Thanks!

**Comment by CodeMaschineX** [comment]
Stram type is audio/mpeg
`Content-Type: audio/mpeg
icy-br: 128
icy-notice1: <BR>This stream requires <a href="http://www.winamp.com/">Winamp</a><BR>
icy-notice2: SHOUTcast Distributed Network Audio Server/Linux v1.9.8<BR>
`

**Comment by fdambrosio** [comment]
We have same problem, thanks for the fix.

**Comment by wzzle** [comment]
We've got the same issue with mp4 in html5 player version 7.8.7 in firefox. The preload quick fix works for us.

**Comment by fdambrosio** [comment]
This issue will be fixed?
