### ISSUE TITLE
Config option for localStorage persistence

### ISSUE THREAD

**Issue by Hyddan** [jwplayer/jwplayer#1287]
### Expected Behavior

To be able to choose whether settings are persisted or not.
### Actual Behavior

Since the move from cookie storage to localStorage there doesn't seem to be any way to control this anymore.
### Alternatively

The config option could instead be an array of which settings should be persisted, overwriting the default ones if specified.

**Comment by johnBartos** [comment]
@Hyddan You can do this only with mute - the config option `"mute": "true"` will override any localstorage volume settings. For the other settings we want the user (i.e. their localstorage) to have priority. Whats your use case?

**Comment by Hyddan** [comment]
@johnBartos We use the JW player only as a provider in a larger system, controlling the player entirely through the Api and thus, we have the settings stored elsewhere. If we can't control whether the player will persist settings and use those there will be discrepancies. A user could for example save settings on our end, go to any other site that uses the JW player and fiddle around with the controls, then come back to us and watch a video and not get the configuration they chose earlier. Or even worse, if they have chosen auto bitrate switching on our end and this other site calls for instance setCurrentQuality() without their knowledge, when they come back to watch one of our videos they would no longer be in auto switch mode even though that would be expected.

**Comment by robwalch** [comment]
We used to support disabling persisted settings using `cookies: false`. If you want this functionality back it would be easy to add to [controller.js here](https://github.com/jwplayer/jwplayer/blob/master/src/js/controller/controller.js#L77). For example:

```js
  var storage = null;
  if (options.cookies === false) {
    storage = new Storage();
    storage.track(_model);
  }
  var config = new Config(options, storage);
```

**Comment by johnBartos** [comment]
@Hyddan `localstorage` is stored per domain, so players on other sites won't affect users on your site.

http://stackoverflow.com/questions/4201239/in-html5-is-the-localstorage-object-isolated-per-page-domain

**Comment by Hyddan** [comment]
@johnBartos Indeed, you're right, the different sites example may have been a bit ill conceived. We have since then tracked the issue we had that led to this ticket down to a combination of playing a multi bitrate stream, us setting the quality through the API (getting a qualityLabel stored) and switching to a single bitrate stream - this caused the player to crash (presumably because that stream didn't have a bitrate with the stored qualityLabel). When doing the same thing but clearing the localStorage before playing the second stream it did not crash.

@robwalch Yeah, we are aware of this. But perhaps I should have also mentioned that we have the commercial ads version and are not really interested in maintaining a deviating fork.
We could submit a PR for the feature if there is a chance it will get pulled into the main repo. If not, could you make an array of the tracked value public so it could be accessed from outside the player?
The way we see it this is a regression in the controllability of the player which is a shame because we really like the high level of flexibility but it is not a big deal as we have already worked around it. It would just be more preferable to be able to properly control the player behavior.

**Comment by jnatalzia** [comment]
Hi @Hyddan, given you've `already worked around this`, I'll be marking this as `answered`. Feel free to remove the label in the event that you need additional assistance. Thanks!

**Comment by Hyddan** [comment]
@jnatalzia, yeah, this can be closed.
