### ISSUE TITLE
Is there an example how to use jwplayer with angular?

### ISSUE THREAD

**Issue by RobbertWolfs** [jwplayer/jwplayer#1304]
Is there a good example how to implement jwplayer inside an angular application?
Or a good npm package or something?

Thanks

**Comment by johnBartos** [comment]
@RobbertWolfs No npm package (yet), but our portal team uses the player with Angular so I'll see if I can get an example from them

**Comment by johnBartos** [comment]
Let me know if this helps: https://github.com/jwplayer/jwdeveloper-demos/blob/master/demos/customization/feeds-angular-js/player/player.js

**Comment by RobbertWolfs** [comment]
I'll check and try this tomorrow.
Thanks for the response. I'll keep you posted.

**Comment by RobbertWolfs** [comment]
@johnBartos it worked for me :)

The problem was that we are trying to use the jwplayer inside a ngDialog and that the moment we called the jwplayer setup function it doesn't found the "id element" because the template of the ngDialog was not loaded yet..

So now I just call the jwplayer setup after the ngDialog template was loaded and it works fine 👍 

Thanks for the example.
Robbert

**Comment by johnBartos** [comment]
Great! Happy to help out

**Comment by RobbertWolfs** [comment]
@johnBartos any idea if there would come a npm package in the near future?

**Comment by johnBartos** [comment]
@RobbertWolfs It's something we've discussed before (and something I'd like) but I'm not certain what we intend to do about it. I'll bring it up next time I get the chance

**Comment by johnBartos** [comment]
Closing this out
