### ISSUE TITLE
AirPlay/ChromeCast does not work properly when using mobiles devices like iPad

### ISSUE THREAD

**Issue by einthusan** [jwplayer/jwplayer#1321]
### Expected Behavior

Casting from iPad should work without stuttering issues.

### Actual Behavior

Casting causes stuttering playback issues. This DOES NOT happen with JW 7.4.

### Environment

- iPad/iPhone and some other mobile devices
- JW 7.5 beta 2

**Comment by einthusan** [comment]
Also, a lot of users on our site have also mentioned that they cannot even see the "casting" button on the player. However, during an ad playback, it appears but disappears again after advertisement is done playing.

**Comment by johnBartos** [comment]
@einthusan Thanks again for the report - we'll look into it asap

**Comment by johnBartos** [comment]
Chromecast support is low on our priority list right now so there won't be a fix in for this release. The good news is that we'll be overhauling our Chromecast implementation in the coming weeks

**Comment by einthusan** [comment]
@johnBartos So can we confidently say 7.6 will have the overhauled implementation? Just as an approximation, what is the ETD for 7.6.

**Comment by johnBartos** [comment]
Not sure, I'll update when more cetain

**Comment by robwalch** [comment]
Unable to duplicate. Please provide a test page and reopen.
