### ISSUE TITLE
iOS/iPhone | audio + vtt | caption text is aligned to the left, with cutted text

### ISSUE THREAD

**Issue by fdambrosio** [jwplayer/jwplayer#1324]
### Expected Behavior 

With 7.5.0 it seems solved the problem of playing audio with vtt on iOS, but it seems there's a regression: 
on ios/iphone, when I play audio with captions, the player must go in fullscreen mode showing caption text centered on the screen.

### Actual Behavior

On iOS/iPhone player go in fullscreen mode but the caption text is aligned to the left, cutting part of the text

### Steps to reproduce

1. setup jwplayer with audio m4a + HLS + track .vtt file
2. go to the page with iPhone/iOS, turn on caption 
3. play going in fullscreen mode 

### Environment

- iPhone 5S
- iOS 9.3.2
- jwp 7.5.0 RC-1

demo: http://www.fdambrosio.net/test/player7/audio-750.html

### Screenshot 
![4e355922-475e-11e6-805d-7a7be96d71c7](https://cloud.githubusercontent.com/assets/2962823/16946061/09794744-4da8-11e6-94b7-cd5618581321.png)

**Comment by johnBartos** [comment]
@fdambrosio Thanks for testing out the RC, we'll look into this soon

**Comment by fdambrosio** [comment]
Thanks @johnBartos, 
I've already reported this issue with beta 1. 
I hope I will be fixed in 7.5.0 release.

**Comment by egreaves** [comment]
@fdambrosio Thanks for identifying this issue. Unfortunately, this fix will not make it into our 7.5.0 release, but will be addressed in an upcoming patch. I will update this issue with the patch version as soon as it's been prioritized.

**Comment by robwalch** [comment]
Looks OK to me in release. @fdambrosio can you update your test?

**Comment by fdambrosio** [comment]
@robwalch i've updated the test page with 7.5.0 final release, and bug is still here 

http://www.fdambrosio.net/test/player7/audio-750.html

Safari 
iPhone 5s 
iOS 9.3.2

**Comment by fdambrosio** [comment]
I'm testing 7.5.2 release and bug is still here

**Comment by robwalch** [comment]
I am able to duplicate this issue in the iOS simulator (iOS 9.2-5s and iOS 10-6s). The problem occurs only in fullscreen mode, not when displayed inline.

@fdambrosio this is a bug in iOS that you should report to Apple. It can be duplicated in a vanilla video tag setup like this (you might need to update the media url)

https://jsfiddle.net/pd8Ltn5c/2/ (https://jsfiddle.net/pd8Ltn5c/2/show/ on the iphone)
```html
<video crossorigin controls autoplay style="background:#000;">
<source src="//wowza-3.radioradicale.it:1935/aac-1/_definst_/2016/02/06/MP818669.m4a/playlist.m3u8" type="application/x-mpegURL">
<track label="English" kind="subtitles" srclang="en" src="//www.radioradicale.it/trascrizioni/8/4/1/2/2/841225.vtt" default >
</video>
```

**Comment by fdambrosio** [comment]
thanks @robwalch but audio hls + vtt doesn't work with video tag on Safari yet: http://www.fdambrosio.net/test/player7/safari-bug.html
Your jsfiddle code doesn't start player on Safari (Mac or iOS)

I've read (https://github.com/jwplayer/jwplayer/issues/1155#issuecomment-219448295) that Jwplayer use a vtt parser instead of adding the VTT files to the DOM. 
There's no problem until jwplayer 7.2.4

**Comment by fdambrosio** [comment]
Now I'm able to reproduce this issue using an mp3 file instead of HLS stream. 
I open a bug report to Apple

**Comment by johnBartos** [comment]
@fdambrosio Ok cool, going to close this out
