### ISSUE TITLE
Missing video tag on ready event

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#1329]
### Expected Behavior

When listening on "ready" event player should contain video tag.

### Actual Behavior

While using JW + Chrome (without flash) + HLS stream and listening on "ready" video element do not appear. This causing that our third party plugin fails. 
While i'm playing regular mp4 streams then everything works as intended what can suggest that issue relates to caterpillar provider.

### Steps to reproduce

1. Create player with this stream http://svpvod-vh.akamaized.net/i/2016/03/20160303_56d83080aef49_vg01/,1280_720_3500,960_540_1500,640_360_800,480_270_500,.mp4.csmil/master.m3u8
2. Open on chrome without flash
3. Attach player.on('ready', function() { debugger });
4. Check DOM (image attached)

![image](https://cloud.githubusercontent.com/assets/2443904/17020509/3a7130aa-4f42-11e6-8a47-c066b66d1779.png)

### Environment

- *hardware | MacBook*
- *operating system | OSX 11.10.5*
- *JW Player version | beta-7.5.0-rc.1 (//cdn.svp.schibsted.io/jw/7.5.0-beta/player.min.js)*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Hi @artur-michalak,

I'm able to reproduce this issue in development. This change was introduced when we moved provider loading out of setup. I'm looking into a fix that involves deferring ready until the initial playlist item is set and the provider has been loaded and updated the view.
