### ISSUE TITLE
Youtube and Facebook video playback on Android

### ISSUE THREAD

**Issue by ywj7931** [jwplayer/jwplayer#1334]
### Expected Behavior
Youtube and Facebook video playback on Android

### Actual Behavior

I cannot play youtube and facebook video on JWPlayer

### Steps to reproduce

PlaylistItem pi = new PlaylistItem.Builder()
                .file("https://youtu.be/NI7VH38xFlw")
                .title("BipBop")
                .description("A video player testing video.")
                .build();

### Environment

- Android
- Android
- 'https://mvn.jwplayer.com/content/repositories/releases/'
'com.longtailvideo.jwplayer:jwplayer-android-sdk:+'

**Comment by johnBartos** [comment]
@ywj7931 What android version and which browser?

**Comment by ywj7931** [comment]
@johnBartos Thanks for replying, My android is :minSdkVersion 16
        targetSdkVersion 24.

**Comment by ywj7931** [comment]
@johnBartos  Is it supported to play youtube and facebook video?

**Comment by johnBartos** [comment]
@ywj7931 Not the SDK version, the OS version. Check [this link](https://en.wikipedia.org/wiki/Android_version_history) for a list

**Comment by ywj7931** [comment]
@johnBartos I tried 6.0.1 and 5.1.1, I contacted the JWplayer support, they said currently JW player does not support youtube url playback, is that true?

**Comment by johnBartos** [comment]
We support it in 7 and 6, but you should be using 7

**Comment by ywj7931** [comment]
@johnBartos Just to clarify, I am using JW SDK for Android instead of JW player for web.

This is the link I asked the support before:
https://support.jwplayer.com/customer/portal/questions/16369986-youtube-mobile-playback-

**Comment by johnBartos** [comment]
@ywj7931 Oh this is for the JW SDK. This isn't the right place for the issue but I'll ask someone on that team

**Comment by ywj7931** [comment]
@johnBartos Sorry for the confusion, thank you very much for your help.

**Comment by johnBartos** [comment]
No problem. Just asked, we don't support youtube or facebook videos on the sdk

**Comment by ywj7931** [comment]
Gotcha, thank you
