### ISSUE TITLE
Error event rised on page change in Firefox

### ISSUE THREAD

**Issue by CodeMaschineX** [jwplayer/jwplayer#1336]
### Expected Behavior

Error event should not be raised
### Actual Behavior

Error event is raised
### Steps to reproduce
1. Use this code
   `<div id="audioplayer">Loading...</div> <script type="text/javascript"> var playerInstance = jwplayer("audioplayer"); playerInstance.setup({ file: 'http://stream.rtvbn.com:8522/;', width: 300, height: 40, type: 'mp3', preload: 'auto', autostart: 'true' }); jwplayer().setVolume(40); jwplayer().on('play', function () { setTimeout(function () { var textAlt = document.querySelectorAll('#' + jwplayer().id + ' .jw-controlbar-center-group .jw-text-alt')[0]; if (textAlt) textAlt.innerHTML = 'Test'; }, 300); }); 
   jwplayer().on("error", function () {
        console.log("error")
       }); </script>`
2. try to navigate from that page to any other page and error event is raised
### Environment

Windows 10 x64
Firefox 47.01 x64

**Comment by johnBartos** [comment]
@CodeMaschineX What version of the player are you using? We saw this bug in a previous version but put a fix in for it recently.

**Comment by CodeMaschineX** [comment]
I'm using JW Player v7.50 last release version

**Comment by robwalch** [comment]
If this is still a problem in Firefox 50 and you can copy the error details, I'd recommend [opening an issue with Mozilla](https://bugzilla.mozilla.org/)

I don't want to run JavaScript on "beforeunload" to workaround this browser specific issue. Let me know if and how the error interrupts UX on your site(s).

The DIY approach to preventing it would look something like:

```js
window.addEventListener('beforeunload', function() {
    jwplayer().remove();
});
```
