### ISSUE TITLE
Replace SRT module with vttParser

### ISSUE THREAD

**Issue by hghazzi** [jwplayer/jwplayer#1343]
Parse SRT with vttParser and deprecate srt module

src/js/providers/tracks-mixin.js

**Comment by robwalch** [comment]
This is done, no? If so please add version it was completed in to milestone and close.

If there are additional steps to complete please comment.

**Comment by hghazzi** [comment]
@robwalch No it isn't. The PR #1342 was where I saw the TODO for it, and created a tech debt issue for it. 

https://github.com/jwplayer/jwplayer/blob/064a0e162b9e1dad736916f9b7f17abc2165d020/src/js/controller/tracks-loader.js#L67
