### ISSUE TITLE
HLS live multiple audio |  audio is not loaded.

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#1346]
### Expected Behavior

Change audio track at any time.
 
### Actual Behavior

Changing audio tracks is only possible within the first 1-5 minutes. If you change the audio track, sound disappears and the player only downloads video files.

playlist.m3u8:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="pl",NAME="Polski",DEFAULT=YES,AUTOSELECT=YES,URI="chunklist_w1768395325_b131072_ao_slpl_t64UG9sc2tp.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="English",DEFAULT=NO,AUTOSELECT=YES,URI="chunklist_w1768395325_b131072_ao_slen_t64RW5nbGlzaA==.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=2000000,NAME="720p",CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=1280x720,AUDIO="aac"
chunklist_w1768395325_b2000000_vo_slpl_t64NzIwcA==.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=500000,NAME="360p",CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360,AUDIO="aac"
chunklist_w1768395325_b500000_vo_slpl_t64MzYwcA==.m3u8
```

**Video stream:**
media_w1768395325_b500000_vo_slpl_t64MzYwcA==_x.ts
**Audio stream:**
media_w1768395325_b131072_ao_slen_t64RW5nbGlzaA==_x.ts
media_w1768395325_b131072_ao_slpl_t64UG9sc2tp_x.ts

Status: Player works fine.
![ OK ](https://s32.postimg.org/ljv3drv2d/Capture.png)
Status: Audio files are not loaded to the player.
![ OK ](https://s31.postimg.org/obwf8dbxn/Capture2.png)

### Steps to reproduce

1. Run a stream with multiple audio tracks
2. After 5-10 minutes to change the audio track

### Environment
- *operating Windows / OSX
- *JW Player 7.5.0 
- *Wowza 4.5.0

**Comment by johnBartos** [comment]
@mtoczko Great report, I'll get back to you with an update soon. Are there any console errors?

**Comment by mtoczko** [comment]
@johnBartos  I don't have any error.

**Comment by johnBartos** [comment]
Are you sure that your audio tracks have more than 5 minutes of playback?

**Comment by johnBartos** [comment]
Also, what browser are you using?

**Comment by mtoczko** [comment]
Windows: Firefox 57, Chrome 52 - Flash 22
OSX: Chrome 51, Safrafi 9.1.1 (Safari does not have this issue)

> Are you sure that your audio tracks have more than 5 minutes of playback?
I'm talking about streaming live, VoD works fine.
After reloading the player works well.

**Comment by mtoczko** [comment]
This morning I did another test, Live & DVR to work properly. The problem occurs only when streaming live, lose synchronization of video and audio when you change the audio track.

**Comment by johnBartos** [comment]
@mtoczko Apologies for the delay, I'll try and get some answers for you soon

**Comment by johnBartos** [comment]
@mtoczko Multi-track audio is an HLSv4 feature that we haven't implemented yet. v4 support is on the roadmap and we will get around to it but there's no fix for you today.
