### ISSUE TITLE
Feature request: Prevent default behavior when clicking a related video

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/jwplayer#1349]
### Requested Behavior

As a developer I want to be able to prevent the default behavior when a users clicks on a related video. Same goes for the auto advance functionality.

**Example:**

A developer uses JW Player in a single page application and wants to navigate the user to a new page which plays the 'related' video.

### Actual Behavior

The player always loads the 'related' item in the existing player instance.

### Possible solution

```
relatedPlugin.on('play', function (event) {
  
  // call to preventDefault
  event.preventDefault();

  // or to stop
  this.stop();
});
```

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
@ChristiaanScheermeijer What do you specifically want to do by overriding play? We don't have plans to expose the play method but maybe we can hack something together

**Comment by johnluther** [comment]
@johnBartos , @ChristiaanScheermeijer is working with us on JW Showcase, which is a single-page application. You can see an example at https://tv.jwplayer.com/

**Comment by ChristiaanScheermeijer** [comment]
Hi John, currently I hook into the play event from the related plugin to
navigate to a different page. But before the navigation I still see the
player starting to play the related video. If there was a way to prevent
the player from loading the related video this wouldn't be the case.

Thanks!

Op 1 aug. 2016 17:46 schreef "John Bartos" <notifications@github.com>:

**Comment by johnBartos** [comment]
@ChristiaanScheermeijer I believe you're in luck - there's a config option for related called `onclick`, which has two modes: `play` and `link`, where link redirects the user instead of playing the video. This also controls the autoplay behaviour

Your config block would look like:
````
{
    "related": {
        "onclick": "link"
    }
}
````

Check this out (scroll down to the `code` tab)
https://support.jwplayer.com/customer/portal/articles/1483102-related-videos

**Comment by ChristiaanScheermeijer** [comment]
thank you @johnBartos, I have tried the `onclick: 'link'` option, which I somehow totally missed, but I'm having trouble defining the link.

The related feed comes directly from the JW Platform so I'm not able to add a link (dynamically) to each related video. I would like to prevent that content publishers need to add these links manually in the portal.

**Comment by johnBartos** [comment]
Closing out
