### ISSUE TITLE
JWPlayer Throwing Error in Vivaldi Browser Versions

### ISSUE THREAD

**Issue by mholzschlag** [jwplayer/jwplayer#1356]
### Expected Behavior

Video should begin play with no errors
![type-error-video](https://cloud.githubusercontent.com/assets/443708/17435908/c1e152a4-5ac8-11e6-91ab-4b02d65310bb.PNG)

### Actual Behavior

Player shows TypeError: Cannot read property "buffered" of undefined (see attachment)

### Steps to reproduce

1. Open http://tv.lrytas.lt?id=14640147271463559449
2. Wait until advertisement has ended
3. Main video starts

### Environment

Issue confirmed for:
Vivaldi 1.1.453.59 Final (32bit)
Vivaldi 1.2.485.14 Snapshot (32bit)
Chromium 51 (32bit)
Tested on Windows 10x64
Another user confirmed for Lubuntu

Video plays in:
Chrome 50.0.2661.102 (32bit)
Opera 37.0.2178.43 (32bit)
Opera 39.0.2234.0 (32bit)

**Comment by johnBartos** [comment]
Vivaldi doesn't support Media Source Extensions, which we use to play HLS stuff. We don't officially support this browser so this isn't likely to change until they add support. Force the player to Flash and your videos should play.

````
{
    "primary": "flash"
}
````

Should do it.

Here's a previous issue related to Vivaldi: https://github.com/jwplayer/jwplayer/issues/1180

**Comment by johnBartos** [comment]
Closing this out, feel free to talk with us some more on Gitter if you want to try and hack a solution

**Comment by mholzschlag** [comment]
Thanks @johnBartos this is very helpful! Will follow up if necessary and very much appreciate the helping hand.

**Comment by nifgraup** [comment]
@johnBartos Vivaldi does support Media Source Extensions

**Comment by Cqoicebordel** [comment]
@johnBartos Yep, confirmed, Vivaldi does support Media Source Extensions.
Also, note that Vivaldi is built on top of Chromium, so it supports virtually the same things that Chromium supports.
So I think this bug should be reopened.

**Comment by johnBartos** [comment]
Hey guys I'll install Vivaldi and poke around when I get the chance but I'm pretty busy trying to get 7.7 out the door. 

@Cqoicebordel We use feature detection when we can, MSE included
