### ISSUE TITLE
[7.5.2] mp3 duration not detected on Android 4.1.2

### ISSUE THREAD

**Issue by BrentBaccala** [jwplayer/jwplayer#1358]
Duration of MP3 files doesn't detect correctly on Android

### Expected Behavior

Here's a page displayed in Firefox on Ubuntu Linux:

![Ubuntu screenshot]
(https://cloud.githubusercontent.com/assets/5731463/17465887/785ae1a0-5c9d-11e6-9d7c-713b55f0f938.png)

### Actual Behavior

Here's how it displays on my cellphone in landscape mode:

![Android screenshot](https://cloud.githubusercontent.com/assets/5731463/17465905/c4b43c40-5c9d-11e6-9dbc-1156001d8023.png)

Notice that the MP3 duration, on the right hand side of the jwplayer (in audio mode), displays on Ubuntu as 04:05, but on Android as 00:00.  The other differences are just because of the smaller screen size (I think).

### Steps to reproduce

Load http://www.freesoft.org/biblia/B01C050.htm

**Comment by dannyfinks** [comment]
@BrentBaccala this is because the Android browser is likely unable to preload any metadata about the audio until playback begins. You can take a look at this article for further information - https://support.jwplayer.com/customer/portal/articles/2200669-video-preload.

**Comment by BrentBaccala** [comment]
@dannyfinks I suspected that.  Of course, I can figure the duration of the file in advance.  Can anybody advice me how to modify my Javascript to set the duration "manually"?

**Comment by johnBartos** [comment]
@BrentBaccala Try this:

````
    jwplayer().on('ready', function () {
        document.querySelector('.jw-text-duration').innerHTML = 'the duration';
````

It works for only one player on the page but the concept is the same - select the `.jw-text-duration` on the player and set `innerHTML` to your duration.

**Comment by BrentBaccala** [comment]
@johnBartos Thank you!  That worked.  I know it's a kludge, but at least it looks right.

**Comment by johnBartos** [comment]
@BrentBaccala No problem! What's the actual correct duration of your video?

**Comment by BrentBaccala** [comment]
@johnBartos  Well, there's several hundred audio files.  I accidentally used one for the images and a different one for my posting yesterday.  For the longer one, mp3info reports either 04:31 or 04:29, depending on whether the -F (Full scan of entire file) option is specified.  jwplayer reports 04:30 on Android (once it starts playing) and 04:32 on Firefox.  I'm not sure what (exactly) to specify!

**Comment by johnBartos** [comment]
@BrentBaccala I don't know how the Android player works but we get the duration from the HTML5 video tag. I'd assume that's the correct one.

**Comment by johnBartos** [comment]
Closing this out
