### ISSUE TITLE
HLS caption not enabled in version 7.5.2 for chrome

### ISSUE THREAD

**Issue by yanglinz** [jwplayer/jwplayer#1359]
### Expected Behavior

Given a HLS stream with `#EXT-X-MEDIA:TYPE=SUBTITLES`, I want JWPlayer to display the closed caption toggle, even when `hlshtml` flag is passed to the video setup config. 

### Actual Behavior

Closed caption toggle shows up if the `hlshtml` flag is not passed and `flash_adaptive` is the provider. But with `hlshtml` flag passed, the closed caption toggle does not show up in the video ui. 

### Steps to reproduce

1. Serve the following html locally and open it in chrome (I'm on version 51)

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>HLS First</title>
</head>

<body id="home">
  <div id="player"></div>
  <script src="/jwplayer.js"></script>
  <script>
    var jwplayer = window.jwplayer;
    jwplayer.key = 'foo';

    // video url taken from demo page https://developer.jwplayer.com/jw-player/demos/toolbox/hlsv4-audio-tracks/
    var videoUrl = 'https://wowzaec2demo.streamlock.net/vod-multitrack/_definst_/smil:ElephantsDream/ElephantsDream.smil/playlist.m3u8';
    var playerInstance = jwplayer('player');
    playerInstance.setup({
      file: videoUrl,
      hlshtml: true
    });
  </script>
</body>
</html>
```

2. Observe that when `hlshtml: true` is omitted from the setup parameter, video provider is `flash_adaptive` in chrome and that closed caption ui toggle shows up in the video player.

3. Observe that when `hlshtml: true` is passed into the setup parameter, video provider is `caterpillar` and that closed caption ui toggle does not show up in the video player.

### Environment

- Macbook Pro
- OSX 10.11.6 | Chrome 51
- JWPlayer version 7.5.2

----------------------------------------------------------------------------------------

As far as I know, this is a feature listed here https://support.jwplayer.com/customer/portal/articles/1430189-about-hls-streaming, specifically the bullet point that says: `WebVTT subtitle tracks through #EXT-X-TYPE=SUBTITLES`. Let me know if I can provide more info :)

Thanks!

**Comment by johnBartos** [comment]
@yanglinz SMIL is a flash only thing, so they won't work in HTML 😬

Use VTT captioning if you can - we've done a lot of work on them recently. You can sideload a VTT file too, so your video doesn't need them embedded

**Comment by rudemateo** [comment]
@johnBartos the "smil" you're seeing in the example is simply part of the stream url, a byproduct of wowza streaming engine, but it is actually an HLS .m3u8 playlist

**Comment by egreaves** [comment]
Hello @yanglinz,

Our HLS HTML5 provider does not yet support subtitles tracks in HLS streams - we intend to add support in v7.9.0 of the player. 

As you've identified, though, it is supported by our flash provider, but with browsers planning to block flash in the near future, we understand the need to gain parity and will be working assiduously to make this happen.

**Comment by yanglinz** [comment]
@egreaves Got it, thanks for the update!

**Comment by rudemateo** [comment]
We have "sidecar" WebVTT and DFXP caption files available as well. The problem is that since our HLS files have "embedded" segmented WebVTT, the player ends up playing two caption files in some cases. And there doesn't seem to be an easy way to tell the JWPlayer to choose only one, or to fallback to the sidecar captions if the html5 hls parser can't currently play the embedded ones.
