### ISSUE TITLE
RSS feeds with incorrect mime-type get rejected

### ISSUE THREAD

**Issue by hkrutzer** [jwplayer/jwplayer#1365]
I'm dealing with a backend that cannot easily set the correct mimetype for an RSS playlist feed.

There seems to be code that should perhaps handle this? https://github.com/jwplayer/jwplayer/blob/master/src/js/utils/ajax.js#L163

But the feed is rejected nonetheless.
### Expected Behavior

RSS feeds with incorrect mime-type still get recognized as RSS.
### Actual Behavior

Error loading playlist: Not a valid RSS/JSON feed
### Steps to reproduce

Use an RSS feed with incorrect mime type.
### Environment
- JW Player version | 7.4.4+commercial_v7-4-4

**Comment by johnBartos** [comment]
@hkrutzer What browser are you using, and can you give us a sample page or the playlist URL itself?

**Comment by hkrutzer** [comment]
Chrome 52 on OSX. Here's an example: http://www.holland.com/web/videoplayerservlet?query=47870,48104,47840
