### ISSUE TITLE
Bufferlength issue

### ISSUE THREAD

**Issue by jimeshgajera** [jwplayer/jwplayer#1378]
_I want to buffer my long length audio file. I have set attribute bufferlength but it will not help_

```
var playerInstance 	= jwplayer("container");
playerInstance.setup({
 playlist: [{"file":"http://localhost/walkmymind/app/webroot/img/audio/1471599395chittiyan.mp3","image":"http://localhost/walkmymind/app/webroot/img/audio/1464423855images2.jpg","title":"Dipesh","mediaid":"1"}],
 rtmp: {
        bufferlength: 4
   }
 });

```
### Environment
- https://content.jwplatform.com/libraries/QRf83JpJ.js

**Comment by johnBartos** [comment]
@jimeshgajera Maybe increasing the buffer length isn't the solution for your issues. As far as I know `bufferlength` is working fine but you can modify the code yourself:

https://github.com/jwplayer/jwplayer/blob/master/src/flash/com/longtailvideo/jwplayer/media/RTMPMediaProvider.as#L468
