### ISSUE TITLE
Custom skin no longer loaded in 7.5.x

### ISSUE THREAD

**Issue by pixelchutes** [jwplayer/jwplayer#1387]
### Expected Behavior

Providing a skin configuration directive _with_ a skin URL should load the custom skin file, regardless of the skin's name. With a custom skin URL defined, it should always get loaded.

### Actual Behavior

Naming your custom skin "seven" prevents your skin's CSS file from ever being loaded. Upgrading to JW Player v7.5.x+ broke our custom skin delivery which we also named: "**seven**"

Sure, we can rename it to "seven_custom" or something else, but the CSS URL directive was completely ignored due to the name of the custom skin matching the player's new default skin? 

What will happen when JW Player v8.0.0 comes out in the future with a new default skin, and happens to chose a skin name a customer was already using, and their skin's CSS randomly stops loading?

### Steps to reproduce

1. Create a JW Player instance 
2. Provide a custom skin configuration, name it "seven" and provide the URL to your custom seven skin:
    
    ```js
    skin: {
        name: 'seven',
        url: 'https://domain.com/path/to/custom/skins/seven_custom.css'
    }
    ```
3. Load the page and watch as your skin's CSS file is never loaded.
4. (optional) Rename the custom skin to "seven2" or "seven_custom", refresh, and see your CSS get loaded as expected.

Perhaps related? https://support.jwplayer.com/customer/portal/questions/16376249-jwplayer-7-5-use-self-hosted-provider-js-files

### Environment

- Mac / Chrome stable (v52)
- OS X 10.11.6
- JW Player v7.5.2

**Comment by dannyfinks** [comment]
@pixelchutes which version were you using previous to 7.5.2? I checked various versions of 7.x.x and this has always been the case.

**Comment by robwalch** [comment]
@pixelchutes does your skin extend the rules in the built in seven skin? Even if we load you're CSS we will not remove the `jw-skin-seven` rules already added to the DOM by default.

You're right we are not loading `skin.url` when `skin.name` matches a the name of a skin already built into the player. This is not new behavior though, so I'm not sure how this would have worked in any version of 7. It was never intended to.

https://github.com/jwplayer/jwplayer/blob/2bfc1bc75256f49a2799bb5b38f9e85db3780a71/src/js/controller/setup-steps.js#L194

**Comment by johnBartos** [comment]
@pixelchutes To expand on this, the Seven skin is compiled (with webpack) into the player, meaning that `.jw-skin-seven` styles are in the DOM before we even read the configuration.

https://github.com/jwplayer/jwplayer/blob/e09122d3ebf8a05c02aece121e8201e11f3dd63d/src/css/jwplayer.less#L42

**Comment by pixelchutes** [comment]
Sorry, to clarify, jumped from 7.3.3 > 7.5.2. The name change (to "seven") occurred at that time, but the custom styles (yes, @robwalch, that extend the default) suddenly failed to load.

It was a simple pattern for us to define our skin URL and have it load, was shocked to find our extended skin URL was bypassed due to our name!

**Comment by robwalch** [comment]
We'll have to look at treating the explicit setup `skin.url` separately from `skin.name`. The name is used to set the player's jw-skin class name. The url is a css file you want us to load and inject in the DOM. Makes sense.
