### ISSUE TITLE
The speed of video changed while playing

### ISSUE THREAD

**Issue by elhay-av** [jwplayer/jwplayer#1393]
### Expected Behavior

Video will play in normal speed 

### Actual Behavior

from 13s video playing speed increased 

### Steps to reproduce

1. [open jwplayer-tester](http://demo.jwplayer.com/stream-tester/)
2. play this link https://qatestlab.vod-download-01.perfectomobile.com/qatestlab/3961456658556144367a6d6155473349524153347964306a31514b44792b346d69505032543948716976493d/7c2db86c0a3c602a096b23c0c79ed8c6e6ff66238a1f5b9dff8478575e0fcb08.flv
3.  from 13s the speed changed

### Environment

- *Chrome 52.0.2743.116 (64-bit) | Mac*
- *OSX | 10.11.6*

** in VLC it work as expected (playing in normal speed)

**Comment by johnBartos** [comment]
@elhay-av Thanks for the report, that's pretty funny. I'll look into it soon

**Comment by johnBartos** [comment]
Not sure why this is happening but I can't reproduce it with other streams. Due to Flash being killed by Google very soon (end of September) we're not going to look into it. Re-encode it to .mp4 and it should work fine.
