### ISSUE TITLE
Duplicated subtitles on Safari

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#1405]
### Expected Behavior

Subtitles displayed only once

### Actual Behavior

Subtitles are duplicated

### Steps to reproduce

1. Open http://www.aftenposten.no/verden/STUCK-ep-1-Nar-doden--On-the-verge-of-death-603793b.html in Safari Desktop
2. Turn of EN subtitles (if turned off)
3. Subtitles are duplicated
![image](https://cloud.githubusercontent.com/assets/2443904/18386050/8b63ecf4-7694-11e6-8396-4867ce255518.png)

Playlist config:
![image](https://cloud.githubusercontent.com/assets/2443904/18386071/b2da7dd4-7694-11e6-81df-b87b239245fd.png)

### Environment

- *hardware | device* Desktop
- *operating system | version* OSX
- *JW Player version | url* 7.5.0

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
Thanks for the report, we'll look into this when we get the chance

**Comment by johnBartos** [comment]
@artur-michalak Try using the v7.6.1 player, I believe this issue is fixed there. I tried copying your player but couldn't find where you were initializing it.

**Comment by artur-michalak** [comment]
Thanks for quick reply. I checked and you are right - bug was identified and fixed in version 7.5.2 - https://developer.jwplayer.com/jw-player/docs/developer-guide/release_notes/release_notes_7/
