### ISSUE TITLE
With custom .smil file, JW Player sometimes stops with error on resize

### ISSUE THREAD

**Issue by IsaacSchemm** [jwplayer/jwplayer#1419]
### Expected Behavior

When playing a custom .smil file pointing to three RTMP streams (on a Limelight CDN), and when quality is set to "Auto", JW Player should keep playing when it gets resized.
### Actual Behavior

When using a custom .smil file (http://www.lakora.us/jwplayer-smil-resize-issue/custom.smil), JW Player stops playing once its width crosses a certain threshold, with "Error loading stream: ID not found on server."
This does not occur when quality is not set to "Auto".
### Steps to reproduce
1. Go to http://www.lakora.us/jwplayer-smil-resize-issue/
2. Play the second stream on the page
3. Increase the width of the box that the player is in

(The first stream gets a .smil file directly from a Wowza server, and this works correctly.)

Note: IE/Edge don't support the resize: both CSS property, so you won't be able to resize the box - try in another browser instead.
### Environment
- Firefox 48 on Windows 10
- Flash 23
- JW Player 7.6.1

**Comment by johnBartos** [comment]
@IsaacSchemm Thanks for the test page. I'm not sure what's going on here but I don't believe it's a problem with the player if the Wowza stream is working - have you confirmed that all your endpoints are valid?

**Comment by IsaacSchemm** [comment]
Yes, the individual streams are valid, or at least, they play correctly. I can also manually switch between them in the player on the test page (using the HD icon), and that works fine.

**Comment by robwalch** [comment]
This format is no longer supported.
