### ISSUE TITLE
Localization of captions labels

### ISSUE THREAD

**Issue by johanberonius** [jwplayer/jwplayer#1421]
### Expected Behavior

Localization of strings related to captions should probably be possible.
### Actual Behavior

There are some hard-coded language strings in English.
### Steps to reproduce

Hardcoded strings I found:
1. "Off" https://github.com/jwplayer/jwplayer/blob/49ebf2ecfa93cd4c67f345af750e53f79abd3aa5/src/js/controller/model.js#L371
2. "Unknown CC" https://github.com/jwplayer/jwplayer/search?q="Unknown+CC"
3. "Off" https://github.com/jwplayer/jwplayer/blob/9cebe7c64ec604bcedb5952ffe3f07dc2be83a35/src/js/controller/captions.js#L139

Should possibly be present in `Defaults.localization`
https://github.com/jwplayer/jwplayer/blob/master/src/js/api/config.js#L23
### Environment
- JW Player version 7.7.0-beta.1

**Comment by johnBartos** [comment]
Hey @johanberonius, looks like you've done a lot of work for this already. Want to go a bit further and make a PR? If you need a bit of assistance I'd be happy to help.


Localization is a property on the model so it should be easy to access.
1. In `model.js`, you should have access to localization via `this.localization`
2. In `caption.js`, use `this._model.localization`

2. `tracks-mixin.js` doesn't have access to the model, but the providers it mixes with do. Going to have to take a bit of a deeper look into this one.

**Comment by johanberonius** [comment]
I have not written any code to fix this. I just found the strings and translated them in place in my local copy of the minified release build.

**Comment by robwalch** [comment]
Currently we have language mapping for Audio Tracks and RSS parsing:

https://github.com/jwplayer/jwplayer/blob/c7405ce694e18377c82c08b42a50b351e3a2daad/src/js/utils/language.js
https://github.com/jwplayer/jwplayer/blob/c7405ce694e18377c82c08b42a50b351e3a2daad/src/js/parsers/mediaparser.js#L27
