### ISSUE TITLE
Volume slider disappears when changing volume in IE11

### ISSUE THREAD

**Issue by davidjeliba** [jwplayer/jwplayer#1428]
### Expected Behavior

The volume slider should remain visible when changing the volume.
### Actual Behavior

The volume slider disappears when changing the volume. The volume still changes but the container disappears.
### Steps to reproduce
1. Hover over volume indicator to bring up the volume slider
2. Click and drag on the rail (div with class .jw-rail)
### Environment
- Windows 8.1
- JW Player versions tested: 7.4.4 and 7.6.1

**Comment by johnBartos** [comment]
I was able to reproduce this. It looks like the slider is hiding itself immediately when grabbed. I'll update when I get more info on a fix but this may be an issue with IE11 itself.

**Comment by adinapoli** [comment]
Hey guys, we have been recently hit by this as well. Any update on whether this is an issue with IE11 itself or something the JW team can solve? Many thanks!
