### ISSUE TITLE
Full width controlbar

### ISSUE THREAD

**Issue by kultz** [jwplayer/jwplayer#1431]
I'm trying to make a full-width controlbar for JW 7 as you see in the images(for full screen mode, small controlbar looks a bit inefficient):
I tried to style .jw-controlbar class but didn't work out
This is the default controlbar style which is not full width

![This is the default controlbar style which is not full width]
(http://pasteboard.co/images/5K7kgPWM1.png/load)

This is the one which fits to the player edges
![This is the one which fits to the player edges]
(http://pasteboard.co/images/5Kb0YMHEl.png/load)

Any idea how can i do this ?

**Comment by johnBartos** [comment]
@kultz The default controlbar style (i.e. `Seven`) is full width - that player is using the Bekle skin. It also has less styling so it's easier to customize.

**Comment by johnBartos** [comment]
Feel free to reopen if you find some issues with a skin (or have some improvements on working with them)
