### ISSUE TITLE
[enhancement] Inline Video Playback in Safari 10/iOS

### ISSUE THREAD

**Issue by fdambrosio** [jwplayer/jwplayer#1432]
Hi , I would suggest to enhance jwplayer playing inline videos on Safari 10 (iOS)

New Safari 10 allow vides to play inline, as reported on this changelog: 
"When the webkit-playsinline property is specified, Safari on iPhone allows videos to play inline. Videos without the property will commence playback in fullscreen, but users can pinch close on the video to continue playing the video inline"

**Comment by dannyfinks** [comment]
Take a look at the 7.7.0-beta1 where we have added the ability to play inline for Safari. We will also be working on the ability to autostart for mobile in the near future.

**Comment by johnBartos** [comment]
Going to close this out since we're already working on it
