### ISSUE TITLE
Error build jwplayer 7.7.0-rc.2

### ISSUE THREAD

**Issue by jamejiraju** [jwplayer/jwplayer#1449]
Hello,

I build it so many times on Windows 10 and I receive errors as in the picture. I think it only builds on OS X. You can send me a solution to resolve this issue. 

![error](https://cloud.githubusercontent.com/assets/18496193/18878556/4ed5dc3c-84fb-11e6-9842-bb62378b7c37.png)

Thank you very much for your help.
Kind regards,

**Comment by johnBartos** [comment]
Does the build still complete? `fsevents` isn't required for the player to work.

**Comment by jamejiraju** [comment]
I think it isn't complete, although the assets will be available in the bin-release folder. You can see the screenshot below. I wonder that is the player will work correct?
![after-build](https://cloud.githubusercontent.com/assets/18496193/18918841/3f79c228-85c6-11e6-8d28-f66d2a802e56.png)

**Comment by johnBartos** [comment]
@jamejiraju It should work fine. You can ignore the Flash stuff if you don't want to build that
