### ISSUE TITLE
React Js and JW Player

### ISSUE THREAD

**Issue by mrbarde** [jwplayer/jwplayer#1455]
### Expected Behavior

I want to stream videos with JW Player on my platform, I am loading JW with React Js.

### Actual Behavior

But when I load the player i get a console error saying that JW player is not a function.

### Steps to reproduce

This is how I implemented JW player with React JS

`var  jwplayer = require('../../../assets/plugins/jwplayer-7.6.1/jwplayer.js');

loadPlayer(){
    var {ui} = this.props;
    var {camera} = ui;

    jwplayer(this.state.playerEl).setup({
        sources: [{
            file: camera.src,
        }],
        streamer: camera.streamname,
        provider: 'rtmp',
        aspectRation: '16:9',
        width: '100%',
        rtmp: {
            bufferlength: 3
        },
    });
}`

### Environment

- Dell Laptop
- Windows
- JW Player 7

Thanks in advance.

**Comment by johnBartos** [comment]
@mrbarde `jwplayer is not a function` means you haven't required the player properly. You're on the right track though - this is what you need to do:

- Initialize the player on `componentWillMount()` (alternatively: `componentWillUpdate`, etc. but keep something on the state that will let you know when the player is there). You don't want to call `jwplayer(...)` on each state change.
- Destroy the player when the component unmounts

What are you using to compile your JS? Webpack will make your life pretty easy - you can alias your `jwplayer` package, making your require statement just `require(jwplayer)`.

https://webpack.github.io/docs/configuration.html#resolve

**Comment by mrbarde** [comment]
@johnBartos I followed your direction but I still get the same error saying that jwplyaer is not a function and yes I am using webpack and writing in ES6.

**Comment by mrbarde** [comment]
@johnBartos I finally found the cause of my problem, I had  a loader for jwplayer set in webpack like so
`,
			{
		        test: /jwplayer.js$/,
		        loader: 'expose?jwplayer'
		    }`
I honestly don't know the relevance of having a loader for it so i took it out, and it worked, thanks for your help.

**Comment by johnBartos** [comment]
@mrbarde From what I understand the `expose-loader` takes a variable already known to webpack and puts it on the global scope. Since `jwplayer.js` wasn't already known to webpack it exposed it as undefined. A good takeaway may be to make our own jwplayer loader so it's easier to do stuff like this.

**Comment by johnBartos** [comment]
Closing this out. I think we'd like to have a React guide though.

**Comment by iDVB** [comment]
+1 React guide

**Comment by eagsalazar** [comment]
+1 with 'create-react-app'.  I couldn't get this working at all.

**Comment by sbbird** [comment]
+1 React guide

**Comment by johnBartos** [comment]
@sbbird https://github.com/micnews/react-jw-player

These guys do it right

**Comment by sbbird** [comment]
@johnBartos Great, thank you.
