### ISSUE TITLE
IMA mute functionality in JW 7.7 RC 3

### ISSUE THREAD

**Issue by maxisatwork** [jwplayer/jwplayer#1459]
### Expected Behavior

Instantiating JW Player setup using the configuration option {mute: true} should suppress all sound output from the player (including sound generated by preroll ads) until further user interaction.

### Actual Behavior

In pervious versions of JW Player (7.5, 7.6,) instantiating the player with {mute: true} will correctly result in a muted player instance, including suppressing sound from ads, so long as the player's primary render mode is set to HTML5. However, if we use Flash as the primary environment, then some additional calls are required to mute a preroll IMA ad. This is as follows:

```
var tag = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=" + Math.floor(Math.random()*10000000);

var player = jwplayer('my_video').setup({
    primary: "flash",
    file: 'http://content.jwplatform.com/videos/Wf8BfcSt-kNspJqnJ.mp4',
    advertising: {
        client: 'googima',
        schedule: {
            "myAds": {
                "offset": '00:00:00:000',
                "tag": tag
            }
        }
    },
    mute: true
});

player.on('adImpression', function(){
    player.setMute(true);
    if (player.getPlugin != undefined){
        var ima = player.getPlugin("googima");
        if (ima && ima.mute != undefined){
            ima.mute(true)
        }
        var vast = player.getPlugin("vast");
        if (vast && vast.mute != undefined){
            vast.mute(true)
        }
    }
});
```

In JW 7.7 rc3, the returned object for player.getPlugin("googima") no longer has the mute() function present. As such, the googima ad will autoplay with sound enabled, despite the JW Player instance having been setup with {mute: true}.

Is there another method of muting googima ads available within JW 7.7?

Any help here would be much appreciated, thanks!

### Environment

- *Chrome*
- *OSX*
- *JW Player 7.5.2, 7.6, 7.7 rc3*

**Comment by johnBartos** [comment]
@maxisatwork Thanks for the report! We're already aware of this and it will be fixed in time for the release.

**Comment by maxisatwork** [comment]
Great to hear - thank you very much for the quick response.
