### ISSUE TITLE
Capture/Save/Record a video playing on JWplayer

### ISSUE THREAD

**Issue by mayank250004** [jwplayer/jwplayer#1465]
Jwplayer working fine on android device but i want to save or record a video which is currently playing on JWPlayer so is it possible ? 

if yes then how?

**Comment by johnBartos** [comment]
@mayank250004 No it's not possible through the player - however, you can inspect the dom and copy the `src` attribute for the `<video>` tag. Only works for simple videos like `.mp4` though - live streams access files from a server via manifest (`.m3u8`, etc) files. Some videos may also be encrypted which will prevent playback, unless you have the key, of course.
