### ISSUE TITLE
Wrong right-click menu position on IE

### ISSUE THREAD

**Issue by TVS-Bruno** [jwplayer/jwplayer#1466]
### Actual Behavior

On a right clicking during a playback, the menu appears far away of the mouse position. It's only on IE and when a video plays.
### Steps to reproduce
1. Play a video on IE (11)
2. Right click on it
3. The menu doesn't appear behind the mouse
### Environment
- Windows (7)
- JWPlayer 7 (7.7.0)
- IE (11)

**Comment by johnBartos** [comment]
@Bruno-Tvtrip I'll ask if there's a reason we haven't fixed this but it's super low priority since it's IE11/W7
