### ISSUE TITLE
"Unknown playback error" with DASH in 7.7.0

### ISSUE THREAD

**Issue by mattcoz** [jwplayer/jwplayer#1468]
This DASH video plays in all previous versions of JW Player, using the latest 7.7.0 I get an "Unknown playback error".

https://www.arclearn.com:8443/jwplayertest-captions.jsp?version=7.7.0
https://www.arclearn.com:8443/jwplayertest-captions.jsp?version=7.6.1

**Comment by dannyfinks** [comment]
@mattcoz we're looking into the issue with your stream and I will get back to you when I have more details

**Comment by mattcoz** [comment]
@dannyfinks Thanks!

**Comment by mattcoz** [comment]
It's a bug in Shaka. It tries to determine the manifest type by issuing a head request and checking the Content-Type header. If the header includes the character encoding in addition to the mime type it fails. I've submitted a pull request with a fix on their GitHub page.

**Comment by dannyfinks** [comment]
Apologies @mattcoz I meant to get back to you earlier today. That did seem to be the issue. We put your manifest into an .mpd which seemed to play fine. Thanks for following up with Shaka on that. I will keep a lookout for the resolution of that issue on our end so we can let you know in advance when we update to the latest version of Shaka.

**Comment by dosercz** [comment]
I have a same problem with JW Player 7.7.0 and streaming server Wowza 4.4

**Comment by johnBartos** [comment]
@dosercz It's a bug in Shaka, the library we use to play Dash videos. See the PR @mattcoz made against their repo: https://github.com/google/shaka-player/pull/546
