### ISSUE TITLE
Documenting how to remove UI (Playlist) overlays

### ISSUE THREAD

**Issue by ghost** [jwplayer/jwplayer#1477]
Hello everyone,

I've been searching on the [JWPlayer API Reference](https://developer.jwplayer.com/jw-player/docs/developer-guide/api/javascript_api_reference/) and [JWPlayer Configuration Reference](https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/) and I am unable to find anything on removing the Playlist UI and "Next UP"-UI on JWPlayer 7.7. Is there any documentation on this?

Settings the nextupoffset to 0 does not stop the nextup ui from displaying, maybe this should be changed too?

Sorry for not following the guidelines since this is not a bug.

**Comment by fdambrosio** [comment]
Hi, 
try this: 
```
.jw-releated-dock-btn .jw-overlay {
  display: none !important;
}
```

**Comment by johnBartos** [comment]
@StrategistXIV To turn the Playlist UI off (including the dock button) use the config property `visualplaylist: false`.

````
jwplayer('player').setup({
    visualplaylist: 'false'
});
````

We don't have a config to disable the Next Up tooltip. What's your use case for hiding these overlays? We'd like to know more about how developers are using these new features.

**Comment by StrategistXIV** [comment]
@johnBartos Thanks a lot for your response, this seems like a clean solution!

My usecase for removing the NextUp Tooltip is because we have video's with builtin subtitles. Because the Tooltip shows 10 seconds before, the last 10 seconds on subtitles is not completely readable anymore. (We embed the subtitles for reasons, but I can imagine there are also parties that use video's with embedded subtitles from external parties)

Sorry for my late reply!

**Comment by basdirkse** [comment]
I also need to have the 'next-up' removed from my player, is there now a config setting available?

**Comment by StrategistXIV** [comment]
I saw this MR (https://github.com/jwplayer/jwplayer/pull/1640) but for me this does not fix things yet. I tried to set the showNextUp: false in the players configuration, but this did not help sadly enough.

**Comment by fdambrosio** [comment]
We need to completely remove nextup tooltip because we use playlist for long events splitted in multiple files, so we haven't a real playlist. 
The previous  code: 
```
.jw-releated-dock-btn .jw-overlay {
  display: none !important;
}
```
does not work with 7.9

**Comment by fdambrosio** [comment]
I've fixed using 
`visualplaylist: 'false'` 
and
` .jw-nextup { display: none; }`

**Comment by johnBartos** [comment]
@StrategistXIV Not great that your embedded subtitles are blocked but there's not much we can do about it - the user can always dismiss the tooltip also

@basdirkse Nope

@fdambrosio Lots of UI & CSS changes in 7.9, thanks for the update. If I make a Wiki page with common hacks like this can you contribute this and other hacks you've created? I think it would be useful for people with similar questions and help us target pain points to resolve.

**Comment by fdambrosio** [comment]
of course @johnBartos I'll be glad to contribute with this and more hacks

**Comment by CIB-Video** [comment]
> I've fixed using
visualplaylist: 'false'
and
.jw-nextup { display: none; }

@fdambrosio 

I am adding this code to the .html and the .css of the skin?

**Comment by simsketch** [comment]
Using the following combination of css and player config worked for me:
```
.jw-nextup {
	display:none;
}
```
```
jwplayer('div').setup({
"playlist": [{
    "file":"video1.mp4"
}, {
    "file":"video2.mp4"
}],
//the important bit
nextupoffset: -1,
```

**Comment by Craft4u** [comment]
@fdambrosio i set it , but it can't help for nextup button, only for playlist tooltip. How i can hide nextUp button ?

**Comment by Craft4u** [comment]
so anyone help me ?

**Comment by johnBartos** [comment]
@Craft4u Which button? If you want to hide the "next up display" (the thing which pops up 10s before the end of the video), set `nextUpDisplay: false` in your top-level configuration.

```
jwplayer().setup({
    nextUpDisplay: false
});
```

**Comment by Craft4u** [comment]
@johnBartos I mean button in the bottom of player near volume control.
