### ISSUE TITLE
JWPlayer 7.7.0 import with Typescript and Webpack

### ISSUE THREAD

**Issue by marcusgraf** [jwplayer/jwplayer#1483]
Hi

at the moment we use your jwplayer 7.6.1 via typescirpt and webpack. 
We Import the player with this line:

`var jwplayer: any = require("vendor/jwplayer");`

But with version 7.7.0 this doesn't work anymore. The player is undefined in this case.

In your release notes you wrote, that you Improved compatibility with RequireJS. 

Can u give me a quick tip whats the best way to include the jwplayer now with typescript and webpack. 

Thanks a lot!

**Comment by johnBartos** [comment]
Can you paste your webpack config?

**Comment by marcusgraf** [comment]
Webpack Config:

var path          = require('path');
var webpack       = require('webpack');
var precss        = require('precss');
var autoprefixer  = require('autoprefixer');
var cssnano       = require('cssnano');
var modernizr     = require('modernizr-loader');
var WebpackConfig = require("webpack-config");

var config = {
    path: {
        dist: path.join(__dirname, 'static/hash/'),
        outputPublic: '/static/javascripts/'
    },
    assetHashFilename: 'assets-javascript.json'
};

module.exports = new WebpackConfig().extend("webpack.base.config").merge({
    entry: {
        'bootstrap/common': './common/static/src/typescript/bootstrap/common.ts',
        'bootstrap/commercials': './common/static/src/typescript/bootstrap/commercials.ts',
        'bootstrap/article': './article/static/src/typescript/bootstrap/article.ts',
        'bootstrap/video': './video/static/src/typescript/bootstrap/video.ts',
        'bootstrap/live': './live/static/src/typescript/bootstrap/live.ts',
        'core': './common/static/src/typescript/core.ts'
    },

    output: {
        publicPath: config.path.outputPublic,
        filename: '[name].[chunkhash].js'
    },

    plugins: [
        // https://github.com/webpack/docs/wiki/optimization#multi-page-app
        new webpack.optimize.CommonsChunkPlugin('core', 'core.[hash].js'),

        // Asset-Hashing
        function () {
            this.plugin("done", function (stats) {
                var assetHashWithoutStaticFolder = stats.toJson().assetsByChunkName;
                var assetHashWithStaticFolder    = {};
                Object.keys(assetHashWithoutStaticFolder).map(function (key) {
                    assetHashWithStaticFolder[key] = "javascripts/" + assetHashWithoutStaticFolder[key];
                });

                var fs = require('fs');
                if (!fs.existsSync(config.path.dist)) {
                    fs.mkdirSync(config.path.dist);
                }
                fs.writeFileSync(
                    path.join(config.path.dist, config.assetHashFilename),
                    JSON.stringify(assetHashWithStaticFolder)
                );
            });
        }
    ],


    postcss: function () {
        return [
            precss,
            autoprefixer({browsers: ['last 2 versions']}),
            cssnano({zindex: false})
        ];
    }
});

And our webpack.base.config:

var path    = require('path'),
    webpack = require('webpack');

module.exports = {
    // Dependencies
    resolve: {
        root: [
            path.join(__dirname, 'common/static/src/typescript/'),
            path.join(__dirname, 'common/static/src/javascript/components/')
        ],
        extensions: ['', '.ts', '.js'],
        alias: {
            'vendor/bonzo': path.join(__dirname, '/common/static/src/javascript/components/bonzo/bonzo.js'),
            'vendor/qwery': path.join(__dirname, '/common/static/src/javascript/components/qwery/qwery.js'),
            'vendor/bean': path.join(__dirname, '/common/static/src/javascript/components/bean/bean.js'),
            'vendor/lodash': path.join(__dirname, '/common/static/src/javascript/components/lodash/lodash.js'),
            'vendor/q': path.join(__dirname, '/common/static/src/javascript/components/q/q.js'),
            'vendor/reqwest': path.join(__dirname, '/common/static/src/javascript/components/reqwest/reqwest.js'),
            'vendor/lazysizes': path.join(__dirname, '/common/static/src/javascript/components/lazysizes/lazysizes.min.js'),
            'vendor/scrollMonitor': path.join(__dirname, '/common/static/src/javascript/components/scrollMonitor/scrollMonitor.js'),
            'vendor/logentries': path.join(__dirname, '/common/static/src/javascript/components/logentries/le.js'),
            'vendor/fastclick': path.join(__dirname, '/common/static/src/javascript/components/fastclick/fastclick.js'),
            'vendor/webcomponents': path.join(__dirname, '/common/static/src/javascript/components/webcomponentsjs/webcomponents-lite.min.js'),
            'vendor/picturefill': path.join(__dirname, '/common/static/src/javascript/components/picturefill/picturefill.js'),
            'vendor/sinon': path.join(__dirname, '/static/test/javascripts/components/sinonjs/sinon.js'),
            'vendor/jwplayer': path.join(__dirname, '/common/static/src/javascript/vendor/jwplayer/jwplayer.min.js'),
            'Modernizr': path.join(__dirname, '/common/static/src/javascript/modernizr.json'),
            'vendor/liveTicker/client': path.join(__dirname, '/live/static/src/javascript/components/cazzo-culo/client.js'),
            'eventemitter2': path.join(__dirname, '/common/static/src/javascript/components/eventemitter2/eventemitter2'),
            'vendor/la-party': path.join(__dirname, '/common/static/src/javascript/components/la-party/EventSystem.js'),
            'vendor/homad': path.join(__dirname, '/common/static/src/javascript/vendor/homad/homad.js')
        }
    },

    externals: ['curl'],

    module: {
        loaders: [
            {
                test: /\.ts$/,
                loader: 'ts-loader'
            },
            {
                test: /\.html$/,
                loader: "html"
            },
            {
                test: [/\.css$/],
                loaders: [
                    'style',
                    'css',
                    'postcss'
                ]
            },
            {
                test: /modernizr\.json$/,
                loader: "modernizr"
            },
            {
                test: [/\.scss$/],
                loaders: [
                    'style',
                    'css',
                    'postcss',
                    'sass'
                ]
            }
        ],

        noParse: [
            /\/sinon\.js/,
            /\/jwplayer\.min\.js/
        ]
    }
};

**Comment by johnBartos** [comment]
Try removing jwplayer from `noParse` - believe that you want it in `resolve` or `externals` instead. 
https://github.com/webpack/webpack/issues/1768

Check out my comments here https://github.com/jwplayer/jwplayer/issues/1455, I briefly went over webpack with jwplayer. Essentially, you need to 1) tell webpack to ignore jwplayer when compiling and 2) tell webpack where to look when you `require('jwplayer)`.

**Comment by marcusgraf** [comment]
Hi, thanks. Kind of works now for us.

We also had to change our call:
this.playerInstance = jwplayer(this.id);

to:
this.playerInstance = window.jwplayer(this.id);
