### ISSUE TITLE
MP3 audio stream fails using HLS JS provider

### ISSUE THREAD

**Issue by johanberonius** [jwplayer/jwplayer#1484]
### Expected Behavior

Audio stream should play just like it does using the Flash provider.

### Actual Behavior

Playback freezes about every ten seconds in Firefox 50 but seems to work in Firefox 52.

No timeline is visible in Chrome 55 and 57, it says "Live broadcast" even though it's not.

### Steps to reproduce
1. Go to https://johanberonius.github.io/jwplayer-test/jw7-hls-js-mp3.html
2. Press play

### Environment
- JW Player version 7.8.3 with Enterprise key
- Streaming server: Wowza Streaming Engine 4 Perpetual Edition 4.5.0.01 build18956
- Browsers without native support for HLS but with support for MSE, eg. Firefox 50 - 52 or Chrome 55 - 57.

**Comment by johnBartos** [comment]
@johanberonius I don't believe your stream is actually an mp3 - our player supports mp3 playback, but we're not detecting any compatible codecs in your media. As a sanity check I loaded the stream in Hls.js and it did not work.

**Comment by johnBartos** [comment]
@johanberonius We did some more investigating and your stream is fine - in 7.7.1 we introduced a regression which breaks mp3 streams with ID3 metadata. Thanks for the report, we'll get this one into the backlog and fix it.

**Comment by johanberonius** [comment]
It seems this stopped working in version 7.7.0.
In version 7.6.1 it worked using Caterpillar in Chrome and Flash in Firefox.

**Comment by fdambrosio** [comment]
we've a similar problem with our mp3 HLS stream and 7.7.1 
Until 7.6.1 this stream works fine:  
http://video.radioradicale.it/store-64/_definst_/mp3:dltpatch/CA057230.mp3/playlist.m3u8
but in your Stream Tester the player breaks with loop buffering icon.
It's happen both on Chrome and Firefox

**Comment by robwalch** [comment]
This is the error that occurs when using streams with MPEG2 TS segments which only contain 1 elementary audio/mp3 stream. We do not support this configuration in html5 without Flash.

**Comment by johanberonius** [comment]
> We do not support this configuration in html5 without Flash. 

It did work without Flash using Caterpillar in Chrome in version `7.6.1`.

**Comment by robwalch** [comment]
Yes but only in Chrome. Since we now support playback in Firefox and cannot support MP3 in that browser we removed this functionality.

**Comment by fdambrosio** [comment]
What happen about mp3 stream that still work until 7.6.1? Flash fallback? 
Mp3 support on html5 is reported here: https://support.jwplayer.com/customer/portal/articles/1403635-media-format-reference

**Comment by johanberonius** [comment]
The release notes for `7.7.1` for states:
> Added messaging in Firefox when MP3 HLS streams cannot be played

https://developer.jwplayer.com/jw-player/docs/developer-guide/release_notes/release_notes_7/#771-101016

There is no real error message, just a hanging spinner and "Error: No tracks found after end of file." in the console log.

**Comment by robwalch** [comment]
@johanberonius the release notes are incorrect. We now play video only in streams with mp3 audio tracks. If there is not video, you get the error you are seeing.

**Comment by fdambrosio** [comment]
can I fallback to flash if there's that error?

**Comment by johanberonius** [comment]
> can I fallback to flash if there's that error? 

Yes, but you have to set `hlshtml` to `false` just for radio-programs, otherwise the player will try and fail.
I have this code in my player configuration:
```
// Don't use HLS in JS for audio to avoid "No tracks found after end of file"-bug in JW Player caterpillar-provider.
if (file.contains('/mp3:')) {
    player.config.hlshtml = false;
}

**Comment by fdambrosio** [comment]
I've tested that with 7.7 jwp is using hls.js provider to stream mp3; the latest hlsjs dev release has added mp3 support https://github.com/dailymotion/hls.js/pull/808
You can add this feature in the next release?

**Comment by johnBartos** [comment]
@fdambrosio Yeah we regularly pull in the latest changes but we're on a feature freeze for 7.8

**Comment by fdambrosio** [comment]
ok @johnBartos thanks, I hope it will be updated soon ;)

**Comment by johanberonius** [comment]
This workaround doesn't work anymore since `7.8.0-beta.4` seems to ignore `hlshtml = false`.
Now it tries and fails regardless of the setting in config for mp3-sources with the message:
> Hlsjs shutdown Media Error: no level with compatible codecs found in manifest

This works instead, but it doesn't feel right to force Flash to be the primary choice. 
```
// Don't use HLS in JS for audio to avoid "no level with compatible codecs found in manifest" in JW Player hlsjs-provider.
if (file_http.contains('/mp3:')) {
    player.config.primary = 'flash';
}
```

**Comment by johanberonius** [comment]
Updated the title, description and link to test page for this issue.
https://johanberonius.github.io/jwplayer-test/jw7-hls-js-mp3.html

**Comment by johanberonius** [comment]
Not fixed in `7.8.1` which is using hls.js `0.6.9`. 
Test mp3-stream with latest hls.js `0.6.12`:
http://streambox.fr/mse/hls.js-0.6.12/demo/?src=https://streaming4.ur.se/urse/_definst_/mp3:196000-196999/196066-4.mp3/playlist.m3u8

**Comment by fdambrosio** [comment]
This issue has been fixed in hls.js 0.6.11. 
With 0.6.12 has been fixed the mp3 error with 'mp4a.40.34' codec

**Comment by johnBartos** [comment]
If it doesn't make it into the next production release we'll get it into a 7.8 patch

**Comment by johnBartos** [comment]
@here https://github.com/jwplayer/hls.js/pull/28

**Comment by sajkec** [comment]
Does this mean we will get HLS HTML5 mp3 support back* in the future JWPlayer builds? Or that there will be a fallback to Flash version if mp3 is detected?

*Referring to the Note: JW Player 7.7 removes support for mp3 audio in HLS HTML5. HLS streams should use AAC audio instead.

**Comment by fdambrosio** [comment]
Yes @sajkec, jwp dev have said that this fix will be introduced soon and we'll be able to play mp3 using HLS HTML5.
I would ask if I can update hlsjs provider on 7.8.1 myself

**Comment by johnBartos** [comment]
![good news!](https://i.ytimg.com/vi/wRn_qYIpdqo/hqdefault.jpg)

Good news everyone! 7.8.3 is up to date with hls.js 0.6.13, which has great mp3 support. Check it out

**Comment by johanberonius** [comment]
Great. Only to discover new problems:
- Playback freezes about every ten seconds in Firefox 50 but seems to work in Firefox 52.
- No timeline is visible in Chrome 55 and 57, it says "Live broadcast" even though it's not.

Test page is updated to `7.8.3`:
https://johanberonius.github.io/jwplayer-test/jw7-hls-js-mp3.html

**Comment by johnBartos** [comment]
Strange - can you open up a new issue for this? I'd like to close this one out.

From what I've been seeing, the duration isn't updated until about halfway through the stream, which is why we say it's live. Watch until about 3:17 and you should see the bar appear.

**Comment by johanberonius** [comment]
Ok, closed this one and opened https://github.com/jwplayer/jwplayer/issues/1589
