### ISSUE TITLE
Quality toggle should work with multiple streaming sources using Caterpillar, Shaka or Flash-providers, like it does when using HTML5-provider.

### ISSUE THREAD

**Issue by johanberonius** [jwplayer/jwplayer#1488]
This is possibly a feature-request rather than a bug report since the documentation states that the quality toggle should work with static video files.
https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/#quality-toggle-for-video-files

### Expected Behavior

Both sources are available and the quality toggle is displayed, like it is when using HTML5-provider.

### Actual Behavior

Only the first source plays and quality toggle is not available when using Caterpillar, Shaka or Flash-providers.

### Steps to reproduce

1. Go to https://rawgit.com/sveriges-utbildningsradio/jwplayer-test/master/streaming-quality-toggle.html
2. Press play

### Configuration
- Multiple sources of the same type using a streaming protocol (HLS or DASH) with different non-adaptive qualities.

### Environment

- JW Player version 7.7.1 with Enterprise key
- Streaming server: Wowza Streaming Engine 4 Perpetual Edition 4.5.0.01 build18956

**Comment by robwalch** [comment]
Caterpillar, Shaka and our Flash-HLS provider support adaptive streams which can contain multiple qualities. All qualities should be contained in a single manifest.  This is not a feature we have any plans or reason to include in the player.
