### ISSUE TITLE
'playAd' in 'play/beforePlay' event makes video start over after being paused

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/jwplayer#1489]
### Expected Behavior

After playing ads via the `playAd` (googima) method I want the player to resume playback at the position I've paused the video.
### Actual Behavior

After clicking `play` the player enters the `buffer` state for approximately 10 seconds and starts video playback from the beginning.

Jwplayer 7.3.6 doesn't seem to show this behavior.
### Steps to reproduce
1. Go to http://demo.videodock.com/jwplayer/jwplayer-googima/
2. Press play
3. Skip ad after 5 seconds
4. Play video for a few seconds (or seek to random position)
5. Click pause
6. Click play  
7. Problem should occur
### Environment
- _Macbook Pro_
- _OS X Chrome | 53.0.2785.143 (64-bit)_
- _7.7.1 | http://demo.videodock.com/jwplayer/jwplayer-googima/_

---

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text _in italics_ with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Unable to reproduce.

**Comment by ChristiaanScheermeijer** [comment]
Hi @robwalch,

Sorry, I meant beforePlay. Although this issue occurs in both events. I've updated the test page.

**Comment by ChristiaanScheermeijer** [comment]
Did some further investigation and think I have found the problem.

After calling `playAd` the `adStarted` callback adds a `beforePlay` event listener with `once`. 

```
void e.once("beforePlay", function(e) {
                return k.beforePlay(e)
``` 

This callback is never being called during the ad (or cleaned up after the ad has completed). This callback does get called after pausing and resuming the video after the ad.
