### ISSUE TITLE
Automatically fullscreen exiting on playlistComplete

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#1493]
### Expected Behavior

Player not exit fullscreen automatically. https://github.com/jwplayer/jwplayer/blob/c6e479223c034ddee642e62fe95b21630645e901/src/js/view/view.js#L892 

I think the best would be to have this configurable as there is no way to stay in fullscreen mode after complete playback.
### Actual Behavior

Currently after playlist is completed player exits fullscreen which is not desired. There are several reasons why:
- we use ads plugin which should also play in fullscreen
- if there is no ad - we'd like to play next video automatically without leaving fullscreen
### Steps to reproduce
1. Open basic example
2. Enter fullscreen mode
3. Watch stream till end - player will exit fullscreen.
### Environment
- _hardware | Macbook_
- _operating system | OSX 10_
- *JW Player version | 7.7.1 *

---

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text _in italics_ with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
@artur-michalak We deliberately exit fullscreen, so this is a feature request. We'll discuss if this is something we want to add to the player but you can also make the change yourself:

**Comment by johnBartos** [comment]
Delivered!
