### ISSUE TITLE
levels event not triggered after preroll

### ISSUE THREAD

**Issue by kasty** [jwplayer/jwplayer#1494]
### Expected Behavior

Quality selector should be displayed after playing a preroll
### Actual Behavior

The « levels » event is not triggered after playing a preroll on a HLS video with jwplayer in flash mode. This induces the quality selector is never displayed.
### Steps to reproduce

This issue is complementary to this one https://github.com/jwplayer/jwplayer/issues/1456
I made a simpler demo page, based on a nude jwplayer so that it would be easier for you to understand the problem
1. Here is the demo page : http://player-v3-dev.arte.tv/test/jwplayer_nude.php
2. The bug seems to append more often in Chrome than in Firefox but I can reproduce in both of them
3. See in the debug console, when levels event is triggered it says "levels triggered" and sometimes it does not append.
4. I could note that the delay caused by our tests seem cause the problem but I don't clearly know why
5. If you disable the timeout that simulate our rights tests (on this url http://player-v3-dev.arte.tv/test/jwplayer_nude.php?notimeout) you see that the bug never happens, but we can't make without them
### Environment
- MacBook Air
- OS X El Capitan / Chrome Version 53.0.2785.116 / Firefox 49.0.1 / Flash Version 23
- JW Player 7.6.0

**Comment by johnBartos** [comment]
Thanks for the update, I'll look at this soon but based on your repro steps I'm not sure that it's something we can fix

**Comment by robwalch** [comment]
Hi @kasty,

Are you still seeing this issue in v7.9 or v7.10?

**Comment by johnBartos** [comment]
This appears to be working now.
