### ISSUE TITLE
Feature request: Dispatch user activity events

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/jwplayer#1498]
### Feature Request

In JW-Showcase I want to be able to show/hide the header based on the controls state set by user  activity of a Jwplayer instance. Currently this is only possible by using CSS next sibling selectors using the '.jw-flag-user-inactive' classname, but this will force you to add the element after the Jwplayer container.

```
jwplayer()
  .on('userInactive', function () {
    // no user activity
  })
  .on('userActive', function () {
    // user activity (only fired when the previous state was userInactive)
  });
```

---

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text _in italics_ with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
We can do this as part of the "chromeless" work we're doing now. Just be aware that while these events would lineup with toggling of the 'jw-flag-user-inactive' class, it doesn't mean the controls are or are not visible.

**Comment by ChristiaanScheermeijer** [comment]
Thanks! I see you have removed the uiActivity events, were those events not
suitable?

**Comment by robwalch** [comment]
I wasn't really set on uiActivity, and hoped to make those events internal only. Considering that others have asked for similar functionality and it's an easy change, I think this is the way to go.

**Comment by mwleinad** [comment]
@robwalch is this alreaady live on the https://www.jwplayer.com/ ??

thanks!

**Comment by robwalch** [comment]
@mwleinad not yet. It will be part of v7.11.0. The current release is v7.10.5.  Beta versions of 7.11 should start showing up on the [beta channel players](https://support.jwplayer.com/customer/portal/articles/2149561-using-player-release-channels) next week.

**Comment by johnBartos** [comment]
Delivered!

**Comment by shmdhussain** [comment]
how to access these events?, I like to trigger the user active event thru javascript?, how to use this api, unable to find this api in doc reference https://developer.jwplayer.com/jwplayer/docs/jw8-javascript-api-reference.

thanks in advance for any help
