### ISSUE TITLE
Replace tracks-helper.renderNatively with model.captionsRenderer

### ISSUE THREAD

**Issue by robwalch** [jwplayer/jwplayer#1515]
The tracks-helper.js mixin is part of all internal providers and has a method `renderNatively(providerName)` that looks at the userAgent and determines if rendering should be done natively with the current provider. It is also used in captions.js and captionsrenderer.js.

This exposes provider names not used in this project and is difficult to maintain as providers are added. It also doesn't allow external providers to render captions "natively" (using text tracks).

Providers should declare how captions will be rendered using an event - either existing captions/subtitleTracks events or a new one. This will tell the model what captionsRenderer will be used. It can be either "video", or "vttrenderer". Current providers can continue to set `_renderNatively` based on this setting.

**Comment by robwalch** [comment]
What do you guys think?

This is in reaction to these changes to tracks-helper https://github.com/jwplayer/jwplayer/pull/1487/files

**Comment by robwalch** [comment]
@egreaves is this still relevant? Where are we now with captions tech-debt?

**Comment by johnBartos** [comment]
Resolved!
