### ISSUE TITLE
Specify function for fetching media segments with jwplayer

### ISSUE THREAD

**Issue by silverbucket** [jwplayer/jwplayer#1516]
I'm trying to create my own media fetching function for jwplayer, I've read through the API docs and guides and didn't find anything that explained how to do this.

With other players like hls.js or dash.js, there are ways - during initialization - to register your own function which is called whenever the player needs a new segment of media (assuming we're reading from a playlist). Is there a way to do this with jwplayer?

**Comment by johnBartos** [comment]
@silverbucket This is just for HLS streaming right?

**Comment by silverbucket** [comment]
Well, it could be any media type. Either a really large file in which the player might want to fetch byte ranges, or an HLS or DASH playlist stream. But the most common use case I guess would be a live stream.

**Comment by johnBartos** [comment]
In the near future we'll allow users to configure their own functions for downloading HLS media, but we don't plan on allowing configuration on our other media downloading functions. You can replace our ajax util with your own (as long as it matches our interface):

https://github.com/jwplayer/jwplayer/blob/master/src/js/utils/ajax.js

**Comment by silverbucket** [comment]
@johnBartos - thanks for the pointer. So just to clarify, is there a way to override this function on the fly? Or would I need to maintain a special build where I've swapped out the files?

**Comment by silverbucket** [comment]
ping @johnBartos

**Comment by johnBartos** [comment]
@silverbucket No way to override, we've made a choice not to allow overriding of functions in our config

**Comment by silverbucket** [comment]
@johnBartos Thanks for the clarification. It might be something to consider as a feature down the road, this way other logic for fetching media segments (ie. p2p) could integrate with your player simply by providing a media fetching function for you to call.
