### ISSUE TITLE
Vast Ad and the video dont start in Firefox 38.7.0

### ISSUE THREAD

**Issue by marcusgraf** [jwplayer/jwplayer#1520]
### Expected Behavior

Hey, we included a vast tag in our player and it works very well in nearly all browsers.
Just Firefox 38.7.0 dont want to play the video. 

Our Editorial Office use Firefox 38.7.0 so we have to fix this somehow.
### Actual Behavior

In Firefox 38.7.0 the vast tag load successful but the video dont start. 
You have to click on play again to start the advertisment and the video
### Steps to reproduce
1. Open The page: https://www.welt.de/debatte/kommentare/article159071846/Beim-Bundespraesidenten-stellt-Gabriel-die-Machtfrage.html
2. See :)
### Environment

Firefox 38.7.0 Mac and Windows
Jwplayer 7.7.2

Is there a workaround or something?

**Comment by robwalch** [comment]
Please check to see if your version of Firefox and Windows supports the video you are trying to play. If it does not, you will need to include a video that your browser does support in our player, update your browser, or force Flash playback.

MP4 is only supported in Firefox HTML5 in Windows 7 and above.

**Comment by robwalch** [comment]
We do not take ad bug reports in this repo. Thank you.
