### ISSUE TITLE
Caterpillar is making XHR requests but HTML5 provider is not

### ISSUE THREAD

**Issue by deluxor** [jwplayer/jwplayer#1522]
Small question here, if I open a test stream on chrome for instance, it will load the caterpillar provider and everything will be fine. But if I try to open the same stream on a mobile device for instance an android device it will load html5 provider. Ok that's fine for normal setups, but lets think that I want to implement some hotlinking protection based on ORIGIN header, on XHR requests this header is sent, but on normal requests like the ones that are being made from html5 provider they don't send it. 
What can I do in this situation?

I appreciate some help with this please 👍

**Comment by johnBartos** [comment]
@deluxor With the html5 provider the browser makes the request - we don't (and can't) attach headers to it

**Comment by robwalch** [comment]
Could you look at referer instead?

http://homakov.blogspot.com/2012/04/playing-with-referer-origin-disquscom.html

**Comment by robwalch** [comment]
Feel free to discuss. I'm closing the ticket as this is not a player issue.
