### ISSUE TITLE
如何将jwplayer播放的视频流实时的转发给其他服务

### ISSUE THREAD

**Issue by wechat361** [jwplayer/jwplayer#1526]
您好，我有一个新的需求，需要在播放器中通过socket将视频流转发到指定的地址，但是我不知道具体的视频流是在那部分代码中解析出的，还请告知一下，谢谢。

**Comment by johnBartos** [comment]
````
Google Translate:

Hello, I have a new demand, in the player through the socket will be transmitted to the specified video stream address, but I do not know the specific video stream is in that part of the code to resolve out, please inform, thank you .
````

From what I understand you're trying to stream a video to another destination. We don't support this and don't plan to

**Comment by wechat361** [comment]
I would like to achieve this function by myself, but I do not know how the video is being broadcast from the stream, can you tell me how to do? Thank you

**Comment by wechat361** [comment]
I would like to achieve this function by myself, but I do not know how the video is being broadcast from the stream, can you tell me how to do? Thank you

**Comment by wechat361** [comment]
I would like to achieve this function by myself, but I do not know how the video is being broadcast from the stream, can you tell me how to do? Thank you

**Comment by robwalch** [comment]
Our players supports video served over http(s), rtmp and youtube only.
