### ISSUE TITLE
You must set environment variable $AIR_HOME or $FLEX_HOME

### ISSUE THREAD

**Issue by mikeevstropov** [jwplayer/jwplayer#1545]
Hi! As u can see `$FLEX_HOME` is available and `mxmlc` also, but i cant build.
OS: Linux Mint 18 Sarah x64

![2016-11-12 11-07-21](https://cloud.githubusercontent.com/assets/15070249/20235577/36a37a3e-a8c8-11e6-86b8-cb0455e8b618.png)
```console
git clonse https://github.com/jwplayer/jwplayer.git && cd jwplayer
npm install
npm install minimist
grunt
```
Please help! What i need do?

**Comment by johnBartos** [comment]
If you're not building flash you can `--force` the command or use webpack directly: `webpack-dev-server --only debug -w --port 8888 --output-public-path /bin-debug/`.

If you need flash, you have to set up the flash SDK in your environment variables: https://github.com/jwplayer/jwplayer#build-instructions

**Comment by mikeevstropov** [comment]
@johnBartos Okay, thank you! If i want use only html5 part, its free? Or i need pay for license key? I have more than 10k video plays.
