### ISSUE TITLE
augmenting existing providers

### ISSUE THREAD

**Issue by mrbar42** [jwplayer/jwplayer#1546]
I'm trying to write a provider for jwplayer7 and it looks like the case is all or nothing.
trying to mimic the existing providers i'm able to use the peripheral utils like `jwplayer._` and `jwplayer.utils` etc,
but it seems impossible to take an existing provider as a template and augment it.

the `html5` provider for example (the one I want to use), has many dependencies, so when i tried copying all of it as a start i could satisfy almost all of the dependencies through hacky methods except `tracks-mixin` which has so many sub dependencies making it impractical to copy.

What i would want ideally, is to be able to get the html5 provider's constructor and create a sub-class under different name and register it replacing only the few methods i need.

ideal example:
```js
var baseProvider = jwplayer.providers.html5;

function MyNewProvider(id, config) {
  baseProvider.call(this, id, config);

  // override specific methods
  this.load = function (item) {
    // do something different
  }
}

MyNewProvider.prototype = Object.create(baseProvider.prototype);
MyNewProvider.getName = function () {
  return {name: 'myNewProvider'};
}

jwplayer.api.registerProvider(MyNewProvider);
```

is there a way to achieve that?

**Comment by johnBartos** [comment]
@mrbar42 The [default provider](https://github.com/jwplayer/jwplayer/blob/master/src/js/providers/default.js) is the base contract for our providers. You can simply implement all these methods and have a working provider without extending any base class. You do need to mix in the `tracks-mixin` though. I'd do it like this:

````
// Squish the mixins into their own object
const mixins = Object.assign({}, Tracks);
// Compose the provider's prototype from the mixins and it's own prototype
// Allows the prototype to shadow base methods
CustomProvider.prototype = Object.assign(Object.create(mixins), CustomProvider.prototype);
````

Your example is pretty much exactly what we do in our closed-source product when extending the html5 provider. We use delegation to extend behavior - here's a snippet:

````
define([
    'os/providers/html5',
    'os/utils/ajax',
    'os/events/events',
    'os/utils/underscore'
], function(VideoProvider, ajaxUtils, events, _) {
  // VideoProvider is the open source html5 provider
    var CommercialVideoProfiler = function(_playerId, _playerConfig) {
        VideoProvider.call(this, _playerId, _playerConfig);

        var superInit = this.init;
        var superLoad = this.load;
        var superDestroy = this.destroy;

        this.init = function(item) {
            // do custom stuff here
            superInit.call(this, item);
        };

        this.load = function(item) {
            superLoad.call(this, item);
        };

        this.destroy = function(item) {
            superDestroy.call(this, item);
        };
    };
 // ...
````

You need to be careful with shadowing and reassigning prototypes.

**Comment by mrbar42** [comment]
thanks.
the problem with your example is that it assumes that my provider is part of the jwplayer bundle.
i want to achieve your exact example externally like so:

```html
<script src="//my.cdn.com/jwplayer-v.7.x.x.js"></script>
<script>
function ExternalVideoProvider() {
  var _ = jwplayer._;
  var utils = jwplayer.utils;
  // inherit from html5 provider somehow
}

jwplayer.api.registerProvider(ExternalVideoProvider);
</script>
```
