### ISSUE TITLE
JW Player Flash video loading error "Cannot load M3U8: crossdomain access denied (2048)" on Firefox only

### ISSUE THREAD

**Issue by cpeterso** [jwplayer/jwplayer#1557]
### Expected Behavior

JW Player video should play in Firefox like it does in other browsers.

### Actual Behavior

The JWPlayer video plays correctly in Chrome (Mac and Windows), IE, Edge, Safari (Mac), but fails to load in Firefox (Mac and Windows) with the following error message in JW Player:

`Cannot load M3U8: crossdomain access denied (2048)`.

### Steps to reproduce

1. Enable Flash in Firefox.
2. Load http://www.dailydot.com/bazaar/nes-classic-walmart/
3. Scroll down to the section called "FROM OUR VICE PARTNERS".
4. Wait for any pre-roll ads to finish playing and then you should see the `Cannot load M3U8: crossdomain access denied (2048)` error message in JW Player.

### Environment

- MacBook Pro and Windows laptop
- macOS 10.12 and Windows 10
- JW Player version 7.5.2 and Flash Player version 22.0.0.209 and 23.0.0.207 (on Mac) and 24.0.0.145 (on Windows)

**Comment by johnBartos** [comment]
@cpeterso The difference between Chrome and FF is that FF is using Flash, which is probably being blocked. Try out the 7.8 beta - we have a new HLS library and HTML5 google IMA client (which are also enabled by default). Flash is 💀

**Comment by cpeterso** [comment]
Thanks. I think we close this issue then. It sounds like this is a problem with @DailyDot not properly configuring their video server to allow Flash crossdomain access. Apparently they never tested in Firefox. :(

**Comment by johnBartos** [comment]
@cpeterso Get them to upgrade! 7.8 is the future

**Comment by abhithakkar19** [comment]
heyyyyy there

can u give me a source code of a player to play m3u8 on my web page

i am having a problem that my video is on s3 and i want to play that video in player but the player is not playing that video

also i checked the s3 link with online player and its working fine

but when i want to play it on my web page its not working

so anyone help me with this

**Comment by johnBartos** [comment]
@abhithakkar19 You need the commercial version of the player to play HLS content with HTML5. It is closed source.

**Comment by abhithakkar19** [comment]
No I want it for free. I am a student and want it for a project.
If u can help me that will be great sir

**Comment by johnBartos** [comment]
You can use this project: https://github.com/video-dev/hls.js

We use it internally to play HLS content

**Comment by abhithakkar19** [comment]
Ok thank u John sir

**Comment by abhithakkar19** [comment]
Sir there have been lots of files in that
how am i suppose to get player
i have to put the player in my website
can u simplify that thing for me
it would be nice

**Comment by johnBartos** [comment]
Follow the steps: https://github.com/video-dev/hls.js#getting-started
