### ISSUE TITLE
HLS: ID3 metadata shown as captions and is not available when captions are off

### ISSUE THREAD

**Issue by IsaacSchemm** [jwplayer/jwplayer#1559]
### Expected Behavior

ID3 metadata in an HLS stream should always be sent to the .on('meta') handler, and should not be displayed to the user in the player itself.

### Actual Behavior

In JW Player 7.8.0-beta2, HLS metadata only gets sent to .on('meta') when closed captions are turned on, and the metadata is shown as closed captions (at least in Firefox.)

### Steps to reproduce

1. Load an HLS stream with ID3 metadata into JW Player 7.8.0-beta2
2. Set up a .on('meta') handler
3. Try turning captions on and off

### Environment

- Windows 10 laptop
- Firefox 49
- JW Player 7.8.0-beta.2+commercial

**Comment by johnBartos** [comment]
@IsaacSchemm We're cutting beta-3 soon which may fix this

**Comment by IsaacSchemm** [comment]
Just tried beta4 and it's working as expected. Thanks!
