### ISSUE TITLE
Missing segments on hls make player switch and block in error state

### ISSUE THREAD

**Issue by privaloops** [jwplayer/jwplayer#1569]
### Expected Behavior

Continue playing even if some segment are missing (juste like with 7.6.0)

### Actual Behavior

With > 7.7.0, an error is triggered and the player blocks in error state, no possibility to read video anymore.

### Steps to reproduce

1. go on old stream tester : http://demo.jwplayer.com/developer-tools/http-stream-tester/
2. use this hls : http://artehls-vh.akamaihd.net/i/am/tvguide/default/052745-000-A_2_VO-STF_AMM-Tvguide_XQ.9726875.smil/master.m3u8
3. select 720p (where segments are missing)

### Environment

- IE11
- Windows 7
- jwplayer 7.7.0

**Comment by robwalch** [comment]
We don't error in 7.8.0, but the video does not play either. We can see this behavior in the hls.js demo page as well. I'm not sure yet what is preventing the player from beginning playback http://dailymotion.github.io/hls.js/demo/?src=http%3A%2F%2Fartehls-vh.akamaihd.net%2Fi%2Fam%2Ftvguide%2Fdefault%2F052745-000-A_2_VO-STF_AMM-Tvguide_XQ.9726875.smil%2Fmaster.m3u8&enableStreaming=true&autoRecoverError=true&enableWorker=false&levelCapping=-1&defaultAudioCodec=undefined

**Comment by shaikhimran786** [comment]
hi @robwalch , any updates on this?

**Comment by fdambrosio** [comment]
we've similar issue too

**Comment by privaloops** [comment]
the given example hls has been reencoded, no more missing segment for the demo sorry

**Comment by johnBartos** [comment]
@shaikhimran786 We're working on improving HLS playback in cases where a segment is missing/incomplete. There's a lot of cases but the big one is when a segment 404's. You can track our progress on these issues in our hlsjs fork: https://github.com/jwplayer/hls.js/pulls

**Comment by robwalch** [comment]
Streams with missing segments will error one way or another. Please address the issue with your missing segments.
