### ISSUE TITLE
autostart does not work in iOS 10.0.2

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/jwplayer#1573]
### Expected Behavior

When using JW Player 7.8 beta the video should autostart muted when adding `autostart: true` in the player options. 

### Actual Behavior

The video does not autostart and the `jw-gesture-required` className is set on the video element.

### Steps to reproduce

1. Embed player with autostart set to true

### Environment

- *iPhone 6 plus*
- *iOS | 10.0.2*
- *7.8.0-rc.1+commercial...*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by dannyfinks** [comment]
Can you provide an example of your player configuration? Are you creating an ad schedule with a preroll?

**Comment by ChristiaanScheermeijer** [comment]
Hi @dannyfinks,

The player configuration looks like this:

```
vm.playerSettings = {
    width:          '100%',
    height:         '100%',
    aspectratio:    '16:9',
    ph:             4,
    autostart:      true,
    playlist:       playerPlaylist,
    related:        false,
    sharing:        false,
    visualplaylist: false
};
```

Below the player defaults (from dashboard):

```
jwplayer.defaults = {
  "aspectratio": "16:9",
  "autostart": true,
  "controls": true,
  "displaydescription": true,
  "displaytitle": false,
  "flashplayer": "//ssl.p.jwpcdn.com/player/v/7.8.0-rc.1/jwplayer.flash.swf",
  "height": 270,
  "key": "",
  "mute": false,
  "ph": 1,
  "pid": "yvm8svn8",
  "plugins": {
    "https://assets-jpcust.jwpsrv.com/player/6/6124956/ping.js": {
      "pixel": "https://content.jwplatform.com/ping.gif"
    }
  },
  "preload": "none",
  "primary": "html5",
  "repeat": false,
  "stagevideo": false,
  "stretching": "uniform",
  "visualplaylist": true,
  "width": "100%"
};
```

**Comment by dannyfinks** [comment]
@ChristiaanScheermeijer I used your config and those defaults and was not able to reproduce the issue. Would you be able to create a test page for us to reproduce the issue? We haven't seen any such issue with mobile autostart.

**Comment by ChristiaanScheermeijer** [comment]
@dannyfinks thank you for looking into this. I was able to reproduce this in [JW Showcase](http://demo.videodock.com/jwplayer/jw-showcase/). 

P.s. I could not reproduce this in my simulator which is running iOS 10.1.

**Comment by egreaves** [comment]
Hi @ChristiaanScheermeijer,

I just tested this with v7.8.0 and was not able to reproduce the issue on my iPhone 6+ running iOS 10.0.1. Autostart worked for me on JW Showcase for all the videos that I tried. 

If possible, could you examine the player's config by calling `jwplayer().getConfig()` from the developer console and confirm that both `autostart` and `autostartMuted` are set to `true` as in the screenshot below: 

![JW Player Config](https://cloud.githubusercontent.com/assets/4603952/20731313/ddf78f2c-b657-11e6-8489-e8b8a520a5a2.png)

Here's a guide for remote debugging of iOS Safari: https://blog.idrsolutions.com/2015/02/remote-debugging-ios-safari-on-os-x-windows-and-linux/

**Comment by dannyfinks** [comment]
@ChristiaanScheermeijer are you using Safari on iOS10 or iOS Chrome? iOS Chrome does not currently support autoplay in line.

**Comment by ChristiaanScheermeijer** [comment]
You are right, it works fine in Safari. The issue was found in the Cordova app but debugged in Safari, I think it was still using a cached version (without JW Player 7.8-beta).
