### ISSUE TITLE
HLS + Amazon CloudFront + Signed Cookies

### ISSUE THREAD

**Issue by parmarsanjay** [jwplayer/jwplayer#1580]
### Expected Behavior

I am trying to set-up JWplayer Premium Edition with following set-up. 

Application URL - Users access application through this URL. 
https://test.domain.ai

AWS Cloudfront URL to host HLS Videos
https://cdn.domain.ai

Sample Video URL
https://cdn.domain.ai/vdeos/video1/master.m3u8

Have set-up crossdomain.xml at this URL and it's available as public URL.
https://cdn.domain.ai/crossdomain.xml

Cloudfront URLs are protected. They are not accessible as public URLs.

Using AWS cloudfront Signed Cookies to protect the URLs. Application generates the necessary signed cookies when user access the application through application URL. These cookies have domain set to 

.domain.ai 

Running into few issues. This is the behaviour i am seeing. 

- HLS video plays in Flash. 
- All the signed cookies are getting forwarded to AWS cloudfront when I play the video. 

### Actual Behavior

when I set-up player to use the HTML5 using following set-up, HLS Video doesn't work. 

hlshtml: true,

In this set-up signed cookies are not getting forwarded to AWS cloudfront URL. 

I have looked up JWplayer documentation and support articles but couldn't find anything close. 

It's not clear whether such a set-up is supported for HTML 5 player. 

BTW, I have also setting up withCredentials: true but still it doesn't work.

I was hosting jwplayer from https://test.domain.ai. I thought may be hosting jwplayer from cdn.domain.ai will resolve the issue. I tried that and still see the same issue. 

### Environment

- *10.11.6 Mac OSX El Capitan | version*
- *Latest Chrome Version*
- *Latest JW player 7.7.x*

**Comment by mkozlov1** [comment]
Did you tried to add 'withCredentials' property in setup?
https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/#playlist

**Comment by parmarsanjay** [comment]
Thanks @mkozlov1. Yes, I did try adding that property but it didn't have any effect.

**Comment by robwalch** [comment]
Update to v7.9.3. `hlshtml: true` is no longer required.

**Comment by desa-eduardo** [comment]
someone have some alternative for cookie signed and JWPlayer ?

**Comment by Leeaandrob** [comment]
This issue is closed but dont have any changes..

**Comment by robwalch** [comment]
You need to add `withCredentials` to your player config or the playlist item(s) that requires cookies to be sent with the media requests.
