### ISSUE TITLE
HLS encrypted stream failing to play on Firefox 49.0

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#1585]
### Expected Behavior

Stream is playing in Firefox

### Actual Behavior

Firefox is downloading master.m3u8 but fails on chunks. See console screenshot below
![image](https://cloud.githubusercontent.com/assets/2443904/20963029/0b3deb1a-bc6c-11e6-9c52-083c3ac78e4a.png)

- master.m3u8 request
![image](https://cloud.githubusercontent.com/assets/2443904/20963091/45106f7a-bc6c-11e6-9111-d1ad62dda52b.png)

- first chunk request
![image](https://cloud.githubusercontent.com/assets/2443904/20963115/5e84d176-bc6c-11e6-9964-ff100d278c5d.png)

Screenshots are from version 7.7.4 but 7.8.1 behaves similar.

### Steps to reproduce

1. Open this stream 
https://svpsecurehdvod-vh.akamaihd.net/i/2016/09/bf1d2fbd8715cbd0c9ef9012e804bec1/,1280_720_3500,960_540_2000,640_360_1000,480_270_500,.mp4.csmil/master.m3u8?hdnea=st%3D1481622858~exp%3D1482054858~acl%3D%2F*~hmac%3Db7e342227c1d20e8638f898f9c1fa03ad021dc850dd435e44bcbea829353b0ea (new token valid till 18.12)
(token is valid for 1week, write comment if  you are geoblocked so we'll whitelist your IP)
2. Try to play above stream in Firefox with html5 provider

### Environment

- *hardware | MacBook Pro*
- *operating system | OSX 10*
- *browser | Firefox 49.0 *
- *JW Player version | 7.7.4 and 7.8.1*

----------------------------------------------------------------------------------------

**Comment by artur-michalak** [comment]
@robwalch any chance to have a look on this one? After small debugging i suspect hlsjs issue itself. I'm pushing on this because secure streams are big part of our business and as a result we can't switch fully to html provider.

**Comment by robwalch** [comment]
What are we trying to reproduce here? It looks like you server is returning 403 error codes in the console screenshot.

**Comment by artur-michalak** [comment]
Yes, it returns which is wrong. Here is flow diagram

![image](https://cloud.githubusercontent.com/assets/2443904/21172584/099f66dc-c1d3-11e6-8fc3-75035b14f137.png)

It looks like player is failing to set this long living token. As you can see master m3u8 has 200 but then chunks are getting 403. This problem exists only on Firefox. You can find more info here http://frenchweb.fr/wp-content/uploads/2012/05/Akamai_SecureHD1.pdf (page 4)

I'll create example for you to make test easier

**Comment by robwalch** [comment]
@artur-michalak an example of your setup config is needed. Thanks.

**Comment by shaikhimran786** [comment]
@artur-michalak , I am also phasing same issue, it will be great help if you provide example of your setup config.

**Comment by artur-michalak** [comment]
@robwalch @shaikhimran786 I created example. 
You can check it here https://cdn.svp.schibsted.io/example/jw.html.

Here are screenshots with requests details for first media chunk (https://absvpsecurefvod-vh.akamaihd.net/i/2016/12/44c4ec9fb076455d8e8da3cb50a60a9e/,1280_720_3500,960_540_2000,640_360_1000,480_270_500,.mp4.csmil/index_0_av.m3u8)

Chrome (works):
![image](https://cloud.githubusercontent.com/assets/2443904/21346421/9ba84532-c6a4-11e6-8709-2a85cd6722cc.png)

Firefox (does not  work):
![image](https://cloud.githubusercontent.com/assets/2443904/21346325/4074a5fc-c6a4-11e6-869b-06fe09d6280e.png)

I found difference in `Accept` request header:
Chrome: `Accept:*/*`
Firefox: `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`
This maybe why it does not work on FF.

**Comment by johnBartos** [comment]
@artur-michalak Please post your config

**Comment by artur-michalak** [comment]
jwplayer("player1").setup({
            "playlist": [{
                "file": stream,
                "mediaid": 121031
            }],
            "primary": "html5",
            "androidhls": true,
            "flashplayer": "//cdn.svp.schibsted.io/jw/7.8.1/player.flash.swf",
            "wmode": "transparent",
            "key": "I71qyJ0z98WOuWtf1coTYg3jFkb4GoyGimmxgQ==",
            "autostart": true,
            "width": "100%",
            "mute": true,
            "height": "100%",
        });

view-source:https://cdn.svp.schibsted.io/example/jw.html

**Comment by johnBartos** [comment]
This is 403ing in Chrome too.

**Comment by artur-michalak** [comment]
Probably because of geoblock:

> Edit: Please use VPN with Swedish IP as we don't have any stream configuration without geoblock (we can also restrict your IP but i do believe this is more convenient)
https://github.com/jwplayer/jwplayer/issues/1585#issuecomment-268204909

Could you point where should i look for hls.js initialization? I will debug it then.

**Comment by artur-michalak** [comment]
@johnBartos @robwalch finally i found why this does not work. HLS.js by default is not setting withCredentials flag to true. This causes issue on Firefox which is not sending cookies.
I found that you can set it in JW.. https://github.com/jwplayer/jwplayer/blob/e5b576cfc45dd88fc254e397375604139c62e14e/src/js/playlist/playlist.js#L57 but it's not documented anywhere. 
I'll close this issue but please update your documentation.

**Comment by johnBartos** [comment]
@artur-michalak Yes, by default hls.js does not set the credentials but if `withCredentials` is true it does. Here's the snippet from the provider: 

```
        xhrSetup(xhr, url) {
            if (withCredentials) {
                xhr.withCredentials = true;
            }

            if (aesToken) {
                let token = url.indexOf('?') > 0 ? '&token=' : '?token=';
                xhr.open('GET', url + token + aesToken, true);
            }
        },
        fetchSetup(context, initParams) {
            initParams.credentials = 'include';
            return new Request(context.url, initParams);
        }
```

**Comment by robwalch** [comment]
@artur-michalak it's right here https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/#playlist

`withCredentials` is never on by default because of HTTP access control (CORS) restrictions. Same as XHR https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials
