### ISSUE TITLE
Replace grunt-recess

### ISSUE THREAD

**Issue by egreaves** [jwplayer/jwplayer#1586]
Recess is [no longer maintained](https://github.com/twitter/recess) and does not work with newer versions of less (>1.3.0).

Using `grunt-contrib-less`, `grunt-contrib-csslint`, `grunt-contrib-cssmin`, we could take advantage of newer less features and, ultimately, reduce the size of compiled css.

**Comment by johnBartos** [comment]
Done, thanks @jw-kaurand!
