### ISSUE TITLE
MP3 audio stream using HLS JS provider freezes in Firefox and shows no timeline in Chrome.

### ISSUE THREAD

**Issue by johanberonius** [jwplayer/jwplayer#1589]
### Expected Behavior

Audio stream should play just like it does using the Flash provider.

### Actual Behavior

Playback freezes about every ten seconds in Firefox 50 but seems to work in Firefox 52.

No timeline is visible in Chrome 55 and 57, it says "Live broadcast" even though it's not.

### Steps to reproduce
1. Go to https://johanberonius.github.io/jwplayer-test/jw7-hls-js-mp3.html
2. Press play

### Environment
- JW Player version 7.8.6 with Enterprise key
- Streaming server: Wowza Streaming Engine 4 Perpetual Edition 4.5.0.01 build18956
- Browsers without native support for HLS but with support for MSE, eg. Firefox 50 - 52 or Chrome 55 - 57.

**Comment by fdambrosio** [comment]
we have the same issue on FF 48 (Mac 10.12) but it seem to be an hlsjs issue: https://github.com/dailymotion/hls.js/issues/853

**Comment by fdambrosio** [comment]
in Chrome 55/Mac player says "Live broadcast" even though it's not 
http://web-0.radioradicale.it/prova/player7/7.8.3.html

**Comment by fdambrosio** [comment]
This happen with FF 50.1 (Mac 10.12) too

**Comment by fdambrosio** [comment]
last hlsjs git master fix the issue on FF, we'll be fixed in jwp 7.8.3 release?

**Comment by fdambrosio** [comment]
hlsjs 0.6.14 has fixed mp4+mp3 problem on FF

**Comment by johnBartos** [comment]
@fdambrosio Great, we'll try and get it merged in soon

**Comment by fdambrosio** [comment]
I'm testing 7.8.6: on FF mp3 stop after 10 seconds, on Chrome it shows 'live broadcast'

**Comment by johanberonius** [comment]
Test page is now on `7.8.6`

**Comment by johnBartos** [comment]
@fdambrosio Great thanks, I'm merging in 0.6.15 today and I'll test it out

**Comment by fdambrosio** [comment]
there's new 0.6.16 that has fixed a video freeze issue 
https://github.com/dailymotion/hls.js/issues/890 

there's the last issue because on Chrome the player shows 'live broadcast' without the timeline

**Comment by johnBartos** [comment]
Awesome, I'll get this into the update PR

**Comment by fdambrosio** [comment]
good news! The last commit has fixed the timeline issue on Chrome 
https://github.com/dailymotion/hls.js/pull/908

**Comment by fdambrosio** [comment]
> Chrome + MP3 codec, fix seeking not working until fully buffered #908 
0.6.17 
https://github.com/dailymotion/hls.js/releases/tag/v0.6.17

**Comment by fdambrosio** [comment]
Hi @johnBartos hls.js 0.6.16 will be merged with jwp 7.9.0 ? 
Thanks

**Comment by johnBartos** [comment]
@fdambrosio No, we're frozen for 7.9. It'll either go out in a 7.9 patch or 7.10

**Comment by fdambrosio** [comment]
thanks @johnBartos hope there will be a 7.9 patch :-)

**Comment by fdambrosio** [comment]
Hi, there's a new hls.js release (0.6.18) 
https://github.com/dailymotion/hls.js/releases/tag/v0.6.18

**Comment by fdambrosio** [comment]
there's 0.6.19, I hope that 7.9 will be patched 😄

**Comment by johnBartos** [comment]
@fdambrosio It'll land in 7.10

**Comment by fdambrosio** [comment]
thanks @johnBartos we're waiting this update to be able to do the big jump 7.6 -> 7.10 😄

**Comment by fdambrosio** [comment]
@johnBartos @johanberonius  I'm testing 7.9.3 and it seems that mp3 playback is fixed on Chrome. Hls.js provider library has been updated?

**Comment by fdambrosio** [comment]
hi @johnBartos what's the hlsjs library version merged on 7.10.0 ?

**Comment by johnBartos** [comment]
@fdambrosio 0.6.21
