### ISSUE TITLE
Vast Ad doesn't start in Firefox 50

### ISSUE THREAD

**Issue by privaloops** [jwplayer/jwplayer#1590]
### Expected Behavior

Ad should play

### Actual Behavior

player is blocked and doesn't start

### Steps to reproduce

1. go here http://demo.jwplayer.com/ad-tester/
2. paste this vast url https://adserver.adtech.de/?advideo/3.0/1419.1/4890007/0//cc=2;vidAS=pre_roll;vidRT=VAST;vidRTV=3.0;kvvideoisolang=fr_FR;kvvty=ARTE_PLUS_SEVEN;kvvdu=49;kvcaseprogram=318_serie-tv-prime-time;kvgenreprogram=undefined;kvvs4=undefined;cors=yes;acao=http://demo.jwplayer.com

### Environment

- macbook pro 2016
- OS X 10
- FF 50
- jwplayer latest version (7.8.2 at this moment)

**Comment by privaloops** [comment]
Precision : works on FF Windows

**Comment by dannyfinks** [comment]
@privaloops I am not able to reproduce on FF 50 on OS X. Are you using Flash or HTML5?

**Comment by privaloops** [comment]
html5

**Comment by privaloops** [comment]
Many users around me have seen the problem, does the ad video plays ? What can you see ?

**Comment by dannyfinks** [comment]
I actually do see that it is working with the VAST Ad Client and not Google IMA.

**Comment by dannyfinks** [comment]
Another place to test whether or not your ad tag will work with the IMA Ad Client is https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector

**Comment by privaloops** [comment]
I'm sure that this vast is correct, it is in production and works (thousands of views each days).
This bug is also described here : https://github.com/jwplayer/jwplayer/issues/1520

**Comment by robwalch** [comment]
We do not take ad bug reports in this repo. Thank you.
