### ISSUE TITLE
Documentation: "muted inline autoplay" on iOS10/Android is undocumented

### ISSUE THREAD

**Issue by bramus** [jwplayer/jwplayer#1596]
Hidden in the releasenotes I found out that version 7.8.1 [“added support for inline autoplay while muted on iOS and Android”](https://developer.jwplayer.com/jw-player/docs/developer-guide/release_notes/release_notes_7/#781-113016).

The docs – both the [JS API Reference](https://developer.jwplayer.com/jw-player/docs/developer-guide/api/javascript_api_reference/) as [API Introduction](https://developer.jwplayer.com/jw-player/docs/developer-guide/api/javascript_api_introduction/)) – however have no mention of this.

**Comment by egreaves** [comment]
Hi @bramus,

You are correct in that we introduced a new feature, but the only API change for mobile autoplay pertains to ads and is documented with this new config option:

`autoplayadsmuted:true` (documented [here](https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/#advertising))

I'll close this issue and address the issue you raised re: the `getMute()` api call in the other issue you opened.
