### ISSUE TITLE
Is there a way to disable the chromecast buffering overlay?

### ISSUE THREAD

**Issue by jones-in-the-fast-lane** [jwplayer/jwplayer#1598]
I am having big problems with the jw player chromecast skin/theme/gui: Whenever it needs to (seemingly) buffer it will darken the screen a little and have the buffering icon appear on the TV buttom left. This happens _constantly_ even though I can see no noticable stutter on the video. This never happened when casting the html5 directly using Android Chrome's inbuilt casting button (the one that would appear on all html5 <video>, which they have since removed).

Is there a way to keep casting ability but remove the use of JW Player's GUI and instead use Chrome's default? Or perhaps disable the buffering screen part of the JW Player GUI?

**Comment by johnBartos** [comment]
We're about to replace our Chromecast implementation with a new implementation - this issue isn't a problem there
