### ISSUE TITLE
jwplayer cannot stop or pause in UC browser Live video

### ISSUE THREAD

**Issue by klouskingsley** [jwplayer/jwplayer#1614]
### Expected Behavior
Stops the player (returning it to the idle state) and unloads the currently playing media file.

### Actual Behavior
do not stop , continue to play the video

### Steps to reproduce

1. click to play the live video
2. call jwplayer().stop() function

### Environment

- RedMi 3 
- Android 5.1.1 LMY47V (MIUI 7.2.5.0)
- UC Browser V11.2.5.884
-  jwplayer7.6.1

**Comment by klouskingsley** [comment]
you can download the browser from [mi app store](http://app.mi.com/details?id=com.UCMobile&ref=search) or [GooglePlay](https://play.google.com/store/apps/details?id=com.UCMobile.intl&hl=en)

**Comment by robwalch** [comment]
UC Browser is not on our list of browsers we support.
