### ISSUE TITLE
Name parameter in m3u8 no longer works

### ISSUE THREAD

**Issue by JustinasDaugela** [jwplayer/jwplayer#1615]
### Expected Behavior

Name parameter should set the stream quality name

### Actual Behavior

It doesn't, qualities are shown in kbps

### Steps to reproduce

1. Use an m3u8 file with name parameter:
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1663000,NAME="High"
2. See that doesn't work

### Environment

- *Jwplayer 7.8.4*

**Comment by johnBartos** [comment]
I don't believe we've implemented this feature before

**Comment by JustinasDaugela** [comment]
@johnBartos We were using jwplayer 6 before and it worked, so it was implemented.

**Comment by johnBartos** [comment]
@JustinasDaugela That's flash - our current HTM5 library (hls.js) supports the property but we don't  use those names in our quality selector. I just checked our backlog and we have a ticket in for this already. We'll bump it up in get around to it soon but it's a lower priority item

**Comment by robwalch** [comment]
We don't use names because more times than not, the names are not appropriate for level selection. @johnBartos is working on a feature now that allows you to customize the names in the player configuration.

**Comment by JustinasDaugela** [comment]
@robwalch well, in my case I want to present users with proper names instead of stream values in kbps and there's currently no option of doing this. Since this was in the flash player I thought it should be available in html5 as well?

**Comment by robwalch** [comment]
If anything we would remove the feature from flash. @johnBartos can fill you in on the `qualityLabels` setup option we're adding. It has parity with the `hlslabels` option of yore https://support.jwplayer.com/customer/portal/questions/11313802-hls-labels

**Comment by JustinasDaugela** [comment]
@robwalch the problem with hlslabels option is that you're assuming all videos should have the same bandwith. Every video may have a different bitrate, that's why I prefer having the names in the m3u8 file itself.

**Comment by johnBartos** [comment]
@JustinasDaugela You can use `qualityLabels` (and `hlslabels`) to define a range.

https://github.com/jwplayer/jwplayer/blob/v7.10/src/js/utils/quality-labels.js#L50-L66

https://github.com/jwplayer/jwplayer/blob/v7.10/test/unit/quality-labels-test.js

We'll choose the custom label which most closely matches the bandwidth of any given level.

**Comment by JustinasDaugela** [comment]
@johnBartos that doesn't suit our usecase, though. Depending on the master video our quality levels vary:

One video can have 5k/2k/1k, the other can have 2k/1k/500 - this is why I want to use the quality labels encoded in the m3u8 files.
