### ISSUE TITLE
jwplayer是用什么工具开发的？

### ISSUE THREAD

**Issue by wechat361** [jwplayer/jwplayer#1632]
您好，我想问一下，这套jwplayer播放器，是使用什么工具开发的，我现在使用Flash build 4.7 导入后，无法编译和测试

**Comment by robwalch** [comment]
Details on Flex Lib: https://github.com/jwplayer/jwplayer/pull/1592

Remove any FLEX_HOME or AIR_HOME env vars previously set. Run `npm install`.

We still compile to a minimum of Flash plugin 11.2 to support Firefox on Linux.
