### ISSUE TITLE
Player fails to load flv files on Chrome 56

### ISSUE THREAD

**Issue by erikdonohoo** [jwplayer/jwplayer#1684]
### Expected Behavior

Player should play flvs on all browsers

### Actual Behavior

Chrome 56 a console error occurs and the player never loads

### Steps to reproduce

1. https://erikdonohoo.github.io/jwplayer-flash-player-issue/ . (view the error)
2. Code is here https://github.com/erikdonohoo/jwplayer-flash-player-issue

### Environment

- Mac OS X 10.12.2 (also 10.12.1)
- Chrome 56 (current beta, soon to be stable in a week)

This is a major issue that will soon impact all users trying to play flash videos on chrome.  We are happily paying customers right now, but since we use a flash video recorder in the browser, we require the ability to play flvs.

**Comment by dannyfinks** [comment]
Thank you for alerting us on this issue. This appears to be a chromium bug which we are following up with the chromium team on. If you would like to track its progress you can refer to https://bugs.chromium.org/p/chromium/issues/detail?id=678986

**Comment by erikdonohoo** [comment]
Thanks for the update.  I sure hope they resolve it before 56 launches so we don't have to do some ugly warning for users on 56.

**Comment by robwalch** [comment]
@erikdonohoo flvs are never going to work in Chrome with HTML5 by default. While we have identified a problem with Flash in Chrome 56, it is not the behavior you describe. Using FLV files is not a solution for playing video across browsers in 2017.

**Comment by erikdonohoo** [comment]
Of course flvs aren't the right answer, but the web isn't ready for everything flash was built to handle.  We do live video recording and we play back a recorded flv immediately after capture through wowza.  It gets encoded and then is playable in mp4 thereafter, but since the webrtc spec keeps changing and isn't finalized, there is no good replacement for flash in this regard yet.  Does flash suck?  Yes.  But not everything flash does is replicated in html5 yet.  We are working on a new html5 recorder, but it will not be able to support all browsers our flash one does  (cough IE, Safari).

**Comment by robwalch** [comment]
Just merged the workaround for the [Chrome 56 issue](https://bugs.chromium.org/p/chromium/issues/detail?id=678986). It will be included in JW Player 7.9 which we aim to release later this month. Hopefully the Chrome team will acknowledge the issue in Chrome beta/canary and provide a fix before v56 goes production.
