### ISSUE TITLE
Construction error

### ISSUE THREAD

**Issue by stoneyong** [jwplayer/jwplayer#1706]
### Expected Behavior

Construction error

### Actual Behavior

*Describe actual behavior*

### Steps to reproduce
In the implementation of grunt build times wrong  :
Fatal error: spawn C:\Users\zoucy\Desktop\jwplayer-master\jwplayer-master\node_m
odules\jwplayer-flex-sdk\lib\flex_sdk\bin\mxmlc.bat ENOENT

### Environment

- *hardware | device*
- *operating system | version*
   win7
- *browser | version*
- *JW Player version | url*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
I don't believe our build will work in windows 7. What grunt command are you using?

**Comment by stoneyong** [comment]
n the execution of the grunt command to run to the flash:bug will prompt the error, flash file compiler, however, other normal. I am not familiar with flash, try to use other tools to compile the flash file is OK, so I am not sure what is the problem?

**Comment by BilalHalayqa** [comment]
Hello any luck with this ? I am using windows 10

**Comment by robwalch** [comment]
No. We do not support Grunt flash compilation errors on Windows.

If you can provide a PR we'll consider merging a fix whether it's here or in https://github.com/jwplayer/node-flex-sdk
