### ISSUE TITLE
Captions (vtt) under controlbar [7.9.0 / Firefox]

### ISSUE THREAD

**Issue by fdambrosio** [jwplayer/jwplayer#1711]
### Expected Behavior

 Captions are always visible. 

### Actual Behavior

On Firefox (50.1.0) the captions text slide under the control bar when the mouse cursor move over the player.

### Steps to reproduce

1. create a page with jwplayer 7.9.0 beta 1, setup with HLS stream and vtt file track. 
2. open that page with Firefox 50.1.0 
3. click to CC button and you have move the mouse over player 

demo page: http://web-0.radioradicale.it/prova/player7/7.9.0.html

### Environment

- Mac 10.11.6
- Firefox 50.1.0 (on Chrome and Safari the captions works as expected)
- jwplayer 7.9.0 beta 1
----------------------------------------------------------------------------------------

**Comment by fdambrosio** [comment]
There is stll the issue with 7.9.0 RC 1 on Firefox 50.1/Mac

**Comment by robwalch** [comment]
@fdambrosio this should be fixed in 7.9.0. It's on our beta player channel now and will be released to the production player channel very soon.

**Comment by fdambrosio** [comment]
hi @robwalch with 7.9.3 this issue has not been fixed

**Comment by MTYannick** [comment]
Bug is still present in 7.10.1.
