### ISSUE TITLE
cast icon does not show in Version 7.9-beta.1

### ISSUE THREAD

**Issue by Schnaaf** [jwplayer/jwplayer#1717]
### Expected Behavior

*cast icon should show up when enabled in player Version 7.9-beta.1*

### Actual Behavior

*cast icon does not show up when enabled in player Version 7.9-beta.1*

### Steps to reproduce

1. set release channel to beta
2. checked the option "Enable Chromecast and Airplay casting"
3. loaded the player preview: no cast button
4. loaded the player on my website: no cast button

### Environment

- *PC*
- *Windows 10*
- *Chrome 55.0.2883.87 m*
- *Version 7.9-beta.1*

**Comment by johnBartos** [comment]
I think we've fixed a bug related in this that will make it into beta-2

**Comment by robwalch** [comment]
Check beta 2. Thanks.
