### ISSUE TITLE
livestream HLS : changing quality makes player crash

### ISSUE THREAD

**Issue by privaloops** [jwplayer/jwplayer#1718]
### Expected Behavior

change quality

### Actual Behavior

crash without being handled

### Steps to reproduce

1. play this hls livestream
2. wait for quality to change or change it manually
3. see the player stop playing

### Environment

- Mac OsX Sierra | 10.12.2
- Chrome Version 55.0.2883.95 (64-bit)
- JW Player >7.8.2, no problem before

The stream is coming from akamaï, no problem in flash, and html with previous version

**Comment by privaloops** [comment]
stream here : http://artelive-lh.akamaihd.net/i/artelive_fr@344805/master.m3u8

**Comment by johnBartos** [comment]
@privaloops The stream 403s for me

**Comment by privaloops** [comment]
Hi John, thank you very much to check what the problem is. Unfortunately this stream is geo restricted to fr and de. Any chance to use a VPN ?

**Comment by robwalch** [comment]
Sorry, You'll need to provide a stream we can access in the states.

**Comment by robwalch** [comment]
Also please indicate which version of JW Player you are seeing the issue in specifically.

**Comment by privaloops** [comment]
"JW Player >7.8.2, no problem before"

**Comment by geoffhensley** [comment]
I can verify this happens with any HLS live stream that has multiple bitrates included. We experienced it at 7.8.3 and forward. If you need a stream, I can also offer one.

**Comment by johnBartos** [comment]
@geoffhensley We test with several mutli bitrate streams and haven't seen this yet, except when the different bitrates have wildly different PTS timestamps (which should not be the case). Any test streams would be great

**Comment by geoffhensley** [comment]
@johnBartos We did some more tests and it appears that as of 7.8.7, there is now a green flicker instead of it completely stopping. Here's a stream to test that with: 
http://jDM865y-lh.akamaihd.net/i/gatewaytrans_1@345760/master.m3u8

**Comment by privaloops** [comment]
I admit I have also witnessed that, plus a white screen sometimes before crashing.

**Comment by geoffhensley** [comment]
The white screen happened for us as well. In fact, on Beta 2 of 7.9.0 it looks like it's doing the white screen and crashing again on the above stream.

**Comment by johnBartos** [comment]
Can you verify in the hlsjs demo page?

**Comment by privaloops** [comment]
Work on hlsjs by me

**Comment by johnBartos** [comment]
Hmm ok please open a new issue so we can get a bit more organized.

**Comment by geoffhensley** [comment]
Here ya go, @johnBartos  https://github.com/jwplayer/jwplayer/issues/1722
