### ISSUE TITLE
Controls flickers when pausing video via display icon

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/jwplayer#1727]
### Expected Behavior

After clicking the pause icon in the display view the controls stay visible.

### Actual Behavior

The controls first briefly hides and becomes visible right after.

### Steps to reproduce

1. Go to http://demo.videodock.com/jwplayer/jw-showcase/video/WXu7kuaW/127Vi5Xd with a mobile device (max width 420px / jw-breakpoint-0 or jw-breakpoint-1).
2. Click the play icon.
3. Click the pause icon in the display.

### Environment

- *Android/iOS*
- *7.9-beta.2 | http://demo.videodock.com/jwplayer/jw-showcase/video/WXu7kuaW/127Vi5Xd*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
I hope you mean 7.9 beta 😅

**Comment by dannyfinks** [comment]
Thanks @ChristiaanScheermeijer we are aware of the issue and it will be resolved before 7.9 is released to production channel

**Comment by ChristiaanScheermeijer** [comment]
Cool, thanks!
