### ISSUE TITLE
jwplayer视频播放过程中连续点击时间轴尾部，导致视频时长增加为原时长两倍问题

### ISSUE THREAD

**Issue by wechat361** [jwplayer/jwplayer#1743]
您好，
      我使用jwplayer做开发的时候，发现，视频播放过程中，联系点击时间轴末尾，视频时长增加为原来的两倍了，请问这个问题是怎么产生的，该如何解决呢？

**Comment by johnBartos** [comment]
Please fill out the issue template and provide reproduction steps with a test stream.
