### ISSUE TITLE
How to change captions font size

### ISSUE THREAD

**Issue by Prokopl** [jwplayer/jwplayer#1748]
Hi,
I would like to ask, if there is a way to change font size of captions. I know, that I can use: _captions: {fontSize: xx}_, but in fact it doesn't work. I mean, if there is a way to change it in for example some .js or .css official file.

The only way I succeeded is, that I add in header of my .html site this:

```
<style>
.jw-captions {
font-size: xx!important;
}

.jwplayer video::-webkit-media-text-track-container {
font-size: xx!important;
}
</style>
```

It works, but it is not responsive - in small window or in fullscreen it's same.

Can you help me to find better way to solve this problem? What and where to change to reach a bit smaller font?

Thank you very much!

**Comment by johnBartos** [comment]
@Prokopl What browser and JWP version?

**Comment by Prokopl** [comment]
I am using a JWP version 7.8.7 - self-hosted.

_captions: {fontSize: xx},_ is not working in Chrome and Opera, only in Firefox font size is changed, but not responsive (I guess, maybe it's not problem).

Maybe we don't understand each other, I am just searching for some part of code, where responsive captions font size defined is and I can edit it there (for example to half font size). Because official font size is so big, that it occupies a lot of space in video.

**Comment by trinvh** [comment]
I think recent versions of jwplayer use natively captions renderer, so we can not style elements by css.
I also try to change captions position into top of player, but I can't.

To change captions font-size, you can use api:

`jwplayer().setCaptions({fontSize': 30});`

**Comment by egreaves** [comment]
This has been addressed in https://github.com/jwplayer/jwplayer/pull/1819
