### ISSUE TITLE
[Feature Request] primary:flash doesn't work on 64 bit Firefox for Windows

### ISSUE THREAD

**Issue by atlanto** [jwplayer/jwplayer#1749]
64bit Firefox for Windows is not supporting or is preventing or is bugged to invoke embedCallback from jwplayer.loader.swf.
At http://demo.jwplayer.com/flash-object/, it failed.
>Callback set: `function () { console.log('ActionScript invoked swf.embedCallback().') }`

only in console.

It is causing problem at http://webtv.ert.gr/

### Steps to reproduce

1. Start 64bit Firefox on Windows
2. Go to http://webtv.ert.gr/
3. Click any video (some of them are provided from youtube and they are not subject of this issue)

### Expected Behavior

Video (ad first) is ready to start normally.

### Actual Behavior

"Error loading media: File could not be played" appears.
(because primary:flash is cleared and providers-list is reset to initial order, later provider.html5.js is chosen instead of provider.flash.js.)

### Environment

Windows10 x64
Firefox x64 (any version including 53.0a1)
Flash Plugin 24.0.0.194
jwplayer.version at http://webtv.ert.gr/
7.8.7+commercial_v7-8-7.145.commercial.31bcf7.jwplayer.1258bf.freewheel.32b252.googima.ec15fb.vast.e14071.analytics.57a12a.plugin-gapro.7e936b.plugin-related.940118.plugin-sharing.fc6359.vr-plugin.5ca0dc.hls.js.

No problem at least on 32bit Firefox/Windows, 64bit Firefox/Linux(x64, mint), 64bit Google Chrome/Windows.
Bug report against mozilla is https://bugzilla.mozilla.org/show_bug.cgi?id=1332802.

### Request

If possible, something workaround only for 64bit Firefox/Windows would be appreciated.

**Comment by johnBartos** [comment]
We ignore `primary: flash` in the case the browser will not play flash content. Flash is dead and will be gone by the summer - switch your content over to hls or dash which our player supports very well on all browsers.

**Comment by atlanto** [comment]
I see. It's OK. Thanks for spending your time for this issue.
(I'm not a person of webtv.ert.gr, btw. I'm an outsider.)

**Comment by johnBartos** [comment]
@atlanto No problem, thanks for the report 😁
