### ISSUE TITLE
withCredentials not set for XMLHttpRequests

### ISSUE THREAD

**Issue by brynjagr** [jwplayer/jwplayer#1761]
### Expected Behavior
The XMLHttpRequest calls should have withCredentials set to `true`, when `playlist[index].withCredentials` is set to `true` in the config (https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/)
### Actual Behavior
When the player does requests for manifests and segments the xmlHttpRequest object has withCredentials set to `false` even if `playlist[index].withCredentials` is set to `true`.

Our current workaround is:
```
!function(send){
       XMLHttpRequest.prototype.send = function (data) {
           console.log(this);
           this.withCredentials = true;
           send.call(this, data);
       }
}(XMLHttpRequest.prototype.send);
```

### Steps to reproduce

1. Set `playlist[index].withCredentials = true`
2. Attempt to play an MPEG dash stream
3. Inspect the `this.withCredentials `value in `XMLHttprequest.prototype.send`

### Environment

- Macbook Pro
- macOS Sierra
- Chrome Version 55.0.2883.95 (64-bit)
- JW Player 7.8.2

**Comment by johnBartos** [comment]
Thanks for the report! I investigated and confirmed this bug. We'll get a fix in for either 7.9.1 or 7.10.

**Comment by seesoe** [comment]
Same issue here, cookies aren't being sent when trying to play CloudFront HLS with HTML5 player.

**Comment by johnBartos** [comment]
@seesoe I've seen a few reports about this but haven't been able to reproduce. Can you open a new issue with your config?

**Comment by seesoe** [comment]
@johnBartos , Thanks for the follow up. We did some server changes for the header and got it to work now. The only issue that remains is with the `withCredentials` flag not being obeyed. I did the prototype override trick for now and it's good to go.

**Comment by johnBartos** [comment]
@jw-kaurand Correct 👌
