### ISSUE TITLE
parameter pass through

### ISSUE THREAD

**Issue by Schnaaf** [jwplayer/jwplayer#1768]
I learned from your support engineer Randy Lemoine that the following is not a feature currently supported/implemented. So here is my feature request.

I would like to be able to pass a custom parameter name/value pair to an embedded player/playlist in my HTML. This parameter/value pair should then be appended to the configured video source as a GET parameter.

purpose:
We self host our media on a [Nimble Streamer](https://wmspanel.com/nimble) server. This server supports some advanced [paywall features](https://wmspanel.com/paywall) like [pay-per-view control](https://wmspanel.com/nimble/pay_per_view). We have obtained a premium licence for the excellent JWP and its excellent API. We will use the API for the management of videos, players and playlists. Now for getting the videos to work with the nimble streamer pay-per-view feature we have to sign every video with a wmsAuthSign GET parameter. The value for this parameter is generated on every client request and is unique to every request every user makes and is never the same twice. So I'd like a feature where I'm able to pass the wmsAuthSign parameter and its dynamic value to an embedded video/player/playlist which I got from the dashboard. This parameter should then be appended to the source of the video which is configured in the dashboard. Because of the dynamic nature of the value of this parameter I'm not able to append this name/value pair to the video source in advance.

I hope I have been clear enough and that this feature is worth considering

**Comment by johnBartos** [comment]
We've discussed implementing this in the past but AFAIK it didn't get enough traction to become implemented. I'll bring it up for discussion again in light of your use case.

**Comment by Schnaaf** [comment]
Hi John,

Thanks for the feedback. Is there any known workaround?


Op ma 30 jan. 2017 om 23:51 schreef John Bartos <notifications@github.com>

**Comment by robwalch** [comment]
Adding add key value pairs to your video urls is not the player's responsibility. If you are setting the player with JS you can modify the url with JS.

**Comment by Schnaaf** [comment]
@robwalch that means I won't be able to use your API and/or dashboard because the URL is unique for every user on every request. I know that I can use the JS API to built a player on the client side but then I'm missing out on the JW Showcase and JW Platform features.
