### ISSUE TITLE
issues and inconsistencies between mobile/desktop site on android device

### ISSUE THREAD

**Issue by Schnaaf** [jwplayer/jwplayer#1771]
I experience several issues and inconsistencies in Chrome on Android when requesting the mobile and desktop site.

JWP is
- on the beta channel with casting enabled
- loaded with HLS stream containing different qualities and caption

When requesting the mobile site in Chrome on Android I experience these issues:
- no quality selector is displayed
- no captions in video play
- no captions selector is displayed
- User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Safari/537.36
- Screenshot with remote debug console output:
![image](https://cloud.githubusercontent.com/assets/2668143/22370895/281113e8-e494-11e6-80c3-c9f3882b9b2b.png)

When requesting the desktop site in Chrome on Android I experience these issues:
- now the quality selector is displayed (as expected)
- now captions selector is displayed (as expected)
- no Chromecast button is displayed; see errors in console output
- playback does not start; probably because of JS errors in console output
- User-Agent:Mozilla/5.0 (Linux; Android 6.0.1; SM-T805 Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Safari/537.36
- Screenshot with remote debug console output:
![image](https://cloud.githubusercontent.com/assets/2668143/22370899/2e25e86c-e494-11e6-995e-d45b4f1e2810.png)

### Environment

- *Samsung Galaxy Tab S*
- *Android 6.0.1*
- *Chrome app on Android | Chrome/55.0.2883.91*
- *JW Player beta-rc1*

**Comment by hghazzi** [comment]
Hi @Schnaaf, can you provide a configuration and steps so we are able to reproduce the issues?

**Comment by Schnaaf** [comment]
1. open [this url](https://streaming4me.info/public_html/player/web/jwplayer_protected) in chrome on android device; I used a Samsung Galaxy Tab S on Android 6.0.1with Chrome app version: Chrome/55.0.2883.91
2. you should see the player as in the first screenshot

to get the behavior from the second screenshot open up the options menu from the Chrome app and check the option "request desktop site".

I'm using [Remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging) to remote debug live content on my Android device from Windows.

**Comment by Schnaaf** [comment]
@hghazzi do you have the the link from the previous post so I can remove it from the post? Do you need any more information?

**Comment by hghazzi** [comment]
I got the link, and will look into it and let you know if I need anything
else, thanks.

On Mon, Jan 30, 2017 at 7:45 AM, Patrick Savelberg <notifications@github.com

**Comment by hghazzi** [comment]
@Schnaaf 

The first issue you describe is expected behavior, and happen with or without casting enabled. We do not support quality and captions for HLS streams on Android Chrome, hence why they only shows on desktop and Android Chrome in desktop mode.

As for the second issue, are you able to consistently produce that console error? My first guess would be that chromecast is not supported when in that Android Chrome is in that desktop mode.

**Comment by Schnaaf** [comment]
@Hussam

For the first issue. At the time of the screenshot I am not casting yet.
The cast button is there because it had been enabled in the player, but it
hasnt been pressend yet. Shouldnt quality and captions be available until i
actually start casting? At least thats how it works on iOS and on desktops,
so would expect the same on Android.

For the second issue. Yes its consistent. Your guess could be right.
Anyways, there would be be no need for doing this if it weren't for the
first issue.

Op di 31 jan. 2017 om 00:12 schreef Hussam Ghazzi <notifications@github.com>

**Comment by robwalch** [comment]
Desktop on Chrome changes the browser user agent which breaks Google's Chromecast sender API, and changes our player's ability to play HLS. We do not support Android Chrome in desktop mode and neither does the Google's Chromecast sender API.

**Comment by Schnaaf** [comment]
Thanks @robwalch that makes sense and answers the second issue. I now see that I have misread @hghazzi answer. He says "We do not support quality and captions for HLS streams on Android Chrome". That's quite disappointing. Is there an overview of which technologies on which platforms are supported? I'm considering the refund option because too many things are currently not working on JWP.

**Comment by robwalch** [comment]
On Android, HLS playback depends on the capabilities on the device/browser. We cannot support features not supported by the browser with native playback.

**Comment by robwalch** [comment]
> Is there an overview of which technologies on which platforms are supported?

JW Player Developer: The State of HTML5 Video
https://developer.jwplayer.com/articles/html5-report/

That covers what is supported by the browsers. We use MSE in Chrome and Firefox on desktop to support DASH and HLS. Native browser or Flash support is used elsewhere. Finally is a format is not supported, we fallback to the next format provided in the playlist item.

We may add support for hls.js and shaka-player on Android with Android Chrome, but have no timeline for this enhancement at this time. IMO native playback is the most efficient option, so if you need a feature like captions you should provide a side loaded VTT or srt file for these devices.

**Comment by Schnaaf** [comment]
Thanks for this info, very helpfull!
