### ISSUE TITLE
MP3s not working Chrome 56 with JwPlayer autostart enabled

### ISSUE THREAD

**Issue by messenjer** [jwplayer/jwplayer#1773]
### Expected Behavior

Play mp3 in Chrome

### Actual Behavior

We experience several issues when playing mp3 in Chrome. The audios mp3 don't play or stop after 1 second.

We don't have this issue with other browsers Firefox, Internet Explorer, ...

We can play the mp3 directly in the Chrome browser (directly in the location url) or when we set autostart to false in JwPlayer.

### Steps to reproduce

1. MP3 to test: https://rtbf-vod.prp.l3.freecaster.net/rod/rtbf/geo/open/4/4jp8hrQ604.mp3
2. Test with JW Player Stream Tester : https://developer.jwplayer.com/tools/stream-tester/
3. When the stream plays, it stops after 1 second

#### Config JwPlayer

```
{
  "playlist": [
    {
      "sources": [
        {
          "default": false,
          "file": "https://rtbf-vod.prp.l3.freecaster.net/rod/rtbf/geo/open/4/4jp8hrQ604.mp3",
          "label": "0",
          "type": "mp3",
          "preload": "none"
        }
      ]
    }
  ],
  "autostart" : true,
  "primary": "html5",
  "hlshtml": true
}
```

### Environment

- Desktop
- Max Os X, Linux Ubuntu
- Chrome | 56.0.2924.76 (64-bit)
- JW Player 7.8

**Comment by robwalch** [comment]
Thanks for the detailed bug report.

**Comment by messenjer** [comment]
Hello, it was an issue with a http header (HTTP Accept-Ranges: bytes). It's fixed on our side.
