### ISSUE TITLE
Do not add unused styles

### ISSUE THREAD

**Issue by robwalch** [jwplayer/jwplayer#1784]
### Problem

Our view test reveals that unused styles are added to the DOM for captions and style overrides (`setup({ activeColor: '#fff' }`). If these features are not used (not configured or not active) we should not add styles to the DOM when setting up the view. All defaults should be defined in the core style (less files).

#### Examples

1. These rules are added even when captions are not present in the media or custom font colors are configured. The defaults we set, cause these to be injected even when there is no customization. These should only be added lazily, when captions will be rendered by a player and defaults should be included in our less files
.
```css
#playerid .jw-text-track-display (with override color, no captions)
#playerid .jw-text-track-cue
#playerid .jw-video::cue
#playerid .jw-video::-webkit-media-text-track-display-backdrop
```

2. The Safari fix for background gradients with timeslider above now always injects this rule for all players even where there is no custom background override. This is completely unnecessary and should be guarded against when [skinColorBackground](https://github.com/jwplayer/jwplayer/blob/9f9d346599bff4c72c04cb4b7f5633c1235b7fa3/src/js/view/view.js#L372-L375) is undefined.

```css
#playerid .jw-flag-time-slider-above .jw-background-color.jw-slider-time { transparent }
```

### Expected

A basic player setup has no CSS injected by JS specific to that player (css rules that start with #playerId).

```js
jwplayer('playerId').setup({
    file: 'video.mp4'
});
```

### Test Page

/test/view

**Comment by egreaves** [comment]
Resolved with https://github.com/jwplayer/jwplayer/pull/1864
