### ISSUE TITLE
When playing MP4 in IE or Edge, video does not resize when player size changes

### ISSUE THREAD

**Issue by IsaacSchemm** [jwplayer/jwplayer#1788]
### Expected Behavior

When an MP4 is playing, and the player is resized, the video should resize to fill the player.

### Actual Behavior

The video size does not change - it gets cut off if the player is made smaller, and does not grow if the player if made larger.

### Steps to reproduce

Play an MP4 in JW Player 7.9 in IE 11 or Microsoft Edge.
Example: http://www.lakora.us/jwplayer-ie11-mp4-issue/

### Environment

- Windows 10
- Internet Explorer 11 / Microsoft Edge
- JW Player 7.9

**Comment by robwalch** [comment]
@IsaacSchemm we can't support responsiveness when you modify the player's DOM element width and height style attributes directly. These must be managed by the player. There are two ways in which I recommend you resize the player:

1. Use `jwplayer().resize(width, height)`
2. Put a responsive player in a container that you controls the dimensions of with CSS

The first option will work best for your example. `resize` will update the same attributes that your test page modifies with jQuery, but will also update the media and player breakpoints that augment controls. When you setup the player with a fixed width and height, the player is not responsive to external size change, so you must use `resize` in this case.

Responsive players are setup using percentages for width: `width: "100%` and either `height: "100%` or `aspectratio: "16:9"`.
