### ISSUE TITLE
Slow switching audio track - DVR, VOD.

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#1796]
### Expected Behavior
Faster  switching the audio track. http://dailymotion.github.io/hls.js/demo/ ( < 1s)
### Actual Behavior
VOD and DVR: Slow switching audio track (10-20s.) and stoping playback.
### Steps to reproduce

1. Open page: https://developer.jwplayer.com/tools/stream-tester/  and load https://wowzaec2demo.streamlock.net/vod-multitrack/_definst_/smil:ElephantsDream/ElephantsDream.smil/playlist.m3u8
-or- 
https://developer.jwplayer.com/jw-player/demos/toolbox/hlsv4-audio-tracks/
2. Switch audio track.

### Environment

- OSX 10.12 
- Chrome 55
- JW Player 7.9

**Comment by johnBartos** [comment]
Currently looking into thos

**Comment by mtoczko** [comment]
It may be related to #1803 
Download every audio file and searches for a file only forward. 
TEST:
1. Run player
2. Switch audio track
3. Seek +60s

**Comment by mtoczko** [comment]
@johnBartos: I found solution: 
**provider.hlsjs.js**
```js
case R.IDLE:
    var n = this.tracks;
    if (!n)break;
    if (!this.media && (this.startFragRequested || !a.startFragPrefetch))break;
    e = this.loadedmetadata ? this.media.currentTime : this.nextLoadPosition ? this.nextLoadPosition : 0;
     var s = this.mediaBuffer ? this.mediaBuffer : this.media,
     o = h["default"].bufferInfo(s, e, a.maxBufferHole), l = o.len, d = o.end,
     c = this.fragPrevious, f = a.maxMaxBufferLength, v = this.audioSwitch,
     p = this.trackId;
     /*  
     // Old if
     // if (l < f && p < n.length)) {
     */
     if ((l < f && p < n.length) || this.audioSwitch) {
         if (r = n[p].details, "undefined" == typeof r) {
             this.state = R.WAITING_TRACK;
             break
           };
```

**Comment by johnBartos** [comment]
@mtoczko Interesting. This is hls.js source code

**Comment by mtoczko** [comment]
@johnBartos Fixed - hls.js 7.5
