### ISSUE TITLE
cannot full screen on chrome of macbook 

### ISSUE THREAD

**Issue by wechat361** [jwplayer/jwplayer#1798]
### Expected Behavior

when click full screen , it can show full screen right now on chrome of macbook 

### Actual Behavior

it cannot full screen on chrome of macbook , and my screen is 1920 x 1080

### Environment

- *hardware | device*
- macos 10.12.3 (16D32)
- *browser | chrome 55.0.2883.95 for mac
- *JW Player version 6.8

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by dannyfinks** [comment]
@wechat361 we are no longer supporting any of the JW6 versions of the player. The latest version of our player is 7.9.0. Please find our release notes here https://developer.jwplayer.com/jw-player/docs/developer-guide/release_notes/release_notes_7/
