### ISSUE TITLE
The same video(flv) will be different show in different brower

### ISSUE THREAD

**Issue by wechat361** [jwplayer/jwplayer#1799]
### Expected Behavior

the same video have same show

### Actual Behavior

the same video can play end on chrome , but it cannot play end on firefox

### Steps to reproduce

1.
2.
3.

### Environment

- macbook pro
- macos 10.12.3 (16D32)
- browser chrome 55.0.2883.95 / firefox 51.0.1 (64-bit)
- *JW Player version 6.8

----------------------------------------------------------------------------------------

**Comment by johnBartos** [comment]
Support for JW6 ended December 31, 2016. Please upgrade to the latest player (7.9).

Additionally, I don't believe FLVs work in Firefox.
