### ISSUE TITLE
LIVE with empty manifest will keep loading

### ISSUE THREAD

**Issue by sajkec** [jwplayer/jwplayer#1800]
### Expected Behavior

LIVE with empty manifest should detect that there is no stream and "fail"  (show image from playlist)

### Actual Behavior

LIVE with empty manifest is showing loading spinner all the time.

### Steps to reproduce

1. Open https://video.arnes.si/live7.html in Chrome/Firefox and press play
2. Repeat in Safari, where it works ok (fail after a few seconds)

### Environment

- Macbook pro, HP laptop
- MacOS Sierra, Debian Linux 8
- Safari 10, FF 50, Chrome 56
- Jwplayer 7.9.0 (JWplayer CDN Production)

**Comment by johnBartos** [comment]
@sajkec Post your config please? This errors out in a naked player (just a `file` attribute).

**Comment by sajkec** [comment]
Further investigation shows that this issue is only with Live HLS. Minimal config to repeat the issue:

    jwplayer("jw").setup({          
                    'file': 'https://prenosi.arnes.si/187-2017-1-16-117e/_definst_/ngrp:arnes_all/playlist.m3u8'     
    });

While with DASH this errors in 2seconds:

    jwplayer("jw").setup({
                        file: 'https://prenosi.arnes.si/187-2017-1-16-117e/_definst_/ngrp:arnes_all/manifest.mpd'       
    });

You can test with my sources above, they are Wowza ngrp based playlist/manifest files. Addin 'hlshtml':'true' and does not make a difference.

**Comment by robwalch** [comment]
This has been addressed in v7.10. @johnBartos can provide details on the error event dispatched by the player when live streams timeout or stop updating.

**Comment by robwalch** [comment]
Live streams that return the same result and run out of buffer should error with the message: "The live stream is either down or has ended"
https://github.com/jwplayer/jwplayer/pull/1858
