### ISSUE TITLE
HLS with separate audio/video track issue

### ISSUE THREAD

**Issue by jeremydenoun** [jwplayer/jwplayer#1805]
Hi,

Please find a bug report about hls streaming (I can give you a sample url with issue if needed)

### Expected Behavior

HLS stream with separate audio/video tracks should work

### Actual Behavior

With jwplayer `v7.8.7`, HLS look like :

```
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="eng",NAME="English",AUTOSELECT=YES,DEFAULT=YES,URI="aud_index.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=8000000,CODECS="mp4a.40.2, avc1.4d401e",RESOLUTION=1920x1080,AUDIO="audio"
vid_index.m3u8
```
work perfectly

since jwplayer `v7.9` (and `v7.9.1`) this doesn't work

Network console let's appear audio m3u8 and first segment are download but never play (and no new segment are download)

### Steps to reproduce

1. create a m3u8 with audio and video separate
2. try to play it

### Environment

- macbook
- osx 10.11.6
- chrome 56
- multiple jwplayer versions

**Comment by johnBartos** [comment]
@jeremydenoun Hmm we recently fixed a bug with this, can you give us a stream please?

**Comment by jeremydenoun** [comment]
sent by mail
