### ISSUE TITLE
[Feature Request] Define cast stream

### ISSUE THREAD

**Issue by jeremydenoun** [jwplayer/jwplayer#1806]
Hi,

I have a suggestion about your fresh cast/airplay feature,
For assure compatibility with some devices we can present some alternative sources and first one can be incompatible with chromecast player.

(example first stream can be a HLS stream with multi-bitrate, multi audio and webvtt and fall back is a mp4 stream / chromecast doesn't support this kind of hls)

This will be perfect if we can choose stream (we can imagine default option use primary stream) when we press cast button. (maybe if necessary player should switch to target stream on local before start casting.

Thanks

**Comment by hghazzi** [comment]
Hi @jeremydenoun, 

That is something we may consider doing to support fallback, but will unlikely be a feature we would introduce in the near future.

As for your HLS stream, I tested one with the same features and I was able to cast it. Can you share a stream that is not working? Might be a different issue. Here's one that I confirmed works.

`//wowzaec2demo.streamlock.net/vod-multitrack/_definst_/smil:ElephantsDream/elephantsdream2.smil/playlist.m3u8`

**Comment by jeremydenoun** [comment]
Hi @hghazzi,

ok for fallback, but simpler than fallback I think custom_cast_url can be more usefull because if you cast only "primary content url" you can't specify language/subtitle than casting device should use
(we can imagine JS API can change it on event callback for be sure to use right url) or you should maybe implement https://developers.google.com/cast/docs/player#cycling-through-audio-streams

I just check your hls stream and I see for my side some issue maybe linked to [my other issue](https://github.com/jwplayer/jwplayer/issues/1805) :

- If I start to play content in english and I try to change audio to spanish this doesn't work
- chrome casting work but I can't prove but I suspect wowza generate specific playlist maybe with video/audio merged) for chromecast but for confirm it we should analyze wowza logs.. _I will made some tests for progress on it and give you feedback if you are interested_
- If I change to spanish before start content, the content play to spanish but if I try to cast I have english version and if I stop casting the audio comeback to english

**Comment by jeremydenoun** [comment]
for informations I just find why my chromecast don't want read my HLS stream (if this can help anybody) if your HLS video stream specify codec like `CODECS="mp4a.40.2, avc1.4d401e"` chromecast directly stop casting but if codecs look like `CODECS="avc1.4d401e"` this work.

same thing if you have something like :
`#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audios",LANGUAGE="en",NAME="English",DEFAULT=NO,AUTOSELECT=YES,URI="xxx.m3u8"`
this work but
`#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audios",LANGUAGE="en",NAME="English",DEFAULT=YES,AUTOSELECT=YES,URI="xxx.m3u8"` break default mediaplayer.js

**Comment by jeremydenoun** [comment]
I finish my tests and for resume this issue/feature request we have :
- chromecast can only read "aac" audio segmented content (and not aac embed in mpegts)
- codecs ordering definition is important for chromecast
- if you have a direct return to player when you try to cast a content this can mean :
   1) you have an error into your content (syntax, format, ...)
   2) this combination isn't supported
- jwplayer not forward selected audio stream so chromecast render default stream configuration (and 

thanks @hghazzi for demo stream this help me to compare and fix broadcasting

**Comment by hghazzi** [comment]
Hi @jeremydenoun, at the moment, we are not currently supporting multiple audio tracks while casting (which is why the audio tracks button is hidden when connected), so it will always uses whichever audio track is set to default. Currently, we have no plans to introduce that feature. 

As for when connecting when when you select spanish before connecting and get english when you disconnect, we have some work planned that should resolve this problem. No date has yet to be set for when this fix will be released. If you could, can you create a separate issue for this, so we can track it and keep you updated?

Finally to see which video and audio formats are supported, they are available in the Casting documentation `https://developers.google.com/cast/docs/media`

**Comment by jeremydenoun** [comment]
done thx
