### ISSUE TITLE
Captions Styling doesn't works in Firefox

### ISSUE THREAD

**Issue by magsout** [jwplayer/jwplayer#1813]
### Expected Behavior

Captions Styling works in Firefox

### Actual Behavior

Captions Styling doesn't works in Firefox

### Steps to reproduce

@Fanolian submited a bug on Webcompat about caption Styling. You can found the issue here https://webcompat.com/issues/4418 or here https://github.com/webcompat/web-bugs/issues/4418

I tried to custom style for caption directly from your documentation https://developer.jwplayer.com/jw-player/demos/customization/captions-styling/ Nothing happens in Firefox. It works perfectly in Chrome.

### Environment

- Mac / Windows
- Mac OS 10 / Windows 10
- Firefox 51 and >
- Powered by JWPlayer 7.8.6

###Firefox 
![capture d ecran 2017-02-10 a 14 02 12](https://cloud.githubusercontent.com/assets/1997108/22827719/90c1e54c-ef99-11e6-9ab7-74a610bca37b.png)

###Chrome
![capture d ecran 2017-02-10 a 14 01 11](https://cloud.githubusercontent.com/assets/1997108/22827718/90aed0ba-ef99-11e6-9c71-185df3b87d6e.png)

**Comment by Fanolian** [comment]
Thanks @magsout for the demo site. I did not know about it when I filed the viu.tv compatibility issue.

I see a different result for the demo on my machine.
On my machine, the captions styling at the demo site (player version 7.9.1) does not work only if I visit the site the first time in a brand new Firefox profile (100% reproducible). Any subsequent (re)loadings of the demo do not show any problems changing the styles.

Nonetheless, the issue at viu.tv (player version 7.8.6) remains no matter how many times I have visited the site.

### Environment
Windows 10
Firefox 51 or current Nightly (2017-02-10)
JWPlayer 7.9.1 (demo) or 7.8.6 (viu.tv issue)

**Comment by charlesduco** [comment]
When playing HLS-streams with WebVTT-captions, styling doesn't work cause jwplayer's hls library uses native rendering for WebVTT captions on Firefox.
Firefox hasn't implemented yet the ::cue pseudo-element for styling WebVTT captions: https://bugzilla.mozilla.org/show_bug.cgi?id=865395

But a possible solution exists, jwplayer has a polyfill for WebVTT rendering in which captions styling is working.
Using the WebVTT polyfill instead of native rendering fixes this issue.

Setting the variable `renderNatively` for Firefox to false in jwplayer's hls library is a possible fix untill Mozilla has implemented the ::cue pseudo-element.

**Comment by mattcoz** [comment]
This now also applies to DASH in 7.10

**Comment by elstonsa** [comment]
Would this (::cue pseudo-element support) also be a problem for styling CEA-608 / 708?

**Comment by charlesduco** [comment]
Yes, but only for HLS/Dash streams in Firefox. JWPlayer developers will fix this very soon: https://github.com/jwplayer/jwplayer/issues/1883#issuecomment-284799131

**Comment by elstonsa** [comment]
I see this issue on Microsoft Edge too. Is there any workaround for Edge?

**Comment by johnBartos** [comment]
Thanks for the input guys, lets move the discussion here: https://github.com/jwplayer/jwplayer/issues/1813

**Comment by elstonsa** [comment]
I have tested the closed captions on firefox with my own app and also from here https://developer.jwplayer.com/jw-player/demos/customization/captions-styling/ 
The CC styling still does not work.
