### ISSUE TITLE
Chromecast not working if first source is not castable

### ISSUE THREAD

**Issue by jones-in-the-fast-lane** [jwplayer/jwplayer#1817]
Referencing this thread: https://github.com/jwplayer/jwplayer/issues/1806

Using Chrome on Android phone as well as Win10 I am unable to Cast if the first source in the playlist is FLV. I have 2 sources, FLV first and MP4 second. It appears to try to cast but then die back to the regular Chromecast screen so I am assuming it is sending the FLV link to the device instead of picking the MP4.

I will note I use primary: flash option if that is of importance. Also using a playlist with just the MP4 file works perfectly.

**Comment by hghazzi** [comment]
Hi @jones-in-the-fast-lane, as referenced in #1806, here is the list of supported formats that Casting: `https://developers.google.com/cast/docs/media`. 

For formats that we can identify beforehand playback, we can introduce more logic to ignore them, though there is no timeline on when we would make those changes.

**Comment by robwalch** [comment]
"primary: flash" will be deprecated in JW Player 8. We recommend against using it now that support for Flash in browsers is in decline. We also recommend against using flv video sources - exlspecially when MP4 is an option and well supported across all browsers without plugins. For these reasons, this is not an issue we will address on our end.
