### ISSUE TITLE
can myself custom load the div dom ?

### ISSUE THREAD

**Issue by javyuan** [jwplayer/jwplayer#1818]
error:
Uncaught TypeError: jwplayer(...).setup is not a function
my main code(a jsp tag):
`<div id="player"></div>`
`<script type="text/javascript">`
`		jwplayer("player").setup({`
`			file: "${fileUrl}"`
`		});`
`</script>`
in my html , i use `window.parent.parent.document.getElementById(xx)` to get dom,
i think this error is becose of jwplayer can not find my "player" div. 
can i custom to get the player div ? just like jwplayer(DOM).setup?

**Comment by johnBartos** [comment]
@javyuan Yeah you can use an id, just like in your example. That error sounds like you're not loading the JW player library though - even if it can't find your div it'll create a new one.

**Comment by javyuan** [comment]
when not loading the jwplayer.js the error is "jwplayer is not defined"
