### ISSUE TITLE
how to download video from this website?

### ISSUE THREAD

**Issue by jameshentai** [jwplayer/jwplayer#1826]
it is type jw player video. but i don't know how to download http://tiphero.com/easy-apple-pie-cookies/. please help.

**Comment by johnBartos** [comment]
@jameshentai We don't condone downloading videos from publishers without their permission.

**Comment by grahamperrin** [comment]
https://mobile.twitter.com/grahamperrin/status/1051005890491506693 is thought-provoking. MEDIAL use of JW Player, AFAICT there's no _easy_ way for the content owner (original producer) to download his or her own content. This is, I think, one of a number of UX mistakes by MEDIAL.
