### ISSUE TITLE
ChromeCast not follow selected language in jwplayer

### ISSUE THREAD

**Issue by jeremydenoun** [jwplayer/jwplayer#1830]
> hghazzi, February 16th 2017 
As for when connecting when when you select spanish before connecting and get english when you disconnect, we have some work planned that should resolve this problem. No date has yet to be set for when this fix will be released. If you could, can you create a separate issue for this, so we can track it and keep you updated?

more details on https://github.com/jwplayer/jwplayer/issues/1806

**Comment by hghazzi** [comment]
From the Google Cast docs:
`Note: Currently, the Styled and Default Media Receivers allow you to use only the text tracks with the API. To work with the audio and video tracks, you must develop a Custom Receiver.`

https://developers.google.com/cast/docs/chrome_sender_advanced

We currently have no plans to reintroduce a custom receiver and will be using the default receiver for the foreseeable future.

**Comment by jeremydenoun** [comment]
ok it's a good reason
