### ISSUE TITLE
Page lags when zone.js is included and playing an rtmp stream

### ISSUE THREAD

**Issue by adamk33n3r** [jwplayer/jwplayer#1836]
### Expected Behavior

Normal lag-free behavior

### Actual Behavior

Page/player/input lag while playing an rtmp stream.

### Steps to reproduce

1. Include zone.js.
2. Play rtmp stream.
3. Video and text inputs are extremely laggy/frozen.

### Environment

- Windows
- Chrome Version 56.0.2924.87
- JW Player version 7.8.7 and 7.4.3

Now I don't know if there's even something that can be done about this I just wanted to put the information out there. The workaround solution that I've come up with is to put the player in an `<iframe>`. This puts it in its own instance away from the zone.js code. But it also greatly complicates the interaction between the player and the rest of the sites code.

Link to zone.js: https://github.com/angular/zone.js/

**Comment by johnBartos** [comment]
If you use the HTML5 player with zone does it still lag?

**Comment by adamk33n3r** [comment]
I think using the HTML5 player is fine. I'm just not able to use that for RTMP, afaik.

**Comment by robwalch** [comment]
Sounds like an issue with zone.js...

v7.10.1 [has changes](https://github.com/jwplayer/jwplayer/milestone/44?closed=1) that may help the with performance when other libraries on the page block js or schedule timeouts frequently.

**Comment by robwalch** [comment]
Our latest release includes some Flash performance enhancements. If you are still experiencing issues, reach out to zone.js and/or stop using Flash.

**Comment by adamk33n3r** [comment]
Thanks for the info! I'll be sure to check out the beta. Hoping it works since HTML5 unfortuneately doesn't support RTMP :smile:
