### ISSUE TITLE
YouTube Player PlayBTN tap on Mobiles Android / IOS

### ISSUE THREAD

**Issue by geoSo** [jwplayer/jwplayer#1842]
### Issue

When  youTube player is on a mobile device, and a user taps on play-btn,
it doesn't always activates playing.

After some testing i found the the  
`<div class="jw-icon jw-icon-display jw-button-color jw-reset" role="button" tabindex="0" aria-label="Start playback"</div>`
doesn't inherits the _pointer-events: none_

I tested to delete the element, or to give it the same css, and it seems to work a bit smoother 

### Possible Solution

The css **pointer-events: none** needs to be on :

**.jw-display-icon-container** (as it is already)
and on **.jw-display-icon-container > .jw-icon**

### Steps to reproduce

1. open player with a utube file from a smartphone or tablet and tap it to play

### Environment

- *android | ios*
- *JW Player version | 7.8

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
@geoSo Can you reproduce this in 7.9? We shipped a lot of UI changes with it.

**Comment by geoSo** [comment]
On 7.9 version, in order to achieve the same behavior, i used

**.jw-display-icon-container** and **.jw-display-icon-container .jw-icon**

The exact code is:

`player.on('playlistItem', function () {`
`if (media.isYoutube) {`
                `        $(wrapperID).find('.jw-display-icon-container').css({'pointer-events': 'none'});`
               ` $(vars.wrapperID).find('.jw-display-icon-container .jw-icon').css({'pointer-events': 'none'});`
         `   } else {`
              `  $(vars.wrapperID).find('.jw-display-icon-container').css({'pointer-events': 'auto'});`
               `  $(vars.wrapperID).find('.jw-display-icon-container .jw-icon').css({'pointer-events': 'auto'});       `         
       `     }`
            `    })`

**Comment by geoSo** [comment]
On 7.9 version, in order to achieve the same behavior, i used

**.jw-display-icon-container** and **.jw-display-icon-container .jw-icon**

The exact code is:

`player.on('playlistItem', function () {`
`if (media.isYoutube) {`
                ` $(wrapperID).find('.jw-display-icon-container').css({'pointer-events': 'none'});`
               ` $(vars.wrapperID).find('.jw-display-icon-container .jw-icon').css({'pointer-events': 'none'});`
         `   } else {`
              `  $(vars.wrapperID).find('.jw-display-icon-container').css({'pointer-events': 'auto'});`
               `  $(vars.wrapperID).find('.jw-display-icon-container .jw-icon').css({'pointer-events': 'auto'});       `         
       `     }`
            `    })`

**BUT** for some reason now (a change between 7.8 and 7.9), user have to wait 1 second before tap the play-btn. It seems like scripts are not ready.
 If he doesn't wait, the state remains inactve

**Comment by spello** [comment]
Sadly, it doesn't fix my issue #2097 Do you have any example so I could test it on my mobile?

> ### Steps to reproduce
> 1. open web browser on iPhone or other supported but non-Android device
> 2. go to http://qa.jwplayer.com/~abussey/demos/general/play-via-link-youtube.html
> 3. click at `<a onclick="playerInstance.play();">Click here</a> to begin playback.`
> 4. it won't play YouTube video
