### ISSUE TITLE
HLS sometimes stopped screen like a snap shot.

### ISSUE THREAD

**Issue by allostue** [jwplayer/jwplayer#1843]
### Expected Behavior

HLS on jwplayer

### Actual Behavior

Sometimes stopped screen like a snap shot.

### Steps to reproduce

When i start streaming look good everything.
But sometimes jwplayer stop screen (like a snap image).
Network packet was called .m3u8 only when stopped screen.
.ts files not called.
Refresh chrome or jwplayer then download .ts again.

here is my m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:33130
#EXT-X-TARGETDURATION:2
#EXTINF:2.000,
stream-33130.ts
#EXTINF:2.000,
stream-33131.ts
#EXTINF:2.000,
stream-33132.ts

Is this problem is CDN or server cache? or network? or nginx settings?
I don't have any idea.
This problem occurred randomize pc and time. (sometime hls 10hours no problem. but sometime stopped 2~3 times per hour)
If someone have expierence this problem please help me.

### Environment

Stream client program : Xsplit 2.9.x
Web browser : Chrome (any version same problem)
Streaming player : jwplayer premium (embed js)
Stream server : Ubuntu 16.04 / nginx-rtmp-module 1.1.4 / nginx 1.11.9
Host server : Amazon EC2 m4.large + Cloudfront all edge

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
@allostue Is that your whole m3u8? It stops like a "snapshot" (instead of closing gracefully and showing the replay icon) because your manifest has no `#EXT-X-ENDLIST`. This tag tells us that the stream is not live and that playback should end.

**Comment by allostue** [comment]
@johnBartos Yes this is my whole m3u8.
This is http live streaming am i need to add `#EXT-X-ENDLIST` tag in manifest?
But when i check jwplayer test web page also look the same as my m3u8.

```
http://demo.jwplayer.com/developer-tools/http-stream-tester/
http://wowza.jwplayer.com/live/jelly.stream/chunklist_w1306304430.m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:16
#EXT-X-MEDIA-SEQUENCE:58346
#EXTINF:8.009,
media_w1306304430_58346.ts
#EXTINF:12.012,
media_w1306304430_58347.ts
#EXTINF:8.009,
media_w1306304430_58348.ts
```

Anyway i'll try to add `#EXT-X-ENDLIST` tag in manifest.
Thanks!

**Comment by robwalch** [comment]
Please include a test page or sample setup and player configuration.
