### ISSUE TITLE
VAST XML And Impressions

### ISSUE THREAD

**Issue by vixa2012** [jwplayer/jwplayer#1851]
Hello. We create our ADServer and we get some problems. We need your help!

This is our vast dynamical page: [http://vast.adserver4.com/tag/7](http://vast.adserver4.com/tag/7)
How you can see we add to vast our impression element and tracking events:
```
<Impression>
<![CDATA[
http://vast.adserver4.com/api/events?event=impression&demand_tag=63&supply_tag=7
]]>
</Impression>
```

When player return impression our server write request to redis then dump it to our db.

We add this vast Dynamical page to player on a third-party server. When we see statistics on Third-party server and on our ADServer we get different results.

Third-party server use your jwpayer to show ad.

Our ADServer got 115 000 impressions, but third-party server show 5000 impression.

This is large difference. Can you help me, why third-party server got 5000 impression, at the same time our server show 115000 impressions?

**Comment by johnBartos** [comment]
Please post your config and player version

**Comment by robwalch** [comment]
We can help with playe issues, not with ad server problems

Let us know if you notice browser behavior that doesn't match what you expect from the IAB's VAST spec. Please include a test page with a bug description and steps to reproduce.
