### ISSUE TITLE
Chrome browser on iOS only shows AirPlay icon, even if Chromecast is available

### ISSUE THREAD

**Issue by jones-in-the-fast-lane** [jwplayer/jwplayer#1867]
I'll update this soon but I have noticed this

**Comment by dannyfinks** [comment]
Hi @jones-in-the-fast-lane the default Chromecast media receiver we use does not currently support iOS Chrome. If its mentions that it is support in any of our documentation, I will follow up on that.

**Comment by hghazzi** [comment]
Hi @jones-in-the-fast-lane & @kennysmoothx, the latest version of the chromecast API does not support Chrome iOS, it only supports Airplay. 

We deprecated support for custom receivers, as we wanted to simplify the process of enabling casting without having to register with Google. Even if it was supported, it would not work with Chrome iOS. 

All the changes in casting is available in the support site, though we do need to update it to clarify what is supported by iOS.

https://support.jwplayer.com/customer/portal/articles/1611847-introduction-to-casting

**Comment by kennysmoothx** [comment]
Thats very odd, why wouldn't Google's default media receiver support Chrome for iOS?

Shouldn't the receiver receive the same data from Android/Desktop/iOS Chrome?

**Comment by hghazzi** [comment]
@kennysmoothx It isn't that the receiver does not support iOS Chrome, but rather due to the limitations of Chrome on iOS, the browser cannot support the new Chromecast API, and only works with Airplay.
