### ISSUE TITLE
Mobile Website, Full Screen Ads Delivery

### ISSUE THREAD

**Issue by musictelevision** [jwplayer/jwplayer#1870]
### Expected Behavior
(Showcase, mobile view -- I presented the matter within the Showcase page, and the team recommended we post here -- https://github.com/jwplayer/jw-showcase/issues/103)

Viewing a film in full screen mode, on a mobile device, we're expecting linear video commercials to play properly in full screen mode, with the film restarting after the end of the commercial or ad pod break.

### Actual Behavior

When we come to a commercial break, in full screen mode, the video pauses like it should. About 50% of the time, we're able to hear the audio of the commercial playing (the other 50% of the time, from a user perspective, it seems as if the screen / video / player has frozen). By clicking done, we're brought back to the video page, where the video commercial and or ad pods play perfectly, in a small screen view, the view with the film description below.

### Steps to reproduce

Visit www.legendstv.com from a mobile device
click on any of the film arts

###Environment

Safari, iPhone 5
iOS |10.2.1
Current Showcase Version | www.legendstv.com

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
@musictelevision What's your player version?

**Comment by musictelevision** [comment]
I believe we're on using the most up to date version -- the showcase app runs from the cloud, and I recall seeing somewhere that cloud hosted players auto update

Sent from my iPhone

On Mar 2, 2017, at 2:58 PM, John Bartos <notifications@github.com<mailto:notifications@github.com>> wrote:


@musictelevision<https://github.com/musictelevision> What's your player version?

**Comment by robwalch** [comment]
This an issue with the Google IMA SDK. They recently changed the behavior of video tags with the playsinline attribute. We're working with Google to get a fix in the SDK as we don't think using this attribute should mean the player won't go full screen. They're "custom playback" mode is still needed. 

In the mean time if we don't yet have a workaround you could query the video tag and remove the attribute to see if it restores custom playback (custome playback ensures the same video tag is used for ads and content playback.) That behavior is not controlled by our player, but the IMA SDK.

**Comment by musictelevision** [comment]
Sounds like switching our ad schedule protocol to VAST within the dashboard should do the trick

Charles I. Blanton
Legends Media Group, Inc. | CEO
Isaac@legendstv.us<mailto:Isaac@legendstv.us>
404.432.4356

________________________________

**Comment by robwalch** [comment]
Yes. If you've contacted us outside of github about this issue, we should get back to you when the issue is resolved so that you can take advantage of features in IMA.

**Comment by musictelevision** [comment]
Awesome thanks Rob

Charles I. Blanton
Legends Media Group, Inc. | CEO
Isaac@legendstv.us<mailto:Isaac@legendstv.us>
404.432.4356

________________________________
