### ISSUE TITLE
Captions (vtt) under controlbar [7.10.0 beta / Firefox]

### ISSUE THREAD

**Issue by fdambrosio** [jwplayer/jwplayer#1883]
### Expected Behavior

Captions are always visible.

### Actual Behavior

On Firefox (51.0.1) the captions text slide under the control bar when the mouse cursor move over the player.

### Steps to reproduce

- create a page with jwplayer 7.10.0 beta 1, setup with HLS stream and vtt file track.
- open that page with Firefox 51.0.1
- click to CC button and you have move the mouse over player

demo page: http://web-0.radioradicale.it/prova/player7/7.10.0.html

### Environment

- Mac 10.11.6
- Firefox 51.0.1 (on Chrome and Safari the captions works as expected)
- jwplayer 7.10.0 beta 1

**Comment by mattcoz** [comment]
It seems to now be using native caption rendering in Firefox and not styling them properly.

**Comment by johnBartos** [comment]
<img width="553" alt="screen shot 2017-03-07 at 12 24 47" src="https://cloud.githubusercontent.com/assets/5042276/23669109/243a61be-0331-11e7-9d77-0940d2efb101.png">


fyi

**Comment by egreaves** [comment]
@fdambrosio @mattcoz thanks for pointing this out. We are aware of this limitation in Firefox with natively rendered captions. 

Currently, captions are rendered natively for HLS/Dash media. Since Firefox doesn't yet support styling Shadow DOM elements, we can't move captions up when the control bar appears like we do in Chrome/Safari. We'll be addressing this by providing a configuration option to display captions using the player's renderer in lieu of native rendering.

**Comment by mattcoz** [comment]
@egreaves That'll be great.

**Comment by fdambrosio** [comment]
thanks @egreaves @mattcoz - waiting for the configuration option; maybe I can hide controlbar when the user doesn't move mouse. 
You can see that there's a logo top-right positioning issue

**Comment by egreaves** [comment]
@fdambrosio - the logo position issue will be addressed in 7.10.0, which will be out really soon.

**Comment by fdambrosio** [comment]
@egreaves  testing 7.10.4 this issue is still here

**Comment by mattcoz** [comment]
Any update on this? When will we get the configuration option?

**Comment by johnBartos** [comment]
@mattcoz The feature is in progress and is set to be released in 7.11

**Comment by fdambrosio** [comment]
I'm testing 7.11.0 release, and the issue is still here. 
demo: http://web-0.radioradicale.it/prova/player7/711.html
open the page with Firefox and seek to 01:30

**Comment by johnBartos** [comment]
Try `renderCaptionsNatively: false` in the config

**Comment by egreaves** [comment]
@fdambrosio to expand on what @johnBartos mentioned, as of `7.11.0`, the player chooses how captions are rendered based on browser capabilities (limitations). Now, the player renders captions in all browsers except Safari and Chrome, where browser support for captions rendering is sufficient to meet FCC guidelines. 

In this instance, the `VTTCue` at the `1:30` mark has way too much text to be rendered accurately in any environment. Take a look at Safari, for example, where majority of the text is positioned below the player:
![screen shot 2017-05-15 at 3 13 48 pm](https://cloud.githubusercontent.com/assets/4603952/26074835/43c4f2fc-3981-11e7-9b5d-66b57557d0ca.png)

Try testing this with a reasonable amount of text per cue. It should work fine in all environments.

**Comment by mattcoz** [comment]
I've tried setting renderCaptionsNatively both at the root of my config and under captions, neither are working. This is in 7.11.2

**Comment by johnBartos** [comment]
@mattcoz What browser?

**Comment by mattcoz** [comment]
Firefox, both current and nightly.

- Matt

**Comment by mattcoz** [comment]
Still an issue in 7.11.3 but looks like it is fixed in the 7.12 beta.

**Comment by treyseals** [comment]
This is still an issue in Safari.
