### ISSUE TITLE
Crashes in JW Player

### ISSUE THREAD

**Issue by ashishg656** [jwplayer/jwplayer#1893]
### Expected Behavior
Application should not crash

*Describe expected behavior*
Even if some error occurs in JW Player internal files, it should handle the error gracefully. 

### Actual Behavior
Getting log of crashes in JW Player. 

*Describe actual behavior*
Hi, I am getting log of error in JW Player Android SDK implementation. Please help me in fixing these issues. I am not able to check why the crashes are occurring since proguard has changes method names for JW Player. Crashlytics logs are -
1. http://crashes.to/s/35bcf8a881f - 1529 crashes in past 30 days.
2. http://crashes.to/s/baa56117c79 - 505 crashes in past 30 days.
There are other issues as well but these are ones which are at highest priority. Also created a support ticket, but still haven't got any fix yet.
I have got multiple crashes in JW Player Sample App as well.

### Steps to reproduce

1. Play video
2. Click on pause button
3. Crash

### Environment

- *hardware | device* - Redmi Note 3 and all android devices - mentioned in crashlytics logs
- *operating system | version* - Android version 6.0 and others as well - check crashlytics link
- *browser | version*
- *JW Player version | url* - 2.7.0 Android 

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
This project is not the place to report mobile SDK issues. Please contact support at jwplayer.
