### ISSUE TITLE
JW Player only casting first source instead of default source to Chromecast

### ISSUE THREAD

**Issue by dominovox** [jwplayer/jwplayer#1896]
### Expected Behavior

As described here https://support.jwplayer.com/customer/portal/articles/1611847-introduction-to-casting the JW Player should cast the "default quality" source to Chromecast, the default source is set by "default": "true" as described here https://support.jwplayer.com/customer/portal/articles/1428524-hd-quality-toggling , in my case the 720p file.

### Actual Behavior

The JW Player always casts the first source in the list to Chromecast, ignoring the "default": "true" config, in my case it is always the 480p one.
A temp. workarround would be changing the quality order so that 720p would be the first source, but the default feature does not work as described.

### Steps to reproduce

1. Go to my testpage in Chrome: http://www.pietsmiet.de/playertest/player.html
2. Cast to Chromecast
3. All 3 videofiles have their resolution as text in video, you can check the sources by yourself in the sourcecode.

### Environment

- *hardware | Chromecast Gen 1 and 2*
- *operating system | Win 10 Home 64bit + 1607*
- *browser | Chrome v 57.0.2987.98 64bit*
- *JW Player version | v 7.9.0, 7.9.3 and 7.10.0 rc 1 (problem is there since v7.9.0)*

Could you please look into this?
Thank you in advance,
Dominik

**Comment by hghazzi** [comment]
Hi @dominovox,

This appears to be a valid bug in our player and we should play the default source on the chromecast device. We will review the priority of implementing a fix.

**Comment by dominovox** [comment]
Hi @hghazzi,

thank you for investigation, our users and I hope for a fix soon. I need to add that I can't test if the player has the same problem with AirPlay too, just for your information.

Thanks,
Dominik

**Comment by hghazzi** [comment]
@dominovox This has been fixed, and should be released in the next week or so. Default will be used and if there isnt any, the first source will be used.

**Comment by hghazzi** [comment]
@dominovox this has been resolved in v7.10.4, which has been released
