### ISSUE TITLE
Captions fontSize configuration doesn't work in 7.10.0-beta.2 and higher

### ISSUE THREAD

**Issue by charlesduco** [jwplayer/jwplayer#1898]
### Expected Behavior

When configuring `captions: {fontSize}` in player setup, the size of the captions text in the player should change accordingly.

### Actual Behavior

When configuring `captions: {fontSize}` in player setup, the size of the captions text in the player stays the same.

### Steps to reproduce

1. Set `captions: {fontSize: 50}` in player setup with MP4 file and WebVTT captions
2. Play video and wait for captions to show up
3. Set `captions: {fontSize: 100}` in player setup
4. Play video again and wait for captions to show up
5. You realize there in no difference in captions text size between step 2. and step 4.

### Environment

- HP Compaq | notebook
- Linux Mint | 18
- Mozilla Firefox | 51.0.1
- JW Player 7.10.0-beta.2 and higher

### Possible solution

Pass `fontSize` variable in `_setFontScale` function properly to `_model.once` callback function in captionsrenderer.js

**Comment by ArmsAsuncion** [comment]
Actually, it's not just fontSize that's not working since Beta 2, but even backgroundOpacity.

Also, since we're in the topic of subtitles, since 7.9.3, captions styling doesn't work in Safari, it stays the default style, except for backgroundOpacity. (Which worked until beta 2)

**Comment by dannyfinks** [comment]
Hi @charlesduco I can reproduce the issue and we will resolve this issue before releasing 7.10 to the production channel. Thank you.

**Comment by charlesduco** [comment]
I can confirm this is fixed in v7.10.0. Thanks.
