### ISSUE TITLE
Minimist package is missing from package.json

### ISSUE THREAD

**Issue by mohessaid** [jwplayer/jwplayer#1902]
### Expected Behavior
When I build or serve using grunt or webpack I am supposed to see this
```bash
TOTAL: 213 SUCCESS


Done.
```
at the end. And  two new folders under the player's folder `bin-release` and `bin-debug`.

### Actual Behavior
This is what I am getting: 
```bash
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'minimist'
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
```
This won't generate any build folder and you won't get any player.

### Steps to reproduce

1. Open a c9.io workspace with Nodejs preinstalled in it. 
2. Follow the building guide of jwplayer.

### How I fixed it

I simply added `minimist` package to the list of dependencies in `package.json`.
`"minimist" : "1.2.0"`

**Comment by johnBartos** [comment]
What version of node?

**Comment by robwalch** [comment]
Sounds like a child dependency of another npm module that is only not installed on your OS or version of npm. It's not an issue with our package.

**Comment by mohessaid** [comment]
@johnBartos  :  `node : v4.7.3` and `npm : 2.15.11` and `grunt-cli v1.2.0     grunt v1.0.1`
@robwalch  : I tried it in another workspace with the last version of node and npm and it worked just fine.
