### ISSUE TITLE
Passing XML to playAd

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#1903]
I would like to play the ad by using "playAd" but without making an additional ajax call to the ad server, which is important, because we'd like to play it in a live stream at a particular time. With high traffic, this could bring down the ad servers due to multiple concurrent requests.
Is there a way to pass object with XML response? Or make call earlier and trigger ad in given time?

**Comment by robwalch** [comment]
@artur-michalak which ad plugin are you using?

**Comment by robwalch** [comment]
I can confirm this is not supported with the VAST plugin.

**Comment by artur-michalak** [comment]
Vast. Any ideas how to make this? I imagine, this will be a case for others too, because more and more CDNs support midrolls in live streaming.

BTW. Is vast plugin proprietary code?

**Comment by robwalch** [comment]
Yes it a private repo. There isn't a workaround for `playAd` as it's implemented now.

You're best bet is to send a feature request to support. I'll also pass the ask on to our Ads team.
