### ISSUE TITLE
Improve consistency between autostart and play

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#1909]
### Expected Behavior
Player Mobile UI will look the same whatever autostart: true or .play() is used.

### Actual Behavior
When using autostart: true on ios safari or android chrome player displays "muted autostart" icon. Unfortunately when we set autostart:false and then on('ready', player.play) it doesn't. 
https://github.com/jwplayer/jwplayer/blob/2bbdb0f09ad42927575b3bc1dbd7f7e513dcb781/src/js/view/view.js#L676

### Steps to reproduce

1. Embed player
```javascript
var player = jwplayer("player1").setup({
        "playlist": [{
            "file": "http://content.jwplatform.com/videos/bkaovAYt-640.mp4",
        }],
        "key": "I71qyJ0z98WOuWtf1coTYg3jFkb4GoyGimmxgQ==",
        "autostart": false,
        "mute": true,
        width: 320,
        height: 180
    });

    player.on('ready', function () {
        player.play();
    });
```
2. Run and check with autostart: true|false

I'm attaching screenshots:

1. autostart: true
![image](https://cloud.githubusercontent.com/assets/2443904/23951294/f8b9bf40-098d-11e7-802d-34752ef2d8da.png)

2. autostart: false, on('ready', player.play);
![image](https://cloud.githubusercontent.com/assets/2443904/23951335/15eaf390-098e-11e7-8269-9076932f8684.png)

### Environment

- *hardware | iPhone*
- *operating system | ios10 *
- *browser | Safari*
- *JW Player version | JW 7.9.3*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
@artur-michalak The first player is actually using autostart - that's what the muted autostart UI looks like. The second player is not technically autostarting, so you get the normal UI.

**Comment by egreaves** [comment]
@artur-michalak the key difference is that by setting `"mute": true`, you're also muting desktop players. The more common use case for autostart is for the player to not be muted on desktop. The reason the player is muted on mobile devices is to circumvent the need for user interaction in order to start playbackWhen `"autostart": true`.

**Comment by daviderik** [comment]
@egreaves a use case we have is when we want to silently start the video on mobile, through the API, when it is scrolled in view. This is when a consistent look for "activate sound" would be useful. Any pointers how we should approach this?

**Comment by johnBartos** [comment]
@daviderik In 7.10 (coming soon) we'll have a new config option: `autostart: viewable`, which will start the player when at least 50% of the player is viewable & the player is in the active tab. To autostart on mobile, your player needs to be muted.

What do you mean by "active sound"?

**Comment by daviderik** [comment]
@johnBartos I see. By that I mean the button shown by the "muted autostart UI". Since for the user, there is no difference between the video autostarting silently through "autostart:true" or us starting the player silently through the API. 

Will `autostart:viewable` and muted result in the "muted autostart UI" on a mobile?
