### ISSUE TITLE
Mismatch anonymous define() module error thrown post-optimization with r.js

### ISSUE THREAD

**Issue by mdublin** [jwplayer/jwplayer#1919]
Currently building a simple VueJS-based SPA that uses JWPlayer (self-hosting the JS source code that I downloaded for the JW Player 7 - production 7.9.3 from my account) and the AMD API via requirejs.  

Everything works fine using requirejs, JWPlayer is integrated as a module in my main.js file with no issues whatsoever, app loads with JWPlayers that are created in various scenarios programmatically via the JWPlayer Javascript API, etc. 

But when I attempted to optimize the project using r.js, in order to concatenate all of my JS files together into one JS file, I got the following error message upon loading my app Chrome 55.0.2883.95 (64-bit) and Firefox 52.0.1 (64-bit): 

```Error: Mismatched anonymous define() module: function (){return o}```

This error message initially seems to emanate from the main-build.js file which was created from running the requirejs optimizer. 

But the line the error message points to specifically is just my requirejs config module, where all dependencies/modules are defined, etc. That's not too helpful as the config.js module works fine pre-optimization. The config.js file looks like this: 

```
requirejs.config({
    baseUrl: './assets/js',
    paths: {
         'jquery': 'vendors/jquery-3.1.1.min',
        'vue': 'vendors/vue.min',
        'jwplayer': 'vendors/jwplayer-7.9.3/jwplayer',
        'videowallplayer': 'vendors/videowallplayer'
    }
});

requirejs(['app/main']);
```

In order to use JWPlayer in the main.js module, I'm including it like this: 

```
define(['jquery', 'jwpbackground', 'jwplayer', 'vue'], function($, jwb, jwplayer, Vue) {
    ....
});
```

The Requirejs docs list [four possible causes](http://requirejs.org/docs/errors.html) for this apparently common error, although none of that info was immediately elucidating. 

However, a search for an anonymous define() module did finally lead me to the following anonymous define() module in line 7494 of the jwplayer.js file in the jwplayer-7.9.3 package: 

```...
    return "function" == typeof i.define && i.define.amd && i.define([], function() {
     ...
```

Clearly, there's an anonymous define module at the end of this line. When I entered an arbitrary module ID, thus making it no longer anonymous, like so: 

```...
    return "function" == typeof i.define && i.define.amd && i.define('jwplayer', [], function() {
     ...
```

I re-ran r.js optimizer to create a new main-build.js file and now everything works perfectly fine, app loads as expected and no require.js errors. 

Prior to adding the module ID to the aforementione line in jwplayer.js, the code from the jwplayer.js file that was dumped into main-build.js did not include the module ID "jwplayer" that in that was provided in the config.js file in that line, unlike with similar AMD-handler sections of the jquery and vuejs library source code, which after optimization included the module ID provided in the config.js file. 

But this can't possibly be the fix, and I'm sure I'm missing something obvious here in terms on how I've incorrectly implemented JWPlayer with requirejs. Any suggestions would be greatly appreciated.

**Comment by johnBartos** [comment]
With webpack we name all of our define modules with the option `umdNamedDefine: true`. If you run another optimizer on top it has to preserve some kind of name; otherwise, you get that error.

**Comment by mdublin** [comment]
Hi John, thanks for responding! Going to set about redoing this implementation with Webpack :)

**Comment by skovmand** [comment]
Hi. Thanks for this fix.

We have exactly the same problem using requirejs and newer versions of JWPlayer (currently on 7.12.6), and the same fix works. However, we don't like to have to patch your player releases manually.

We have a very big application which depends on JWPlayer and RequireJS, so we cannot migrate to webpack without a big time investment.

If this fix is that simple, can we make you include it in the JWPlayer bundle?

Thanks.
