### ISSUE TITLE
iOS Safari, no spinner when buffering.

### ISSUE THREAD

**Issue by kennysmoothx** [jwplayer/jwplayer#1926]
![Safari and jwplayer](http://i.imgur.com/ontT0fM.png?2)

> The player is actually buffering and loading, yet no spinner just a play button

### Expected Behavior

When you click play on a video, the spinner should show up spinning to indicate to the user that the player is loading and buffering the video.

### Actual Behavior

On Safari for iOS, when you click play, there is no spinner.

Instead the play button just stays there, when in reality it is buffering and loading.

The user has no indication that the player is buffering so they believe the player is not loading.

### Steps to reproduce

1. Load jwplayer
2. Press play on Safari iOS

### Environment

Latest iOS 10, Latest iOS Safari
JWPLAYER 7.9 & 7.10

**Comment by johnBartos** [comment]
@kennysmoothx Hey, sorry for the long wait and thanks for the report. We've been aware of this issue but haven't heard many complaints; however, it sounds like more people want it now. I'll try and get this prioritized for a future release.

**Comment by manuelprojects** [comment]
Same problem here, any ideas for a temporary workaround?
The player seems not working in iOS devices...
Thx

**Comment by sepiette** [comment]
Same problem on iOS Safari (latest iOS version 10.3.2). Takes about 4-5 seconds for play button to change on both audio and video player. Is there any fix to this bug, or a decent workaround?

**Comment by agronom81** [comment]
Hi!
I use next hack
`$('body').on('touchend', '.player-btn-play', function() {
		$('#loader').show();
	});`

**Comment by kennysmoothx** [comment]
This is still a huge issue,

This is even persisting on v8 of JWPlayer,

Whats the deal? Why has this not been addressed in over 6+ months?

**Comment by johnBartos** [comment]
@kennysmoothx Fixed as of https://github.com/jwplayer/jwplayer/pull/2347. It was fixed as part of a ticket completely reworking how we handle play attempts. This wasn't addressed for 6+ months because it was purely cosmetic and did not affect playback on iOS. You should see the change in the next release (tentatively next Wednesday).
