### ISSUE TITLE
JWPlayer manager memory on iPhone 5s

### ISSUE THREAD

**Issue by kilirushi** [jwplayer/jwplayer#1934]
Dear Team,
I have problem with memory application when loading video quality high on iPhone 5s. Please check help to me.
### Expected Behavior
Out of memory when loading video...
*Describe expected behavior*
You can watch video below to learn more
### Actual Behavior
[JWPlayer.zip](https://github.com/jwplayer/jwplayer/files/870008/JWPlayer.zip)

*Describe actual behavior*

### Steps to reproduce

1. Loading video
2.
3.

### Environment

- *hardware | device* : iPhone 5S
- *operating system | version*: iOS 9.3
- *browser | version*
- *JW Player version | url*: jwplayer-ios-sdk-2.7.1+24

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
@kilirushi ios9 is limited to 10mb per page. If your video is too large we cannot do anything about it.
