### ISSUE TITLE
Add additional stylelint rules for linting LESS

### ISSUE THREAD

**Issue by jw-kaurand** [jwplayer/jwplayer#1936]
Additional test stylelint tests should be added to the linting process to improve the formatting of the LESS files and improve their ability to be debugged.

The following linting test(s) should be added:
"no-descending-specificity": true
Warnings:
"selector-max-compound-selectors": 3
"selector-max-specificity": "0,3,0"

The following plugin(s) should be added:
stylelint-order: https://www.npmjs.com/package/stylelint-order

**Comment by robwalch** [comment]
@radium-v please edit this tech-debt ticket if you agree that we need to improve stylint rules or close this ticket.
