### ISSUE TITLE
jwplayer 7.10.1 stops Javascript setInteval

### ISSUE THREAD

**Issue by narfffy** [jwplayer/jwplayer#1941]
### Expected Behavior

when Javascript setInterval is set prior to calling jwplayer().setup, it should continue to fire. 
This works correctly with jwplayer 7.9.3

### Actual Behavior

setInteval stops firing when jwplayer().setup is used. This may also affect setTimeout.

### Steps to reproduce

1. Use setInterval to send text to the console.
2. Setup jwplayer with a video
3. setInterval will stop firing.

### Environment

- PC
- Windows 10
- Chrome 56.0.2924.87 and Firefox 52.0.1
- jwplayer 7.10.1

Example code used is below. Watch the browser console. When you click on setup, it will stop logging "test" to the console. 

```
<html><head>
<script src="https://content.jwplatform.com/libraries/uvNBkg49.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
$(function(){
        setInterval(function(){ console.log('test'); }, 1000);

        $('#setup').on('click', function(){
                var player = jwplayer("player").setup({
                        "file": "//content.jwplatform.com/videos/C4lp6Dtd-640.mp4"
                });
        });

});
</script>
</head><body>
<div id="player"></div>
<div id="setup">Setup</div>
</body></html>

```

**Comment by johnBartos** [comment]
Thanks for the report, this is fixed in 7.10.3
