### ISSUE TITLE
[HLS Streaming  could not be Adaptived in Safari<-v 10.0.3 (12602.4.8)> ]

### ISSUE THREAD

**Issue by treesea2014** [jwplayer/jwplayer#1946]
### Expected Behavior
**It should have a HD button in the controlbar**

### Actual Behavior

*There isn't a HD button in the controlbar*
*But it's normal in Chrome & Firefox*

### Steps to reproduce

1.Here's codes copied from [Adaptive Streaming](https://developer.jwplayer.com/jw-player/demos/toolbox/adaptive-streaming/)
```
jwplayer("player").setup({
		file: '//content.jwplatform.com/manifests/vM7nH0Kl.m3u8',
		tracks: [{
			kind: "thumbnails", file: '//content.jwplatform.com/strips/vM7nH0Kl-120.vtt'
		}],
		autostart: true,
		width: 860,
		height: 484
	});

```
2. Visit the [demo]((https://developer.jwplayer.com/jw-player/demos/toolbox/adaptive-streaming/) with different browers like Safari and Chrome
3.

### Environment

- *JW Player version 7.10.0

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by treesea2014** [comment]
Please excuse me for my poor English~

**Comment by johnBartos** [comment]
@treesea2014 In Safari we use the browser's native HLS playback, which does not allow you to select a quality level. Therefore we hide the menu

**Comment by treesea2014** [comment]
Many thanks !

**1.  In Safari :**
If I want the 'HD' shown in Safari, it works like below. and It doesn't work In Chrome.
```
jwplayer("player").setup({
	autostart: true,
	width: 860,
	height: 484,
	playlist:[{
			sources:[
				{
					file:'http://gxb-video.oss-cn-beijing.aliyuncs.com/57801edc-2940-11e5-9bb9-525400e95588.m3u8',
					label:'360p',
					type:'application/vnd.apple.mpegurl'
				},
				{
					file:'http://gxb-video.oss-cn-beijing.aliyuncs.com/57801edc-2940-11e5-9bb9-525400e95588.m3u8',
					label:'720p',
					type:'application/vnd.apple.mpegurl'
				}
			]
		}
	]
});
```
**2.In Chorme**
The 'HD' button show In Chorme if I configure a mainfest file. and it doesn't work In Safari because "In Safari we use the browser's native HLS playback, which does not allow you to select a quality level."  
```
jwplayer("player").setup({
	autostart: true,
	width: 860,
	height: 484,
	playlist:[{
			sources:[
				{
					file:'https://wowzaec2demo.streamlock.net/vod-multitrack/_definst_/smil:ElephantsDream/ElephantsDream.smil/playlist.m3u8',
					type:'application/vnd.apple.mpegurl'
				},
			]
		}
	]
});
```
*playlist.m3u8*
```
#EXT-X-STREAM-INF:BANDWIDTH=2962000,NAME="Main",CODECS="avc1.66.30",RESOLUTION=1280x720,AUDIO="aac",SUBTITLES="subs"
chunklist_w214510474_b2962000_vo_slen_t64TWFpbg==_cfRWxlcGhhbnRzRHJlYW0vRWxlcGhhbnRzRHJlYW0udHRtbA==.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1427000,NAME="Main",CODECS="avc1.66.30",RESOLUTION=768x432,AUDIO="aac",SUBTITLES="subs"
chunklist_w214510474_b1427000_vo_slen_t64TWFpbg==_cfRWxlcGhhbnRzRHJlYW0vRWxlcGhhbnRzRHJlYW0udHRtbA==.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=688000,NAME="Main",CODECS="avc1.66.30",RESOLUTION=448x252,AUDIO="aac",SUBTITLES="subs"
chunklist_w214510474_b688000_vo_slen_t64TWFpbg==_cfRWxlcGhhbnRzRHJlYW0vRWxlcGhhbnRzRHJlYW0udHRtbA==.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=331000,NAME="Main",CODECS="avc1.66.30",RESOLUTION=284x160,AUDIO="aac",SUBTITLES="subs"
chunklist_w214510474_b331000_vo_slen_t64TWFpbg==_cfRWxlcGhhbnRzRHJlYW0vRWxlcGhhbnRzRHJlYW0udHRtbA==.m3u8`
```

**Is there a Unified configuration in Function [setup] If I need the [HD] button In all browers?**

**Comment by fdambrosio** [comment]
there's news about this?
