### ISSUE TITLE
IE issue - 'Promise is undefined'

### ISSUE THREAD

**Issue by Bruno-Tvtrip** [jwplayer/jwplayer#1969]
### Actual Behavior

On IE 11/Windows 7, sometimes since the new version, I have this error in my console "'Promise' is undefined" File: jwplayer.js, line: 2, Column: 11787. The player doesn't work and the message "Setup Timeout Error: Setup took longer than 30 seconds to complete" is displayed.

### Steps to reproduce

1. On IE 11, Windows 7 (maybe on other Windows also)
2. Clear your cache with The Developer Tools and active the option "Always refresh from server"
3. Load a page with JWPlayer 7.10.4

### Environment

- Desktop
- Windows 7
- IE 11
- JWP 7.10.4

**Comment by robwalch** [comment]
If you're using a development version this will address it:

https://github.com/jwplayer/jwplayer/commit/95359aa0ac62cd02fb1c1925e1358b95a493cd11

I'm not sure where the promise dependency would be in 7.10.x. Can you please provide a sample setup? We need to know what plugins and type of media you are trying to load.

**Comment by Bruno-Tvtrip** [comment]
Thanks. I will try this fix Tuesday. Do you plan a 7.10.5 version soon?

The setup is simple, just HTML5 with a array of mp4 for SD/HD and no plugin.

Do you success to reproduce it ? It's not always, maybe that depend on the network.

**Comment by robwalch** [comment]
7.10.5 has been released. Can you reproduce it in 7.10.5? I have not. I have only seen the issue development and it should be fixed with #1982
