### ISSUE TITLE
Cannot read property 'label' of undefined & Invalid license key

### ISSUE THREAD

**Issue by Stosiu** [jwplayer/jwplayer#1970]
### Expected Behaviour

*Player should be able to load/setup without errors.*

### Actual Behaviour

We have two errors we cannot fix:
- Error in "buffer" event handler: TypeError: Cannot read property 'label' of undefined (it happens 100% of times on first player load)
- Error setting up player: Invalid license key (it has about 0.05% chance to happen and break the player on startup. We are using your cloud hosting, so maybe there is a problem with your licence algorithm?)

After one of the latest releases we also started receiving this setup error:
 - Setup Timeout Error: Setup took longer than 30 seconds to complete. (could you provide us instructions what should we do to solve it? It occurs in 0.1%)

### Steps to reproduce

1. Visit https://www.blitztv.com/
2. Open console
3. Click on play button

### Environment

- *Generally all types of devices, 90% of sessions comes from mobile devices (Mobile Safari, Chrome, Firefox), but we received error reports from desktop users as well.*
- *JW Player version: latest, cloud-hosted, 7.10.4*

**Comment by johnBartos** [comment]
@Stosiu I took a quick look but I couldn't find anything. Can you link a specific video which reproduces your error?
