### ISSUE TITLE
is there any to add an event that triggers when the player goes inactive?

### ISSUE THREAD

**Issue by mwleinad** [jwplayer/jwplayer#1981]
### Expected Behavior

*we are working in a very customized version of the jwplayer, but without touching the base code,
however some of the bugs we encounter are caused by not being able to trigger something when the player goes inactive. Also is a good idea to be able to modify the inactivity time or disable altogether (and use the setcontrols to true or false depending on the case manually*

### Actual Behavior

*There's no way to detect player went inactive*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
See #1498

**Comment by mwleinad** [comment]
@robwalch what about changing the inactive time or turning it off altogether?
thanks!

**Comment by robwalch** [comment]
Not an option. You can override the CSS that hides elements if you want to disable hiding when inactive. You can also set 'controls' to false and provide your own UI on the player.
