### ISSUE TITLE
HLS: Automatic quality never selects higher quality levels

### ISSUE THREAD

**Issue by roquez** [jwplayer/jwplayer#1984]
### Expected Behavior
When a stream is played with auto quality, the player selects the highest possible quality given the bandwidth at any given moment.

### Actual Behavior
I have a stream with the following quality levels: 
[108p, 162p, 252p, 432p, 558p, 594p, 612p, 648p, 720p, 1080p]

My internet connection speed (100 Mbps) is definitely fast enough to play 1080p.

When using hls.js provider, the player selects maximum quality of 594p and ignores higher levels.
When using flash provider, the player selects maximum quality of 720p and ignores 1080p.

On [stream tester](https://developer.jwplayer.com/tools/stream-tester/) it acts a bit differently: both hls.js and flash provider selects maximum quality of 432p.

### Steps to reproduce

1. Play this example stream: https://content.uplynk.com/ext/d874124ecca24c88a3c9575e78686acf/10058310.m3u8
2. Set quality to auto.

### Environment

- Windows 10
- Chrome 56
- JW Player 7.10.5

**Comment by johnBartos** [comment]
@roquez We cap our upswitching to the size of your video player, rounded up. For example, if your player is not above 720p, it will not upswitch to 1080p. https://github.com/video-dev/hls.js/blob/master/doc/API.md#capleveltoplayersize

**Comment by roquez** [comment]
@johnBartos I would never have come across this. Thanks!

**Comment by meeysoft** [comment]
this is the best example of hls quality levels selector
please test this in firefox
`<script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
<video width="800" controls></video>
<ul class="levels"></ul>
<script>
hls = new Hls();
Source = "https://content.uplynk.com/ext/d874124ecca24c88a3c9575e78686acf/10058310.m3u8";
hls.loadSource(Source);
video = document.querySelector("video");
hls.attachMedia(video);
hls.on(Hls.Events.MANIFEST_PARSED,function() {
for (i=0; i < hls.levels.length; i++) {
width = hls.levels[i].width;
height = hls.levels[i].height;
bitrate = Math.floor(hls.levels[i].bitrate / 1024);
log = "new hls level attached. Track: Resolution: "+width+"x"+height+", bitrate: "+bitrate+"kbps";
console.log(log);
levels = document.querySelector(".levels");
level = document.createElement("li");
level.classList.add("level");
level.setAttribute("level",i);
level.innerHTML = height+"p";
if (height > 2000) level.innerHTML += "<span style='color:red; font-size: 9px;'>4K</span>"
else if (height > 700) level.innerHTML += "<span style='color:red; font-size: 9px;'>HD</span>";
levels.appendChild(level);
newLevel(level,i);
};
function newLevel(levelQuery,levelNum) {
levelQuery.onclick = function(){hls.currentLevel = levelNum;};
};
autoLevel = document.createElement("li");
autoLevel.innerHTML = "auto";
autoLevel.classList.add("level");
autoLevel.setAttribute("level","auto");
autoLevel.onclick = function(){hls.currentLevel = -1;};
levels.appendChild(autoLevel);
Levels = document.querySelector(".levels");
levels = document.querySelectorAll(".level");
for (i=0;i < levels.length;i++) {
beforeElement = Levels.childNodes[0];
afterElement = Levels.childNodes[i];
Levels.insertBefore(afterElement,beforeElement);
};
});
</script>`
