### ISSUE TITLE
Keyboard shortcuts conflicts with elements on top of the player

### ISSUE THREAD

**Issue by mwleinad** [jwplayer/jwplayer#1988]
### Expected Behavior

We are working on a heavy modified version of the jw player
When we add an input text on top of the jw-player I expect to type anything correctly without pausing/playing or going full screen/

1. Is there a way to disable the shortcuts?
2. even better, is there a way to change the shortcut keys?

### Actual Behavior

When I add an input on top of the player and press the space bar, the player pauses/plays

### Steps to reproduce

1. add an input key on top of the player container
2. type something in the input

**Comment by mwleinad** [comment]
So, I found a solution. I was overthinking this and just a few hours away from the keyboard gave me the solution. I just needed to stop the bubbling generated by my input on the keydown event. 

` $interactiveBar.find(".comment-input").keydown(function(e){
        e.stopPropagation();`

**Comment by johnBartos** [comment]
@mwleinad Great! Closing this out
