### ISSUE TITLE
It losts a package named adaptive when I build a flash with Gruntfile.js.

### ISSUE THREAD

**Issue by treesea2014** [jwplayer/jwplayer#1991]
@robwalch
### Expected Behavior

*I've purchased a JWPlayer ,and the jwplayer.flash.swf contains a package [adaptive]
![image](https://cloud.githubusercontent.com/assets/13939353/25088178/e4c2cb7a-23a6-11e7-894e-0b570edf801b.png)
*

### Actual Behavior

*I download source from github[tag7.9.0], and I get a swf after [grunt build-flash
],the swf doesn't contain [adaptive],
![image](https://cloud.githubusercontent.com/assets/13939353/25088258/754a0ec4-23a7-11e7-8850-2c505e8755da.png)
*

###How can I get Corresponding source code ? Or how to build?  @robwalch ,I'm very  new ~ many thanks!

**Comment by robwalch** [comment]
You're looking at compiled classes from the commercial product. You can download updates from your dashboard. Commercial source is private and not part of this github project.
