### ISSUE TITLE
Event: 'time' - (live) negative duration.

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#2014]
### Expected Behavior
Live stream, duration is Infinity
```js
{position: 94.029748, duration: Infinity, type: "time", viewable: 1}
```

### Actual Behavior
```js
{position: 94.029748, duration: -32.033, type: "time", viewable: 1}
```
### Steps to reproduce

1.  Stream: https://wowza.jwplayer.com/live/jelly.stream/playlist.m3u8
2.
```
jwplayer().onTime(function(e){console.log(e)})

```
3. After 90 seconds negative duration.

### Environment

- *operating system | OSX 10.12.4
- *browser | Chrome 57.0.2987.133 
- *JW Player version | 7.10.7

----------------------------------------------------------------------------------------

**Comment by johnBartos** [comment]
@mtoczko Duration changes to negative when in DVR mode, which is a live stream whose duration exceeds the `minDvrWindow` (default: 120). This stream increases in duration over time and eventually passes the threshold. When it does, we return the negation of the current level's duration:

````
````

**Comment by johnBartos** [comment]
I made a fix for this just now, it'll be arriving in 7.11. It's not in the current beta

**Comment by mtoczko** [comment]
Thanks
