### ISSUE TITLE
Issues with HLS live stream on Chrome and MacOS

### ISSUE THREAD

**Issue by konradpietrzkiewicz** [jwplayer/jwplayer#2023]
### Expected Behavior

- live video play normally

### Actual Behavior

- video is paused after 1st chunk (10s)

### Steps to reproduce

1.  go to https://developer.jwplayer.com/tools/stream-tester/
2.  put  https://aftonbladetg-lh.akamaihd.net/i/20130121x1245_01@3943/master.m3u8
3. video play through 1st chunk (10s) and pausing

We don't see this issue on older jwplayer version 7.9.3. And also when we change the chunk duration on live stream to 6s:
https://aftonbladetg-lh.akamaihd.net/i/20130121x1245_01@3943/master.m3u8?set-akamai-hls-revision=4&set-segment-duration=quality

### Environment

-  MacBook Pro
-  Mac OSX sierra 10.12.4 (16E195)
-  Chrome 57.0.2987.133 (Official Build) (64-bit)
- 7.10.5, 7.10.7, 7.11.0-beta-1.175

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
I'm seeing this work correctly in our current RC build; I'll ping you here when its released so you can reverify the bug

**Comment by konradpietrzkiewicz** [comment]
I see on current 7.11 version the issue is still there

**Comment by jgh-** [comment]
I'm trying to debug similar issues we're seeing, how can I view HLS with a custom build? It seems that using grunt doesn't really generate a build that works with my key....

**Comment by johnBartos** [comment]
@konradpietrzkiewicz I can repro it in the test page but not in a standalone player, can you verify it somewhere else?

@jgh- You can't debug HLS playback with JWPlayer - it's not open source. However, you can certainly debug with the [Hlsjs demo player](http://video-dev.github.io/hls.js/demo/) (we use Hlsjs internally). I also answer streaming issues on that repo.

**Comment by johnBartos** [comment]
@konradpietrzkiewicz The stream is working for me in the 7.12 beta. Closing this out
