### ISSUE TITLE
No playback on big play button on IE11

### ISSUE THREAD

**Issue by Bruno-Tvtrip** [jwplayer/jwplayer#2025]
### Expected Behavior

Launch the playback when clicking on the first big play button on IE11. Actually, users need to click around the play button (the arrow) or on the video for the first play.

### Steps to reproduce

1. Setup a simple page with a classic player with .mp4
2. Click on the arrow on IE11
3. No playback!

### Environment

- Desktop
- Windows 7
- IE11
- JWPlayer 7.10.6

**Comment by johnBartos** [comment]
We're having trouble reproducing this, can you paste your config? Also, are you using custom CSS?

**Comment by Bruno-Tvtrip** [comment]
Hello,

I try this morning and I don't reproduce it in the 7.11.beta, I will wait for the 7.11 final version.

Thank you

**Comment by robwalch** [comment]
@Bruno-Tvtrip you might try 7.10.7 in the mean time.
