### ISSUE TITLE
Add event 'complete' after ended of stream DVR.

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#2034]
### Expected Behavior
1. Event 'complete'.
2. Add button 'Replay' like in VOD and start stream from beginning.
### Actual Behavior
The player returns only an error:
```
Hlsjs shutdown The live stream is either down or has ended
```

**Comment by johnBartos** [comment]
@mtoczko The ticket I did for this wanted an error to be thrown rather than event, I'll bring this up. Thanks

**Comment by robwalch** [comment]
@mtoczko we only complete HLS streams with and #EXT-X-ENDLIST tag at the end of the manifest. If the manifest never comes back with one, we cannot assume that the stream is complete. If the manifest becomes empty of stale that is an error, and the error message provided is the best feedback we can provide.

You can treat it as complete by replacing the jw-state-error class on the player element with jw-state-complete.

**Comment by mtoczko** [comment]
@robwalch for my complete is when positon == duration. But O.K.
But the only option to catch this error is: 
```
onError(function (e) {
            if (e.message === 'The live stream is either down or has ended') {
            }
```
It is not elegant and practical. Missing error code... Or adding a new event for DVR end.
