### ISSUE TITLE
Auto-pause video when not in view

### ISSUE THREAD

**Issue by alinchican** [jwplayer/jwplayer#2036]
# Feature request

Auto-pausing videos is a feature found on websites like Facebook which display a lot of videos in a feed.

### Steps to reproduce

1. Player with `autostart: viewable` starts playing
2. Same player with `autopause: hidden` pauses when outside view

### Environment

Mobile/desktop

----------------------------------------------------------------------------------------

Thank you!

**Comment by mtoczko** [comment]
Try this:
```js
jwplayer('video').setup({
...
events: {
                onTime: function(e){
                    if(!e.viewable){
                        this.pause();
                    }
                }
}
...
)}
```

**Comment by johnBartos** [comment]
@alinchican On mobile this feature is implemented; on desktop it remains playing.

**Comment by MrWiLofDoom** [comment]
Is there a way to disable this feature?
