### ISSUE TITLE
Feature Request: Please add 'togglebuttons = true/false' option.

### ISSUE THREAD

**Issue by 4getit** [jwplayer/jwplayer#2046]
Hello,

First of all, I think 'HD' for the Quality toggle button is poorly chosen. If I have 2 video sources 360p and 480p, 'HD' doesn't make a lot of sense. Same as when I have 720p and 1080p, I think they're both considered HD so toggling the button on and off seems a bit weird.

I would rather always show the menu where the user sees the labels and pick what they want. (and if there's nothing to pick, show what's playing)

Same as for the Captions toggle. 
If I have only (let's say) Polish available, I prefer showing my users the Menu saying 'Off' and 'Polish'. That way it's more clear what caption language is showing and that English is not available. 

If there would be a togglebuttons = true/false option, the user would still be able to see the labels if there are 2 video source or 1 caption track. 

I would even consider always showing the quality button. Even if there's only 1 video source available. That way, the user knows he's watching 360p and there's nothing else to choose from.

### Expected Behavior

Allow be able to show labels to users. Even if there are only 2 (or 1) video sources or 1 caption track.
 
### Actual Behavior

When there are only 2 video sources no quality labels can be shows. 
When there is 1 caption track, no caption labels can be shown.

### Steps to reproduce

1. Load a 360p and a 480p source. When toggling the 'HD' toggle becomes active for whatever was set as the first label. 
2. Load 1 caption track. The user cannot see what caption language is displayed.

- JWPlayer 7.10.7 self hosted

**Comment by robwalch** [comment]
Thanks for the suggestion. We will consider it when updating the look and functionality of the player in the future.

For now you can change the content from HD to something else with CSS.
