### ISSUE TITLE
[7.11.0] HLS playback skips first ts segment

### ISSUE THREAD

**Issue by astierler** [jwplayer/jwplayer#2062]
After upgrading to 7.11.0, my HLS videos when loading (which seem a bit slower than 7.10.x) automatically jump to/start at `0:06` in the video (our HLS segment time is set to 6 seconds)

Confirmed using backup CDN (segments set to `0:10` duration) that the player hangs for the length of the first ts segment, and then begins playing the second.

Network activity shows that the first segment is requested and streamed successfully.

- JW Player 7.11.0 (Chrome 58.0.3029.110 on Linux)
- HLSJS provider (pulling from http://ssl.p.jwpcdn.com/player/v/7.11.0/provider.hlsjs.js )

**Comment by dannyfinks** [comment]
@astierler would you be able to provide the stream or a test page for us to investigate?

**Comment by astierler** [comment]
Further testing (between different pages) reveals that this problem only shows up when `autostart` is set to `true`. If set to false and I render the player then click play, the video segments start as expected

Happens both if I pass the m3u8 directly to `file` or if it goes into a playlist.

@dannyfinks sure I can provide the m3u8 at least, the page is internal but I can bundle it up and upload if needed, but hopefully the autostart hint allows you to reproduce?

https://vod.wwe.com/v1/2017/,1080,720,540,432,360,288,/talksmackcomp005b.m3u8

**Comment by astierler** [comment]
Also here are my default parameters going into the player.

    playerParams: {
      file: src,
      width: 640,
      height: 360,
      hlshtml: true,
      primary: 'html5',
      autostart: true,
      skin: {
        name: "stormtrooper"
      }
    }

**Comment by dannyfinks** [comment]
Thanks @astierler I can reproduce this on my end as well with one of our internal wwe testing streams. I will prioritize having this investigated.

**Comment by dannyfinks** [comment]
@astierler its not ideal, but I observed that the issue does not occur with `preload: 'none'` as a temporary workaround until we look at this during the week.

**Comment by astierler** [comment]
@dannyfinks I can confirm this worked. I've gone ahead and done this on my end (this is for internal use currently, so no preloading is fine.)

Thanks for continuing to look into this and the quick turnaround/suggestion on the temporary solution :1st_place_medal:

**Comment by johnBartos** [comment]
@astierler I believe this fixes the issue: https://github.com/jwplayer/hls.js/pull/94

**Comment by astierler** [comment]
@johnBartos @dannyfinks yep, I can confirm that fixed it (in 7.11.2)! Thanks, closing this issue
