### ISSUE TITLE
Playback events are not triggered after loading a new playlist

### ISSUE THREAD

**Issue by farneman** [jwplayer/jwplayer#2064]
### Expected Behavior

After calling `.load` to load a new playlist or file any previously attached play/pause event listeners should continue to be called.

### Actual Behavior

Once `.load` is called any existing play/pause listeners are no longer triggered.

### Steps to reproduce

1. Load the JWPlayer with a file or playlist.
2. Attach an "on play" event listener to the player.
3. Play the current item and note that the "on play" listener is called.
4. Call `.load` with a new playlist.
5. Play the new item and note that the original "on play" listener is *not* called.

### Environment

- Multiple browsers and operating systems
- At least versions of 7.9.3 through 7.11.0

**Comment by johnBartos** [comment]
Hey @farneman, thanks for the report. We'll look into it

**Comment by robwalch** [comment]
@farneman, can you include a sample of your player's setup config or defaults? That would help us isolate if the event listeners are being detached in this project, or in a player plugin.

Thanks!

**Comment by farneman** [comment]
@robwalch Here's what our setup currently looks like:
```js
jwplayer('some_elem_id').setup({
  aspectratio: "16:9",
  autostart: false,
  events: {
    onBuffer: function () {},
    onComplete: function () {},
    onError: function () {}, 
    onPause: function () {},
    onPlay: function () {},
    onPlaylist: function () {},
    onPlaylistItem: function () {},
    onReady: function () {},
    onSeek: function () {},
    onSetupError: function () {},
    onTime: function () {}
  },
  flashplayer: "/path/to/jwplayer.flash.swf",
  playlist: "http://url.to/playlist.xml",
  primary: "html5",
  skin: "six",
  width: "100%"
});
```
I realize the event callback configuration we're using is a deprecated API, this code was pulled out of an internal wrapper library. The callbacks themselves are pass throughs for consumers to use and I'm seeing the issue occur when doing nothing other than console logging from some of the callbacks. 

I have also tried manually adding event listeners via the console but those don't get called after new playlist load either.

Let me know if there's more info that I can provide.

**Comment by robwalch** [comment]
I'm unable to duplicate this in v7.11.3 using `jwplayer().on('buffer play playlist playlistItem seek', e => console.log(e));` to add event listeners, and `jwplayer().load( _media_item_or_playlist_ )`.

**Comment by farneman** [comment]
@robwalch Thanks for looking at it. I'll take another stab at it and let you know if I can provide any more info. Do you think making use of the callbacks instead of event listeners could be the problem?

**Comment by robwalch** [comment]
The player essentially calls each property in `events` that is a method:

https://github.com/jwplayer/jwplayer/blob/7bfb5ebb65f484adfa07570c079b1470d37a0cde/src/js/api/api.js#L115

They're just aliases for `on(eventName)`

https://github.com/jwplayer/jwplayer/blob/7bfb5ebb65f484adfa07570c079b1470d37a0cde/src/js/api/callbacks-deprecate.js

**Comment by johnBartos** [comment]
@farneman Are you still experiencing this issue?

**Comment by farneman** [comment]
@johnBartos Currently we are. I'm going to dig into it more based on the info that you guys have provided. If I still can't resolve it I'll provide a minimal reproducible case for you to evaluate.
