### ISSUE TITLE
Captions styling doesn't work with MPEG-DASH streams and WebVTT captions in Firefox

### ISSUE THREAD

**Issue by charlesduco** [jwplayer/jwplayer#2072]
### Expected Behavior

When configuring captions styling in player setup, the style of the captions text in the player should change accordingly. For example, when you setup  `captions: {color:"red"}`, the text should have a red color.

### Actual Behavior

When configuring captions styling in player setup, the style of the captions text in the player stays the same.

### Steps to reproduce
1. Set `captions: {color: "red"}` in player setup with an MPEG-DASH stream (.mpd) and WebVTT captions
2. Play video and wait for captions to show up
35. You realize the captions don't have a red color

### Environment

- HP Compaq | notebook
- Linux Mint | 18.1
- Mozilla Firefox | 53.0.2
- JW Player 7.11.1

**Comment by johnBartos** [comment]
@charlesduco I know Firefox Linux has some compatibility issues with captions. Are you able to use the `setCaptions` api? (https://developer.jwplayer.com/jw-player/docs/javascript-api-reference/#jwplayersetcaptionsstyles)

**Comment by charlesduco** [comment]
The setCaptions api doesn't work with MPEG-DASH, but works totally okay with HLS since the 7.11.0-rc.1 release.
When I set ` jwplayer().setup({file: //server/mystream.m3u8});` all captions styling works, but when I set `jwplayer().setup({file: //server/mystream.mpd})` captions styling is gone.

I think in 7.11.0-rc.1 provider.hlsjs uses the javascript captions renderer instead of native rendering.
So, the solution is doing the same for provider.shaka

Also `renderCaptionsNatively` in player configuration is broken,` true` or `false` has no effect.

**Comment by johnBartos** [comment]
@charlesduco We're working on implementing `renderCaptionsNatively` for dash; it only works in Hls right now. Should land in 7.12, beta next week.

**Comment by johnBartos** [comment]
@charlesduco Does this work in the beta?

**Comment by charlesduco** [comment]
Yes, captions styling works now in the beta. But `renderCaptionsNatively` in player configuration is ignored, polyfills.vttrenderer.js is loaded every time, whether you set `true` or `false`.

But, captions styling works. So, I consider this issue as fixed.

**Comment by rnowak8** [comment]
Any progress?
