### ISSUE TITLE
play() action doesn't start YouTube videos on mobile

### ISSUE THREAD

**Issue by spello** [jwplayer/jwplayer#2097]
### Expected Behavior

After clicking at `playerInstance.play();` button on non-Android devices jwplayer should start playing YouTube video.

### Actual Behavior

After clicking at `playerInstance.play();` custom button on non-Android devices YouTube video won't be played.
This error occurs only when YouTube video is played. With any other media everything is fine.

### Steps to reproduce

1. open web browser on iPhone or other supported but non-Android device
2. go to http://qa.jwplayer.com/~abussey/demos/general/play-via-link-youtube.html
3. click at `<a onclick="playerInstance.play();">Click here</a> to begin playback.`
4. it won't play YouTube video

### Environment

- iPhone, iPad, iPod ...
- iOS | any
- JW Player version - current

----------------------------------------------------------------------------------------

**Comment by johnBartos** [comment]
@spello Sorry for the delay here and thanks for the report. I can confirm this bug. However, I believe theYoutube provider is on it's way out - I'll bring this up but we may decide not fix this.

**Comment by spello** [comment]
@johnBartos Why do you want to give up on YouTube support? Embedding YT was the main reason I decided to use jwplayer... At least fix this bug, please...

**Comment by johnBartos** [comment]
@spello Nothing is final but as I understand it, usage is very low. I would like to see this fixed, I'll bring this up the chain.

**Comment by gdhnz** [comment]
Clicking on the video to play has the same issue as well in iOS

Losing youtube support would be a shame as we've started using youtube more for our videos and just load json playlists via ajax using the youtube api and then display a custom playlist via jwplayer.

Funnily enough, desktop bowsers plays the videos fine.  iOS doesn't.

**Comment by erikdonohoo** [comment]
We don't use youtube for our own videos, but our customers reference youtube videos and use them in our system.  hence the need for youtube for us that can't be met by using jwplayers own hosting and cdn.  Our users aren't going to go put their things in your cdn.  Our company is definitely a huge user for jwplayer and we would hate to see youtube support go

**Comment by johnBartos** [comment]
@erikdonohoo Unless we give explicit notice (i.e. not me on github) that Youtube is on it's way out, it will still be supported. What JW developers say on this repo may not be accurate of our future plans. Sorry for the worry.

**Comment by erikdonohoo** [comment]
@johnBartos we are referring to the notice posted [here](https://support.jwplayer.com/customer/portal/articles/1406725-youtube-video-embed).  But when that notice was posted I have no idea.  No email or blog post was ever sent/made.  Its very frustrating to feel like the rug is being pulled out from under us.

**Comment by esboyd** [comment]
Hi @erikdonohoo - YouTube videos will no longer play in our next major version of the player - https://www.jwplayer.com/jw8/ Sign up today to get access to our early alpha where you can read about the upcoming changes. There will be a blog post about this, but likely later when the product is in beta.

**Comment by menoz** [comment]
I report the same problem - the only way to let the video start is by clicking on the video iteself but outside the play icon.
On my application I had to remove the play icon in iphone devices, so that user can play youtube videos clicking on the video.

Waiting for final fix...

**Comment by spello** [comment]
When will you fix this issue?

**Comment by geoSo** [comment]
@spello check here

https://github.com/jwplayer/jwplayer/issues/1842
