### ISSUE TITLE
Serialize localStorage properties as object using JSON.stringify()

### ISSUE THREAD

**Issue by johnBartos** [jwplayer/jwplayer#2101]
Our [localStorage](https://github.com/jwplayer/jwplayer/blob/master/src/js/controller/storage.js) util is limited by our single-value restriction. We should serialize objects using `JSON.stringify()` so that we can store more complex data.

**Comment by robwalch** [comment]
I like this idea. Since most of the values are part of this repo, it would be good to list them and point out trade offs or external dependencies that would need an update with this change.

**Comment by mamaddox** [comment]
Added to the internal backlog: [JW8-10713](https://jwplayer.atlassian.net/browse/JW8-10713)
