### ISSUE TITLE
Run videos with webkit in IOS devices.

### ISSUE THREAD

**Issue by pasStiga** [jwplayer/jwplayer#2110]
Hi,
I am developing a webview for IOS and ANDROID. There are some videos into the webview. I can just run it with the webkit of Android, but with the webkit of IOS I have not been able. I don't know if is possible.
Thanks a lot!

**Comment by johnBartos** [comment]
We don't officially support webviews. However, support will be coming in the near future (we're actively developing it).

**Comment by mwleinad** [comment]
I'd like this as well.
JWPlayer is not working inside a webview in an android App (is working on iOS, though)

**Comment by johnBartos** [comment]
@mwleinad What isn't working?

**Comment by pasStiga** [comment]
Hi,
In a webview actually it's working for Android devices in my case. But the point is that in IOS devices the player doesn't work in the webview. It supports the android webkit but not the IOS webkit. 
Whe I include the player in IOS devices, the appearance is an html video disabled.

**Comment by mwleinad** [comment]
Hello @johnBartos here's a quick video I made
https://app.ilosvideos.com/view/KFWyqJTl3vB1
You can see the jwplayer is not loading

For me is working on iOS but not on Android

**Comment by robwalch** [comment]
@pasStiga and @mwleinad we need more specific details regarding JavaScript execution in your webviews. Your webview settings would be helpful as well.

**Comment by mwleinad** [comment]
@robwalch Tried with jwplayer 8 and it is still failing.
Here's the project in case you want to try it by yourself.
https://drive.google.com/file/d/11l_juQTUS_XTuR4O51fqoD-JEPolrNCk/view?usp=sharing

is a very basic webview, and javascript is enabled.

`public View onCreateView(LayoutInflater inflater, ViewGroup container,
                Bundle savedInstanceState) {
            View rootView = inflater.inflate(R.layout.fragment_main, container, false);
            TextView textView = (TextView) rootView.findViewById(R.id.section_label);
            textView.setText(getString(R.string.section_format, getArguments().getInt(ARG_SECTION_NUMBER)));

            mWebView = (WebView) rootView.findViewById(R.id.wevView);
            mWebView.setVerticalScrollBarEnabled(true);
            mWebView.setHorizontalScrollBarEnabled(true);
            WebSettings webSettings = mWebView.getSettings();
            webSettings.setJavaScriptEnabled(true);

            if(getArguments().getInt(ARG_SECTION_NUMBER) == 1) {
                mWebView.loadUrl("https://app.ilosvideos.com/view/Xb6ASnm0QGsH");
            }

            if(getArguments().getInt(ARG_SECTION_NUMBER) == 2) {
                mWebView.loadUrl("http://demos.flowplayer.org/basics/minimal.html");
            }

            if(getArguments().getInt(ARG_SECTION_NUMBER) == 3) {
                mWebView.loadUrl("https://developer.jwplayer.com/tools/stream-tester/");
            }

            return rootView;
        }`

**Comment by mwleinad** [comment]
@robwalch sorry on the delay, the view is the simplest one.
Here's the code.

`public View onCreateView(LayoutInflater inflater, ViewGroup container,
                Bundle savedInstanceState) {
            View rootView = inflater.inflate(R.layout.fragment_main, container, false);
            TextView textView = (TextView) rootView.findViewById(R.id.section_label);
            textView.setText(getString(R.string.section_format, getArguments().getInt(ARG_SECTION_NUMBER)));

            mWebView = (WebView) rootView.findViewById(R.id.wevView);
            mWebView.setVerticalScrollBarEnabled(true);
            mWebView.setHorizontalScrollBarEnabled(true);
            WebSettings webSettings = mWebView.getSettings();
            webSettings.setJavaScriptEnabled(true);

            if(getArguments().getInt(ARG_SECTION_NUMBER) == 1) {
                mWebView.loadUrl("https://app.ilosvideos.com/view/Xb6ASnm0QGsH");
            }

            if(getArguments().getInt(ARG_SECTION_NUMBER) == 2) {
                mWebView.loadUrl("http://demos.flowplayer.org/basics/minimal.html");
            }

            if(getArguments().getInt(ARG_SECTION_NUMBER) == 3) {
                mWebView.loadUrl("https://developer.jwplayer.com/tools/stream-tester/");
            }

            return rootView;
        }`

**Comment by robwalch** [comment]
@mwleinad can you explain how it's not working exactly? What kind of debugging have you tried? What events are fired from the player after setup? Are there screenshots or errors from any of the pages above that you can share?

**Comment by karimJWP** [comment]
@mwleinad try adding `webSettings.setDomStorageEnabled(true);` for webSettings, and 
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            WebView.setWebContentsDebuggingEnabled(true);
}`
and lastly

`mWebView.setWebViewClient(new WebViewClient());`
