### ISSUE TITLE
How to embed iframe to jwplayer

### ISSUE THREAD

**Issue by hoangitt** [jwplayer/jwplayer#2116]
Hello Everyone,
How to embed iframe to jwplayer, please help me. Thanks
You can consult: http://hdonline.vn/phim-5-anh-em-sieu-nhan-12180.html#Si0KJMkrsX0QVkfR.97

**Comment by johnBartos** [comment]
We don't officially support iframe embedding, but this may help: https://gist.github.com/grappler/4643649
