### ISSUE TITLE
Need to record video live stream including Adds (image overlay or sort video)

### ISSUE THREAD

**Issue by singhvikram704** [jwplayer/jwplayer#2129]
Hello world,

I would like to stream a video with streaming server and want to play on web browser using JWplayer. At the time of streaming I want to show adds in between either using banner or short films.

Now I would like to record the player output, which contains original video with the mixing of ads in between.

Does JWPlayer provide any feature or their is any other way to acheive this?

Thank You

**Comment by johnBartos** [comment]
@singhvikram704 
> Live stream ads
We only support Preroll ads for live streams. We also support server-side ads but that's on the server side.

> Media recording
No, we don't provide media recording capability. You can try using the [media recorder api](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder), but I don't know if it will work with live streams.
