### ISSUE TITLE
Single Item Use Providers

### ISSUE THREAD

**Issue by robwalch** [jwplayer/jwplayer#2130]
Ensuring that the source of a provider cannot be changed will reduce side effects and allow for a cleaner provider API.

Currently `init`, `preload` and `load` accept item arguments, with no guarantee that the item or source will not change.

"preload" is a player property. It is not longer needed as an item or source property, because the provider does not need to read preload from these objects - it is set explicitly by calling `preload` on the provider. To ensure this preload should only accept preload values "auto", "metadata" and "none" ("none" would only be needed to stop preloading which is not something we need yet).

**Comment by johnBartos** [comment]
Resolved by BGL
