### ISSUE TITLE
Closed Caption (VTT) is not showing if the time frame does not have millisecond format

### ISSUE THREAD

**Issue by evan-winata** [jwplayer/jwplayer#2138]
### Expected Behavior

Newer JW Player (after version 7.4.4) should display the closed caption regardless the timeframe format (either it is 00:00:01 --> 00:00:02 or 00:00:01.000 --> 00:00:02.000)

### Actual Behavior

Newer JW Player version does not show the closed caption when it does not have millisecond format. The closed caption works fine at version 7.4.4, but it doesn't work at 7.8.4 and 7.12.1 . Please refer to 'Step to reproduce' section to see the example. I'm guessing that there's a regex filter (might be **/^(\d+):(\d{2})(:\d{2})?\.(\d{3})/** ) in vttparser.js which results in reading only timeframe with millisecond format and skip the others. 

Also, here is some part of VTT file that I use:
WEBVTT

1
00:00:01 --> 00:00:02
Thanks everyone for coming along today.

2
00:00:03 --> 00:00:05
We've got a maths focus for our meeting.

3
00:00:05 --> 00:00:06
Linda, you're taking minutes, yeah?

4
00:00:07 --> 00:00:07
I am.

5
00:00:07 --> 00:00:08
Fantastic.

6
00:00:09 --> 00:00:11
We've got some student work samples to get to

7
00:00:11 --> 00:00:12
in a little while but just to begin,

### Steps to reproduce

Version 7.4.4 (Working version):
1. Go to http://viostream-storage-dev-sydney.s3.amazonaws.com/t/jwembed/seven7_44.html
2. Click 'Embed' button (Ignore the empty textbox)
3. Play the media and see that the closed caption is appearing

Version 7.8.4 and latest (7.12.1 at the moment this ticket is submitted):
1. Go to http://viostream-storage-dev-sydney.s3.amazonaws.com/t/jwembed/seven7_84.html or http://viostream-storage-dev-sydney.s3.amazonaws.com/t/jwembed/latestWithCaption.html
2. Click 'Embed' button (Ignore the empty textbox)
3. Play the media and see that the closed caption is not shown.

### Environment

- *PC*
- *Windows 10 Pro*
- *Chrome 59.0.3071.104*
- *JW Player 7.44 and above*

**Comment by egreaves** [comment]
Hi @evan-winata,

Your assumption is correct in that the player used to allow less precise timestamps, but no longer does. The regex expects timestamp to be formatted with milliseconds, which is a requirement in the [WebVTT spec](https://w3c.github.io/webvtt/#introduction).
