### ISSUE TITLE
Video not loading properly in Chrome and Firefox

### ISSUE THREAD

**Issue by evan-winata** [jwplayer/jwplayer#2139]
Hi there,

I found a problem with the player when I tried to play a video. It works fine on Edge and IE 11, but It stopped loading after a minute in Chrome and Firefox. However, if I change the quality (i.e auto to 720), the video will resume streaming for another few chunks. 

### Expected Behavior

The video should be able to play normally in Chrome / Firefox.

### Actual Behavior

The video stops playing after around a minute and it will keep loading unless the user changes the quality.

### Steps to reproduce

1. Go to http://viostream-storage-dev-sydney.s3.amazonaws.com/t/jwembed/latest.html
2. Copy the following to the text box: 
http://cdn.app.viostream.com/au/8828ce52-efbc-4f8f-85a3-a20701105670/1992f028-0a37-4b18-80cc-0a818e5ff3a8/b0b248b1-4501-4cbb-8006-a7a1008fdde3.m3u8 
3. Click Embed.
4. Watch that the video stop playing after a minute.

### Environment

- *PC*
- *Windows 10 Pro*
- *Chrome 59.0.3071.104 , Firefox 54.0*
- *JW Player 7.12.1*

**Comment by johnBartos** [comment]
Hmm, I can't access your stream:

````
XMLHttpRequest cannot load http://cdn.app.viostream.com/au/8828ce52-efbc-4f8f-85a3-a20701105670/1992f028-0a37-4b18-80cc-0a818e5ff3a8/b0b248b1-4501-4cbb-8006-a7a1008fdde3.m3u8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://player-develop-test-jenkins.longtailvideo.com' is therefore not allowed access.
````
