### ISSUE TITLE
stylelint does not match any files

### ISSUE THREAD

**Issue by x7LoveLin** [jwplayer/jwplayer#2140]
when i run grunt, here is the err:

> jwplayer@7.12.0 lint D:\project\jwplayer
> npm run lint:js && npm run lint:styles

> jwplayer@7.12.0 lint:js D:\project\jwplayer
> eslint './src/js'

> jwplayer@7.12.0 lint:styles D:\project\jwplayer
> stylelint './src/css/**/*.less'

Error: './src/css/**/*.less' does not match any files
    at globby.then.filePaths (D:\project\jwplayer\node_modules\_stylelint@7.11.0@stylelint\lib\standalone.js:124:33)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 80
npm ERR! jwplayer@7.12.0 lint:styles: `stylelint './src/css/**/*.less'`
npm ERR! Exit status 80
npm ERR! 
npm ERR! Failed at the jwplayer@7.12.0 lint:styles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\burn_\AppData\Roaming\npm-cache\_logs\2017-07-05T08_46_16_781Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 80
npm ERR! jwplayer@7.12.0 lint: `npm run lint:js && npm run lint:styles`
npm ERR! Exit status 80
npm ERR! 
npm ERR! Failed at the jwplayer@7.12.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\burn_\AppData\Roaming\npm-cache\_logs\2017-07-05T08_46_16_806Z-debug.log
Warning: Command failed: npm run lint Use --force to continue.

Aborted due to warnings.

**Comment by johnBartos** [comment]
Works fine locally and on our build servers, please make sure that you've cloned our LESS files.
