### ISSUE TITLE
Expected empty line before rule   rule-empty-line-before

### ISSUE THREAD

**Issue by x7LoveLin** [jwplayer/jwplayer#2141]
how to solve it?  

src/css/controls/flags/ads.less
 76:5  ×  Expected empty line before rule   rule-empty-line-before

src/css/controls/flags/audioplayer.less
 13:5  ×  Expected empty line before rule   rule-empty-line-before
 51:5  ×  Expected empty line before rule   rule-empty-line-before
 61:5  ×  Expected empty line before rule   rule-empty-line-before

src/css/controls/flags/controls-hidden.less
 2:5  ×  Expected empty line before rule   rule-empty-line-before

src/css/controls/flags/flash-blocked.less
 2:1  ×  Expected empty line before rule   rule-empty-line-before

src/css/controls/flags/media-audio.less
 3:5  ×  Expected empty line before rule   rule-empty-line-before

src/css/controls/flags/time-slider-above.less
  49:13  ×  Expected empty line before rule   rule-empty-line-before
 131:9   ×  Expected empty line before rule   rule-empty-line-before

src/css/controls/imports/display.less
 80:1  ×  Expected empty line before rule   rule-empty-line-before

src/css/controls/imports/dock.less

**Comment by johnBartos** [comment]
You must have an empty line before each rule, as per our style guide. See: https://stylelint.io/user-guide/rules/rule-empty-line-before/
