### ISSUE TITLE
fatal error flash:debug

### ISSUE THREAD

**Issue by x7LoveLin** [jwplayer/jwplayer#2142]
oh my god, lots of errors.

Running "flash:debug" (flash) task
D:\project\jwplayer\node_modules\_jwplayer-flex-sdk@4.6.0-2@jwplayer-flex-sdk\lib\flex_sdk/bin/mxmlc.bat -compiler.source-path=src/flash -compiler.library-path+=D:\project\jwplayer\node_modules\_jwplayer-flex-sdk@4.6.0-2@jwplayer-flex-sdk\lib\flex_sdk/frameworks/libs -compiler.external-library-path=D:\project\jwplayer\node_modules\_jwplayer-flex-sdk@4.6.0-2@jwplayer-flex-sdk\lib\flex_sdk/frameworks/libs/player/18.0/playerglobal.swc -default-background-color=0x000000 -default-frame-rate=30 -target-player=18.0 -swf-version=29 -use-network=true -static-link-runtime-shared-libraries=true -define+=JWPLAYER::"version,'7.12.0'" -output=bin-debug/jwplayer.flash.swf src/flash/com/longtailvideo/jwplayer/player/Player.as -link-report=bin-debug/jwplayer.flashlink.xml -size-report=bin-debug/jwplayer.flashsize.xml -strict=true -debug=true -define+=CONFIG::debugging,true

Fatal error: spawn D:\project\jwplayer\node_modules\_jwplayer-flex-sdk@4.6.0-2@jwplayer-flex-sdk\lib\flex_sdk\bin\mxmlc.bat ENOENT

**Comment by johnBartos** [comment]
Do you have the Java JRE installed? https://github.com/jwplayer/jwplayer#building-the-player

**Comment by x7LoveLin** [comment]
I have installed Java1.8 and nodejs8.1.2. but still has this problem. 
help!

**Comment by robwalch** [comment]
Our team builds the player in macos and Linux. We don't support issues for building the swf on Windows.
