### ISSUE TITLE
Plugin Related videos : avoid a call to related file if the player isn't started

### ISSUE THREAD

**Issue by messenjer** [jwplayer/jwplayer#2143]
### Expected Behavior

Only load the related.file on player first play, not before.

### Actual Behavior

With the following setup, the file my-recommended-feed.json is called even if the player is not started

```
jwplayer("myElement").setup({
  "file": "http://example.com/myVideo.mp4",
  "height": 360,
  "width": 640,
  "autostart": false,
 "related": {
	"file":"my-recommended-feed.json"
 }
});
```

### Environment

- *hardware | device*
- *operating system | version*
- *browser | version*
- *JW Player version | 7.10 *

**Comment by johnBartos** [comment]
@messenjer Why do you want to delay loading your related feed? While this version doesn't introduce the exact change you want, in 7.12 we added a 2 second delay to loading the related plugin. This is delay starts from the `ready` event, but is canceled if your player will autostart.

**Comment by messenjer** [comment]
Thanks for your answer. It's a request from our sysop team, because our related feed is a recommandation feed based on the user, so it's not really cacheable. I don't see in the change log of 7.12 the new feature with 2 seconds delay. For me it's acceptable solution. I will test it.

Thanks a lot, for all the great work.

Mathieu
