### ISSUE TITLE
How to play a video with video id using JW Player

### ISSUE THREAD

**Issue by Ram2507** [jwplayer/jwplayer#2144]
Hi,
I have uploaded my video into jwplayer. Now, I am trying to play a video in my website using jwplayer API.In jwplayer setup function i am passing file parameter
with video file extension .mp4 as below

````
player = jwplayer('myElement');
player.setup({
	file: "http://content.jwplatform.com/videos/CDQhRiNs-cgMItahJ.mp4",
	image: "Campaign/Campaign_41094_Large_.png",
	autostart: false,
	skin:{
		name:"vapor",
	},
				
});
````

Here, I don't want to mention the extension extensions such as mp4 or mp3. is it possible use video id in place of
file path as show below

file: "http://content.jwplatform.com/videos/CDQhRiNs-cgMItahj

**Comment by johnBartos** [comment]
@Ram2507 The file extension is important, as it lets us know *how* we're supposed to play the media (we used different methods to play back each type). The link you pasted is a JSON feed, which we do support, and contains a bunch of files with extensions included. You cannot just use Id.

**Comment by Ram2507** [comment]
Yes I understand, But is there anyway to hide the extension?
