### ISSUE TITLE
[8.0.0 FINAL] Casting DASH crashes JW Player app on Chromecast

### ISSUE THREAD

**Issue by dominovox** [jwplayer/jwplayer#2163]
Hi,

found a weird issue with casting MPEG-DASH MP4 media to my Chromecasts 1st+2nd gen on JW Player 7.12.0-8.0.0 beta3

### Expected Behavior

JW Player 7.12.x and 8 beta 3 in Chrome should cast DASH streams to a Chromecast normally like it does with older JW Player versions and MP4 files and also HLS streams in 7.12.x. and 8.0.0 beta3

### Actual Behavior

While starting to cast a DASH stream to Chromecast, the player on Chromecast starts to load and crashes immediately to the home screen. DASH works fine with JW Player 7.9.3-7.11.3, also with MP4 progressive downloads and HLS streams on all versions since 7.9.3 to 8.0.0

### Steps to reproduce

1. Go to http://www.pietsmiet.de/tests/jwplayer800.html in Chrome
2. Cast from 2nd player to Chromecast untill the player on Chromecast crahes
3. Check with 7.12 beta here http://www.pietsmiet.de/tests/jwplayer712beta.html - that mostly works (one time my Chromecast 2nd gen crashed completly while seeking in the timeline, had to unplug it)

### Environment

- Chromecast 1st and 2nd Generation
- Win 10 Pro x64 Creators Update
- Chrome 61.0.3163.100 64bit
- JW Player 7.12.0-8.0.0 FINAL

Thanks,
Dominik

**Comment by hghazzi** [comment]
@dominovox Is this using the default receiver? Also, is the DASH stream using VP9? Default receivers do not support VP9.

**Comment by dominovox** [comment]
@hghazzi Yes, default receiver. Normal MP4 with h264/aac converted to DASH, no VP9.

**Comment by dominovox** [comment]
@hghazzi Hi, could you reproduce this issue?

**Comment by hghazzi** [comment]
@dominovox Sorry for not getting back to you sooner about this, we've been busy working on JW* :) I am able to reproduce the issue, will need to look into why it is happening. Is this the only stream that it's happening with?

**Comment by dominovox** [comment]
@hghazzi Hi, had this issue on multiple Dash streams not only from ours, also from various testpages in the internet.

**Comment by dominovox** [comment]
This issue is still occuring on 8.00 beta 3, updated post.
http://www.pietsmiet.de/tests/jwplayer800.html
