### ISSUE TITLE
[8.0.0 FINAL] DASH: Automatically changes quality back to 'Auto' after playing an ad

### ISSUE THREAD

**Issue by dominovox** [jwplayer/jwplayer#2164]
Hi,

found another issue with DASH, which does not occur when playing a normal MP4 progressive video file or a HLS stream.

### Expected Behavior

When playing a DASH stream and selecting the video quality by hand, the quality should stay the one you selected after JW Player plays a midroll ad, like it does with HLS streams and MP4 progressive video files.

### Actual Behavior

When playing a DASH stream and selecting a custom video quality like 480p oder 720p (not 'Auto'), when playing a midroll ad the quality will be switched automatically back to 'Auto' after the ad completes. This does not happen on HLS and MP4 video playbacks, the video quality will stay the one you selected by hand, even after 10 midrolls.

### Steps to reproduce

1. Go to http://www.pietsmiet.de/tests/jwplayer800.html in Chrome/Firefox
2. Play the DASH video and select a quality, except 'Auto'
3. Skip to a position after the first VAST ad (you might need a German IP to see the ad on my testpage)
4. Check the quality, it will be 'Auto', not the one you selected before the ad started

### Environment

- Win 10 Pro x64 Creators Update
- Chrome 61.0.3163.100 64bit and Firefox 56.0 64-Bit
- JW Player 7.9.0-8.0.0 FINAL

Thanks,
Dominik

**Comment by dannyfinks** [comment]
@dominovox I was able to reproduce the issue. I will provide you an update when it has been prioritized to be fixed. Thank you.

**Comment by dominovox** [comment]
@dannyfinks Hi, any news about the fix? I wanted to add that this behaviour happens even with JW Player writing the correct jwplayer.qualityLabel Key with 1080p oder 720p to the browsers local storage. After an ad the quality changes back to "Auto" and the local storage key stays at the previously selected quality.

**Comment by dominovox** [comment]
This issue is still occuring on 8.00 beta 3, updated post.
http://www.pietsmiet.de/tests/jwplayer800.html

**Comment by robwalch** [comment]
This has been fixed in the shaka provider
