### ISSUE TITLE
HLS Playlist NAME parameters are ignored. 

### ISSUE THREAD

**Issue by 4getit** [jwplayer/jwplayer#2166]
### Expected Behavior

The NAME parameter in HLS master playlist should be used as quality label when available and hlslabels:{} isn't set.

### Actual Behavior

The NAME parameters are ignored and the resolution heights are used for the quality labels.

### Steps to reproduce

Based on an answer here: https://support.jwplayer.com/customer/portal/questions/11313802-hls-labels
..I assumed the NAME parameter in a master.m3u8 playlist was used (unless overwritten by hlslabels:{}).

Right now, the NAME parameters are ignored and the resolution heights are used for setting the quality labels.

So for example with this master.m3u8:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3514115,CODECS="avc1.64001F,mp4a.40.2",RESOLUTION=1280x532,NAME="720p"
/736f8278abae9a56/playlist/720p.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=6545493,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x798,NAME="1080p"
/736f8278abae9a56/playlist/1080p.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1651791,CODECS="avc1.4D401E,mp4a.40.2",RESOLUTION=854x354,NAME="480p"
/736f8278abae9a56/playlist/480p.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1053054,CODECS="avc1.42C015,mp4a.40.2",RESOLUTION=640x266,NAME="360p"
/736f8278abae9a56/playlist/360p.m3u8
```
..the quality labels are shown as:

798p
532p
354p
266p

I think that:
- when hlslabels:{} is set, it should be used.
- when hlslabels:{} is not set, the NAME parameters should be used.
- when the NAME parameters are not available, the resolution height should be used.

### Environment

macOS, Chrome and Safari, JW Player 7.12.2

**Comment by johnBartos** [comment]
@4getit We took out this feature because it wasn't flexible enough for all our users. Some customers wanted the `NAME` field to be ignored; others didn't. As a compromise we allow customization through the `qualityLabels` config option.

https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/
