### ISSUE TITLE
7.11.2 update (and all newer versions) bricked player resizing after VAST 2 ad with Chrome/Opera

### ISSUE THREAD

**Issue by dominovox** [jwplayer/jwplayer#2170]
Hi,

found another issue with resizing/fullscreening the player after a VAST 2 ad. That happens only with JW Player 7.11.2 and newer in Webkit based browsers like Chrome and Opera.

### Expected Behavior

After playing a VAST 2 ad in normal or fullscreen size, the player should handle resizing correctly in Webkit based browsers.

### Actual Behavior

After playing a VAST 2 ad in normal or fullscreen size, then switching to fullscreen or back from fullscreen to normal size, the video is moved to the upper left corner (resizing again doesn't help to fix that). That works fine in Firefox with all player versions and with JW Player versions 7.11.1 and older in Chrome/Opera.

![image](https://user-images.githubusercontent.com/26336654/28371929-a5469814-6c9e-11e7-9940-6372f9d7b617.png)

### Steps to reproduce

1. Go to http://www.pietsmiet.de/tests/jwplayer7122.html in Chrome/Opera
2. Play one of the videos
3. Skip to a position after the first VAST ad (you might need a German IP to see the ad on my testpage)
4. Try to go on fullcreen mode - the video will appear only as a small slice in the left corner

### Environment

- Win 10 Pro x64 Creators Update
- Chrome 59.0.3071.115 64bit and Opera 46.0.0.259726201 64bit
- JW Player 7.11.2-7.12.2

Thanks,
Dominik

**Comment by johnBartos** [comment]
@dominovox We don't handle ads-related errors in this repo. Since you pay to have ads, you're entitled to assistance from our wonderful support team. 

https://dashboard.jwplayer.com/#/support

**Comment by dominovox** [comment]
@johnBartos Thanks John, already wrote an email to the support including the link to this issue - and send another mail with the full issue description after seeing this issue closed :) Hope this will be adressed soon!
