### ISSUE TITLE
DFXP parser failed to parse begin and end second when using SMPTE format as `00:00:00:00`

### ISSUE THREAD

**Issue by uditalias** [jwplayer/jwplayer#2185]
### Expected Behavior
Given the begin timestamp `00:00:01:29` and the frame rate is 1
The caption text displayed at the given second (1)

### Actual Behavior
The `strings.second()` function fails to parse the second and the caption text is displayed at the wrong second (30).

### Steps to reproduce

1. Call to `strings.second("00:00:01:29", 1)`

2. The function return value is `30` instead of `1` because 29 marks the frames.

**Comment by robwalch** [comment]
The seconds argument is frameRate. By passing in `1` you saying that the timecode represents 1 second + 29 1-second-long frames.

Can you provide an example of the DFXP file?
