### ISSUE TITLE
HD quality toggle doesnt change color on toggling from high to low quality.

### ISSUE THREAD

**Issue by dandelionred** [jwplayer/jwplayer#2201]
### Expected Behavior

Have a video with 2 sources playing in HD and click the toggle. It should turn grayish according to the `.jw-off` class.

### Actual Behavior

The toggle is still all white.

### Steps to reproduce

1. Open https://support.jwplayer.com/customer/portal/articles/1428524
2. Start playing the video (it starts in low quality).
3. Click the quality toggle once. Notice it becomes all white.
4. Click the toggle once more. Notice it is still all white.
5. Click anywhere on the page (including the video area _but outside of the time slider_) **OR** right-click anywhere on the page (including the video area) and notice the toggle becomes grayish right away.

Also notice: it works as supposed when changing quality from low to high i.e. it works when removing `.jw-off` class but it doesn't work when adding it.

### Environment

- desktop with nvidia gtx 550ti card
- ubuntu 14.04 x86_64, nvidia 375.66 driver
- chrome 60, firefox 54, opera 46. The video plays in html5 `video` element.
- 7.12.3

**Comment by johnBartos** [comment]
@dandelionred This is intended. When you click a button, it's focused and turns white - hovering does not unfocus it. It's standard browser behavior and since mobile devices don't hover, we don't want to add a special case just for desktop.
