### ISSUE TITLE
Clean up the browser utils

### ISSUE THREAD

**Issue by johnBartos** [jwplayer/jwplayer#2204]
We've replace the browser utils with `getEnvironment`, but the code itself is still relied upon internally. We should:

- es6ify the methods
- Remove all references to the internal methods
- Remove all superfluous regexes 
- Optimize regexes & usage patterns (i.e. order of execution of regexes/memos)
- Run all the regex once and put into an object (remove memos)

**Comment by mamaddox** [comment]
Added to the internal backlog: [JW8-10712](https://jwplayer.atlassian.net/browse/JW8-10712)
