### ISSUE TITLE
JWplayer video list won't work

### ISSUE THREAD

**Issue by workmarco** [jwplayer/jwplayer#2264]
Hello team,

I'm having this issue with out jwplayer, I went over JWplayer but they couldn't tell, is there any way you can help me?

Thanks.

### Shared links should play when pasted into the url.

*Describe expected behavior*
The expected behavior should be that a copy and pasted link should play when paste in the browser

### Actual Behavior
*Describe actual behavior*
### Steps to reproduce

1. go to www.evite.com/videos/
2. copy and paste a link from a video to share
3. paste the link into the browser.

### Environment
- *hardware | Any
- *operating system | Any
- *browser | Any
- *JW Player version | Any

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Hi @workmarco,

It looks like you're using JW Showcase? Have you reached out to support about this issue?

It's not clear to me what you mean by "copy and paste a link from a video to share"... are you saying the app should deeplink to the current video you are watching?

**Comment by hblee** [comment]
Hi @workmarco, we've been tracking your Showcase issue with our support team. This is the player project and not the correct GitHub project for your issue.

Can you please create your issue in https://github.com/jwplayer/jw-showcase/issues

This way our team can help you do a custom header & footer in the correct way with Angular (documented in our Wiki at https://github.com/jwplayer/jw-showcase/wiki/Customizing-JW-Showcase).

Thanks!
Henry

**Comment by hblee** [comment]
Linking to https://github.com/jwplayer/jw-showcase/issues/154

**Comment by workmarco** [comment]
Yes, it's opened there, thanks @hblee I'm closing this one.
