### ISSUE TITLE
Question: advertising

### ISSUE THREAD

**Issue by bodinsamuel** [jwplayer/jwplayer#2277]
Hello,

I know this is not an issue, but it's quiet difficult to contact the official support. So I will ask here for future reference and people like me searching for answer.

It's a basic question:
This repo contain everything except the Ad plugin, isn't it ?
It is not actually possible to use the 'advertising' configuration without paying the platinium pricing ?

If it is not possible to use the advertising configuration, is it against the licence to use a custom script to do so ?

Thanks a lot :)

**Comment by robwalch** [comment]
Hi @bodinsamuel,

> This repo contain everything except the Ad plugin, isn't it ?

This repo does not contain any commercial player logic:
- Player plugins - ads, recommendations, or sharing
- HLS or DASH playback providers
- "key" edition logic

> It is not actually possible to use the 'advertising' configuration without paying the platinium pricing ?
Right. See https://www.jwplayer.com/pricing/

> If it is not possible to use the advertising configuration, is it against the license to use a custom script to do so ?

This project's license is for non-commercial use. Running ads would be considered commercial use.

These questions should be answered by the project README. We welcome any suggestions on how to make this clearer:

https://github.com/jwplayer/jwplayer/blob/master/README.md

**Comment by bodinsamuel** [comment]
Thanks a lot for the quick answer.
The readme could use some additional details, all link redirect to the official documentation,
so I can't be quiet difficult to know exactly what it can or can't be done :)

Anyway now it's clearer, thanks again 😄

**Comment by johnBartos** [comment]
Todo: improve docs 👍

**Comment by robwalch** [comment]
@bodinsamuel I've made the disclaimer in our README clearer. There still isn't a specific callout to ads functionality, but there are links to the pricing page that describes what is in each edition.

Let us know if there were other links you found really useful or info in the README we should highlight or add.

**Comment by bodinsamuel** [comment]
Hi, 
I totally forgot to respond. But this disclaimer is great, much clearer (in my opinion) 👍 
I thinks it's enough to disambiguate, thanks
