### ISSUE TITLE
JwPlayer HLS : Add Support for Firefox for Android

### ISSUE THREAD

**Issue by messenjer** [jwplayer/jwplayer#2326]
Hello,

Could you enable support of hls with Firefox for Android ( https://www.mozilla.org/en-US/firefox/android/ )

When I test JwPlayer with an HLS source (on your page), I have this error : "Error loading player : No playable sources found"

* https://support.jwplayer.com/customer/portal/articles/1430218-using-hls-streaming

This stream works with the demo page of hlsjs ( https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8 )

* https://video-dev.github.io/hls.js/demo/?src=https%3A%2F%2Fvideo-dev.github.io%2Fstreams%2Fx36xhzz%2Fx36xhzz.m3u8&enableStreaming=true&autoRecoverError=true&enableWorker=true&dumpfMP4=false&levelCapping=-1&defaultAudioCodec=undefined

Firefox for Android is available in BrowserStack since March 3, 2017

* https://blog.mozilla.org/blog/2017/03/03/mozilla-browserstack-partner-drive-mobile-testing-real-devices/

I posted an issue Dec 19, 2016 https://support.jwplayer.com/customer/portal/questions/16769071-jwplayer-hls-add-support-for-android-firefox . The support said : "We have a feature request for this, but we can not provide an ETA on when or if this will be added to our roadmap.". Do you have more info about this feature ? 

### Expected Behavior

Play a m3u8 with Firefox for Android.

### Actual Behavior

When I test JwPlayer with an HLS source (on your page), I have this error : "Error loading player : No playable sources found"

* https://support.jwplayer.com/customer/portal/articles/1430218-using-hls-streaming

### Environment

- Mobile & Tablet
- Android
- Firefox Android
- JW Player 7.12

**Comment by mtoczko** [comment]
Add to setup
```
androidhls: false,
hlsjsdefault: true,
```

**Comment by messenjer** [comment]
Hello,

Thanks a lot it works.

What is your recommendation  ?

Add these setup options for all browsers ? Or to detect Firefox Mobile user agent and to force these setup option ? 

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#Mobile_and_Tablet_indicators 

Regards

Mathieu

**Comment by johnBartos** [comment]
@mtoczko Thanks for the help!

@messenjer It's not enabled by default because we don't officially support Android Firefox. For HLS content on Android we defer to native support and unfortunately FF doesn't natively support it. Our non-native solution, Hls.js, does support Android FF but there are still bugs to be worked out in our integration with it. You can use it today but you may encounter issues. 

As for detecting Firefox, with JW8 you can get your current environment with the `getEnvironnment` call. You can use these params to toggle your booleans:

````
const env = jwplayer.getEnvironment();
const androidFF = env.OS.android && env.Browser.firefox;
jwplayer().setup({
androidhls: !androidFF,
hlsjsdefault: androidFF
});
````

**Comment by messenjer** [comment]
@johnBartos Thanks for the explanation.

I will add a condition to use hlsjs with Firefox for Android. I hope that one day Firefox Mobile will be fully supported in JwPlayer. Mozilla makes your promotion in their websites https://hacks.mozilla.org/2017/08/life-after-flash-multimedia-for-the-open-web/

**Comment by johnBartos** [comment]
@messenjer It's certainly on the roadmap! Hlsjs is a lot more performant than native android. Closing this out.
