### ISSUE TITLE
Player hangs when changing its position in page

### ISSUE THREAD

**Issue by jithujose** [jwplayer/jwplayer#2340]
I've noticed that the player "hangs" when it's position in page is changed after the setup.
You can see this behavior in the [ad-tester page](http://demo.jwplayer.com/ad-tester/) too. 
Is there any way to restore the previous state of the player after changing its position?

My workaround right now is to use css to change the position of the parent container.

**Comment by johnBartos** [comment]
@jithujose On what div are you changing the position, and what CSS attributes are you changing? Please provide some example code.
