### ISSUE TITLE
Detecting mobile autoplay support

### ISSUE THREAD

**Issue by jithujose** [jwplayer/jwplayer#2341]
Is there any way to detect if jwplayer has autoplay support with the browser its running?

May be an event is useful.

**Comment by johnBartos** [comment]
@jithujose We're moving away from explicitly checking if autoplay is supported. Instead, we'll be trusting the `play()` promise, which is becoming the standard among players:

````
<video id="video" preload="none" src="https://example.com/file.mp4"></video>
 
<script>
  // Show loading animation.
  var playPromise = video.play();
 
  if (playPromise !== undefined) {
    playPromise.then(_ => {
      // Automatic playback started!
      // Show playing UI.
      // We can now safely pause video...
      video.pause();
    })
    .catch(error => {
      // Auto-play was prevented
      // Show paused UI.
    });
  }
</script>
````

https://developers.google.com/web/updates/2017/06/play-request-was-interrupted


But to answer your question, no, there is no way to detect if JWP has autoplay support using our API.
