### ISSUE TITLE
setControls(false) throw an error when there is a logo

### ISSUE THREAD

**Issue by klouskingsley** [jwplayer/jwplayer#2348]
### Expected Behavior

*Describe expected behavior*

remove control bar and no error throwing

### Actual Behavior

*Describe actual behavior*

throw an error like this

``` javascript
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node
```

### Steps to reproduce

1. setup player with an logo and controls on
2. `setControls(false)`

### Environment

- *hardware | device*
thinkpad t430

- *operating system | version*
windows 10

- *browser | version*
60.0.3112.113

- *JW Player version | url*
jwplayer 7.12.4

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
@klouskingsley Thanks for the report, I can confirm this in 7.12.6. The behavior is correct in the 8 beta. We should be able to provide a patch in 7 versions for this, but not until 8 is released in October (but I'll bring it up and see if we want to fix it sooner).

**Comment by robwalch** [comment]
v7.12.9 is on the beta player channel, but will be replaced with v7.12.10 before being pushed to the production player channel. This issue was fixed in https://github.com/jwplayer/jwplayer/pull/2407
