### ISSUE TITLE
Add event listeners as passive

### ISSUE THREAD

**Issue by johnBartos** [jwplayer/jwplayer#2367]
> [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

Since none of our events affect scrolling, we should use passive event listeners, so that scrolling isn't blocked by our player. 

https://developers.google.com/web/updates/2016/06/passive-event-listeners

The specific line: https://github.com/jwplayer/jwplayer/blob/master/src/js/utils/ui.js#L106

**Comment by johnBartos** [comment]
@robwalch Did a lot but there's still more to do. @karimJWP Tried it in related but encountered bad behavior as passive.

**Comment by robwalch** [comment]
This is the work I did. It adds a feature check for passive event listeners to environment, and when the browser supports it, adds it to mouse and touch listeners that do not explicitly call `preventDefault` https://github.com/jwplayer/jwplayer/pull/2601

Future improvements would be to use different events to implement UI drag and component scroll behavior, without the need to call `preventDefault`. And, to add `{ passive: true }` to mouse and touch listeners that never call `preventDefault`.
