### ISSUE TITLE
Video is unwatchable under spotty network conditions — fair buffering is not achievable

### ISSUE THREAD

**Issue by ChaseMoskal** [jwplayer/jwplayer#2380]
### Expected Behavior

Media should be reliably watchable, despite spotty network conditions
- **"watchable":** at least five minutes of continuous playback is achievable

### Actual Behavior

Under spotty network conditions, media playback stutters and halts sporadically, to an unwatchable extent
- it appears impossible for the afflicted user to buffer enough content to, reliably, achieve even a single minute of continuous playback

### Steps to reproduce

1. Attempt to watch the [PBS special on "The Vietnam War"](http://www.pbs.org/kenburns/the-vietnam-war/watch/episode-2/)
    - experience stuttering and halts in playback which makes watching a ken burns documentary (which is already plenty slow paced, let me tell you) completely unbearable
2. Pause to let it buffer, and go make popcorn
3. Get back, hit play, and find the show still unwatchable because no buffering occurred
    - the user cannot pause the video to allow a fair buffer to accumulate
    - the user is at the mercy of the content host's ability to serve the media, which is often compromised
    - the user is at the mercy of their own network connectivity, which is often compromised
    - the user has no ui indicator for buffering progress
    - user is forced to simply give up on the content

### Environment

- Desktop PC
- Windows 7
- Chrome 60.0
- JW Player 7.3.4
- http://www.pbs.org/kenburns/the-vietnam-war/watch/episode-2/

### Additional Notes

- it seems like there are endless threads of people sobbing into the void over this issue: https://support.jwplayer.com/customer/portal/questions/5405413-video-keeps-buffering-and-pausing-every-5-1-secs-
- if my bad experience is simply a sad misconfiguration of jwplayer on the part of PBS webmasters, please let this thread become instructive so that other developers may be convinced to allow their users a longer buffer leash
- it seems like a previous issue related to this was brushed off as though it was something personal https://github.com/jwplayer/jwplayer/issues/1150
- if this issue is a technical limitation of modern web browsers, and jwplayer cannot do anything directly to influence the buffering behavior — I would greatly appreciate it if somebody can articulate this shortcoming, and hypothesize how platforms like YouTube, Vimeo, and others appear to be working around the limitation, and also fantasize about how we could gripe at browser vendors to try and make this happen one day
- if this is an open area where the jwplayer team is seeking development contributions, I would be personally interested in assisting an effort towards buffer-oriented features
- ultimately, we need buffering to be something which jwplayer can leverage, so that users can reliably have a decent viewing experience — otherwise we are doomed to situations like tonight where the PBS content delivery network couldn't hold up their end of the stick, and the users get the short end

Thanks to the jwplayer team for this great long-lasting software,

  // Chase

**Comment by ChaseMoskal** [comment]
Alas, I was disheartened to now see on the [jwplayer price sheet](https://www.jwplayer.com/pricing/), that buffering might actually just be a feature of your commercial product, which isn't available in this free edition

That's too bad, since it's the users that are punished when cheapskates like PBS won't shell out for the fancy player, if that's what's happened here ;)

**Comment by robwalch** [comment]
I'm not sure @ChaseMoskal, but v7.3.4 is almost a couple of years old. Since Safari plays HLS streams natively you might try using it with Flash disabled to get a better playback experience. And request that the site you are having issues with upgrade to the lates player version - v7.12.8 or v8.0.0-beta.3 as of this writing.
