### ISSUE TITLE
Replace use of underscore in tracks mixin

### ISSUE THREAD

**Issue by egreaves** [jwplayer/jwplayer#2394]
The [tracks mixin](https://github.com/jwplayer/jwplayer/blob/master/src/js/providers/tracks-mixin.js) should use native JS Array methods in lieu of underscore methods. The following methods should be replaced: `_.each`, `_.filter`, `_.reject`, `_.findWhere`.

**Comment by hghazzi** [comment]
We can try to use codemods to do this across our codebase

https://github.com/cpojer/js-codemod#underscore-to-lodash-native

https://github.com/cpojer/js-codemod/blob/master/transforms/underscore-to-lodash-native.js
