### ISSUE TITLE
Poster is visible in full screen mode (phone)

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#2454]
### Expected Behavior
The poster should be invisible.
### Actual Behavior
The poster is visible.

![screenshot_20171005-132146](https://user-images.githubusercontent.com/9075761/31276014-09bf4762-aa9a-11e7-9662-816c4e824195.png)

### Steps to reproduce

1.  Launch the page on your phone (Samsung S8+)  

### Environment

- *hardware |  Samsung S8+
- *operating system | Android 7.0.0
- *JW Player version |  8.0.0-beta.3

**Comment by johnBartos** [comment]
@mtoczko Is this reproducible in the latest release? A sample config would help too.

**Comment by mtoczko** [comment]
@johnBartos Version 8.0.0.rc-2 works fine.
