### ISSUE TITLE
"..live stream is either down.." on mobile devices

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#2455]
### Expected Behavior

No error message

### Actual Behavior
I get an error message, but in the background the sound is playing correctly.

![screenshot_20171005-132201](https://user-images.githubusercontent.com/9075761/31276743-aaba6040-aa9d-11e7-89ad-4c83c5bacb1c.png)

### Steps to reproduce

1. Stream: https://nasa-i.akamaihd.net/hls/live/253565/NASA-NTV1-Public/master.m3u8
2. Play stream on phone
3. After a few seconds, an error message appears.

### Environment

- *hardware | Samsung S8+
- *operating system | Android 7.0.0
- *browser | Chrome
- *JW Player version | 8.0.0.beta-3, r2

**Comment by johnBartos** [comment]
@mtoczko Thanks for the report, will look into this

**Comment by johnBartos** [comment]
@mtoczko https://github.com/jwplayer/jwplayer/pull/2462
