### ISSUE TITLE
iOS fullscreen missing seek event

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#2456]
### Expected Behavior

Seek event occurs before seeked

### Actual Behavior

Seek event not present

### Steps to reproduce

1. Create basic html page with JW Player
2. Open it in WebView in iOS app 
3. Play content (it should open if fullscreen mode) and then seek back and forth.
4. Seek event is missing while seeked works correctly.

### Environment

- *iPhone 7*
- *iOS 10*
- *iOS app with WebView*
- *JW Player version - 7.12.8*

**Comment by robwalch** [comment]
@artur-michalak are you seeking in the native view? Our 'seek' event is fired when our player makes the request to update currentTime, not when it is done outside of our player UI/API.

It's a good idea for us to implement this on the media element's 'seeking' event which should take care of this issue if the 'seeking' event implementation is reliable across browsers.

**Comment by artur-michalak** [comment]
Yes i'm seeking in native view (as it goes fullscreen).

I can share sample iOS app which i used for testing. Let me know if you like to get it.

**Comment by karimJWP** [comment]
@artur-michalak please share your sample app. You can send it to karim@jwplayer.com

**Comment by robwalch** [comment]
It should matter if you are in a WebView or Safari on iOS. When the fullscreen iOS controls are used to seek, we do not fire the "seek" event. Firing "seek" from the provider(s) when the video tag fires "seeking" will fix this issue.

@artur-michalak I'm working on getting a fix-version milestone for this issue. Thanks for reporting it.

**Comment by robwalch** [comment]
A fix is making it's way to 7.12.10. The fix for v8 is marked v8.1.0.

**Comment by artur-michalak** [comment]
Checked, 7.12.10 works correctly. Issue can be closed.

**Comment by robwalch** [comment]
@Allan-Nava this thread is closed and unrelated to your question. We don't provide a JS getter for controls visibility. Controls, when active, are displayed based on the `.jw-state-*` and `.jw-flag-user-inactive` classes.
