### ISSUE TITLE
Example isn't working anymore

### ISSUE THREAD

**Issue by Dador** [jwplayer/jwplayer#2474]
### Expected Behavior

In README.md:
> Check out an interactive example in this JSFiddle.

Example from README.md should work: https://jsfiddle.net/Lgs0ou8s/4/

### Actual Behavior

It doesn't work because https://content.jwplatform.com/libraries/L7fM8L0h.js doesn't exists anymore.

**Comment by Dador** [comment]
Link to JSFiddle in README is still the same (maybe wasn't updated yet?) and doesn't works correctly.

**Comment by johnBartos** [comment]
Check it again

**Comment by Dador** [comment]
Yep, it works now. Thank you.

**Comment by robwalch** [comment]
We removed that player because people were copying it and using it on their own sites. If you need a workout ng library player, sign up for a free account at https://www.jwplayer.com
