### ISSUE TITLE
setup (autostart = false) with a hls live stream throw Cannot load M3U8:  404 Not Found

### ISSUE THREAD

**Issue by klouskingsley** [jwplayer/jwplayer#2484]
### Expected Behavior

*Describe expected behavior*
jwplayer setup (autostart = false) with a hls live stream which is not started should not throw a 404 error.

### Actual Behavior

*Describe actual behavior*

jwplayer setup (autostart = false) with a hls live stream which is not started throw an error "Cannot load M3U8:  404 Not Found".

### Steps to reproduce

1. setup jwplayer with a hls live stream url and do not start hls live

### Environment

- *hardware | device*
  
- *operating system | version*
  windows10
- *browser | version*
 chrome 61
- *JW Player version | url*
 jwplayer8.0.0, jwplayer7.6.1

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Media errors will fire for preload attempts where the stream cannot be found. To disable preloading, set preload to "none" in your setup.

**Comment by klouskingsley** [comment]
thanks, it works
