### ISSUE TITLE
Video not autoplaying on mobile devices for jwplayer 7.12.11+commercial

### ISSUE THREAD

**Issue by gauravsoti1** [jwplayer/jwplayer#2510]
### Expected Behavior

On mobile devices, autostart to work as the player comes into the view.
In site settings > media autoplay is allowed, so it is not that issue

### Actual Behavior

The player gets loaded but doesn't actually play, you have to click the play icon to actually play the video

### Steps to reproduce

1. Just go to this link: http://staging.chubbystick.in/watch
You'll see that the video doesn't autoplay on mobile, it should autoplay when it comes into view. What happens instead is that the video loads but it keeps showing the play icon and you have to click on it, otherwise the video won't play.

What I am doing is using jwplayer().play() method whenever the player comes into view 

### Environment

- Xiaomi Redmi Note 4
-Android 7.0.0
- Chrome 61.0.3163.98
- 7.12.11+commercial

**Comment by johnBartos** [comment]
Is this still an issue with 8?

**Comment by gauravsoti1** [comment]
no, it's not. thanks.
