### ISSUE TITLE
Background image not showing when audio file is streamed in V8.0 (Production)

### ISSUE THREAD

**Issue by ajai-sandy** [jwplayer/jwplayer#2511]
### Expected Behavior

When an audio file is streamed given background image should be displayed.

### Actual Behavior

Getting black screen instead of the background image

### Steps to reproduce

1. Navigate to https://nestar.in/video/fLh-u4T706k
2. In top right corner of navigation bar click on the **Audio** toggle button should be similar to the image attached below.
3. Player will start streaming audio file, but you will notice instead of background image just a plain black screen shows up.

`jwplayer('player').setup({sources: audioSource, image: thumbnail});`

 - here audio source and thumbnail are a reference to my dynamic values getting replaced in real-time.

**Plus found out that none of my videos is playing in Safari browser, whereas chrome and firefox does not face this issue.**

### Environment

- Macbook pro 2015
- MacOS 10.12.6
- Chrome - Version 61.0.3163.100, Safari - Version 11.0, Firefox - 56.0.2
- JW Player version 8.0 (Production)

<img width="289" alt="screen shot 2017-11-05 at 8 20 48 am" src="https://user-images.githubusercontent.com/6812847/32411534-45408d48-c203-11e7-99cd-d35cf43ab6e6.png">

**Comment by dannyfinks** [comment]
Thank you for reporting this. This is an issue when the player starts via autostart in audio only mode in JW8. We are aware of this issue and I will get you a timeline for the fix soon.

**Comment by egreaves** [comment]
This has been fixed by https://github.com/jwplayer/jwplayer/pull/2521.
