### ISSUE TITLE
Incorrect playback rate at start

### ISSUE THREAD

**Issue by roquez** [jwplayer/jwplayer#2536]
When I create the player with playback rate controls enabled, the selected rate is always the second menu item (while the video plays at 1x).

### Steps to reproduce

1. Setup player with custom playback rates, so the second is not `1`, e.g. `[0.5, 0.75, 1, 1.5, 2]`
2. Play the video.
3. Look at playback rates menu. In this case the selected rate is 0.75x.

### Environment

- *Windows 10*
- *Chrome 62*
- *JW Player 8.0.4*

**Comment by johnBartos** [comment]
@roquez Thanks for the report. Sounds like a regression, we'll get on it after confirmation.

**Comment by smackayht** [comment]
Was this ever resolved?

**Comment by robwalch** [comment]
This should be resolved. If you are able to reproduce, please reopen this issue with steps to reproduce.
