### ISSUE TITLE
cannot read property 'jwplayer.volume' of undefined

### ISSUE THREAD

**Issue by barsh** [jwplayer/jwplayer#2538]
### Expected Behavior

`jwplayer.js` can be loaded into `jsdom` for rudimentary testing of api.

### Actual Behavior

`error: cannot read property 'jwplayer.volume' of undefined`

![image](https://user-images.githubusercontent.com/2644202/33095083-02ece064-cec8-11e7-96ae-d0b792f5eece.png)

### Steps to reproduce

1.  setup project as described here https://github.com/barsh/jwplayer-jest
2.  run `yarn test`

### Environment

- laptop/desktop
- windows 10
- https://www.npmjs.com/package/jsdom
- https://github.com/barsh/jwplayer-jest/blob/master/jwplayer/debug-v8.0.2/jwplayer.js

### Related
- https://github.com/barsh/jwplayer-jest/issues/1

**Comment by johnBartos** [comment]
Is your first step a false positive? The second step is implying that `jwplayer` is actually undefined.

**Comment by robwalch** [comment]
@barsh The error is occurring here where the player attempts to read from localStorage during setup https://github.com/jwplayer/jwplayer/blob/722bab212fbab29de800f3f52b5e208076021f37/src/js/model/storage.js#L20

If `window.localStorage` is undefined in your environment, and doesn't throw an error this is expected. We can guard against this condition, it's just not one we've seen in any browser environment that we support.
