### ISSUE TITLE
Update playlist item without whole playlist reload

### ISSUE THREAD

**Issue by nterziyski** [jwplayer/jwplayer#2558]
### Expected Behavior

As a user I want to be able to edit a playlist item dynamically and update it without loading the whole playlist inside the player again.

### Actual Behavior

Currently it is only possible to update a single/multiple items inside an already loaded playlist through a player.load(playlist). This is also suboptimal, because by default it just starts the playlist from the first item again.

### User Story

1. As a user I am loading a VAST Tag per playlist item basis.
2. I want to initialise the VAST Tag differently for the subsequent playlist item/s, based on if they were auto-started or there was a user interaction.

### Environment

- Chrome/Firefox
- JWPlayer 8.0.4

**Comment by jnatalzia** [comment]
Hi @nterziyski! 

Apologies for the long wait. We are trialing a new feature request template to triage requests efficiently to our product team. If you wouldn't mind filling out the following, I'll be more than happy to transfer to our internal backlog. Thanks!

```
# Feature Request Title (Clear and Descriptive)

## Problem Overview
This should be a general overview of the problem you're experiencing. It is important to note that this does not go into the solution you are proposing as that is relegated to a later section.

## Current Solutions or Workarounds
This should describe what current ways exist to get around the problem listed above.

## Proposed solution (optional)
Your idea for how to solve the above problem.

## Examples in the wild (optional)
List some other video players or applications where this feature exists.

## Additional Information (optional)
Anything else that does not fit into the above categories.

```
