### ISSUE TITLE
Error loading media: Only on Iphone devices

### ISSUE THREAD

**Issue by ajai-sandy** [jwplayer/jwplayer#2572]
### Expected Behavior

*When the page is loaded on click of play button the video should start to stream.*

### Actual Behavior

*On click of the play button the video is not playing instead getting "Error loading media" error*

### Steps to reproduce

1. Go to https://nestar.in/video/g9ZO0xkufIE on your iPhone
2. Click on play button

Currently, have integrated *JW Player version 8.0 (Production)*, the issue is happening in both normal and incognito mode. As for the Android devices, it works seamlessly.

### Environment

 *iphone 5s*
- Safari (ios 10)
- chrome 62.0.3202.70
- Firefox

 *iphone 6*
- Safari (ios 11.0)
- chrome v56.0.2924.79
- Firefox

 *iphone 7*
- Safari (ios 11.0)
- chrome v62.0.3202.70
- Firefox

**Comment by robwalch** [comment]
Hi @ajai-sandy,

Was https://nestar.in/video/g9ZO0xkufIE a live stream? It's not up anymore.

Our player can only play videos on iOS that are supported natively by the device. This is likely an issue with the video encoder and not our player.

If you have a video source that works in iOS using `video.src=`, but not in our player, please reopen.

**Comment by ajai-sandy** [comment]
Hi @robwalch 

Apologies, my site was down when you tried to investigate, just made it up. It's not a live stream, I am using youtube-dl - npm package to generate the URL in real time. There is no issue streaming the video on Mac, whereas this issue is happening only on the mobile devices.

**Comment by robwalch** [comment]
@ajai-sandy that video is a webm which is not supported natively by Safari. I suggest you use YouTube's player. We do not provide support for use cases which violate YouTube's terms of service which I think this does https://www.youtube.com/static?gl=GB&template=terms
