### ISSUE TITLE
After chrome upgrade to Version 62.0.3202.94 RTMP is not working

### ISSUE THREAD

**Issue by muralimnmcse** [jwplayer/jwplayer#2573]
Cross-origin plugin content from https://ssl.p.jwpcdn.com/player/v/7.12.11/jwplayer.loader.swf must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked.

**Comment by johnBartos** [comment]
Looks like a problem with Chrome. I see VideoJS is having the same problem too. https://github.com/videojs/video.js/issues/4791

Since Flash is deprecated we will not be pursing a fix for this.
