### ISSUE TITLE
Expose getEnvironment()

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#2586]
### Expected Behavior
`getEnvironment()` should work without player instance.
It believe this shouldn't be a big issue as environment part doesn't relay on any instance related options/methods.

### Actual Behavior

Currently if it is not possible to call `getEnvironment()` before player is created. This is inconvenient because sometimes it's desirable to do browser/os specific actions (like load different stream sources or aspect ratio).

### Steps to reproduce

1. Include jwplayer library
2. call `jwplayer().getEnvironment()`
3. expect `Uncaught TypeError: jwplayer(...).getEnviorment is not a function` issue
### Environment

- *hardware | all *
- *operating system | all*
- *browser | all *
- *JW Player version | 8*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by waxidiotic** [comment]
@artur-michalak This should work and is working for me on this test page in which I'm not even calling `.setup()`:

http://bob.jwplayer.com/~alex/getEnvironment.html
