### ISSUE TITLE
Video deformation on fullscreen

### ISSUE THREAD

**Issue by alexisboulet** [jwplayer/jwplayer#2587]
### Expected Behavior

The player should always respect his ratio, in fullscreen mode included.

### Actual Behavior

In very specific environment (see below), where fullscreen is forced, my player ratio is not respected and the video is deformed. It only happen once, at the first start of my video. If I pause then play again, it is not deformed anymore.

I already knew this bug a few months ago but thought it will be resolved with JW8. It is not.

### Steps to reproduce

1. Include a video with JwPlayer in your page.
2. Share your page's url on Pinterest, Snapchat's story or include your player in a Iframe for Facebook Instant Articles.
3. In Pinterest and Snapchat, visit your page. On Facebook Instant Article, visit the article including your player.
4. Play your video, you will see randomly (not happening every time) deformation on the first launch.

I tried to use JwPlayer with no specifics configuration but experienced the same problem.
It only happened on iOS 11.

### Environment

- hardware | iPhone 7
- operating system | iOS 11.2
- browser | Facebook Instant Articles, Pinterest browser in app, Snapchat browser in app
- JW Player version | 7 and 8

**Comment by robwalch** [comment]
Thanks for the bug report @alexisboulet. Can you share a screenshot of what the deformation looks like?

I'll see if we can get a little more testing in WebViews on iOS 11.2 to see if we can duplicate the issue before v8.1.0 is released.

**Comment by karimJWP** [comment]
@alexisboulet could you also share the configuration you use to set up the player ?

**Comment by alexisboulet** [comment]
@robwalch I have this :
![image](https://user-images.githubusercontent.com/8068327/34675435-e9f57570-f489-11e7-95b6-b38ecb6417da.png)
instead of this :
![image](https://user-images.githubusercontent.com/8068327/34675739-cf96944c-f48a-11e7-9ece-4a2aa7d050ea.png)

@karimJWP no specific configuration. For this screenshot, I used this code (jwplayer 8) : 

```
<script src="jwplayer.js"></script>
<script src="jwplayer.core.js"></script>
<div id="myPlayer">Player loading ...</div>
<script>
	var jw = jwplayer('myPlayer');
        jwplayer.key = JW_KEY;
	jw.setup({
		"file": "http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
	});
</script>

**Comment by robwalch** [comment]
Thanks @alexisboulet,

The video should be fit using these `object-fit` rules. Have you notices any other CSS layout issues in this environment? If the `.jw-stretch-uniform` class is being applied to the player, and no other CSS is interfering with it, then this is a Safari bug. It could be that something on the page in the webview is overriding this rule. You may want to apply your own CSS to the player element if that's the case.

```les
    &.jw-stretch-uniform {
        video {
            object-fit: contain;
        }
    }

    &.jw-stretch-none {
        video {
            object-fit: none;
        }
    }

    &.jw-stretch-fill {
        video {
            object-fit: cover;
        }
    }

    &.jw-stretch-exactfit {
        video {
            object-fit: fill;
        }
    }
```

**Comment by alexisboulet** [comment]
No other CSS is interfering with .jw-stretch-uniform class. This style is applied : 
```
video.jw-video.jw-reset {
        object-fit: fill;
}
```

So I tried to override it with this and it worked : 
```
.jw-stretch-uniform video {
        object-fit: contain !important;
}
```
Thank you [@robwalch](https://github.com/robwalch) and [karimJWP](https://github.com/karimJWP)
