### ISSUE TITLE
Fullscreen Fuctionality is breaking.

### ISSUE THREAD

**Issue by rahulsinghvuclip** [jwplayer/jwplayer#2592]
### Expected Behavior
On click of fullscreen the player should expand to full screen.

### Actual Behavior

on click of fullscreen the player is flickering and full screening is not there.
btw i am using react-jwplayer
### Steps to reproduce

1.once player is loaded click on  fullscreen icon.

### Environment

- *JW Player version |8

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
@rahulsinghvuclip We can't reproduce this, so it sounds like a react-jwplayer issue. I see your open issue on that repo (https://github.com/micnews/react-jw-player/issues/76). If it's determined to be a player issue please reopen with thorough reproduction steps.

**Comment by danmakenoise** [comment]
@johnBartos hey! @rahulsinghvuclip put up an example of this [here](https://rahul123player.herokuapp.com/), and I'm trying to debug it. Hopefully you guys can help:

* When clicking fullscreen, the player actually does go into fullscreen, but JW Player immediately decides to remove the `jw-flag-fullscreen` class. 

The logic is minified so it's tough to figure it out, but I think I narrowed it down to [this line](https://github.com/jwplayer/jwplayer/blob/52429954d2aa1984c2d423041a09fa0dc198f18c/src/js/view/view.js#L601)

Any chance you guys could help us? It could definitely be a problem in `react-jw-player`, but we don't really mess with the player itself, we just instantiate them. Any input would be helpful here.

**Comment by rahulsinghvuclip** [comment]
Team any update on this

**Comment by rahulsinghvuclip** [comment]
@johnBartos  any update on this team
