### ISSUE TITLE
Youtube - Setplaybackquality - Not Working

### ISSUE THREAD

**Issue by EXAlejandro** [jwplayer/jwplayer#2595]
In the last days I think there was an update.

When we embed YouTube in Jwplayer, we can not change the quality.

Manuel did not react when I tried.

Setplaybackquality lost function?

**Comment by EXAlejandro** [comment]
Nobody knows?

**Comment by jaboullosa** [comment]
I have noticed the same problem since 8/12/2017
Setplaybackquality  not working

**Comment by EXAlejandro** [comment]
Why?

**Comment by robwalch** [comment]
If a change in YouTube's iFrame/JavaScript API has affected the behavior of your site, please report the issue to YouTube via stackoverflow with the tag `[youtube-api]`.

Here are some results for "setplaybackquality":
https://stackoverflow.com/search?q=%5Byoutube-api%5D+Setplaybackquality
