### ISSUE TITLE
An error occurred while running the “grunt“ command

### ISSUE THREAD

**Issue by joomlarulez** [jwplayer/jwplayer#2608]
When running the “grunt“ command I should have this 

### Expected Behavior
INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
INFO [launcher]: Launching browser PhantomJS with concurrency 1
INFO [launcher]: Starting browser PhantomJS
NFO [PhantomJS 2.1.1 (xxxxxx)]: Connected on socket xxxxxxx with id xxxxxx

And under I have this error return 

### Actual Behavior

INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
INFO [launcher]: Launching browser PhantomJS with concurrency 1
INFO [launcher]: Starting browser PhantomJS
WARN [launcher]: PhantomJS have not captured in 120000 ms, killing.
WARN [launcher]: PhantomJS was not killed in 2000 ms, sending SIGKILL.
WARN [launcher]: PhantomJS was not killed by SIGKILL in 2000 ms, continuing.
Warning: Task "karma:phantomjs" failed. Use --force to continue.
Aborted due to warnings.
##[error]Grunt failed with error: C:\NPM\Modules\grunt.cmd failed with return code: 3
##[section]Finishing: grunt

### Environment

visualstudio.com

**Comment by johnBartos** [comment]
@joomlarulez Is this on Windows?

**Comment by joomlarulez** [comment]
Hello,
It's build on this website environment not locally
visualstudio.com

visualstudio is support for a very large locally environment but I don't know online what server they used.
https://www.visualstudio.com/en-us/productinfo/vs2017-compatibility-vs
https://www.visualstudio.com/vs/features/

see screen capture 
https://screenshots.firefox.com/Gyietj5rgO2oRy4S/joomlarulez.visualstudio.com

Best regards
