### ISSUE TITLE
Player functionality breaks when div id can be coerced into number

### ISSUE THREAD

**Issue by danmakenoise** [jwplayer/jwplayer#2618]
### Expected Behavior

If I launch JW Player into a div with an id that is a number in string form, the player behaves as expected.

### Actual Behavior

Full-screen functionality, and possibly others are broken. (Full-screen renders and then immediately exits, while leaving the browser itself in full-screen)

### Steps to reproduce

[Example](https://codepen.io/danmakenoise/pen/LeRxyG)

1. Create a div with an id of "123" or any number in string form.
2. Launch JW Player into that div.
3. Full-screen functionality is broken.

### Environment

- *Macbook Pro*
- *MacOS High Sierra*
- *Latest Chrome/Firefox/Safari*
- *Confirmed with JW Player 7 + 8*

**Comment by danmakenoise** [comment]
This was the cause of this issue https://github.com/jwplayer/jwplayer/issues/2592

**Comment by robwalch** [comment]
Thanks @danmakenoise! I'm looking into it.

**Comment by robwalch** [comment]
@danmakenoise The fix has been merged and will be released in v8.1.

**Comment by danmakenoise** [comment]
@robwalch thank you!

**Comment by Way-U-Need** [comment]
whats the solution?

**Comment by robwalch** [comment]
@Way-U-Need it's referenced above: https://github.com/jwplayer/jwplayer/pull/2621/files

Alternatively, avoid using numbers as element ids.
