### ISSUE TITLE
anonymous define() error jwplayer and Magento

### ISSUE THREAD

**Issue by evwebcoder** [jwplayer/jwplayer#2620]
### Actual Behavior

*Magento uses RequireJS to load custom javascript and their own code base scripts, you can also load CDN URLs to libraries as an absolute URL, for this I am loading the JWPlayer with the absolute URL and its throwing an error. I have not yet call or initiate the JWPlayer object, I am only added it to the head tag and its already throwing an error.*  

This error is a known issue that the community has posted on this ticket (https://github.com/jwplayer/jwplayer/issues/741) since 2015, until 2017. The issue has been re-open and closed many times with no real solution to this, I am using the latest versions on all platforms and this issue still happens as of today. On the original ticket issue the member **@robwalch** as closed the issue and limited the conversation on the issue and asked to open a new one. I am currently working on a project and I dont have the time to setup a staging environment with the working example, but I should be able to do this after my project in 3 weeks, in the meanwhile this issue should still be handle and looked at, so I please ask for the JWPlayer team to provide solutions and/or documentation for those that still run into this. Thank You.

### Steps to reproduce

1. Install and run a fresh copy of Magento 2 on your local environment 
2. Configure the Magento platform to use the default theme called Luma
3. Update the corresponding layout configuration file to add external Javascript file and add the jwplayer URL with the following syntax (change the PLAYERID with your ID):
```
<script src="https://content.jwplatform.com/libraries/PLAYERID.js" src_type="url" />
```
4. Run the site and navigate to the page you added the jwplayer library and in the browser console you will see the following:  

![ss 2017-12-27 at 10 56 34 am](https://user-images.githubusercontent.com/1063518/34386499-f2383a48-eaf6-11e7-817e-13024059748e.png)  

### Environment

- *MacBook Pro 15-inch, 2017*
- *macOS High Sierra | 10.13.2*
- *Chrome | Version 63.0.3239.108 (Official Build) (64-bit) | Any browser will trigger it, it not browser specific*
- *JW Player version | 8.0.11*
- *Magento | 2.2.2*

**Comment by robwalch** [comment]
@evwebcoder can you provide a sample of page code that shows the order in which libraries are being loaded?

I'm hoping we can reproduce this issue with just require.js and jwplayer. I'm not familiar with setting up the magneto platform. What's important is the order in which scripts are embedded and AMD dependencies are loaded.

My first guess is that the UMD in jwplayer needs the player to be loaded by require.js when it is embedded after the script that defines require.js's `define` method. Would it be possible to move the jwplayer embed up before the magento or requirejs script (that would at least prove my theory here) at least as a workaround, until we can reproduce the issue and determine a viable fix?

The specific issue reported in #741 has been addressed. [Here are samples of the player working with requirejs](http://demo.jwplayer.com/requirejs/). It might be that not every combination of embed order has been addressed. That also might be a limitation of AMD with require.js and our player needing to support being loaded with AMD, as well as side loaded next to AMD libraries.

Another detail that would help is your player config - that'll show us which plugins and features of jwplayer you are using. It might be a plugin, not jwplayer.js proper that is the cause of the exception.
