### ISSUE TITLE
autostart can't  work!

### ISSUE THREAD

**Issue by Johnharvy** [jwplayer/jwplayer#2643]
The HLS format video stream automatically plays OK on the local settings, but the play method is intercepted on the server, and the error occurs in the 7.2 version.

**Comment by robwalch** [comment]
Hi @Johnharvy,

I'm not sure from your description what the error is. Is it a JavaScript error or a network error?

The latest version of the player v8.0.11. The LTS version is v7.12.11. You'll need to update and provide a detailed bug report for us to be able to help.
