### ISSUE TITLE
JWPLAYER - HLS - CLOUDFRONT - SIGNED URLS

### ISSUE THREAD

**Issue by Leeaandrob** [jwplayer/jwplayer#2662]
### Expected Behavior

I want to my playlist master and my file urls loaded by playlist are be signed like my playlistmaster

https://d22h5cna8smpgc.cloudfront.net/app.aulasonline.de/contents/videos/840d2/hls_840d2.m3u8?Expires=1515513349&Signature=asdadadadadadadada__&Key-Pair-Id=adsadadadadaaa

### Actual Behavior

Today are signed url only on master and not on file urls and I receive 403 because the cloudfront only server the urls with signed urls.

### Steps to reproduce

1. Open network specify chrome developer tools
2. Try to play the url https://app.aulasonline.de/contents/1/

### Environment

- *Mac Mini *
- *OSX *
- *Chrome version 64 canary*
- *8.1 | https://app.aulasonline.de/contents/1/*

**Comment by HeidiW** [comment]
Hi @Leeaandrob this issue was brought to my attention by another customer. Going forward, please submit issues via the JW Dashboard Support portal, unless your questions have directly to do with the open source player. Thanks.

**Comment by robwalch** [comment]
https://support.jwplayer.com/submit-support-case
