### ISSUE TITLE
Empty VMAP response

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#2671]
### Expected Behavior

Acoording to specs https://www.iab.com/wp-content/uploads/2015/06/VMAP.pdf point 2.6
![image](https://user-images.githubusercontent.com/2443904/34723561-5f0532f8-f54b-11e7-927a-5fccd5f45324.png)
Player should play content without displaying ad player icons.

### Actual Behavior
Player triggers adError and stalling in infinite spinning state.
![image](https://user-images.githubusercontent.com/2443904/34723606-88c25d78-f54b-11e7-9ce4-858262a3394c.png)

Player returns above 

### Steps to reproduce

1. Embed player with this ad setup:
```
advertising:{
   client:"vast",
   schedule:"https://ib.adnxs.com/vmap?id=1259437322&cb=68341390196"
}
```
2. Try to play content

### Environment

- *hardware | all *
- *operating system | OSX *
- *browser | Chrome 63 *
- *JW Player version | 8.0.11 *

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by paulmandal** [comment]
Can you provide the complete player config?  I haven't been able to reproduce this infinite buffer issue on OSX w/ Chrome 63.  Though I do see the adError event.  This is the config I'm using:

```
{
    "file": "http://content.bitsontherun.com/videos/bkaovAYt-52qL9xLP.mp4",
    "advertising": {
       client:"vast",
       schedule:"https://ib.adnxs.com/vmap?id=1259437322&cb=68341390196"
    }
  }
```

**Comment by artur-michalak** [comment]
This happens when autostart is set to true.

```
    var player = jwplayer("player).setup({
        "playlist": [{
            "file": "http://content.jwplatform.com/videos/bkaovAYt-640.mp4",
        }],
        autostart: true,
        "key": "KEY",
        "advertising": {
            client:"vast",
            schedule:"https://ib.adnxs.com/vmap?id=1259437322&cb=68341390196"
        }
    });
```

This issue has high priority for us because we can't change our ad delivery provider.

**Comment by paulmandal** [comment]
Thank you, I can reproduce the issue with this.  It should be fixed in our next release.

**Comment by artur-michalak** [comment]
Thanks. Please also check this case: 
```
var player = jwplayer('player').setup(...);
player.on('ready', player.play)
```
