### ISSUE TITLE
Error while loading new playlist

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#2678]
### Expected Behavior
Calling `.load()` function while ads are playing causing player `playAttemptFailed` error with message
`The play() request was interrupted by a new load request. https://goo.gl/LdLk22`

### Actual Behavior
Player should finish playback and play new playlist without error

### Steps to reproduce
1. Setup player and check console
    var player = jwplayer("player1").setup({
        "playlist": [{
            "file": "http://content.jwplatform.com/videos/bkaovAYt-640.mp4",
        }],
        autostart: true,
        "key": "928134789273891723987234987234",
        "advertising": {
            client:"vast",
            schedule:"https://ib.adnxs.com/vmap?id=12557825&cb=5890513107&vcontext=1&vskippable=1&vplaybackmethod=1&vp_abl=1&aa-sch-country_code=no&aa-sch-supply_type=web_desktop&aa-sch-publisher=vgtv&no-sno-adformat=preroll&no-sno-news-tv_category=273"
        }
    });

    player.on('all', console.log);

    setTimeout(function () {
        player.load([{
            "file": "http://content.jwplatform.com/videos/bkaovAYt-640.mp4",
        }])
    }, 5000);

### Environment

- *hardware | Desktop OSX*
- *operating system | 10.11.6 *
- *browser | 63.0.3239.132 *
- *JW Player version | 8.0.11 *

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
@artur-michalak we've identified the issue. Thanks for the bug report.
