### ISSUE TITLE
An error occurred while running the “grunt“ command

### ISSUE THREAD

**Issue by alexdem161** [jwplayer/jwplayer#2683]
Error: './src/css/**/*.less' does not match any files
    at globby.then.filePaths (C:\projects\jwplayer-7.12.11\node_modules\stylelint\lib\standalone.js:124:33)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 80
npm ERR! jwplayer@7.12.11 lint:styles: `stylelint './src/css/**/*.less'`
npm ERR! Exit status 80
npm ERR!
npm ERR! Failed at the jwplayer@7.12.11 lint:styles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alexdem161\AppData\Roaming\npm-cache\_logs\2018-01-15T09_01_02_954Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 80
npm ERR! jwplayer@7.12.11 lint: `npm run lint:js && npm run lint:styles`
npm ERR! Exit status 80
npm ERR!
npm ERR! Failed at the jwplayer@7.12.11 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alexdem161\AppData\Roaming\npm-cache\_logs\2018-01-15T09_01_03_029Z-debug.log
Warning: Command failed: npm run lint Use --force to continue.

Aborted due to warnings.

_____________________________________

node version v8.9.4
nmp version 5.6.0
Windows 10

**Comment by robwalch** [comment]
Hi @alexdem161,

Can you execute `stylelint './src/css/**/*.less'` in the project dir? The error suggests that your system isn't able to do that. You may need to instal stylelint globally: `npm i -g stylelint`.

**Comment by clwh92** [comment]
hi,@robwalch, I tried it according to your description, but it didn't work. Is there any other plan?

**Comment by robwalch** [comment]
This issue has been closed for over a year and does not provide enough steps to reproduce. Please follow the README. Open a new bug with steps to reproduce if you are still having problems. Note that we do not support building on Windows.
