### ISSUE TITLE
Parse UC browser; add to environment 

### ISSUE THREAD

**Issue by johnBartos** [jwplayer/jwplayer#2696]
The UC browser comes in as Chrome. We should parse it so that we're able to know usage stats & fix specific bugs

**Comment by waxidiotic** [comment]
@johnBartos I can do this since I recently did the same for Windows Phones.

**Comment by robwalch** [comment]
Leaving this open until `Browsers.UC` is added to environment.

**Comment by waxidiotic** [comment]
Done. Will be in 8.2.0.
