### ISSUE TITLE
Chromecast doesn't work (8.1.0)

### ISSUE THREAD

**Issue by mumi** [jwplayer/jwplayer#2710]
### Expected Behavior:

Same result as this:
https://s3.amazonaws.com/qa.jwplayer.com/~abussey/demos/2017/nov/122156-cast.html
Here I can see the Cast button and  I can stream the video to the chromecast
![Image of Chromecast Button](https://i.imgur.com/kQUxFee.png)

### Actual Behavior:
On my self compiled jwplayer (8.1.0), it doesn't work, so i can't see the cast button

`jwplayer("myElement").setup({`
`			file: "Movie.mp4",`
`			cast:{ }`
`		});`

![Image without Chromecast Button](https://i.imgur.com/dk41HmG.png)

### Environment

- Chromecast 1 version
- PC and Mobile
- Windows 10 and android 8
- Chrome 63.0.3239.132  (64-Bit) and mobile Chrome
- JWplayer 8.1.0

**Comment by waxidiotic** [comment]
@mumi can you provide a URL to a reproduction page showing the chromecast button not appearing for you?

**Comment by mumi** [comment]
@waxidiotic mumi.tk/jw

**Comment by waxidiotic** [comment]
@mumi Thank you for that. It looks like casting is not available on the open-source version of the player. It is one of the features that require a subscription, though any level subscription includes casting.

https://www.jwplayer.com/pricing
