### ISSUE TITLE
Want local file in android as jwplayer skin

### ISSUE THREAD

**Issue by Sudhanshu2610** [jwplayer/jwplayer#2722]
We have provided the feature of downloading the videos and watching them offline in our app which is using jwplayer. We are creating a player config with skin name and a skin url which is a aws url. Is there any way we can have local file as skin for offline watching.

One more thing I noticed that once the user has watched a video online, he can watch it offline also,
I suppose the skin data is stored in cache once it is called

FYI the video which has to be played is stored inside app only.

Device - LenovoA7020a48
OS- Android 

*Describe expected behavior*

### Actual Behavior

*Describe actual behavior*

### Steps to reproduce

1.
2.
3.

### Environment

- *hardware | device*
- *operating system | version*
- *browser | version*
- *JW Player version | url*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
@Sudhanshu2610 No, we don't support local skin files. Skins are also deprecated in JW8; therefore, we won't add a new feature to do so.
