### ISSUE TITLE
Shaka Player TextTrack with a DASH-MEPG file with multi audio

### ISSUE THREAD

**Issue by Roadirsh** [jwplayer/jwplayer#2725]
### Expected Behavior

When loading a multi audio dash file, the player should not shows any caption button on any browser if there is no captions available.

### Actual Behavior

On Chrome 64 and Mac OSX Sierra, the caption button appears if you click in less than 2s the play button and it stay there. The caption written is "Shaka Player TextTrack", it should'nt appears. When you wait a few seconds before playing the video, the caption does not appears.

### Steps to reproduce

1. Have an mdp file with multi audio
2. Load jwplayer
3. Click fast enough on play.

### Environment

- Mac OSX Sierra
- Chrome 64
- Jwplayer 8.1.4
- Test url: https://www.imcas.com/en/academy/test/jwplayer

**Comment by jeremydenoun** [comment]
+1 it's seems this can be avoid (sometime) with preload: none (disable metadata loading) but on android mobile this tricks doesn't work

**Comment by jnatalzia** [comment]
Hi @Roadirsh! 

Is this still an issue for you? Thanks

**Comment by Roadirsh** [comment]
I just tried with version 8.8.5 and I cannot reproduce the issue anymore. 
It seems fixed to me! Thank you.
