### ISSUE TITLE
jwplayer stereomode monoscopic option uses CORS to check the allowed origins

### ISSUE THREAD

**Issue by fpilee** [jwplayer/jwplayer#2732]
### Expected Behavior

*Do not enforce CORS*

### Actual Behavior

*Is asking for CORS* 

### Steps to reproduce

*1. Create a jwplayer video player, load a vr video from other domain*

### Environment

- *Desktop*
- * Windows 10*
- *Chrome 64*
- *JW Player version 7.12*

----------------------------------------------------------------------------------------

```javascript
<script type="text/javascript">
    var playerInstance = jwplayer('player');
    playerInstance.setup({
        skin: {
            name: "bekle"
        },
        playlist: [{
            sources: [{file: "http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4", label: '360p'}],
			"stereomode" : "monoscopic",
		}],
        preload: "auto",
        aspectratio : "16:9"
    });

</script>

```
I used a free non vr video but it also fails the stereomode monoscopic is the issue

**Comment by johnBartos** [comment]
@fpilee We don't enforce CORS, the browser does. The other domain needs to whitelist your domain so that it can cross-origin share. You can use a CORS extension (such as https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en) to disable it for your own browser

**Comment by fpilee** [comment]
So the issue is the option stereomode of the playlist, 
if I set that option to monoscopic jwplayer check for allowed origin headers...

**Comment by fpilee** [comment]
You do enforce when I set stereomode to monoscopic. check the it

**Comment by fpilee** [comment]
at least check before close the issue

**Comment by fpilee** [comment]
check that code with stereomode and without it
