### ISSUE TITLE
Page is un-scrollable after calling remove in fullscreen mode

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/jwplayer#2768]
### Expected Behavior

When a player is playing in fullscreen mode and `remove()` is being called it should restore all modifications to the document.

### Actual Behavior

The body element gets an inline style `overflow-y: hidden` when going to fullscreen mode. This inline style isn't being removed after calling `player.remove()`. This leaves the page un-scrollable.

### Steps to reproduce

1. Go to fullscreen
2. call `jwplayer().remove();`
3. try to scroll

### Workaround

1. Before calling `jwplayer().remove()` call `jwplayer().setFullscreen(false);`

### Environment

- macOS High Sierra | 10.13.3
- Google Chrome | 65.0.3325.146
- 8.1.12

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
@ChristiaanScheermeijer Confirmed this bug, thanks for the report
