### ISSUE TITLE
midroll advertising in playlist: schedule leaks into next video

### ISSUE THREAD

**Issue by Walfisch** [jwplayer/jwplayer#2793]
### Expected Behavior

In a playlist, every video has its own adschedule.

### Actual Behavior

When the player switches from one video to the next, the adschedules of both videos are combined.

### Steps to reproduce

    <!doctype html>
    <html lang="en">
    <meta charset="utf-8">
    <title>play</title>

    <script src="jwplayer.js"></script>
    <script>jwplayer.key = "SOME_KEY";</script>

    <div id="player">Loading the player...</div>
    <script>
    jwplayer("player").setup({
        "advertising": {"client": "vast"},
        playlist: [{
            file: "http://clips.vorwaerts-gmbh.de/VfE_html5.mp4",
            adschedule: {
                midroll0: {
                    offset: 30,
                    tag: "http://demo.tremorvideo.com/proddev/vast/vast2Nonlinear.xml"
                }
            }
        }, {
            file: "http://clips.vorwaerts-gmbh.de/VfE_html5.mp4",
            adschedule: {
                midroll0: {
                    offset: 15,
                    tag: "http://demo.tremorvideo.com/proddev/vast/vast2Nonlinear.xml"
                },
                midroll1: {
                    offset: 45,
                    tag: "http://demo.tremorvideo.com/proddev/vast/vast2Nonlinear.xml"
                }
            }
        }]
    });
    </script>

1. Start the video, see it has one adbreak after 30s.

![](https://images.sport1.de/imagix/filter2/png/_set=empty/imagix/06a24c74-2b91-11e8-87b1-f80f41fc63ce "one ad break")

2. Go to the next video, see it has three adbreaks (15s, 30s, 45s), though only two are configured (15s, 45s).

![](https://images.sport1.de/imagix/filter2/png/_set=empty/imagix/091ef455-2b91-11e8-87b1-f80f41fc63ce "three ad breaks")

### Environment

- MacBook Pro (15-inch, 2016)
- Mac OS X 10.13.3 (17D102)
- Firefox 60.0b4 (64-bit)
- 8.1.12+commercial_v8-1-12.246.commercial.dc66f9.hlsjs..jwplayer.c9fefd.dai.c24260.freewheel.782b72.googima.001e0e.vast.520a81.jwpsrv.785f4d.gapro.fb7ea6.related.bce080

**Comment by waxidiotic** [comment]
This may be because you are using the same ad break id, `midroll0`, for each playlist item. Can you try making them unique and let me know if that resolves it for you?

Also, in the future, this GitHub issues board is only for the open-source player, which does not support advertising. I'll continue to help you out with this issue here but please contact our [support team](https://support.jwplayer.com/) in the future.

**Comment by Walfisch** [comment]
@waxidiotic Thank you. It does not resolve the issue :(
I opened a question in the jwplayer community, maybe that is the right spot for this issue then.
https://support.jwplayer.com/customer/en/portal/questions/17296898-midroll-advertising-in-playlist-schedule-leaks-into-next-video
If you have more ideas, you are very welcome. If not, you may close this one.

**Comment by waxidiotic** [comment]
@Walfisch This seems to only happen when you don't have an ad with an offset of `'pre'` or `'post'` somewhere in your schedule, which is weird. I will file this as a bug. Thanks for reporting!

**Comment by Walfisch** [comment]
Thank you very much for looking into it.

I get the error even when `pre` and `post` are present, and every key is uniq.
If it is different for you, maybe our versions are different.


    <!doctype html>
    <html lang="en">
    <meta charset="utf-8">
    <title>play</title>

    <script src="jwplayer.js"></script>
    <script>jwplayer.key = "SOME_KEY";</script>

    <div id="player">Loading the player...</div>
    <script>
    jwplayer("player").setup({
        "advertising": {"client": "vast"},
        playlist: [{
            file: "http://clips.vorwaerts-gmbh.de/VfE_html5.mp4",
            adschedule: {
                pre0: {
                    offset: "pre",
                    tag: "http://demo.tremorvideo.com/proddev/vast/vast2Nonlinear.xml"
                },
                post0: {
                    offset: "post",
                    tag: "http://demo.tremorvideo.com/proddev/vast/vast2Nonlinear.xml"
                },
                midroll0: {
                    offset: 30,
                    tag: "http://demo.tremorvideo.com/proddev/vast/vast2Nonlinear.xml"
                }
            }
        }, {
            file: "http://clips.vorwaerts-gmbh.de/VfE_html5.mp4",
            adschedule: {
                pre1: {
                    offset: "pre",
                    tag: "http://demo.tremorvideo.com/proddev/vast/vast2Nonlinear.xml"
                },
                post1: {
                    offset: "post",
                    tag: "http://demo.tremorvideo.com/proddev/vast/vast2Nonlinear.xml"
                },
                midroll1: {
                    offset: 15,
                    tag: "http://demo.tremorvideo.com/proddev/vast/vast2Nonlinear.xml"
                },
                midroll2: {
                    offset: 45,
                    tag: "http://demo.tremorvideo.com/proddev/vast/vast2Nonlinear.xml"
                }
            }
        }]
    });
    </script>

**Comment by waxidiotic** [comment]
@Walfisch You're right, sorry about that. I'll note that in the escalation.

**Comment by Walfisch** [comment]
I can confirm that the Bug is fixed in Version 8.2.2
https://github.com/jwplayer/jwplayer/pull/2799
Thanks @waxidiotic
