### ISSUE TITLE
jw7 play m3u8 in flash mode throw "network error: http status 0"

### ISSUE THREAD

**Issue by klouskingsley** [jwplayer/jwplayer#2819]
### Expected Behavior

just play it and throw no error

### Actual Behavior

throw an error "network error: http status 0"

![image](https://user-images.githubusercontent.com/12490787/38233766-4f3a8bda-374e-11e8-91d6-8136b8a302b2.png)

### Steps to reproduce

1.  open the [demo](http://demo.jwplayer.com/developer-tools/http-stream-tester/?playerversion=7) page
2. set player version: jw player 7
3. input file url : http://vod.mudu.tv/media-join-slice/2v5cwms8mw1bnzh8b22brv7rp.m3u8
4. set render mode: Flash

### Environment

- *hardware | device*
- *operating system | version* windows
- *browser | version* chrome latest
- *JW Player version | url* 7.12.13

**Comment by johnBartos** [comment]
@klouskingsley Your stream played for me, but did not choose flash:

![screen shot 2018-04-03 at 10 48 13 am](https://user-images.githubusercontent.com/5042276/38256718-efe98c7e-372c-11e8-8d61-8c6bc0586119.png)

If you can reproduce the error again, please copy Chrome's developer log and paste it here.

**Comment by robwalch** [comment]
`primary: 'flash'` is no longer an available option in JW Player 8. Flash is only used in 8 players to play HLS on Windows 7 with IE 11 where MSE is not available.

We recommend you do not use it if you are using a version 7 player. The error you are seeing is a result of Flash encountering an error when requesting a segment from your stream. I looked into it and playback work in Flash as long as the site you are on is using SSL (https). Your CDN vod.mudu.tv always does a redirect from http to https when the site and Flash player is running in an insecure environment. That is not supported by Flash or our player. Host on https and everything will be fine, or change how your video is hosted.
