### ISSUE TITLE
Local custom provider support broken in JWPlayer 8.2.x

### ISSUE THREAD

**Issue by tri170391** [jwplayer/jwplayer#2828]
### Expected Behavior

Playback providers regstered to `jwplayer` through `jwplayer.api.registerProvider` and `supports` the current `file` should handle the playback. 

### Actual Behavior

This used to work in `8.1.x` and before but since `8.2.x` is released the player failed to load with error:
```
Error loading player: Failed to load media
```

### Steps to reproduce

1. Register a local playback provider through `jwplayer.api.registerProvider`.
2. Play the video.
3. The player failed to load with the aforementioned error.

### Environment

- x86-64 PC
- Windows 10
- Chrome 65.0.3325.181
- JwPlayer 8.2.2

----------------------------------------------------------------------------------------

I have digged into the issue and find that this is the root cause: https://docs.google.com/document/d/1548315Xpz54IkLUGfnOjq8N_NkWom6NTK8BvUYdF1is/edit

I will attempt to fix this and create a pull request when it's ready.

**Comment by johnBartos** [comment]
@tri170391 We're aware of the issue & working on a fix
