### ISSUE TITLE
Controls not visible / not responding in full screen

### ISSUE THREAD

**Issue by adamopenweb** [jwplayer/jwplayer#2829]
### Expected Behavior

1. When entering full screen mode using Firefox Android, we should see the video controls at the bottom (same as Chrome Android).
2. In Chrome mobile the controls should be responsive to taps.

### Actual Behavior

1. No controls are displayed in Firefox Android.
2. Controls aren't responding in Chrome once full screen in enabled.

### Steps to reproduce

1. Navigate to: https://video.vice.com/de/video/the-chinese-friends/56b4e8162f91349469c7df00?latest=1
2. Play the video.
3. Wait for the advertisment to finish playing.
4. Tap the screen to activate the Video controls.

### Environment

- Nexus 6
- Android 7.1.1
- Firefox 59+ and Chrome 65
- https://video.vice.com/de/video/the-chinese-friends/56b4e8162f91349469c7df00?latest=1

Originally reported:
https://github.com/webcompat/web-bugs/issues/8582

**Comment by robwalch** [comment]
@adamopenweb vice.com controls are customized by the site developers. They are not the controls provided by jwplayer.js (`.vp__controls` sits on top of jwplayer). This is an issue for the website developers at video.vice.com.

I can confirm that our player controls work as expected in Firefox Android and Chrome 65 (Pixel 2 XL Android 8.1.0) here http://content.jwplatform.com/previews/sYKZyjxB-rcY6EcsD
