### ISSUE TITLE
Support Presentation API

### ISSUE THREAD

**Issue by jimmywarting** [jwplayer/jwplayer#2833]
http://w3c.github.io/presentation-api/

> The Presentation API aims to make presentation displays such as projectors, attached monitors, and network-connected TVs available to the Web. It takes into account displays that are attached using wired (HDMI, DVI, or similar) and wireless technologies (Miracast, Chromecast, DLNA, AirPlay, or similar).

**Comment by johnBartos** [comment]
@jimmywarting Very cool API! This probably isn't something that we'd build into the player but it could easily be a plugin. Support looks a bit bare right now too.

**Comment by jimmywarting** [comment]
Yea, i know, it's quite new, but at least you don't have to buy & register your application if you're building a Custom Receiver. Maybe the disadvantage will also be that the media controller on your devices won't be able to control the media only the sender will..?

But it will be easier to customize and we can maybe add the missing features that are disabled

> * YouTube video sources cannot be cast
> * Currently only the default quality will play on the receiver (quality toggling is not supported)
> * Quality API
> * Controls API
> * Multiple-audio tracks
> * Advertising
> * Side-loaded captions in AirPlay

**Comment by robwalch** [comment]
We use Google's JavaScript Cast SDK which is build on top of parts of the presentation API for Chromecast support. We don't have plans for reimplementing that, or integrating with other devices.

For Safari we rely on the Airplay JavaScript API.

Thanks for the feature suggestions. We no longer support YouTube sources. Quality, controls, tracks, captions and ads are good feature requests.
