### ISSUE TITLE
What should i do when something is already casting?

### ISSUE THREAD

**Issue by jimmywarting** [jwplayer/jwplayer#2834]
### Expected Behavior

I'm kind of doing what youtube is doing...
Browsing throught videos and having just one player in a single page application...

![skarmavbild 2018-04-09 kl 21 54 16](https://user-images.githubusercontent.com/1148376/38519521-64e49a2e-3c40-11e8-94b9-8de2f4324073.png)

And if I'm already casting a video to my chromecast then navigating away to select a other video or reloading the page and such i wishes to get the same cast session/playlist so that i can add a new video to the que or start to play right away

### Actual Behavior

When initiating another new player instance with a new video source when already casting something it dose not play that new source but instead lets me control the video that is being casted on to my TV.
Doe the poster for the new source are displayed but it's the wrong one for the current playing video

```js
var playerInstance = jwplayer("myElement");
playerInstance.setup({
  cast: {appid: 'CC1AD845'},
  playlist: [{
    ...
  }]
});
```

What i would like to do is something along:
```js
// 1. creating a player instance
var playerInstance = jwplayer("myElement");
// 2. Wait for ready event so the cast session can sync
// between the casting device and web with  playlist, current
// playing video, poster, seek and what not.
playerInstance.on('ready', (evt) => {
  // 3. get the playlist
  playerInstance.getPlayList()
  // add new video to the que, 
  // or stop playing the current video on the TV
  // or start playing the new video
})
```

### Steps to reproduce

1. Cast a stream
2. Initiating another player instance or reload the page.

I'm using 
jwplayer: 8.2.2
chrome: 65

**Comment by jimmywarting** [comment]
The casting provider isn't loading until I have chosen a source 😕
How is it then suppose to take recontrol?

**Comment by karimMourra** [comment]
Hi @jimmywarting thank you for raising these issues. 
To recap, you would like to submit:
1) a feature request to support queueing playlist items while casting
2) a bug where the wrong poster image is displayed when a player is reloaded and connects to an existing cast session.

please confirm if this is correct

**Comment by jimmywarting** [comment]
Gosh, the issue is so old that i don't remember anymore or isn't relevant any longer

But what i wanted to accomplish was something along the line of:

> a feature request to support queueing playlist items while casting

Yea, but also retrieve the the playlist from a ChromeCast session if one already exist.

the scenario is that you should be able to add items to a playlist in ChromeCast to have them play one after the other. You then turn off your phone for a moment while you are watching some of the content. when you turn on your phone again the browser would normally reload the hole page, so you would need to get the current playlist from chromecast again somehow.

With youtube I can add a stream to the queue with my phone. While my sister is adding something else from her phone to the same playlist (queue). (we basically have the same playlist - synced by the chromecast device)

So my feature request would be something more like:
1. create a player instance. 
2. wait for it to sync with chromecast
3. copy over the playlist from chromecast over the player instance so it's synced so you can see what's up next

> a bug where the wrong poster image is displayed when a player is reloaded and connects to an existing cast session.

I think it's was more the other way around... can't really remember.
It did display the new (correct) poster in my video element. but it was still controlling the old (previous) video source on my ChromeCast

**Comment by karimMourra** [comment]
@jimmywarting gotcha. We are trying a new method of accepting feature requests and bugs, please fill out the following templates and I'll get your requests directly into our product backlog for review. Apologies for the wait on this!

- feature request:
```
# Feature Request Title (Clear and Descriptive)

## Problem Overview
This should be a general overview of the problem you're experiencing. It is important to note that this does not go into the solution you are proposing as that is relegated to a later section.

## Current Solutions or Workarounds
This should describe what current ways exist to get around the problem listed above.

## Proposed solution (optional)
Your idea for how to solve the above problem.

## Examples in the wild (optional)
List some other video players or applications where this feature exists.

## Additional Information (optional)
Anything else that does not fit into the above categories.
```

- bug submissions:
```
### Expected Behavior

*Describe expected behavior*

### Actual Behavior

*Describe actual behavior*

### Steps to reproduce

1.
2.
3.

### Environment

- *hardware | device*
- *operating system | version*
- *browser | version*
- *JW Player version | url*
```
