### ISSUE TITLE
Sharing setup

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#2840]
### Expected Behavior

Sharing options should be more flexible

### Actual Behavior

We use share functionality with playlist/load() methods as lot of our websites are single page apps.
Currently we can only use MediaId to setup correct link which makes this solution not as flexible as we would like it to be. In our system we have id which is different than media id. This is causing problems after next stream is loaded (via playlist or with load() method).

I believe there are few options to sort this out.
- sharing option as an function - it could also take playlistItem as param/media id
- set sharing for individual playlist item - then load() function or next item will have it set correctly

### Steps to reproduce

1. Setup playback with custom share option, which does not relay on mediaid
2. Use load() with new playlist
3. Link to sharing will be wrong

**Comment by artur-michalak** [comment]
@johnBartos is there any chance that you'll do this?

**Comment by artur-michalak** [comment]
Ping again, we're struggling here because our mediaID is not used for url sharing. Maybe we could have any field from playlist as we can store anything there?

**Comment by robwalch** [comment]
@artur-michalak What do you think about having `permalink` included in feeds and used by the sharing plugin?

We have a permalink field in the "Videos" edit section of our dashboard. That usually refers to the "home page" for the video.

So adding `permalink` to the feeds or making this a custom param on your items would give us something that the sharing plugin could use. Then would you want a sharing option to prefer `item.permalink` when available, vs using the current page (default) or `sharing.link` logic with the `MEDIAID` macro.

Another option could be to use `__item_{property}__` macros like we do for ad tags. The value or any item property matching the property in a macro would replace that part of the url.

**Comment by artur-michalak** [comment]
Our domain and sharing model is little bit more complex (different websites, urls and contexts) but permalink will be great solution and it should meet all our needs. I also believe that it'll better that magic replacements.

**Comment by jnatalzia** [comment]
Hi @artur-michalak   !

We are trying a new method of accepting feature requests. If this is still something you'd like to see in the player please fill out the following template and I'll get your request directly into our product backlog for review.

```
# Feature Request Title (Clear and Descriptive)

## Problem Overview
This should be a general overview of the problem you're experiencing. It is important to note that this does not go into the solution you are proposing as that is relegated to a later section.

## Current Solutions or Workarounds
This should describe what current ways exist to get around the problem listed above.

## Proposed solution (optional)
Your idea for how to solve the above problem.

## Examples in the wild (optional)
List some other video players or applications where this feature exists.

## Additional Information (optional)
Anything else that does not fit into the above categories.
```
