### ISSUE TITLE
DVR - Timer freezes 

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#2846]
### Actual Behavior

The timer stops and does not update.

### Steps to reproduce

http://b028.wpc.azureedge.net/80B028/SampleStream/595d6b9a-d98e-4381-86a3-cb93664479c2/b722b983-af65-4bb3-950a-18dded2b7c9b.ism/Manifest(format=m3u8-aapl)

### Environment

- OSX 10.12.6
- Chrome 65
- *JW Player version 8.2.2

**Comment by johnBartos** [comment]
@mtoczko This is intended behavior. https://developer.jwplayer.com/release-notes/jw-player/?id=10024480

`Fixed an issue with live videos causing the position in the control bar to change constantly within a few second range, which negatively impacted the viewer experience.`

This also resolves an existing bug: https://github.com/jwplayer/jwplayer/issues/1382
