### ISSUE TITLE
Subtitles do not work with Chromecast

### ISSUE THREAD

**Issue by codebykenny** [jwplayer/jwplayer#2847]
You can view a running example of this behavior here:
https://kennysmoothx.github.io/jwplayer-test/

![image](https://user-images.githubusercontent.com/6720728/38741438-f1a7357e-3f07-11e8-861c-72a1739f6d7d.png)

### Expected Behavior

Subtitles tracks (VTT) should work with Chromecast according to documentation (https://support.jwplayer.com/customer/portal/articles/1611847)

### Actual Behavior

Instead chromecast session always fails when given a subtitle track.

### Steps to reproduce

Setup player with video & captions track and then cast, you will get an error 100% of the time.

### Environment

https://kennysmoothx.github.io/jwplayer-test/

- JWPlayer 8

This happens with all versions of JWPlayer 8

**Comment by kingzcrown** [comment]
The captions don't show when using Airplay either.

**Comment by kennysmoothx** [comment]
This is still broken.

JWPlayer cast capability is rendered useless for foreign customers and users with multiple locales.

**Comment by jnatalzia** [comment]
Hi @codebykenny do you have a new example behavior link? We just tested internally and successfully got VTT captions to show up when casting. Thanks!

**Comment by festhome** [comment]
Still happening it seems, cant get srt or vtt subtitles to be shown when casting even a simple mp4

Test url: https://elderbre.com/player.html

**Comment by AeonFr** [comment]
I'm experiencing issues with captions and Chromecast as well.

Before casting, listeners on the `.on('captionList')` event return an object like this:

```json
[{"id":"off","label":"Off"},{"id":"default","label":"Español","language":"Español"},{"id":"https://static.filmin.es/resources/subtitles/media/22195/ca_15608_cc.vtt","label":"Catalán","language":"Catalán"}]
```

A few seconds after casting begins, a `captionList` event is triggered with this subtitles tracks data:

```json
[{"id":"off","label":"Off"}]
```

It seems like JWPlayer is not correctly interpreting the `.vtt` files we used to configure it as valid Chromecast subtitle tracks. Which might make sense (subtitles might be in a wrong format for some reason). But... Here's the strange part...

If I cast to other device only audio (Google Nest Mini), and then, without quitting the casting session, I change to Chromecast, I can see the subtitles correctly.

And if I forcefully `setCurrectCaptions` on the player instance after casting has begun, subtitles also appear correctly.

So the bug would be, that for some reason the player thinks it doesn't support VTT files and wipes out the list of available captions, in spite of the fact that they are supported and working.

**Comment by AeonFr** [comment]
I was not able to reproduce the issue mentioned above. Looks like my player config had something that the player didn't liked (not sure what, sorry). After rearranging the code, the issue got fixed.
