### ISSUE TITLE
jwplayer doesn't play video in VAST tag

### ISSUE THREAD

**Issue by rm2k** [jwplayer/jwplayer#2873]
I have jwplayer making a call to `/*vast.xml` and getting `VAST` xml in response, but no video is beging played. I tested the same url at `https://developer.jwplayer.com/tools/ad-tester/` and the ad is played with no complaints.

### Expected Behavior

I expect ` jwplayer` to lauch and player and play the video ad from the VAST tag.

### Actual Behavior

No video playing

jwplayer makes a call to `https://video-ads-apex.rubiconproject.com/apex/assets/testad/forest_vast2.xml` and receive video ad in `VAST` tag but doesn't play.

I tested the same url in `https://developer.jwplayer.com/tools/ad-tester/` and the video loads and play.

### Steps to reproduce

I have my ad served from dfp as follows:

    <script src='https://www.googletagservices.com/tag/js/gpt.js'></script>

    <div id='div-gpt-ad-x-0'>
     <script>
        googletag.cmd.push(function () {
        googletag.defineOutOfPageSlot('/xx/oustream_Video', 'div-gpt-ad-x-0').addService(googletag.pubads());
        googletag.pubads().enableSyncRendering();
        googletag.enableServices();
        googletag.display('div-gpt-ad-x-0');});                        
      </script>
    </div>

Watching the network call on chrome, I can see `jwplayer` initiating a call to the `https://video-ads-apex.rubiconproject.com/apex/assets/testad/forest_vast2.xml` endpoint and getting response in the form of:

    <?xml version="1.0" encoding="UTF-8"?>
    <VAST version="2.0">
      <Ad id="TestAd">
        <InLine>
         <AdSystem>...</AdSystem>
        <AdTitle>VAST 2.0 Linear Ad</AdTitle>
        <Impression></Impression>
       <Creatives>
         <MediaFile delivery="progressive" bitrate="410" width="640" height="360" type="video/mp4"><![CDATA[//**/**/*_640x360_400.mp4]]></MediaFile>
          . . .
     </Creatives>
   </InLine>
 </Ad>
</VAST>

### Environment

- *hardware | device*
- *operating system | version*
- *browser | version*
- *JW Player version | url*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Hi @rm2k,

Please submit to issue to https://support.jwplayer.com/submit-support-case

This is the core player repo. We don't address ads issues here.

It sounds like this issue is not with the ad but with how you are using the player. Support can help with that if you share the page and `jwplayer().setup()` or embed code with them.
