### ISSUE TITLE
autoplay not work on android 

### ISSUE THREAD

**Issue by Ultra7girl** [jwplayer/jwplayer#2874]
Autoplay not working on android.
Is JWPlayer8.2 support autoplay on android?
see example setup: http://myaday.net/c/jw/jw8_demo.php

### Environment

- Android | 7,8
- chrome | 65.0
- JW Player 8.2

here is my setup player.Did i do something wrong?
jwplayer('mediaplay').setup({
    "file": "http://myaday.net/c/jw/1253109.m3u8",
    advertising: { 
        "autoplayadsmuted": true,
        client: "googima",
        schedule: [{offset: "pre",tag: "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=" }]
        },
    "primary": "html5",
    'androidhls': true,
    'hlsjsdefault': true,
    "autostart": true
}
);

**Comment by johnBartos** [comment]
@Ultra7girl Can you try setting `autostartMuted: true` instead of `autostart: true`?

**Comment by dannyfinks** [comment]
@Ultra7girl I cannot reproduce with Chrome 66 on Android. Have you tried with Chrome 66 on Android?

**Comment by Ultra7girl** [comment]
@dannyfinks It's working, thank you for your advice.

**Comment by acidkool1** [comment]
@johnBartos autostartMuted: true works fine but video starts with mute audio.
