### ISSUE TITLE
The captions aren't scaled up during fullscreen playback in iOS devices

### ISSUE THREAD

**Issue by zihzihtw** [jwplayer/jwplayer#2884]
### Expected Behavior

The captions should be scaled up during fullscreen playback.

### Actual Behavior

They aren't scaled up.

### Steps to reproduce

![img_0520](https://user-images.githubusercontent.com/7886453/39519271-af07a6dc-4e38-11e8-801c-63863012b234.PNG)
![img_0521](https://user-images.githubusercontent.com/7886453/39519275-b3408db8-4e38-11e8-954b-99ca65fccc98.PNG)

### Environment

- iPad Pro 10.5 inch
- iOS 11.2.2
- Safari
- 8.2.4

https://developer.jwplayer.com/jw-player/demos/customization/captions-styling/

**Comment by kennysmoothx** [comment]
Yes, we are experiencing this issue as well
