### ISSUE TITLE
Vast doesn't work

### ISSUE THREAD

**Issue by gibigate** [jwplayer/jwplayer#2885]
I compiled 8.3.0 version, setup in page with correct VAST url, but preroll ad doesn't work at all.

my setup:
<script src="/jwplayer/bin-release/jwplayer.js"></script>
            <script>
                const player = jwplayer('kt_player').setup({
                    'image' : "path/to/image",
                    sources: [{
                        file: "path/to/mp4",
                        label: "720"
                      },{
                        file: "path/to/mp4",
                        label: "480",
                        "default": "true"
                      },{
                        file: "path/to/mp4",
                        label: "240p",
                      }],
                      "advertising": {
                        "tag": "path/to/correct/xml",
                        "client": "vast",
                        "vpaidmode": "insecure"
                    },
                });

            </script>

**Comment by johnBartos** [comment]
@gibigate This project (`jwplayer/jwplayer`) does not support ads. Our commercial product does, but you need to buy a license.
