### ISSUE TITLE
Possibility to disable fullscreen through configuration or API

### ISSUE THREAD

**Issue by GitNoise** [jwplayer/jwplayer#2887]
### Expected Behavior

When setting a flag in the configuration or calling the API to disable running the player in full screen, the player should not be able to enter full screen mode. 

This should manifest itself by removing the full screen icon from the UI and removing the possibility to enter full screen using keyboard shortcuts or double clicking/tapping the player.

### Actual Behavior

When double clicking/tapping the player it enters full screen mode. Full screen mode can also be accessed from the UI (and using a keyboard shortcut?).

### Rationale

Sometimes there is information around the player which always is needs to be shown when playing the video. Going to full screen hides this information.

We also have the player in a modal window and or in sidebars. Going to full screen messes up the navigation of the application.

**Comment by robwalch** [comment]
Hi @GitNoise,

Good feature request. Can you please submit it to https://support.jwplayer.com/submit-support-case ?

I like the idea of having an `allowFullscreen` option that you could set globally in the config, and update via `jwplayer().setConfig({ allowFullscreen: false }) // or true`.

**Comment by yonatanmn** [comment]
following.
@robwalch, I would like this behaviour too

**Comment by partyconfetti** [comment]
+1 for yonatanmn's way

**Comment by jnatalzia** [comment]
Hi @GitNoise  !

We are trying a new method of accepting feature requests. If this is still something you'd like to have please fill out the following template and I'll get your request directly into our product backlog for review. Apologies for the wait on this!

```
# Feature Request Title (Clear and Descriptive)

## Problem Overview
This should be a general overview of the problem you're experiencing. It is important to note that this does not go into the solution you are proposing as that is relegated to a later section.

## Current Solutions or Workarounds
This should describe what current ways exist to get around the problem listed above.

## Proposed solution (optional)
Your idea for how to solve the above problem.

## Examples in the wild (optional)
List some other video players or applications where this feature exists.

## Additional Information (optional)
Anything else that does not fit into the above categories.
```

**Comment by darrylgrant** [comment]
Does anyone know if this made it to the feature request stage? Is there a way we can view all feature requests? 

I would also be interested in this. Mainly because we often use audio-only streams, and for them fullscreen mode doesn't do anything other than potentially confuse users. 

I do realise that we could hide the full screen button with CSS or $(".jw-icon-fullscreen").hide(), but I think it would be neater to have an API method to do this.

**Comment by jnatalzia** [comment]
Hi @darrylgrant!

Unfortunately it doesn't look like the reporter filled out the information we were looking for. If you're still interested in this feature and would like to fill out the request template I'd be more than happy to transfer your request to our backlog.

In terms of open feature requests, there isn't a public facing page just yet that tracks this but it's something we're looking to get up and running soon.

Let me know if you have any additional questions, thanks!

**Comment by jnatalzia** [comment]
The wiki has been updated with a list of open feature requests. Thanks so much for the feedback! https://github.com/jwplayer/jwplayer/wiki/Open-Feature-Requests

**Comment by darrylgrant** [comment]
Thanks for that, much appreciated.

**Comment by firewaller** [comment]
+1 would also be nice to do this for the "cast" feature

**Comment by Dima-Astreyko** [comment]
+1
