### ISSUE TITLE
How to create new API?

### ISSUE THREAD

**Issue by wechat361** [jwplayer/jwplayer#2901]
### Expected Behavior

*Describe expected behavior*

### Actual Behavior

*Describe actual behavior*

### Steps to reproduce

我想添加一个新的API，请问如何添加，没有找到入口在哪

### Environment

- *hardware | device*
- *operating system | version*
- *browser | version*
- *JW Player version | url*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Please provide an example of the API methods, events or properties you would like to add or extend.
