### ISSUE TITLE
Can we prefetch ads through player config.

### ISSUE THREAD

**Issue by rahulsinghvuclip** [jwplayer/jwplayer#2905]
----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Hi @rahulsinghvuclip,

This issues list if for questions and feedback regarding the source in this repo. We don't answer ads configuration questions here*. You should check https://support.jwplayer.com/  https://developer.jwplayer.com/

*_Tip: You can pass VAST XML in advertising configs. We also are working on options that would prefetch for you._

**Comment by rahulsingh-kits** [comment]
@robwalch  You have roadmap for this.

**Comment by robwalch** [comment]
@rahulsingh-kits Take a look at the commercial release of v8.4.0-beta.1 https://developer.jwplayer.com/release-notes/jw-player/#ads
