### ISSUE TITLE
Player will show an error while loading with Firefox Quantum 59.0.2 (Linux version)

### ISSUE THREAD

**Issue by slumbering** [jwplayer/jwplayer#2910]
### Expected Behavior

The player load the video and start to play it.

### Actual Behavior

The player show "Error loading player: playable sources found" while loading the video.

### Steps to reproduce

1. Open Firefox Quantum 59.0.2 for Linux Mint 18.3 or Firefox Quantum 60.0 for Linux Ubuntu 16.04.
2. Go to https://developer.jwplayer.com/jw-player/demos/toolbox/adaptive-streaming/

### Environment

- *hardware | device*
- *Linux Mint 18.3 and Ubuntu 16.04*
- *Firefox Quantum 59.0.2 and Firefox Quantum 60.0*
- *JW Player 8.3.0*

**Comment by robwalch** [comment]
Hi @slumbering,

That error means that the browser does not support the type of media that player you are viewing is attempting to play, and no fallback source was provided. I would reach out to Mozilla and ask about support for MSE and HLS in the browser you are testing.
