### ISSUE TITLE
WebVTT captions cue styling doesn't work properly with <font> tag

### ISSUE THREAD

**Issue by garconvacher** [jwplayer/jwplayer#2914]
Hi,
According to this [documentation](https://support.jwplayer.com/articles/captions-styling-reference-for-fcc-compliance), WebVTT can be styled at cue level :

> JW Player supports WebVTT cue positioning and inline styling in all browsers.

Bold, italic and underline tags works fine, positioning is fine too but the `<font>` tag do nothing. Color and size attributes have the global values. 
Did I miss something ?

### Environment

- *JW Player version 8.3.0*

**Comment by garconvacher** [comment]
So...
Styling cues with colors works but the documentation need an update.
This example from the documentation don't work:
```
<font color="#3333CC">Violet, <i>please</i>!</font>
```

Using classes in the vtt file and styling in a css file do the trick:
```
WEBVTT

00:00.000 --> 02:00.000
<c.red>This is red text</c>
```
```
.red {
    color: #FF0000;
}
```

**Comment by robwalch** [comment]
HI @garconvacher,

Please submit feedback for support.jwplayer.com on that site here https://support.jwplayer.com/submit-support-case

Issues submitted here should be specific to this repo.
