### ISSUE TITLE
Camera Events 360 Video

### ISSUE THREAD

**Issue by jobando89** [jwplayer/jwplayer#2920]
Hi,

I understand that there are 360 view getters for latitude and longitude of the camera view based on the issue provided below.
[https://github.com/jwplayer/jwplayer/issues/1885](https://github.com/jwplayer/jwplayer/issues/1885)

However, are there Events for the change of latitude, or longitude that I can tap into? I want to position hotspots in 360 videos and I was wondering if events are implemented for this use case. 

--Joel

**Comment by robwalch** [comment]
Hi @jobando89,

There are not. I recommend you listen for `mousemove` (between `mousedown` and `mouseup`) and `touchmove` DOM events on `window` to poll the getters (we listen to these events before moving the camera. Additional requestAnimationFrame listeners would help make this even more performant.
