### ISSUE TITLE
Remove Default Poster Image

### ISSUE THREAD

**Issue by dcharity** [jwplayer/jwplayer#2925]
Is there a way to remove the default play poster image overlay in JS?

<img width="296" alt="screen shot 2018-05-22 at 6 36 55 pm" src="https://user-images.githubusercontent.com/2429995/40393876-26bbd7a0-5def-11e8-8d85-c62149ded6a7.png">

Thanks
Don

Environment

Pixel C
Android 8.0
Native Android code/Javascript
Latest JWPlayer version

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Hi @dcharity,

The poster is added when you specify an `image` for your playlist item. Remove the `image` property and/or use CSS hide and disable the preview element:

```js
.jw-preview {
    display: none !important;
}
```
