### ISSUE TITLE
360 degree video support

### ISSUE THREAD

**Issue by eye8** [jwplayer/jwplayer#2940]
Hi, I work at an educational institution where we have a [web app](https://vialogues.com/) to support collaborative learning with videos. We are self-hosting the open source version of JWPlayer 8.3.0 because we need to support YouTube and Vimeo with the providers we wrote. Is there any way we can support 360 degree videos in our app? I understand vr.js is not open source at present (#1885). But can the open source version support monoscopic video at least?

Thank you.

**Comment by robwalch** [comment]
Hi @eye8,

You can register custom providers with our commercial product. The vr plugin is in the commercial product.

**Comment by eye8** [comment]
Thanks @robwalch for the reply. We made some changes to the open source JWPlayer core in order to achieve some specific features the stakeholders require. Do you have any documentation or example on how to write custom providers for the commercial player and how to register the custom providers? I need to evaluate how much work will be involved in updating our tech stack in order to migrate to the commercial JWPlayer. Thank you for the help.

**Comment by robwalch** [comment]
Hi @eye8,

Here's an example of a provider:
https://gist.github.com/robwalch/79a54638a3081e8c8bbf651132c9fa9c

The SDK project is a bit out of date, but you can find the above example and example plugins here:
https://github.com/jwplayer/jwplayer-sdks

Plugins are instantiated with player instances and get their own div on top of the player.

**Comment by eye8** [comment]
Thank you @robwalch ! I'll look into these resources.
