### ISSUE TITLE
JWPlayer geting crash on url change of player

### ISSUE THREAD

**Issue by raj9686** [jwplayer/jwplayer#2949]
[See here also](https://stackoverflow.com/questions/50669701/jwplayer-geting-crash-on-url-change-of-player)

> 
Facing problem when changing channel url.

        MainActivity.java
    -----------------------------
    rvChannelList.post(new Runnable() {
        @Override
        public void run() {
            mPlayerView.load(((ChannelListAdapter) rvChannelList.getAdapter()).getPlaylistItems());
        }
    });

     rvChannelList.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
        @Override
        public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
            mPlayerView.playlistItem(position);
        }

        @Override
        public void onNothingSelected(AdapterView<?> arg0) {

        }
    });

    ChannelListAdapter.java
    -----------------------------
    public ChannelListAdapter(Context context) {
    this.context = context;
    channels = Realm.getDefaultInstance().where(Channel.class).findAll();
    channels.addChangeListener(new RealmChangeListener<RealmResults<Channel>>() {
        @Override
        public void onChange(RealmResults<Channel> channels) {
            notifyDataSetChanged();
        }
    });
    for (Channel channel : channels) {
        playlistItems.add(
                new PlaylistItem.Builder()
                        .file(channel.getStreaming_url())
                        .mediaDrmCallback(new HomeActivity.WidevineMediaDrmCallback())
                        .description("")
                        .build());
    }

    }

    public List<PlaylistItem> getPlaylistItems(){
    return playlistItems;
    }

    main_activity.xml
    ----------------------------
    <com.longtailvideo.jwplayer.JWPlayerView
            xmlns:jwp="http://schemas.android.com/apk/lib/com.longtailvideo.jwplayer"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="0.6"
            android:id="@+id/mPlayerView"
            android:layout_margin="20dp"
            app:jw_stretching="fill"
            jwp:jw_autostart="false"/>
FATAL EXCEPTION: main Process: PID: 14627 java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1 at java.util.ArrayList.get(ArrayList.java:310) at com.longtailvideo.jwplayer.c.e$1.onRenderedFirstFrame(SourceFile:323) at com.google.android.exoplayer2.SimpleExoPlayer$ComponentListener.onRenderedFirstFrame(SourceFile:974) at com.google.android.exoplayer2.video.VideoRendererEventListener$EventDispatcher$6.run(SourceFile:209) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5422) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by robwalch** [comment]
Hi @raj9686,

That looks like an issue with the Android SDK. This repo is for our web player. For support see https://support.jwplayer.com/articles/android-and-ios-sdk-reference#do-you-provide-support-for-your-sdk-products
