### ISSUE TITLE
Issue with using cloudfront cookies on video content (e.g hls) with jwplayer.

### ISSUE THREAD

**Issue by Aameer** [jwplayer/jwplayer#2950]
### Expected Behavior

*after adding `withCredentials:true` which sends cloud-front cookies with calls we shouldn't see errors on console as calls are successful*

### Actual Behavior

*Even after the calls are successful console throws Cross domain errors and doesn't proceed* 

### Steps to reproduce

1. Set up cloud-front cookies from your back-end for browser.
2. Try out calling a master index file (used in adaptive streaming) sample content of the master index file (.m3u8) 
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=964000,RESOLUTION=640x360,CODECS="avc1.42001e,mp4a.40.2"
1052_360.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1447000,RESOLUTION=640x360,CODECS="avc1.42001f,mp4a.40.2"
1052_480.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2309000,RESOLUTION=640x360,CODECS="avc1.42001f,mp4a.40.2"
1052_720.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=4174000,RESOLUTION=640x360,CODECS="avc1.420028,mp4a.40.2"
1052_1080.m3u8
```

### Description
I have been trying to use cloudfront cookies with jwplayer. For this test I was using hls content (although we use dash too). So the issue which I noticed is:

When my backend sets up the cloudfront cookies for my browser. Calls which I make from js code has cookies attached with it and hence they are successful but the cookies werent not attached with master index file(.m3u8) which contains information for different versioned index files (again .m3u8) which contain the information for .ts files. But when I tried to open the failed call in new tab it executes successfull as cookies are present on the browser. 

So after checking around I found this issue (https://github.com/jwplayer/jwplayer/issues/1185) which is exactly what I am facing. After going throw link I added the suggested `withCredentials:true` in sources (the format for which I had to dig from jwplayer 8.1.1 source code). Once I did this the master index file call had cookies associated with it and was sucessfully executed. Even though the call was sucessfull I still continue to see Cross domain error.

The error which I see on console is " Hlsjs shutdown Cannot load M3U8: Crossdomain access denied ". 
Even though my cross domain settings are correct as other calls which aren't made by jwplayer execute successfully and I have confirmed this from some video and cloudfront experts from amazon too. On top of that the even the call from jwplayer were successfully executed with 200 status but console still continues to throw the error and doesn't proceed to get particular version index files and fails with error mentioned below. 

### Error 
Failed to load https://cloudfront.mydomain.com/530/video/1052/master_530_1052.m3u8: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'https://mydomain.com' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

Failed to load https://cloudfront.mydomain.com/530/video/1052/master_530_1052.m3u8: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'https://mydomain.com' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

Hlsjs shutdown Cannot load M3U8: Crossdomain access denied 

Note than cookies are being set on .mydomain.com

### Jwplayer support
I had locked some resources and kept a sample test link up for jwplayer support for sometime but it may not be possible now. Raising a ticket here as Jwplayer support guys weren't sure and requested me to do so.

### Environment

- *browser - tested on chrome and firefox*
- *JW Player version - replicated behavior on both 8.1.1 and 8.3.3*

----------------------------------------------------------------------------------------

**Comment by Aameer** [comment]
Hey guys, wanted to check if there was any update on this?. Thanks

**Comment by DonniK** [comment]
Hi @Aameer , could you provide me with the ticket number you used to contact support?

**Comment by robwalch** [comment]
> The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' 

@Aameer that error comes from the browser, not jwplayer. Requests with credentials require specific access control headers. Fixing that issue, with your hosting to allow only your site access, would prevent the browser console error and the hls.js error.

**Comment by Aameer** [comment]
@Donnik case #00059113 and  [ ref:_00Dd0bffv._5000V1BK3M1:ref ]. I am assuming case number is the ticket number.

**Comment by PrimeObjects** [comment]
same issue here! please help.

**Comment by raphaelcangucu** [comment]
Hi, same problem here.
