### ISSUE TITLE
Artifacts in the bottom of the video 

### ISSUE THREAD

**Issue by rauldelperal** [jwplayer/jwplayer#2951]
### Expected Behavior

C21 Live Encoder produces HLS. This HLS format is 100% compatible with the all HLS players, included JWPlayer 7.12.13.

### Actual Behavior

We have detected some video artifacts in the lower part of the video playing a HLS produced by Cires21´s Encoder with JWPlayer 8.3.3. All these artifacts don´t appears in JWPlayer 7.12.13.

### Steps to reproduce

1. https://developer.jwplayer.com/tools/stream-tester/?playerversion=8
2. https://kissfm-cires21-video.secure.footprint.net/hittv/master.m3u8
3. Artifacts appears in the bottom of the video.

### Environment

- *hardware | device* PC
- *operating system | version* Ubuntu 16.04, Ubuntu 18.04. Windows 10
- *browser | version* Chrome Version 66.0.3359.117 (Official Build) (64-bit) 
- *JW Player version | url* 8.3.3 --> https://developer.jwplayer.com/tools/stream-tester/?playerversion=8

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by rauldelperal** [comment]
I have taken a screenshoot:
![image](https://user-images.githubusercontent.com/4376210/40921142-eeb1f608-680e-11e8-9879-4b0e0f0413e5.png)

**Comment by robwalch** [comment]
@johnBartos This may be a ticket for hls.js

**Comment by johnBartos** [comment]
Yeah - @rauldelperal Please open an issue here https://github.com/video-dev/hls.js/issues/new

**Comment by rauldelperal** [comment]
@johnBartos What hls.js does JWplayer 8.3.3 / 8.3.5 implement? I am testing the HLS stream with hls.js-0.8.4 and it works properly, I mean without artifacts in the bottom of the video. Could you check?

hls.js-0.8.4 demo player -- http://streambox.fr/mse/hls.js-0.8.4/demo/
hls stream -- http://kissfm-cires21-video.secure.footprint.net/hittv/bitrate_4.m3u8
