### ISSUE TITLE
Deprecated Error Messages still live in Repo

### ISSUE THREAD

**Issue by karimJWP** [jwplayer/jwplayer#2960]
### Context
We successfully standardized errors and replaced deprecated messages with viewer-friendly messages, but we still have the deprecated message strings in our code base. In some cases they are used to throw errors, which when caught are set as sourceErrors for a standardized error. Though these strings are great for providing context, we can do without them. 

### Expected Behavior
Obsolete error messages are deleted.

### Example messages
'Playlist is not an array'

**Comment by johnBartos** [comment]
We did it!
