### ISSUE TITLE
Remove IE8 support from the vtt parser

### ISSUE THREAD

**Issue by johnBartos** [jwplayer/jwplayer#2962]
Prior art: https://github.com/videojs/vtt.js/pull/22/files

We don't support IE8, but there are specific IE8 compatibility flags. These should be removed.

We can also upgrade to the video-dev fork of vtt.js: https://github.com/video-dev/vtt.js

**Comment by mamaddox** [comment]
Added to internal backlog: [JW8-10711](https://jwplayer.atlassian.net/browse/JW8-10711)
