### ISSUE TITLE
Controls autohide problem in responsive iframe

### ISSUE THREAD

**Issue by eye8** [jwplayer/jwplayer#2965]
### Expected Behavior

The player controls should autohide when the mouse cursor moves out of the video screen.

### Actual Behavior

In a responsive iframe setup, the controls only autohide in the following situations:

* When the cursor remains inactive on the video for a few seconds

* When the cursor moves out of the screen from the top, left, or right

The controls won't autohide after the cursor moves out *from the bottom*.

### Steps to reproduce

1. Go to http://video.tc-library.org/static/player/8.3.0/test/vialogues/iframe.html
2. Play the video
3. Move out your mouse cursor from the bottom of the video
4. Player controls won't autohide

### Environment

- MacBook Pro 2012 model
- macOS HighSierra
- Chrome/Safari/FF
- JWplayer v.8.3.0 self hosted. 

The test page uses the setup example provided at https://support.jwplayer.com/articles/how-to-setup-a-responsive-player

**Comment by waxidiotic** [comment]
Thanks, @eye8. The main issue is that when your mouse leaves the player from the controls while the player is in an iFrame, it is immediately starting to hover over the parent frame, so the player in the iFrame never recognizes the `mouseout` event. We're taking a look to see if we can workaround this and I'll let you know what we find out.

**Comment by eye8** [comment]
Thanks for the quick reply @waxidiotic 

Looking forward to your solution.

**Comment by waxidiotic** [comment]
Resolved in v8.4.2.
