### ISSUE TITLE
Integration of JWplayer with Reactjs

### ISSUE THREAD

**Issue by bluefig99** [jwplayer/jwplayer#2971]
### Expected Behavior

We are unable to integrate the Reactjs with JW player. We are hitting with the following issue:

### Actual Behavior

./src/thirdparty/jwplayer/jwplayer.js
  Line 10:  Unexpected use of 'location'  no-restricted-globals

Search for the keywords to learn more about each error.

Below code is not working:

/* global location */
/*eslint no-restricted-globals: ["off", "location"]*/
import React from 'react';

import bannerPic from "./bannerimage.jpg"
import videoFile from "./sample.mp4"

let jwplayer = require("../src/thirdparty/jwplayer/jwplayer.js")

function Setup(){
    window.jwplayer("myDiv").setup({
        "file": {videoFile},
        "image": {bannerPic},
        "height": 360,
        "width": 640
    });

    return(
        <div>
            <div id="myDiv">This text will be replaced with a player.</div>
        </div>
    );
}

export default Setup;
### Environment

We are using Reactjs + Webpack

- *hardware | device* 
- *operating system | version* => Mac OS
- *browser | version* =>Chrome
- *JW Player version | url* . => 8.3.5

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment]
@bluefig99 Looks like your lint rules aren't compatible with our lint rules. You should ignore `jwplayer.js` in your lint file.

Also, these guys have done a really good job with a JW React plugin: https://github.com/micnews/react-jw-player

**Comment by bluefig99** [comment]
Thanks John for the inputs. I will explore the option to ignore the jwplayer.js in my lint file. I will update the thread with my outcome.

**Comment by bluefig99** [comment]
Thanks John. Fixing linting solved my issue.
