### ISSUE TITLE
Cannot load M3U

### ISSUE THREAD

**Issue by thianekhalipha** [jwplayer/jwplayer#2972]
### Expected Behavior

I set up the the player correctly but cannot load m3u is found as an error . For me it's an CORS ERROR
![image](https://user-images.githubusercontent.com/39198360/41507046-e404dc78-71de-11e8-8980-9e618dd00f35.png)

the same m3u link plays well on  (  http://hlstester.com ) 
### Actual Behavior
the same m3u link plays well on  (  http://hlstester.com ) 
 the .htacces of my server    ( Wordpress )

<IfModule mod_headers.c>
<FilesMatch “\.(ttf|ttc|otf|eot|woff|woff2|font.css|xml|ShockwaveFlash|css|js)$”>
Header set Access-Control-Allow-Origin “*”
</FilesMatch>
</IfModule>
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
AddType application/x-shockwave-flash .swf
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond $1 !^(index\.php|images|robots\.txt|css|xml|flash)
RewriteRule . /index.php [L]
RewriteRule .*\.xml$ index.php [L]   # URL suffix .html
</IfModule>

### Steps to reproduce
MY JWPLAYER configuration

<script type="text/javascript" src="http://content.jwplatform.com/libraries/xjMnEyLI.js"></script>
<div id="mediascpace">last</div>
<script type="text/javascript">
jwplayer("mediascpace").setup({
    file: "http://eu10.acangroup.org:1935/output/asfiyahi.stream/playlist.m3u8",
"logo": {
    "file": "http://baobabvision.com/wp-content/jwplayer/vision.jpg",
    "hide": true,
    "link": "http://baobabvision.com",
    "margin": "10",
    "position": "bottom-left"
  },
  "aspectratio": "16:9",
  "autostart": true,
  "controls": true,
  "displaydescription": true,
  "displaytitle": false,
  "height": 270,
hlshtml: true,
type: "hls",
  "hlshtml": true,
  });
</script>
----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
The first browser error states that there is no ‘Access-Control-Allow-Origin’ header on the resource served from ‘eu10.acangroup.org:1935’. That server needs to set the header, not your website.

**Comment by thianekhalipha** [comment]
So how can you explain that the same link is working in hlstester.net using also jwplayer
