### ISSUE TITLE
audioElement different in 8.x?

### ISSUE THREAD

**Issue by 4getit** [jwplayer/jwplayer#2976]
Hello,

I have videos with low audio volume so for those cases, I always added gain like this:

var audioCtx = new AudioContext();
var source = audioCtx.createMediaElementSource(document.getElementsByTagName('video')[0]);
gainNode = audioCtx.createGain();
source.connect... etc.

This always worked in 7.x and somewhat works in 8.x
With 8.x, it works fine in Chrome & Firefox. But in Safari, the audio becomes distorted and the volume slider doesn't work anymore. 

I assume that with 8.x, createMediaElementSource(document.getElementsByTagName("video")[0]) is no longer the right way to snatch the audio.

Where do I get my audioElement from with 8.x?

**Comment by robwalch** [comment]
The player uses multiple video elements to manage loading and detection of autoplay policy.
On `playlistItem` check `jwplayer().getContainer().getElementsByTagName("video")[0]`.
