### ISSUE TITLE
hls not supported for free?!

### ISSUE THREAD

**Issue by hossamnoaman** [jwplayer/jwplayer#2977]
### Expected Behavior

as i see every where mentioned on jwplayer website hls included in free version .

### Actual Behavior

This video file cannot be played.
(Error Code: 102630)

### Steps to reproduce

1.build player as documentation here mentioned.
2.i put html file into bin-release with the following contents :
`<html>
<head>
<script src="jwplayer.js"></script>
</head>
<body>
<div id="mediaplayer"></div>
    <script>
    jwplayer('mediaplayer').setup({
	  "playlist": [
	    {
	      "sources": [
		{
		  "default": false,
		  "file": "https://xxxxxxxx/hls/stream.m3u8",
		  "label": "0",
		  "type": "hls",
		  "preload": "metadata"
		}
	      ]
	    }
	  ],
	  "primary": "html5",
	  "hlshtml": true
	});
    </script>
</body>
</html>`
3.opened in browser jwplayer.js loaded and controller also nothing else and throw mentioned error above.

### Environment

- linux
- any browser
- jwplayer v8

**Comment by johnBartos** [comment]
@hossamnoaman No, sorry. If you need an Hls player check out Hls.js https://github.com/video-dev/hls.js. We use it in JW and help maintain it.

**Comment by hossamnoaman** [comment]
there is no more free edition of jw player

thanks
