### ISSUE TITLE
Keyboard equivalent for rewind 10 seconds button

### ISSUE THREAD

**Issue by yanyufish** [jwplayer/jwplayer#2982]
### Expected Behavior

Has keyboard equivalent for rewind 10 seconds button

### Actual Behavior

No keyboard equivalent for rewind 10 seconds button

**Comment by robwalch** [comment]
Left Arrow

**Comment by yanyufish** [comment]
Isn't left arrow for 5 seconds?

**Comment by robwalch** [comment]
Hi @yanyufish,

Yes, you can use the left and right arrows to seek back and forth by 5 seconds https://support.jwplayer.com/articles/keyboard-shortcut-reference

If you want additional shortcuts please use JavaScript to implement them yourself. For example:
```js
jwplayer(id).getContainer().addEventListener('keydown', function(event) {
    if (event.shiftKey && event.key === 'ArrowLeft') {
        jwplayer(id).seek(Math.max(0, jwplayer(id).getPosition() - 10));
    }
});
```
