### ISSUE TITLE
IE 11.492 - unable to init jwplayer 7.12.13

### ISSUE THREAD

**Issue by lakshmipq** [jwplayer/jwplayer#2984]
### Expected Behavior
JWplayer should play m3u8 as does chrome 

### Actual Behavior
Player does not come up on IE
SCRIPT5007: : Unable to get property 'jwplayer.volume' of undefined or null reference
jwplayer.js (4,12873)

### Steps to reproduce

1. Put in key and m3u8 file in script below. Also replace the jwplayer.js reference. 
2. Runs fine on chrome and FF
3. IE does not initialize at all. Throws error. IE has local storage enabled.
4. Same issue with mp3 file too.

Note:
I have the same version running in my tapestry web application code which fails to display the player but does not throw any error. So I took the javascript bits out  of my webapp code and made this simple html file which throws an error - which for some reason does not come on the webapp
I also noted that on my webapp, the same javascript calls onReady() in chrome but not on IE.
I am hoping solving this issue on this standalone HTML would lead on to a fix on the webapp.

### Environment

- Intel i7 
- Windows 10
- IE 11.492 
- 7.12.13
[bug_in_ie.zip](https://github.com/jwplayer/jwplayer/files/2150928/bug_in_ie.zip)

**Comment by robwalch** [comment]
Hi @lakshmipq,

For support with v7 please [contact support](https://support.jwplayer.com/submit-support-case). I recommend updating to v8 since we don't have plans to patch 7 for issues with IE 11 or web app compatibility.
