### ISSUE TITLE
Duplicated buttons behaviour 

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#2987]
### Expected Behavior
Display only sharing button as iOS does not support changing qualities with HLS stream.
On other devices it is similar when only one bitrate is available.

### Actual Behavior
Sharing and settings button is displayed. Clicking on settings button does exactly the same as sharing. From user perspective they are redundant. 

### Steps to reproduce

1. Create player with this configuration
```javascript
var player = jwplayer("player1").setup({
        width: '100%',
        "playlist": [{
            "file": "https://svpvod-vh.akamaized.net/i/2015/12/20151222_5678f3250e261_vg01/,1280_720_3500,960_540_1500,640_360_800,480_270_500,.mp4.csmil/master.m3u8"
        }],
        "sharing": {
            "link": "https://www.vgtv.no/video/122738",
        },
        autostart: true,
        "key": "KEY"
    });
```
2. Start video in Safari iOS

### Environment

- *hardware |* iPhone
- *operating system |* iOS 11
- *browser |* Safari
- *JW Player version |* 8.4

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Thanks @artur-michalak,

I'm checking to see if we have an internal improvement ticket for this. It's come up in discussion before, since you logged this last month.
