### ISSUE TITLE
Error loading player: Network error

### ISSUE THREAD

**Issue by jayendra-sharan** [jwplayer/jwplayer#2988]
### Expected Behavior
On clicking video file, jwplayer should get initialised and video should play.

### Actual Behavior
Error loading player: Network error is displayed on the screen, jwplayer's ready event is not fired.
![screen shot 2018-07-06 at 16 49 16](https://user-images.githubusercontent.com/13906878/42376370-91a6ce24-813c-11e8-8281-1f90b8f02cae.png)

### Steps to reproduce

1. Click on the video file
2. On click initialise jwplayer [as described on jwplayer's page].

### Environment
All browsers and all OS.
*JW Player version* - 8.2.4

Actual Error:
`Error: Network error↵    at i (https://myserver.com/jwplayer/v824/jwplayer.js?v=37438999:10:21569)`
This error thrown (Promise Rejected) at the time of initialisation in following code:
`return "function" == typeof i ? i : R.a.html5 && "html5" === o ? R.a.html5 : n.load(o)`
`R.a.html5` Promise is rejected

**Comment by robwalch** [comment]
@jayendra-sharan please update your player to the latest version (currently v8.4.1) and let us know if the issue persists. 8.4 introduces error codes that are helpful in debugging playback issues.

**Comment by robwalch** [comment]
@jayendra-sharan For this issue at the network panel. This means a file required by the player could not be loaded - probably jwplayer.html5.js. If you are self hosting, you need all player js files to be hosted in the same location (make sure `https://myserver.com/jwplayer/v824/jwplayer.html5.js` is being served).

**Comment by mbisht** [comment]
Hi guys,
Actually, I am trying the implement Error loading player: Network error could you guide me, actually very new in jwplayer, This thing I am implementing Network error in Angularjs, can you share the code(how to implement).

**Comment by karimMourra** [comment]
Hi @mbisht , what do you mean by implementing the network error ?
You can override the error messages by using our config's intl block https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/#localization
