### ISSUE TITLE
Want to know about pricing details

### ISSUE THREAD

**Issue by nishadhasan** [jwplayer/jwplayer#3007]
Hello, I am using Vimeo right now. But they are taking too much time to upload the videos from my website to Vimeo. So, I want to move to JWplayer. I want to upload videos directly on JWPlayer video hosting server. It should be fast upload. I am quitting Vimeo just because of their slow upload speed from my website to their server. Also, want to know pricing details. Can anyone please help me with pricing details per months and how much storage & bandwidth will I get? What if the assigned storage and bandwidth finished before the end of the month? Please let me know details about pricing and service. It's urgent for me.

Thanks in advance.

**Comment by waxidiotic** [comment]
Hi there,

For pricing details, please visit our pricing page at https://www.jwplayer.com/pricing and/or contact our sales team at https://www.jwplayer.com/contact-us. They will be able to fill you in with the answers to all of your questions.

Thanks for your interest!
