### ISSUE TITLE
Replace webpack task in Gruntfile with grunt-webpack

### ISSUE THREAD

**Issue by radium-v** [jwplayer/jwplayer#3027]
The grunt task for `webpack` should be replaced with the community-maintained [webpack-contrib/grunt-webpack](https://github.com/webpack-contrib/grunt-webpack).

**Comment by johnBartos** [comment]
@radium-v Why?

**Comment by radium-v** [comment]
@johnBartos It's safer to use a community-supported Grunt plugin to load Webpack than a bespoke implementation. It provides stronger error handling, messaging, and task integration.
