### ISSUE TITLE
Add UglifyJS Plugin to fix Windows builds

### ISSUE THREAD

**Issue by radium-v** [jwplayer/jwplayer#3029]
To fix the `92% chunk asset optimization` bug when building on Windows/Ubuntu WSL, the minification step in Webpack should switch to use `uglifyjs-webpack-plugin` directly.

Reference: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/272#issuecomment-408795912

**Comment by robwalch** [comment]
This is no longer relevant since we now use [webpack 4](https://webpack.js.org/migrate/4/).
