### ISSUE TITLE
Create pattern to mock imported dependencies 

### ISSUE THREAD

**Issue by johnBartos** [jwplayer/jwplayer#3049]
Some modules may import dependencies which alter control flow; for example, `OS.iOS` may be a switch for a different logic branch. However, the `OS` module cannot be mocked because it is part of the closure. Unit testing would benefit from a dependency mocking library

**Comment by mamaddox** [comment]
Added to the internal backlog: [JW8-10710](https://jwplayer.atlassian.net/browse/JW8-10710)
