### ISSUE TITLE
Error #224003 on iOS Safari - "withCredentials" support required

### ISSUE THREAD

**Issue by b-jerome** [jwplayer/jwplayer#3056]
### Expected Behavior

Playing WOWZA stream url on iOS Safari.

### Actual Behavior
 
We have an issue playing our WOWZA stream url on iOS Safari. Error message: "This video cannot be played. Error code: 224003". The error does not appear with iOS Chrome.

Demo page: https://clubbingtv.com/demo.php
 
If we load the stream url directly on iOS Safari and then go back to the demo page the player is working. 

### Steps to reproduce

1. Open demo page on iOS safari https://clubbingtv.com/demo.php (Error #224003)
2. Launch stream url directly on iOS Safari
3. Go backto demo page  https://clubbingtv.com/demo.php (No error)

### Environment

- iPhone/iPad
- latest iOS and iOS 11.4
- Safari only
- JW Player version 8 & 8.5.3

----------------------------------------------------------------------------------------
Thanks for your help.

**Comment by johnBartos** [comment]
@b-jerome I can't access your stream on that page. However, the error seems to imply a problem with your content: https://developer.jwplayer.com/jw-player/docs/developer-guide/api/errors-reference/#224003. This error corresponds to the HTMLMediaElement error code 3: https://developer.mozilla.org/en-US/docs/Web/API/MediaError

**Comment by robwalch** [comment]
Hi b,

This error comes from the browser not being able to decode the stream. That suggests an issue with the media streamed from wowza. You should contact Wowsa with steps to reproduce, and a log from the network panel. The smoking gun would be a network response for a segment of the stream that is invalid (resulting in the video tag throwing an error).

Just now I was able to play your demo on my iPhone with iOS 12 beta 10 without any issue, but that’s likely because the stream is stable at the moment. 

There is no difference in how Safari and Chrome play video on iOS. The fact that it works is most likely because the live stream is no longer serving bad segments.

**Comment by b-jerome** [comment]
Thank you,

I am going to check with Wowza then.

**Comment by b-jerome** [comment]
We talked to the wowza support. According to them, as the stream is working well on iOS safari without going through jwplayer, it is therefore an issue of the player. 

Sound like a ping pong game :\

**Comment by robwalch** [comment]
Hi @b-jerome,

It's working fine in the player now too. The issue needs to be reproducible or at least captured in the network panel or a proxy tool. That's not something we can do with the information provided. What I can tell you is that the browser threw an error, so the same thing would have happened if you played the stream in the browser at the same time. If you see it again please record the network traffic and share it with us and Wowza. I'll be happy to reopen the issue if there is more that we can follow up on.

**Comment by roverradio** [comment]
Seeing same thing on some of our streams here. Just beginning to investigate now.

**Comment by b-jerome** [comment]
Hello,

We still have issue with iOS safari. After some test with swift/simulator/safari  we found that the console return a 403 forbidden from chunklist.m3u8. We talked to the wowza support and here is there answer:


> Mac Hill (Wowza Media Systems, LLC) 
> 
> Oct 1, 8:16 PM MDT 
> 
> Hello B.Jérôme,
> 
> Have you reached out to JW player on this?  I see that the direct link plays as expected.  It appears that JW Player is not passing the same cookie on to the chunklist and chunks as it should be. 
> 

Any idea on how to resolve this ?

**Comment by robwalch** [comment]
Hi @b-jerome,

Did you add `withCredentials` to your playlist item so that the player includes cookies with the stream requests? Is it adding cookies to requests in Chrome, but not to requests made by Safari?

**Comment by b-jerome** [comment]
Hello @robwalch 

Yes i added "withCredentials" as you can see in source code of the demo page 

https://clubbingtv.com/demo.php

And yes it is working well with Chrome iOS.

**Comment by robwalch** [comment]
@b-jerome There shouldn't be any different between iOS Safari and iOS Chrome. iOS Chrome is essentially a Chrome skinned WebKit WebView which behaves for the most part like Safari.

**Comment by b-jerome** [comment]
@robwalch 

Maybe there shouldn't be any difference, but none of our iPhone are able to play the stream with the token enabled and all are working under chrome so there is an issue somewhere.

Well, as it seem there is no solution at this time, we will try with another player maybe we will have better luck.

Thank you anyway ;)

**Comment by robwalch** [comment]
@b-jerome The stream also fails in Safari desktop. The issue is probably that we need to add the  `crossorigin="use-credentials"` attribute to the video element for the cookies to be included.

**Comment by b-jerome** [comment]
@robwalch i am waiting reply from wowza and will test another player, i will keep you updated

Thank you.

**Comment by robwalch** [comment]
Thanks @b-jerome,

Maybe you can put me in touch with your contact Mac offline.

> hand off the m3u8 to the native player instead of inline within their player

I don't know what that means in the context of the web player (this project). If they are referring to native iOS applications, that is outside the scope of this project. The player we're working on here -  jwplayer.js - works in Safari and in WebView(s) on iOS. We are only limited by the capabilities of the browser. If Mac is saying that their streams only work in AVPlayer and not in the browser on iOS, then this kind of stream is not one that can be played in the browser on iOS.

**Comment by suyog-kloojj** [comment]
Is anyone has solution for this issue?

**Comment by BrightSoul** [comment]
I've also stumbled across this issue. If I turn off the "prevent cross site tracking" setting in Safari, then the video is playing fine. 
I think I'm going to solve this via DNS, by configuring a name such as `wowza.clubbing.tv` that will CNAME to the Wowza server host name (`wowzaprod130-i.akamaihd.net` in this example). In my case I'm not using Wowza but AWS CloudFront, so that's feasible. I hope Safari won't see the cookies as cross site at that point.

**Comment by robwalch** [comment]
Thanks for the info @BrightSoul. I'll leave this issue open for comment, but am closing it as it's not an issue that we can address in the player, when the browser is blocking cross-site cookies.
