### ISSUE TITLE
How To This Url Stream On JW Player

### ISSUE THREAD

**Issue by Jenosan97** [jwplayer/jwplayer#3058]
@leandromoreira
http://mhdtvlive.online/delta/airtel.php?c=chutti&e=.m3u8

This link Open on google chrome browser normaly showing on playlist

How To stream Jwplayer On this link

**Comment by leandromoreira** [comment]
Hi @Jenosan97 I'm a devoloper of jwplayer but I tried to play your content at [jwplayer demo's page](http://jsfiddle.net/Lgs0ou8s/2479/) and it shows that your stream server lacks of [CORS http headers](https://enable-cors.org/) therefore it seems that it is not a problem of jwplayer.

You can look at [some issues related to that here](https://github.com/jwplayer/jwplayer/issues?utf8=%E2%9C%93&q=cors) and also [here](https://github.com/clappr/clappr/issues/703).

**Comment by Jenosan97** [comment]
@leandromoreira Not play in this url on jw player how to streming this url
https://ylive28-i.akamaihd.net/hls/live/690704/kbous/playlist.m3u8
