### ISSUE TITLE
Seeking after video has completed always plays from the beginning instead of requested position

### ISSUE THREAD

**Issue by mattcoz** [jwplayer/jwplayer#3066]
### Expected Behavior

After a video has completed, clicking on the seek bar should restart the video at the requested position.

### Actual Behavior

Video restarts from the beginning.

### Steps to reproduce

1. Play any video, can use the stream tester.
2. Let it play to completion, can seek to the end to speed this up.
3. Click anywhere on the seek bar to restart the video.

### Environment

PC
Windows 10
Firefox, Chrome
JW Player 8
https://developer.jwplayer.com/tools/stream-tester/

**Comment by jnatalzia** [comment]
Hi @mattcoz, 

Thank you for the report! We have transferred this issue to our internal backlog and will be prioritizing it alongside our other initiatives. Please let me know if you have any additional requests/questions. Thanks!

**Comment by Fernickk** [comment]
Hello, I'm noticing this behavior continues in version 8.26.0, with https://developer.jwplayer.com/tools/stream-tester/. It seems that once the "watch again" icon appears after the end, the progress bar shows that clicking it would seek to a position, but no matter where it's clicked, it always starts from the beginning.
Using Chrome, the issue happens always. With Firefox, however, opening the page shows a player that doesn't display the "watch again" button, and allows seeking after end. But if you click the Test Stream button, then it reloads and shows the "watch again" at the end, preventing seeking.
I would like to know if the seeking will be allowed once the watch again is displayed, or if I have to click twice on the bar (once to clear the watch again, another to seek where I want).
Also, if the watch again could be removed (leaving the video frozen in the last frame), it would also work for me.

I'm attaching a video showing the behavior on Firefox: no "watch again" and good seeking after end on page load, and "watch again" and bad seeking after end on Test Streams.
[SeekAfterEnd.zip](https://github.com/jwplayer/jwplayer/files/9659024/SeekAfterEnd.zip)

Best regards,
Fernickk
