### ISSUE TITLE
Perpetual Loading Screen when network goes offline (No Error provided)

### ISSUE THREAD

**Issue by andriy-fuzz** [jwplayer/jwplayer#3074]
### Expected Behavior
1. Play any Video
2. Before video has loaded, (while you see a loading icon) disconnect from the Internet. You can do this by checking `offline` in Chrome network tab.
3. I should expect to see an error pop up
*Make sure none of the video has loaded in step 2. If some of the video has loaded, then the Error comes up properly when we go offline*

### Actual Behavior
Instead of step 3, we get a perpetual loading screen per image attached.  The on Error or on setUpError events are not triggered as expected.

![no_internet](https://user-images.githubusercontent.com/43006125/45821980-781d7180-bcb8-11e8-994f-de2c6315e788.png)

### Environment
- this happens on any device although I have been testing mostly with a Macbook and Chrome browser.
- MacOS Sierra 10.13.6
- Chrome Version 69.0.3497.92
- jwplayer Version 8.5.6 **(correction)**

**Comment by dannyfinks** [comment]
Hi @andriy-fuzz can you send a page for us to observe? You mentioned jwplayer version 6.3.1 in your details here, but that is no longer a supported version of jwplayer. Our current version of jwplayer is 8.5.6.

**Comment by andriy-fuzz** [comment]
Hey @dannyfinks! There was confusion on my part. The jwplayer version is actually **8.5.6**. Below are the two relevant errors the get **ERR_INTERNET_DISCONNECTED** which is expected but then the `jwplayer().on('setupError')` or `jwplayer().on('error') do not get triggered and video goes in to perpetual loading.

I do not have a public facing page for you to observe at the moment unfortunately. Our features are still being built and need authorization to access. 
` http://jwpltx.com/v1/jwplayer6/ping.gif?h=-1342514232&e=s&n=3671364708091451&aid=F9Yaqok0Eeil4oIQ9XF_2Q&at=1&c=-1&ccp=0&cp=0&d=1&eb=0&ed=6&emi=1k0486d1rql9&i=0&lid=5apj79s53vox&lsa=read&mt=1&pbd=1&pbr=1&pgi=1mwr0th15i0b&ph=1&pid=mL2s96Ls&pii=0&pl=1000&plc=1&pli=x9igt1tc0taf&pp=hlsjs&prc=1&ps=4&pss=1&pt=Peloton%20%C2%AE%7C%20Members&pu=http%3A%2F%2Flocal-members.onepeloton.com%3A1337%2Fclasses%2Fplayer%2Faab7254c5cc545fcaec532013811b38e&pv=8.5.6&pyc=1&s=0&sdk=0&stc=2&tv=3.4.0&tvs=0&vb=1&vi=1&vl=49&wd=1465&abm=1&bwe=34825&cct=0&drm=0&ff=1610&l=4&lng=en&mk=hls&mu=https%3A%2F%2Fsecurevod-vh.akamaihd.net%2Fi%2Fvod%2Fbike%2F09-2018%2F09202018-matt-8am%2F09202018-matt-8am_%2C2%2C4%2C6%2C8%2C13%2C20%2C30%2C60%2C00k.mp4.csmil%2Fmaster.m3u8%3Fhdnea%3Dst%253D1537452917~exp%253D1537460117~acl%253D%252F*~hmac%253Da9f97a2d0d531a3f6c37cd536755097c59eb8d309280be5f027b2f072ac70377&pd=2&pdr=http%3A%2F%2Flocal-members.onepeloton.com%3A1337%2Fclasses&pr=2&q=32&qcr=initial%20choice&sbr=6316&sp=0&tb=10&tt=0&vd=2848&vh=1080&vs=5&vw=1920&sa=1537452919941 net::ERR_INTERNET_DISCONNECTED`

`https://securevod-vh.akamaihd.net/i/vod/bike/09-2018/09202018-matt-8am/09202018-matt-8am_,2,4,6,8,13,20,30,60,00k.mp4.csmil/segment2_7_av.ts?null=0 net::ERR_INTERNET_DISCONNECTED`

**Comment by waxidiotic** [comment]
Hi @andriy-fuzz,

Are you still experiencing this behavior? If so, is it now possible to supply a page url for us to reproduce the behavior on?
