### ISSUE TITLE
Video playback and audio flag on Samsung Internet

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#3085]
### Expected Behavior

Playing videos on Samsung Internet browser should not have audio flag as it forces controlbar to be always displayed.

### Actual Behavior

JW recognizes hls video stream as audio thus adds jw-flag-media-audio.
![image](https://user-images.githubusercontent.com/2443904/46193188-90ffd580-c2fd-11e8-9060-5707d4197fe8.png)

### Steps to reproduce

1. Load example
```javascript
jwplayer('player').setup({
                width: 320,
                height: 160,
                key: "KEY",
                playlist: [{
                    "id": 122059,
                    "image": "https://imbo.vgtv.no/users/vgtv/images/a449730deebf99606df0e1268a6a9bd0.jpg?t[]=680q80",
                    "sources": [{
                        "default": true,
                        "file": "https://svpvod-vh.akamaized.net/i/2015/12/20151207_5665273cdac6e_vg01/,1280_720_3500,960_540_1500,640_360_800,480_270_500,.mp4.csmil/master.m3u8",
                        "type": "hls",
                        "label": "0",
                        "preload": "metadata"
                    }
                }]
            });
```
### Environment

- *hardware | Samsung Galaxy S9*
- *operating system | Android 8*
- *browser | Samsung internet 7.4*
- *JW Player version | 8.4.6 8.5.6*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Thanks @artur-michalak!

This is likely an issue with html5.js and how or when the Samsung Browser (pretty old Android WebKit) reports `video.videoWidth` and `video.videoHeight`.

As soon as the video tag reports width and height we can confirm that the stream does or does not contain a video track:

https://github.com/jwplayer/jwplayer/commit/1394dcf47049ec2383a1bc2fbafce4759d3024ec#diff-516afba75eaadc497dca75d8c83b0fe6R737

However it's possible we exit here first, or something else prevents us from correctly setting the type: 

https://github.com/jwplayer/jwplayer/commit/1394dcf47049ec2383a1bc2fbafce4759d3024ec#diff-516afba75eaadc497dca75d8c83b0fe6R238

**Comment by artur-michalak** [comment]
I'm not big fan of Samsung internet but the traffic it generates is.. significant. Have a look on our stats (i cut numbers, but it shows a scale; it's more than IE + Edge combined)
![image](https://user-images.githubusercontent.com/2443904/46796473-1b5c2680-cd4d-11e8-94b1-d1b0b9b1390d.png)

What are your plans for fixing this?

**Comment by robwalch** [comment]
@artur-michalak The issue doesn't block playback and the numbers we see network wide put Android Webkit under IE11. That puts it on our chopping block in terms of test and development resources.
