### ISSUE TITLE
Async loading jwplayer library

### ISSUE THREAD

**Issue by pdufour** [jwplayer/jwplayer#3130]
### Expected Behavior

Jwplayre should be able to embedded via an async fashion. This can be beneficial for instance if the video is not the top priority on the page, and it can load at a lower priority than other scripts. Things in the critical request chain https://developers.google.com/web/tools/lighthouse/audits/critical-request-chains impact performance a lot by loading these scripts before others.

### Actual Behavior

If you have the following code:
````
<script async src="//content.jwplatform.com/libraries/IDzF9Zmk.js"></script>
````

It's impossible to use because when you try to later use `jwplayer` it could not have loaded yet. Things like google tag manager handle this by defining a variable beforehand and then once the script loads it checks that variable existence and clears all the values on it. GTM probably describes it better https://developers.google.com/tag-manager/devguide#async.

You could have for instance

````
jwplayer.push(function(jwplayer) {
// normal jwplayer object
});
````

This would allow you to have this code run once the library loads without knowing when it will be available.

**Comment by NKjoep** [comment]
I completely agree. 
JS and especially the browser env is async by default and libraries should follow the pattern.

It would be very useful to have an event (or a callback at least) that notifies us when the player is ready to go.

**Comment by karimMourra** [comment]
@NKjoep would the on('ready') callback help with this ?

**Comment by NKjoep** [comment]
Not really. The goal is to load the library programmatically without having to link it in the `<head>` of the page.

This is useful with dynamic web applications where we want to load the needed libraries on demand.

To be clear, what you are suggesting @karimMourra requires the window.jwplayer to already available:

```js
window.jwPlayer.on('ready', function () { console.log('now you can use the player') });
```

So this issue is open because we want to be able to inject the remote script AFTER the page has been loaded (and in any other time when needed) and be notified when the window.jpPlayer is ready.

```js
function videoReady() { console.log('now you can use jwplayer'); }

// async example 1
customLoadRemoteScript('https://content.jwplatform.com/libraries/IDzF9Zmk.js?callback=videoReady')

//asyc example 2
window.addEventListener('jwPlayer.ready', videoReady)

//async example 3
see the first comment in this thread
```

**Comment by robwalch** [comment]
@NKjoep You can use `script.onload`, or UMD loader like require.js. `jwplayer` is defined on load.
