### ISSUE TITLE
Live stream with DVR is played with 30s delay

### ISSUE THREAD

**Issue by konradpietrzkiewicz** [jwplayer/jwplayer#3135]
### Expected Behavior

JW Player play live video without 30s buffer on DVR videos

### Actual Behavior

Live video is played with ~30s delay

### Steps to reproduce

1. go to https://developer.jwplayer.com/tools/stream-tester/
2. set any live dvr video
3. type in console jwplayer().getPosition()
4. live position in video is around 30s behind live edge

### Environment

- PC / chrome
- Windows 10
- Version 69.0.3497.100
- 8.5.6

Our use case is sports events using low latency live streaming (2-3s latency streams with HLS CMAF 1s chunks) with DVR. 
Playback is working fine when we don't use DVR window (we can keep around 3s latency on video). Though we would really like to have DVR on those events and in this case JWPlayer starts video with 25-30s latency and when user click 'live' button she/he is also seeked to position 30s behind live.

Right now we plan to do a nasty workaround:
on playback start:
```
jwplayer().on('play', function(e) { jwplayer().seek(-1) })
```

and remove live button from DOM/CSS and replace it with our own which will trigger:

```
jwplayer().seek(-1);
```

Is there any option we can start live DVR video with live edge without a buffer? Or is there a possibility to add setup option 'low-latency mode' which would disable this buffer.

**Comment by mtoczko** [comment]
Use parameter (default: 25s): 
```
dvrSeekLimit: 5
```
Limit is 5s, you can change in:
https://github.com/jwplayer/jwplayer/blob/6df9d3e46981f23f99525d51c60e4a65babe9c33/src/js/playlist/item.js#L31-32

Pozdrawiam

@johnBartos It is possibles to set own config in hlsjs provider?

**Comment by mtoczko** [comment]
provider.hlsjs.js have default config. But you can't change the settings.

```
liveSyncDuration: 25,
```
(liveSyncDuration - dvrSeekLimit = 20s) 

If it is ASAP, I can help you.

**Comment by johnBartos** [comment]
Hi @konradpietrzkiewicz, apologies for letting this slip by. Thanks for stepping in @mtoczko, your analysis is correct - this can be configured in Hls.js via `liveSyncDuration` but we don't expose it in JW. `dvrSeekLimit` doesn't actually have any bearing on how much Hls.js buffers before starting playback.

> It is possibles to set own config in hlsjs provider?

No, but maybe not *yet*. Let me talk to the team first before saying whether we will/won't make this possible. I personally think its a good idea but there may be other reasons I haven't considered.

**Comment by mtoczko** [comment]
> No, but maybe not _yet_. Let me talk to the team first before saying whether we will/won't make this possible. I personally think its a good idea but there may be other reasons I haven't considered.

@johnBartos Do you have any news?

**Comment by jnatalzia** [comment]
Hi @mtoczko,

We have groomed a ticket in our internal backlog for this change. Unless you have additional requests for this, I'm going to mark this ticket as answered. I'm attaching this github issue to our internal ticket so we can update you in the event it is prioritized.

Really appreciate the input!

**Comment by mtoczko** [comment]
Hi @jnatalzia 
I see a cool solution from the demo http://demo.jwplayer.com/lhls/
```
jwplayer('player').setup(config).on('providerPlayer', function (_ref) {
    var hlsjs = _ref.hlsjs;
```

I'm waiting for this functionality in a stable version

**Comment by jnatalzia** [comment]
I'll be sure to provide an update as that ticket moves through our processes!

**Comment by haakonnessjoen** [comment]
Any progress?

**Comment by robwalch** [comment]
@haakonnessjoen,

As of v8.12 JW Player supports the `liveSyncDuration` config option. You can also set these hls.js options in a `hlsjsConfig` block:
```
        'liveSyncDuration',
        'liveSyncDurationCount',
        'liveMaxLatencyDuration',
        'liveMaxLatencyDurationCount',
        'liveBackBufferLength',
        'loader',
        'pLoader',
        'fLoader',
        'debug'
```
