### ISSUE TITLE
JSFiddle demo not working

### ISSUE THREAD

**Issue by sedubois** [jwplayer/jwplayer#3164]
### Expected Behavior

The README contains a link to a [JSFiddle demo](https://jsfiddle.net/Lgs0ou8s/683/) which should render a functional JWPlayer video.

### Actual Behavior

The video is not working, it just shows a black screen (NB: it has been working at some point yesterday). This demo is quite useful for those who do not yet have an account yet and need to try out JWPlayer quickly.

<img width="1430" alt="screenshot 2018-11-02 at 11 28 18" src="https://user-images.githubusercontent.com/4217871/47906668-6ec81d00-de92-11e8-8aed-3d890e37cb29.png">

### Steps to reproduce

1. visit https://jsfiddle.net/Lgs0ou8s/683/
2. observe that the panel in the bottom right just shows a black rectangle

### Environment

- macOS 10.14
- Firefox 63.0 and Chrome 70.0.3538.77 (Official Build) (64-bit)

**Comment by johnBartos** [comment]
@sedubois Thanks for the report! Very strange, we'll get it resolved asap. Glad that you find the demo useful.

**Comment by johnBartos** [comment]
Ah so we killed that player because people were stealing it. We'll remove the fiddle link from the page. This is why we can't have nice things.

**Comment by robwalch** [comment]
@sedubois I had to disable this player library because it was being used on unlicensed sites. Thanks for the report. We'll update the README and the fiddle.

You should not use that js URL, you should create your own account on jwplayer.com to get a library url of your own, or build this project for non-commercial use.

**Comment by robwalch** [comment]
@johnBartos thanks for removing the deprecated demo.

**Comment by sedubois** [comment]
Thanks for the info @robWalsh and @johnBartos. However I think the solution should just be to restrict that player to only run within jwplayer’s own domain, that should be possible right?

Right now there’s no way to try out JWPlayer before actually paying, which is really strange. I would just like the demos on the jwplayer to be interactive so that I can see the range of possibilities.

Concrète example:
I want to see how JWPlayer behaves when playing pure audio, especially from an iOS device. I just don’t know any way to check that right now without paying.

**Comment by johnBartos** [comment]
>Right now there’s no way to try out JWPlayer before actually paying, which is really strange.

Stay tuned, we have something coming up to address this 😉

**Comment by sedubois** [comment]
Also if that player has been used externally it might be just because of confusion? Before reading all the documentation and understanding JWPlayer’s licensing system, I didn’t understand either that this URL could only be used in the context of the JSFiddle. I thought it was just a standard CDN URL for the open-source version of JWPlayer, with restricted features (that’s what the README suggests after all). I actually tried at some point to see what happened when loading that script from my localhost in order to see how it integrates with my framework.

So something as simple as adding a comment in the fiddle like “do not copy this player URL, it can only be used in this JSFiddle” could do the trick too.
