### ISSUE TITLE
Incompatible with latest Node

### ISSUE THREAD

**Issue by sedubois** [jwplayer/jwplayer#3165]
### Expected Behavior

It should be possible to clone the repo and execute `yarn`, even on a system with the latest Node LTS (Node 10).

### Actual Behavior

Throws `error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.12.0"`.

### Steps to reproduce

1. `git clone https://github.com/jwplayer/jwplayer` && cd jwplayer
2. `yarn`

### Environment

- macOS 10.14
- Node 10.12.0
- yarn 1.10.1

**Comment by johnBartos** [comment]
@sedubois You need to run `yarn --ignore-engines` until all of our child dependencies support Node 10. Everything works fine. We have control over our direct dependencies, but not child ones. You can also downgrade node.
