### ISSUE TITLE
Is there an option to force the player to start playing the first segment?

### ISSUE THREAD

**Issue by Er-rchydy** [jwplayer/jwplayer#3175]
I would like to ask about HLS live streaming, if there are a way to force the player to download and play the first segment instead of the last one. 
if the `m3u8` playlist has `1.ts, 2.ts ...... 6.ts`, the player always download and play `6.ts` or `5.ts`. is there an option to force the player to start from the first segment, i don't mind about the latency.
thanks

**Comment by waxidiotic** [comment]
Hi @Er-rchydy - our apologies in taking so long in responding. Are you still experiencing this issue? If so, can you let me know the URL of the stream you are seeing this behavior on?

**Comment by johnBartos** [comment]
@Er-rchydy We use Hls.js internally, and default it to start 3 segments from the end of the playlist. Can you try seeking to `0` when the stream starts?
