### ISSUE TITLE
360 video showing black screen when play on android phone

### ISSUE THREAD

**Issue by vivekinv8** [jwplayer/jwplayer#3184]
### Expected Behavior
Video should be play on android mobile phone, while it is playing on iPhone.

### Actual Behavior
I am getting sound of video with black screen. I had tried your demo page as well.
Here is the demo link:
https://developer.jwplayer.com/jw-player/demos/innovation/360-video/

### Steps to reproduce
1. open this link https://developer.jwplayer.com/jw-player/demos/innovation/360-video/ to your android mobile phone.
2. You can see black screen but video is playing.
3. Also you can hear sound

Please help me.

Thanks in advance.

**Comment by dannyfinks** [comment]
@vivekinv8 we've recently investigated this issue with another VR video and have found that this is a redirect issue with mp4 360 video streams on the Chrome browser. We have filed a bug for this that you can find here https://bugs.chromium.org/p/chromium/issues/detail?id=902569. This does not happen with m3u8 assets so thank you for bringing this to my attention as I will have that demo get updated to use a more appropriate asset unless the Chromium team's fix is made in a future chrome version. Thanks!

**Comment by lebow01** [comment]
you can try seting  autostart: "false",

**Comment by waxidiotic** [comment]
Hi @vivekinv8,

Are you still experiencing this behavior? I tried that demo link you provided in Chrome on an Android phone and it played both the 360 video and audio successfully.

If you are still experiencing this behavior, please let me know the following:

* Browser, including version
* Android version
* Make and model of the device you are using.

Thanks!
