### ISSUE TITLE
chrome ios device can't load

### ISSUE THREAD

**Issue by lebow01** [jwplayer/jwplayer#3222]
![image](https://user-images.githubusercontent.com/23068980/49911551-cca04980-fec1-11e8-8ad0-385a44852187.png)

i don‘t know why

**Comment by lebow01** [comment]
https://developer.jwplayer.com/jw-player/demos/toolbox/hls-aes-token/

**Comment by lebow01** [comment]
![image](https://user-images.githubusercontent.com/23068980/49911663-3b7da280-fec2-11e8-9249-fe0f2eef57c4.png)

**Comment by imarsv** [comment]
Have same issue. aestoken does not works in chrome on iPhone.

**Comment by robwalch** [comment]
The `102630` error indicated that the media is not playable in the current browser regardless of what you set the user-agent to.

**Comment by iamaamir** [comment]
i am getting the same issue on ipad otherwise its working fine
