### ISSUE TITLE
The custom text in the right-click menu is not shown

### ISSUE THREAD

**Issue by gabriel-esqueda** [jwplayer/jwplayer#3228]
### Expected Behavior

_The custom text in the right-click menu should be displayed when it is configured_

### Actual Behavior

_The custom text is not shown_

### Steps to reproduce

1. _Go to https://developer.jwplayer.com/tools/player-event-inspector_
2. _Add 'abouttext' parameter in the setup_

### Environment

- _MacOS Mojave 10.14.2_
- _Chrome 71.0.3578.98_
- _JW Player 8.6.3_

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by jnatalzia** [comment]
Hi @gabriel-esqueda, I am seeing this working properly in the latest version of the player (8.8.5). Please upgrade and let me know if you are still having issues, thanks!

**Comment by gabriel-esqueda** [comment]
Hi @jnatalzia, I confirm you that is working in the latest version. Thanks!
