### ISSUE TITLE
There is no cardboard icon button on iphone safari when playing 360 VR video. (jwplayer8)

### ISSUE THREAD

**Issue by chenpeiqing1231** [jwplayer/jwplayer#3231]
1.open this link by iphone safari browser. https://developer.jwplayer.com/jw-player/demos/innovation/360-video/
2. you will see there is no cardboard icon button to toggle VR mode, but android phone has it.

### Environment

- *ipone6s* 
- *ios12*
- *safari*
- *jwplayer8 | https://developer.jwplayer.com/jw-player/demos/innovation/360-video/*

----------------------------------------------------------------------------------------
is any config can fix the issues? if can not fix the issues?could you explanation why?

**Comment by robwalch** [comment]
VR mode (the cardboard icon) depends on the WebVR API which is not supported on iOS https://caniuse.com/#feat=webvr
