### ISSUE TITLE
Apple Mobile Safari for iOS can not play 360 VR video in fullscreen.(jwplayer8)

### ISSUE THREAD

**Issue by chenpeiqing1231** [jwplayer/jwplayer#3232]
### Steps to reproduce

1.open this link https://developer.jwplayer.com/jw-player/demos/innovation/360-video/ by iphone safari.
2.clike the full screen button
3.you will see the black screen.

### Environment

- *iphone 6s*
- *ios12*
- *safari*
- *jwplayer8*

----------------------------------------------------------------------------------------

**Comment by robwalch** [comment]
Thanks @chenpeiqing1231,

You should see the video in iOS fullscreen, just not mapped to a 3D sphere because iOS fullscreen displays the entire video. It's only very recently that Apple allows for DOM elements other than the video tag to be displayed in fullscreen mode on iPad (not yet for iPhone).
