### ISSUE TITLE
Jwplayer switch playlist error

### ISSUE THREAD

**Issue by FintinaMadalinSGM** [jwplayer/jwplayer#3239]
### Expected Behavior

When switching to the new playlist the source flagged with "default" true is not played instead is plaing the first one and the quality selector is not generated from the new playlist.

### Actual Behavior

When switching the playlist play the source flagged with default true and generate the quality selector

JwPlayer version 8.2.3
----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
The player selects the first supported source in the current playlist item. `default` is ignored. Sort your sources in your preferred order (with "default" first) to get the behavior you are looking for.

**Comment by FintinaMadalinSGM** [comment]
Thank you!

**Comment by robwalch** [comment]
@FintinaMadalinSGM Here's a little more info I found after digging deeper. These are the remaining references to `Source['default']`:

https://github.com/jwplayer/jwplayer/blob/v8.7.3/src/js/playlist/source.js#L20
https://github.com/jwplayer/jwplayer/blob/v8.7.3/src/js/providers/html5.js#L406

`Source['default']` is used by our Flash and HTML5 providers when multiple mp4 sources are used as quality levels. The default mp4 will be chosen as a quality level if the player has not already played a particular quality with a label that matches one of the qualities. The last quality "label" selected by the user or played by the player will take higher priority than `Source['default']` for mp4 source quality levels.
