### ISSUE TITLE
IE11 compatibility environment detection - agent parameter is undefined or null

### ISSUE THREAD

**Issue by slengyel-lnx** [jwplayer/jwplayer#3242]
### Expected Behavior

The player should load with no error using IE11 (Windows 10)

### Actual Behavior

Exception is thrown because navigator.userAgent is null or empty in certain cases.
This happens when the standalone script is injected at runtime. The webpage where the error happens is and Angular JS app (closed for external users).

### Steps to reproduce

1. Inject minified jwplayer source at runtime (e.g. via document.createScript)
2. Initialize the player // jwplayer(node).setup({})
3. Exception might be thrown.

![selection_177](https://user-images.githubusercontent.com/34274270/50884244-fda56880-13f2-11e9-9f2f-987d9c58beaf.png)

![selection_178](https://user-images.githubusercontent.com/34274270/50884280-1f9eeb00-13f3-11e9-8814-1d095146d4db.png)

I know that you might not be able to reproduce the issue (it might be caused by some vendor script used within the app). The desired action would be to make the environment detection fail safe in case the agent string is null or empty.

### Environment

- Acer vn7-712g
- Windows 10
- Internet Explorer 11
- 8.0.13+commercial_v8-0-13.223 / standalone (self hosted)

**Comment by robwalch** [comment]
@slengyel-lnx do you know which vendor script would be clearing userAgent? If we can reproduce the issue, it will help make the case for addressing it.

**Comment by slengyel-lnx** [comment]
@robwalch unfortunately I don't know, did not have the time to check them all. As a temporary solution I've added an if condition to check the agent param before calling indexOf (did all of it in the minified jw source).

Some vendors which might cause the issue are:
* angular 1.3.20
* jquery 2.2.4
* highcharts
* jquery-file-upload
* moment js
* html2canvas
* etc

Honestly I don't know which of the vendor was causing the userAgent clearing. The best I know it is supposed to be a constant.

**Comment by robwalch** [comment]
@slengyel-lnx any chance you could share package.json and an html page that sets up the player with this issue in IE11? If I can reproduce it I will look into providing a patch.

**Comment by slengyel-lnx** [comment]
@robwalch unfortunately there is no package.json (gulp + bower is used for the angular 1 app).

The good news is that the issue no longer effects in v8.7.5, since we upgraded from 8.0.13

![image 2](https://user-images.githubusercontent.com/34274270/52847512-14875b00-3115-11e9-9ddc-f675047bf243.png)

This time we get the above error when playback starts, but the player itself is functional.

The issue can be closed from our side.

**Comment by robwalch** [comment]
Thank you. For that issue share your config. The event handler throwing an exception is either a plugin, or a callback in you app.
