### ISSUE TITLE
Captions Styling in settings menu

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#3248]
I think it would be a good idea to add Captions Styling in the settings menu.
Like it is in the youtube player. And adding font size controls (50%, 75%, 100%, 125,% 150%, 175%, 200%)

**Comment by zetagame** [comment]
In the meantime, you can style captions using the `.jw-text-track-cue` class via CSS.

**Comment by jnatalzia** [comment]
Hi @mtoczko !

We've recently implemented a new template for feature requests. If you could please fill out the following we can transfer to our internal backlog and get it into the hands of our product team. Thanks so much!

```
# Feature Request Title (Clear and Descriptive)

## Problem Overview
This should be a general overview of the problem you're experiencing. It is important to note that this does not go into the solution you are proposing as that is relegated to a later section.

## Current Solutions or Workarounds
This should describe what current ways exist to get around the problem listed above.

## Proposed solution (optional)
Your idea for how to solve the above problem.

## Examples in the wild (optional)
List some other video players or applications where this feature exists.

## Additional Information (optional)
Anything else that does not fit into the above categories.
```

**Comment by mtoczko** [comment]
# Feature Request Title (Clear and Descriptive)
Captions Styling in settings menu

## Problem Overview
There is no possibility to set up yourself captions style (e.g. font size, color, background)
Disable person need bigger fonts with better contrast e.g. (fontSize: 200%, color: Yellow).
For not disable person there is no needed and disturb watching content.
## Current Solutions or Workarounds
Today we can do only some changes in API.
End customer haven't got any possibility to do that kind of changes in player.
https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/#captions

## Examples in the wild (optional)
THEOplayer - https://demo.theoplayer.com/closed-captions-subtitles
Bitmovin - https://bitmovin.com/demos/caption-styling

**Comment by mtoczko** [comment]
Hi @jnatalzia 
I got a response from support.

> The engineers told me that they are working on adding this feature in the future (Q2 or Q3). 

 You can confirm that?

**Comment by aliciahurst** [comment]
Hi @mtoczko I'm the product manager of the web player. Thanks for submitting this request, apologies it's going to take us longer than expected to deliver on this, but unfortunately it's not going to be available by that timeline. We'll let you know when it's ready, but in the meantime, our javascript API allow you to build a captions styling menu pretty easily, my favorite example of which is PBS's: 
* https://www.pbs.org/video/grit-9b9uzj/
* https://developer.jwplayer.com/jw-player/demos/customization/captions-styling/
* https://developer.jwplayer.com/jw-player/docs/javascript-api-reference/#jwplayersetcaptionsstyles

**Comment by mtoczko** [comment]
Hi @aliciahurst 
Thank you for your answer.
I know these pages, they add nothing.
Are you already planning work on it? Because I've been getting the same links for a year...

**Comment by aliciahurst** [comment]
@mtoczko we're going to do our best to implement this in Q4 of this year. Stay tuned, thanks again for your patience.

**Comment by jnatalzia** [comment]
Hi @mtoczko, as per our issue triage process, I've moved your issue to our `Open Feature Request` section in our wiki now that we have internal tracking around this. You can follow along here for any updates: https://github.com/jwplayer/jwplayer/wiki/Open-Feature-Requests

Thank you again for the submission!
