### ISSUE TITLE
Document lack of hsl and dash support of free player

### ISSUE THREAD

**Issue by augusto** [jwplayer/jwplayer#3253]
I was wondering if you would accept a pull request to document that HLS and DASH are not supported on the non-commercial version of the player. Just a few sentences as it's somehow confusing that the 'free' version of the player allows HLS/DASH (with limits) while the non-commercial does not.

**Comment by robwalch** [comment]
Feedback in PR form is welcome. You can also comment on the contents of the [README](https://github.com/jwplayer/jwplayer#disclaimer) in this thread if you like.

This project only supports native browser (`video.src =`) playback. This project is not the "free" edition of our commercial product. The commercial product leverages code outside of this project which implements features like license edition. Details on what is offered in each edition is covered on jwplayer.com and is outside the scope of this project. Any suggestions on how to improve the [disclaimer in our README](https://github.com/jwplayer/jwplayer#disclaimer) are welcome.
