### ISSUE TITLE
[BUG] Caption live  - turned off after resuming 

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#3265]
### Expected Behavior

After resuming,  player keep all settings for caption.

### Actual Behavior

Live stream + caption:

<img width="330" alt="jw-caption" src="https://user-images.githubusercontent.com/9075761/51753082-39aa2000-20b9-11e9-83e1-16e3d6b5cf8a.png">

----

##### provider.html5 (Safari)

----

Everything works correctly - after resuming captions are turned on 

**start**:
UI: caption: on
Displaying caption: yes
Load vtt files: yes
Load m3u8  (caption): yes

**stop**
UI: caption: on
Displaying caption: yes
Load vtt files: yes
Load m3u8 (caption): yes

**resume**
UI: caption: on
Displaying caption: no
Load vtt files: yes
Load m3u8 (caption): yes

----

##### provider.hlsjs

----

###### renderCaptionsNatively: false
**start**:
UI: caption: on
Displaying caption: yes
Load vtt files: yes
Load m3u8  (caption): yes

**stop**
UI: caption: on
Displaying caption: yes
Load vtt files: no
Load m3u8 (caption): yes

**resume**
**UI: caption: on**  - **Caption are turned off after resuming, but UI show the caption are turned on.**
**Displaying caption: no**
Load vtt files: no
Load m3u8 (caption): no

----

###### renderCaptionsNatively: true
**start**:
UI: caption: on
Displaying caption: yes
Load vtt files: yes
Load m3u8  (caption): yes

**stop**
UI: caption: on
Displaying caption: yes
Load vtt files: no
Load m3u8 (caption): yes

**resume**
**UI: caption: off**  - **Caption are turned off after resuming.**
**Displaying caption: no**
Load vtt files: no
Load m3u8 (caption): no

### Environment

- *operating system | version* W10, MacOS
- *browser * chrome, firefox
- *JW Player* 8.7.4

**Comment by karimMourra** [comment]
Hi @mtoczko do you mean version 8.7.4 instead of 7.8.4 ? Also could you please provide a test stream?

**Comment by mtoczko** [comment]
@karimMourra Version 8.7.4. I can send the stream address in a a private message.

**Comment by karimMourra** [comment]
Great! please send to support@jwplayer.com

**Comment by mtoczko** [comment]
@karimMourra Did you receive a message?

**Comment by karimMourra** [comment]
@mtoczko support received the message, they are looking into it.
