### ISSUE TITLE
Error tracking not propagating correctly

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#3270]
### Expected Behavior

<Error> tracking should be propagated from wrapped responses up to vast root.

### Actual Behavior
We found sketchy error with our vast setup. 
With one <Ad> in Pod an <Error> trackers are fired correctly but when <Wrapped> ad with <Error> is second in sequence then cascading doesn't work.

### Steps to reproduce

1. Open [first example](https://stage-cdn.svp.schibsted.io/examples/vast-tracking/first-example.html?v1); check VAST and network calls (screen below)
![image](https://user-images.githubusercontent.com/2443904/51903413-61043400-23bc-11e9-980e-d3b88fa93d08.png)

2. Open [second example](https://stage-cdn.svp.schibsted.io/examples/vast-tracking/second-example.html?v1); here we have two ads and second sends only one call
![image](https://user-images.githubusercontent.com/2443904/51903476-8d1fb500-23bc-11e9-869b-3614a99e7a1c.png)
`

### Environment

- *hardware | all *
- *operating system | all *
- *browser | Chrome *
- *JW Player version | 8.7.3*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by waxidiotic** [comment]
Hi @artur-michalak. This repo is our non-commercial, open source version of the player. Our Support Team would like to take a look at your issue and you can reach them at https://support.jwplayer.com.
