### ISSUE TITLE
[FEATURE REQUEST] JW8 - Add secondary title (subtitle) in player and info overlay

### ISSUE THREAD

**Issue by quebello** [jwplayer/jwplayer#3285]
### Expected Behavior

We want to add a secondary title in the player (template) and in the info overlay, between title and description.

### Actual Behavior

No secondary title exists.

### Steps to reproduce

No steps.

### Environment

- on all browsers supported by jwplayer
- JW Player version 8.7.3

-----------------------
If i do a PR -> https://github.com/jwplayer/jwplayer/pull/3284

**Comment by robwalch** [comment]
Thanks for the PR @quebello but we're not interested in adding code for this feature which could be achieved with html formatting or by adding your own overlay.
