### ISSUE TITLE
Expose more events on the VR player

### ISSUE THREAD

**Issue by Antho2407** [jwplayer/jwplayer#3287]
Hey there ! I've been playing with the 360 video player, and I was wondering if some methods could be exposed to get some additional engagement measures..

Is there any way to track the current camera position in the video every time the user drags the video / movies his device round ?

Ultimately, would be awesome to plot those points on some sort of heatmap with the flattened preview of the video  😄

**Comment by robwalch** [comment]
Hi @Antho2407,

You can access methods to get the orientation from the 'vr' plugin:

```js
$ jwplayer().getPlugin('vr')
VrPlugin {
enableVRMode: ƒ (enable)
getMode: ƒ ()
getOrientation: ƒ ()
getOrientationAngles: ƒ ()
getStereoMode: ƒ ()
off: ƒ off(name, callback, context)
on: ƒ on(name, callback, context)
once: ƒ once(name, callback, context)
resetPose: ƒ ()
resize: ƒ resizeDrawingBuffer()
resizeHandler: ƒ resizeDrawingBuffer()
trigger: ƒ trigger(name)
}

$ jwplayer().getPlugin('vr').getOrientation()
Float32Array(4) [
0: -0.0362798273563385
1: 0.028774980455636978
2: 0.0010450729168951511
3: 0.9989267587661743
]

$ jwplayer().getPlugin('vr').getOrientationAngles()
{
pitch: -0.07248509397502313
roll: 0.004186811574440091
yaw: 0.05774767181765458
}
```
