### ISSUE TITLE
Question: How to open the info overlay triggered by a button click

### ISSUE THREAD

**Issue by quebello** [jwplayer/jwplayer#3288]
Hello, in the control bar, we have a new button "about" that should open the panel that displays the information about the media. (See screenshots) How can I achieve that ?

We have the button "about" (white circle).
![screenshot 2019-02-13 at 14 26 13](https://user-images.githubusercontent.com/22831335/52715737-791faa00-2f9d-11e9-84ad-6cba2de747bd.png)

And we want to show this after click: 
![screenshot 2019-02-13 at 14 43 26](https://user-images.githubusercontent.com/22831335/52715839-bf750900-2f9d-11e9-84c3-4881467f45e8.png)

Here is my code but I cant find any documentation on how to programmatically do that :
```
jwplayer().addButton(
        "myicon",
        "About",
        () => {
          $('.jw-icon[button=about]').on('click', () => {
            // here we want to open the info panel (jw-info-overlay)
            jwplayer().pause()
        }),
        "about"
      })
```

Kind regards,
Quebello

**Comment by karimMourra** [comment]
hi @quebello we don't currently have an API for displaying the info panel. When it is opened with the right click, we position the panel based on where the click was. Would you expect the panel to cover the entire player when opened with your button ?

**Comment by quebello** [comment]
Hello @karimMourra, yes we want to open the panel to cover the entire player.

the other solution is to create our iframe code and put in the information about media like the info panel... but before that i want to be sure that you have not a better solution for my use case
