### ISSUE TITLE
Wiki home page's link to JW Player Support is broken

### ISSUE THREAD

**Issue by JamesSkemp** [jwplayer/jwplayer#3290]
### Expected Behavior

I would click on the JW Player Support link on https://github.com/jwplayer/jwplayer/wiki and go to the support page.

### Actual Behavior

I am taken back to the main wiki page.

### Steps to reproduce

1. Go to https://github.com/jwplayer/jwplayer/wiki
2. Click on the JW Player Support link in the body of the page.

Page just needs the full link, with protocol.

### Environment

n/a

**Comment by jnatalzia** [comment]
Fixed! Thanks for the heads up.
