### ISSUE TITLE
1 in 100 app runs gives player error 100012, works on restart

### ISSUE THREAD

**Issue by alexcone** [jwplayer/jwplayer#3291]
### Expected Behavior
Expected the player to always work or always have a bad license.  Having a failure on 1 in 100 launches when running with a valid key is no good.

### Actual Behavior
Approximately 1 in 100 launches, the iOS player refuses to load and gives a 100012 error.  Trying to run any video in the app always gives this error.  It goes away on relaunch.

### Steps to reproduce
1. Run app 100 times and play a video.
2. 1 in 100 times we get an error and the player will not load
3. Playing other videos with the JWPlayer gives the same error

### Environment
- iPhone X or simulator
- iOS 12.1.X
- native Swift app
- JW Player version 3.2.0

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Hi @alexcone,

This space is for web player issues. For commercial products like the iOS and Android SDK please submit a support case at https://support.jwplayer.com/submit-support-case

**Comment by alexcone** [comment]
Sorry about that!  Have submitted to JWPlaer directly
