### ISSUE TITLE
Trying to build 

### ISSUE THREAD

**Issue by Ziiweb** [jwplayer/jwplayer#3329]
Hi,
Im getting this when trying to build jwplayer:

```
jwplayer v8.8.0-beta.2
(node:20875) ExperimentalWarning: The http2 module is an experimental API.
Running "clean:dist" (clean) task
>> 1 path cleaned.

Running "webpack" task
Unhandled rejection (<(debug) ./src/js/jwplayer.js
Module bu...>, no stack trace)

```

**Comment by waxidiotic** [comment]
Hi @Ziiweb -

I just tried cloning a fresh copy of the repo, running `yarn install` and then `grunt build` and was able to build it successfully.

Have you tried re-running `yarn install`?

**Comment by Ziiweb** [comment]
Thanks @waxidiotic, this is what I get when running `yarn install`:
```
yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

```

**Comment by waxidiotic** [comment]
Hmm, I Googled that error and it seems to be common on Linux.

Take a look at this StackOverflow article and see if it helps you: https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install
