### ISSUE TITLE
VAST is not played

### ISSUE THREAD

**Issue by Ziiweb** [jwplayer/jwplayer#3333]
Hi,
I have the code below, but it doens't show the VAST video:

```
<div id="my-video"></div>
<script type="text/javascript" src="jwplayer/bin-release/jwplayer.js"></script>
<script type="text/javascript">
    jwplayer("my-video").setup({
        advertising: {
            client: "vast",
            schedule: {
                "myAds": {
                    "offset": "pre",
                    "tag": "https://syndication.vagrant.test/splash.php?idzone=3205661"
                }
            }
        },
        file: "http://techslides.com/demos/sample-videos/small.mp4",
        width: "580",
        height: "370"
    });
</script>
```
I'm not getting any error in console.
No problem using the same tag on FluidPlayer.

**Comment by waxidiotic** [comment]
Hi @Ziiweb - Playing ads in JW Player requires a commercial license and is not available with the open source player. For more information, [please see our site](https://www.jwplayer.com/pricing/).

If you do have a commercial license and need support playing ads, please [contact our support team](https://support.jwplayer.com/) as this Issues board is only for the open-source player.
