### ISSUE TITLE
seek event issue.

### ISSUE THREAD

**Issue by jason0853** [jwplayer/jwplayer#3342]
I want to play same part repeatedly, so need to use seek().
It worked well a few days ago, but it doesn't work now. I don't know why.
The playing status is true, but player is not working.
Also, if I add handleRepeat() twice, it works well. why?

handleRepeat = () => {
      const { mediaScript } = this.props;
      const { playerIndex: idx, currentTime } = this.state;

      this.setState(
        prevState => ({
          playing: prevState.playing ? false : true,
        }),
        () => {
          if (this.state.playing && !this.state.repeatClick) {
            this.player.seek(mediaScript[idx].start);
            this.setState({ repeatClick: true });
          } else if (this.state.playing && this.state.repeatClick) {
            this.player.seek(currentTime);
          } else {
            this.player.pause();
          }
        },
      );

      this.player.on('time', e => {
        e.currentTime >= mediaScript[this.state.playerIndex].end &&
          this.player.pause();
      });
 };

    setTimeout(() => {
         this.setState({ disabled: false });
         this.handleRepeat();

         //this.handleRepeat(); <-- if I add one more, it works well. why?
     }, 1000);

**Comment by karimMourra** [comment]
@jason0853 as of 8.8.0 we respect the previous state when seeking, meaning that if the player was paused before seeking, after seeking it stays paused. You therefore no longer need to call pause after seeking
