### ISSUE TITLE
How to replace error with buffering spinner

### ISSUE THREAD

**Issue by Khalid-Alqahtani** [jwplayer/jwplayer#3352]
Hi 

I streaming hls content but the stream maybe not ready when user start the player

So I want the player to keep the spinner when retrying to get the content 

So can I keep the spinner also when it is error 

Thank yoy

**Comment by waxidiotic** [comment]
Hi @Khalid-Alqahtani,

When a live stream is embedded in the player and playback is initiated, the player is assuming the stream is valid and live. Having the player not error after trying the stream a few times is not something we are looking to implement in the player.

With that being said, you may have two options:

1. Some live stream encoders offer the ability to display a static image in the stream before you actually go live with your content. To the player, the stream would be live but the user may see a message saying "We will be beginning soon" or something along those lines.
2. You can have the player respond to an `.on('error')` event by attempting to re-load the stream after a certain amount of time. I have not tested this code but it may look something like this:

```javascript
jwplayer().on('error', () => {
  setTimeout(() => {
    jwplayer().load({"file": "yourlivestreamurl.m3u8"});
  }, 1000);
});
```
