### ISSUE TITLE
how to disable auto-pause

### ISSUE THREAD

**Issue by newguy2019** [jwplayer/jwplayer#3363]
Hi, I'm using JW Player to play songs, and I have a .jpg file with each song's title and composer playing as the video with each song. For many years, it would play through my playlist without stopping, but perhaps with the latest update it now stops playing automatically after the first song unless Google Chrome's tab for the website the player is on is open and on top. Is there any way to disable this auto-pause feature, or if not, could I self-host a version of JW Player in which this feature isn't there? If yes, what is the latest version in which the auto-pause feature isn't there, and where can I download it? Thanks.

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by waxidiotic** [comment]
Hi @newguy2019 - Auto-pause should only be enabled if you explicitly have it enabled. It's off by default.

* Are you referring to Chrome on desktop or on Android?
* Can you send me a URL to a page in which I can see the behavior, along with reproduction steps (if any are needed)?

Thanks!

**Comment by newguy2019** [comment]
Thanks for your reply, waxidiotic. Well, I know it will make it harder to solve this issue, but I'd rather not make the site url public at the moment. The problem happens in Chrome and Firefox on desktop. Here is the part of the code dealing with JW Player, with my JW Player Id replaced by "x"s. 

<head>
<script src="https://jwpsrv.com/library/+xxxxxxxxxxxxxxxxxxxx.js"></script>
<body>
<center>
<div id="playerxxxxxxxxxxxx">
</div>
</center>
</body></head>

<script type="text/javascript">
    function shuffle(array) {
      var tmp, current, top = array.length;

      if(top) while(--top) {
     current = Math.floor(Math.random() * (top + 1));
     tmp = array[current];
     array[current] = array[top];
     array[top] = tmp;
    }

    return array;
    }

       jwplayer('playerjVNjWCsZfnlq').setup({
       playlist: shuffle([{

**Comment by newguy2019** [comment]
<head>
<script src="https://jwpsrv.com/library/+xxxxxxxxxxxxxxxxxxxx.js"></script>
<body>
<center>
<div id="playerxxxxxxxxxxxx">
</div>
</center>
</body></head>

<script type="text/javascript">
    function shuffle(array) {
      var tmp, current, top = array.length;

      if(top) while(--top) {
     current = Math.floor(Math.random() * (top + 1));
     tmp = array[current];
     array[current] = array[top];
     array[top] = tmp;
    }

    return array;
    }

       jwplayer('playerxxxxxxxxxxxx').setup({
       playlist: shuffle([{

**Comment by newguy2019** [comment]
Well, I know it will make it harder to troubleshoot this issue, but I'd rather not make the site url public at the moment. The problem happens in Chrome and Firefox on desktop. The part of the code dealing with JW Player is here, with the my player id replaced by "x"s: <script src="https://jwpsrv.com/library/+xxxxxxxxxxxxxxxxxxxx.js"></script>
<script type="text/javascript"> function shuffle(array) { var tmp, current, top = array.length; if(top) while(--top) { current = Math.floor(Math.random() * (top + 1)); tmp = array[current]; array[current] = array[top]; array[top] = tmp; } return array; } jwplayer('playerxxxxxxxxxxxx').setup({ playlist: shuffle([{

**Comment by waxidiotic** [comment]
I would need to see the entirety of your call to `jwplayer().setup()`.

Also, the player embed script you are using is very outdated and not something we have used in years. Do you know what version of the player you are using? You can find out by right-clicking on the player.

**Comment by newguy2019** [comment]
It might have something to do with this issue: https://stackoverflow.com/questions/50201494/bypassing-chrome-autopause-on-videos-with-sound.

**Comment by newguy2019** [comment]
It's 8.8.2. Yes, someone wrote the script for me in 2015, I think, and it hasn't been updated since. Those are the only references to JW Player in the code, so I'm not sure where to start copying to include the entirety of my call to it.

**Comment by newguy2019** [comment]
Also, someone wrote that script to randomize the playlist, but if it could be re-written to make it even more random, that would be great. Thanks.

**Comment by waxidiotic** [comment]
From the looks of it, you are using JW Player 6 which has not been supported for quite a while. It has also never been updated to work with browsers' autoplay policies that were enacted in the last year or so.

I would recommended upgrading your player. You can upgrade an existing player or create a new one by logging in to your [JW Player Dashboard](https://dashboard.jwplayer.com/).

**Comment by newguy2019** [comment]
The player's not self-hosted, so it is updated automatically, I think.

**Comment by waxidiotic** [comment]
While the player is cloud-hosted, it is only automatically updated with minor and patch versions (i.e. 6.x.x). I do not believe they were automatically updated to JW Player 7, let alone JW Player 8.

To be sure though, I would really need to see the page. I understand not wanting to make it public so if you would like, you can [contact our Support Team](https://support.jwplayer.com/submit-support-case) and either supply them a link that wouldn't be a public-facing website, or you can attach the HTML file to them if need-be.

**Comment by newguy2019** [comment]
I searched for Chrome's auto-play policy based on your lead above, and this is what I found: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes.

**Comment by newguy2019** [comment]
Could I add some code based on that page that would change the auto-play policy to allow auto-play for users in Chrome and Mozilla? If yes, could you provide it? Obviously, I'm not a programmer ; )

**Comment by newguy2019** [comment]
And thanks for providing the Support Team link. I'll contact them, too.

**Comment by waxidiotic** [comment]
Having to deal with browsers' autoplay policy is not something that can easily be done with a few lines of code. :(

**Comment by newguy2019** [comment]
Rats--thanks for your advice, though : )

**Comment by newguy2019** [comment]
And someone from JW Player Support emailed me and referred me to https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/#autopause.

**Comment by waxidiotic** [comment]
What I am confused about, however, is that autoPause is disabled by default. You have to enable it for it to take effect. Has the Support Team taken a look at your page?

**Comment by newguy2019** [comment]
No, they didn't see the page. It's definitely a browser issue, though, as this article explains: https://arstechnica.com/tech-policy/2017/09/google-chrome-block-auto-play-video. I found a fix by keeping player's tab on top or opening player in another window, with it being on top if multiple tabs are open in that window. On Android, the player's window must be on top of other windows.

**Comment by waxidiotic** [comment]
I'm glad you found a solution that works for you!

**Comment by newguy2019** [comment]
Thanks! That solution was working the other day but stopped today--very strange!
