### ISSUE TITLE
Custom controls

### ISSUE THREAD

**Issue by adamszeptycki** [jwplayer/jwplayer#3374]
how can I make add custom controllers to JWPlayer when it is in full-screen mode

**Comment by pajong** [comment]
@adamszeptycki The player applies `jw-flag-fullscreen` class to the `div` that was used to set up the player. You can use that css class to make custom controller when it is in fullscreen mode.
JW Player's controlbar has the class `jw-controlbar`, so you can use the two classes to determine whether if you want to hide the controller.

**Comment by adamszeptycki** [comment]
How would I go about it in iOS?

**Comment by pajong** [comment]
The fullscreen that you see is the iOS native fullscreen, and the controller that you see is from Safari. I believe that there is no way to overwrite the controller for iOS on fullscreen mode.

**Comment by adamszeptycki** [comment]
@pajong thanks. I solved it.

**Comment by Maximusdb1** [comment]
@adamszeptycki if you don't mind me asking, how did you solve this issue?
