### ISSUE TITLE
Question: Floating Player

### ISSUE THREAD

**Issue by Teranode** [jwplayer/jwplayer#3380]
I see that the later versions of jwplayer supports the floating player on scroll concept. Is there a way to force the floating player via a button or an example of how that might be accomplished rather than only for scrolling?

**Comment by jnatalzia** [comment]
Hi @Teranode !

Unfortunately as of now, the floating behavior is only available based on the scroll position of the user. If you'd like to submit a feature-request to have alternate triggers for the floating behavior please fill out the following and we'll be sure to transfer to our internal backlog. Thank you!

```
# Feature Request Title (Clear and Descriptive)

## Problem Overview
This should be a general overview of the problem you're experiencing. It is important to note that this does not go into the solution you are proposing as that is relegated to a later section.

## Current Solutions or Workarounds
This should describe what current ways exist to get around the problem listed above.

## Proposed solution (optional)
Your idea for how to solve the above problem.

## Examples in the wild (optional)
List some other video players or applications where this feature exists.

## Additional Information (optional)
Anything else that does not fit into the above categories.
```
