### ISSUE TITLE
VAST 4.1 Macros

### ISSUE THREAD

**Issue by Vendin** [jwplayer/jwplayer#3395]
How use macros from VAST 4.1 ?

Paragraph 6.
https://iabtechlab.com/wp-content/uploads/2018/11/VAST4.1-final-Nov-8-2018.pdf

I use for tracking clicks in ClickThrough. Player not replaced macros. Version player v8.8. All by specification.

```
    <ClickThrough><![CDATA[https://ya.ru/?t=[DOMAIN]]]></ClickThrough>

```

Full example.

```
<?xml version="1.0" encoding="UTF-8"?>
<VAST version="4.1">
   <Ad id="17">
      <InLine>
         <AdSystem><![CDATA[Ad]]></AdSystem>
         <AdTitle><![CDATA[In-stream Ad]]></AdTitle>
         <Error><![CDATA[https://ad.com/isv_errors?out_name=1&cisai=17&errorcode=[ERRORCODE]]]></Error>
         <Impression><![CDATA[https://ad.com/isv_shows?out_name=1&cisai=17]]></Impression>
         <Creatives>
            <Creative>
               <UniversalAdId idRegistry="ad.com">17</UniversalAdId>
               <Linear skipoffset="00:00:05">
                  <Duration>00:00:16</Duration>
                  <VideoClicks>
                     <ClickThrough><![CDATA[https://ya.ru/?t=[DOMAIN]]]></ClickThrough>
                     <ClickTracking><![CDATA[https://ad.com/isv_clicks?out_name=1&cisai=17]]></ClickTracking>
                  </VideoClicks>
                  <TrackingEvents>
                     <Tracking event="progress" offset="00:00:10"><![CDATA[https://ad.com/isv_views?out_name=1&cisai=17]]></Tracking>
                  </TrackingEvents>
                  <MediaFiles>
                     <MediaFile delivery="progressive" type="video/mp4" height="720" width="1280"><![CDATA[https://ad.com/is/p/17/6512bd43d9caa6e02c990b0a82652dca.mp4]]></MediaFile>
                  </MediaFiles>
               </Linear>
            </Creative>
         </Creatives>
      </InLine>
   </Ad>
</VAST>
```

![image](https://user-images.githubusercontent.com/9011975/57240250-a75dd480-7036-11e9-9a3f-d19d9b4a9319.png)

**Comment by robwalch** [comment]
Hi @Vendin,

This is the list of macros we currently support https://support.jwplayer.com/articles/ad-tag-targeting-macro-reference

For domain we support `__domain__`. It shouldn't be hard for us to also support the standard macros. I'll look into it, but highly recommend to file a feature request with our support team.

**Comment by robwalch** [comment]
We will add additional VAST 4.1 macros as the standard gets adopted. We already support the following VAST macros for tracker urls as of jwplayer v8.8.5:

[ERRORCODE], [CACHEBUSTING], [ASSETURI], [TIMESTAMP], [CONTENTPLAYHEAD]

**Comment by Vendin** [comment]
Hi @robwalch

How getting DOMAIN correctly on click event ?

so
```
    <ClickThrough><![CDATA[https://ya.ru/?t=[__domain__]]]></ClickThrough>
```

or so
```
    <ClickThrough><![CDATA[https://ya.ru/?t=__domain__]]></ClickThrough>
```

or how ?

**Comment by robwalch** [comment]
Sorry @Vendin,

The double underscore macros listed [here](https://support.jwplayer.com/articles/ad-tag-targeting-macro-reference) only apply to VAST ad tag and VMAP urls. They are not applied on tracker urls. For tracker urls we support [ERRORCODE], [CACHEBUSTING], [ASSETURI], [TIMESTAMP], [CONTENTPLAYHEAD].

**Comment by Vendin** [comment]
Hi @robwalch 

Where can I find the source code for replacing macros?

I want to create a PR with adding other macros.

I found only the minified code.

```
a["[TIMESTAMP]"] = encodeURIComponent((c = new Date, d = c.getTime(), b = c.getTimezoneOffset() / 60, f = 6E4 * c.getTimezoneOffset(), (new Date(d - f)).toISOString().slice(0, -1) + (0 < b ? "-" : "+") + ("0" + b).slice(-2))), a["[CACHEBUSTING]"] = Math.random().toString().slice(2, 10), a["[ASSETURI]"] = encodeURIComponent(this.trackerPlayerUtils.getFile()), a["[CONTENTPLAYHEAD]"] = encodeURIComponent((g = this.trackerPlayerUtils.getPosition(), h = ("0" + Math.floor(g / 3600)).slice(-2), 
```
and that
https://github.com/jwplayer/jwplayer/blob/ea628736140633698a1cda6077b8fbb14dfda55c/src/js/plugins/utils.js#L20
