### ISSUE TITLE
Interactive captions/transcript. Reloading caption on real time?

### ISSUE THREAD

**Issue by mwleinad** [jwplayer/jwplayer#3403]
We are working on a interactive captions/transcript using JwPlayer and we found this.
https://developer.jwplayer.com/jw-player/demos/innovation/interactive-transcripts/

This is great! Is mostly everything we need. However we want to take it one step ahead and include real-time edition of captions.
Meaning you click a cue and you can edit it and it will reflect on the caption file. 

Unfortunately we can't find anything in the documentation that will allow us to do this.

I was taking a look at this
https://github.com/jwplayer/jwplayer/issues/1675
But it seems captions.preprocessor was removed.

Is there anyway, and if there is, what would be the best way to reload a caption file?

**Comment by karimMourra** [comment]
Hi @mwleinad. What is the use case for modifying captions on the fly ? This functionality will most likely not be exposed in the Player because the FCC has rules enforcing caption quality for accessibility purposes https://www.fcc.gov/general/closed-captioning-video-programming-delivered-using-internet-protocol-ip. Non-compliance can result in fines.

**Comment by mwleinad** [comment]
@karimMourra So the use case is this.
- An admin user uploads a video to our site.
- admin user generates machine captions (using any AI service around)
- admin user plays the video. A sidebar like in https://developer.jwplayer.com/jw-player/demos/innovation/interactive-transcripts/ appears
- admin user notices an error  on a cue and clicks it to edit it in real-time. Notice this is only real time for the Admin user
- If a normal user plays the video too, the normal user doesn't have any edition capabilities.

I don't see why this wouldn't be allowed.
Actually you can edit captions in real time in the jwplayer dashboard

![image](https://user-images.githubusercontent.com/15146158/58571425-54270e00-81ff-11e9-85a1-71c8f9b69f04.png)

Problem is that video is not jwplayer, but I think is an HTML5 video.

**Comment by karimMourra** [comment]
@mwleinad gotcha. I currently don't know of any ways to reload captions files. If you would like to submit 
a feature request for us to expose a way to do so, please fill out the following template and I'll get your request directly into our product backlog for review. Apologies for the wait on this!

```
# Feature Request Title (Clear and Descriptive)

## Problem Overview
This should be a general overview of the problem you're experiencing. It is important to note that this does not go into the solution you are proposing as that is relegated to a later section.

## Current Solutions or Workarounds
This should describe what current ways exist to get around the problem listed above.

## Proposed solution (optional)
Your idea for how to solve the above problem.

## Examples in the wild (optional)
List some other video players or applications where this feature exists.

## Additional Information (optional)
Anything else that does not fit into the above categories.
```
