### ISSUE TITLE
getCurrentQuality() returns -1 if player in error state

### ISSUE THREAD

**Issue by nodanaonlyzuul** [jwplayer/jwplayer#3404]
### Expected Behavior

If a _quality_ is missing and the `error` event is thrown, `getCurrentQuality()` should
return the index of the errant quality. This is how version 7.12.13 worked.

### Actual Behavior

If a _quality_ is missing and the `error` event is thrown, `getCurrentQuality()` is
returning -1, not the index of the errant quality. We're seeing this in version 8.8.5.

### Background

Ideally we have high, medium, and low quality derivatives for each of our assets.
However, sometimes we only have one of those derivatives. (This collection is huge and has been around a lonnnngggg time)

We wrote a small `setupJwPlayer()` function that wraps `jwplayer.setUp()` and has an `error` callback that, re-instantiates the player, but without this errant quality from the `sources` array/option. It's trying to retry/gracefully degrade.

This worked in 7.12.13 but has broken since our upgrade to 8.8.5.

### Example

[I've put together a test-fixture page](https://nodanaonlyzuul.github.io/jw-player-pr-example/) to compare the behavior between 7.12.13 and 8.8.5.
If there's an approach to degrading/retrying that's more in-line with 8.8.5 - I'd love to hear about it.  

### Environment

- *OS X | 10.14.12*
- *FF | 66.0.5 (64-bit)* / *Chrome |  74.0.3729.131 (Official Build) (64-bit)*
- *JwPlayer 8.8.5*

### Finally 

Thanks to all maintainers and contributors for your time and hard work!

**Comment by waxidiotic** [comment]
Hey @nodanaonlyzuul - thanks for the report and the great test page. I'm going to look more into this and let you know what we find!

**Comment by nodanaonlyzuul** [comment]
No problem - make sure to view each test page in a private/incognito window since quality 
preference is stored in the cookie. Let me know if there's anything else I can help with,

**Comment by waxidiotic** [comment]
Hi @nodanaonlyzuul,

We took a look into this. We are changing the value that is returned in `getCurrentQuality()` to `-1` in the process of clearing out the video tag once it errors. This way, we can properly prime the tag for a fallback source, if provided. 

My suggestion to accomplish what you are looking for is to either get the index by comparing the source URL being used (via `getPlaylistItem()` or `getPlaylistItem().file`) and remove it from your sources that way.

Alternatively, you could keep track of what index is being called via the `on('levelsChanged')` [event handler](https://developer.jwplayer.com/jw-player/docs/javascript-api-reference/#jwplayeronlevelschanged).

Hope this helps!

**Comment by nodanaonlyzuul** [comment]
Hey @waxidiotic,

Thanks for taking the time to look into this and special thanks for offering different approaches to maintaining our fallback behavior.
