### ISSUE TITLE
Swollen web-driver click action by GoogleIMA vast client

### ISSUE THREAD

**Issue by Karponter** [jwplayer/jwplayer#3419]
### Expected Behavior

For configured GoogleIMA vast client on Chrome browser:
WebDriver performs click on player controls and player react successfully.

### Actual Behavior

For configured GoogleIMA vast client on Chrome browser:
WebDriver performs click on player control, consider it as successful, but player do not react to this click.

Still, works fine for Firefox or manual clicks in Chrome. 

### Steps to reproduce

1. Configure JW8 player with following config
```
      playerInstance.setup({
        file: 'https://vjs.zencdn.net/v/oceans.mp4',
        height: 360,
        width: 640,
        muted: false,
        autostart: false,
        advertising: {
          client: 'googima', // google IMA client is chosen
          vpaidmode: 'insecure',
          vpaidcontrols: true,
          tag: 'https://raw.githubusercontent.com/googleads/videojs-ima/master/test/webdriver/content/canned_ads/skippable_linear.xml',
        },
      });
```

2. Setup any basic webdriver test that loads page, starts player and attempts to click some player controls.

```
describe('JW8, GoogleIMA vast client, Chrome', () => {
  it('Reproduce swollen click', () => {
    return driver.get(fullUrl)
      .then(() => wait(2000))
      // Successfully start ad playback in any case
      .then(() => driver.findElement(webdriver.By.css('.jw-icon-display')).click())
      .then(() => setTimeoutPromise(5000))
      // Mutes ad in Firefox or with default client, does nothing for Chrome Google IMA case
      .then(() => driver.findElement(webdriver.By.css('.jw-icon-volume')));
  });
});
```
  
3. As a result, we can see that webdriver action passed successfully, but still player do not react on click command.

### Environment

- device: Lenovo Thinkpad X270, MacBook Pro 2017, Cloud VMs
- operating system: Win10, MacOS MOJAVE, Ubuntu 19.04
- browser: Chrome 73
- JW Player url: https://cdn.jwplayer.com/libraries/jDUp2UAs.js

**Comment by zetagame** [comment]
Hi Karponter! The issue you're describing is the result of a known chromedriver [bug](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2758&q=&colspec=ID%20Status%20Pri%20Owner%20Summary). We have a ticket in for a local fix and will be addressing this issue in a future release.

**Comment by Karponter** [comment]
Thanks, @zetagame!
Looking forward for future release with a bug-fix.

Still interested, do you know some workaround of this problem? I'm ok with any programmatic way to force click on specific JWPlayer control while GoogleIMA is launched.
