### ISSUE TITLE
[iOS SDK] Chrome cast doesn't work

### ISSUE THREAD

**Issue by adamszeptycki** [jwplayer/jwplayer#3420]
I have built JWCasting from this repo add a key and everything (video player works). BUT
it doesn't find any devices. There is a chrome cast device right next to my phone and other apps (YouTube and TedTalks app) don't have any problem finding it.
Any clues how can I debug it?

**Comment by karimMourra** [comment]
Hi @adamszeptycki ! Thank you for reporting this issue. Unfortunately I will have to close it since this repo is specific to our web player, and your issue is specific to the iOS SDK. I will respond to the duplicate in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps/issues/18
