### ISSUE TITLE
Unable to determine jw-info-overlay show/hide event

### ISSUE THREAD

**Issue by jaketrimble** [jwplayer/jwplayer#3425]
How is it possible to determine when `jw-info-overlay`  is visible? It is incredibly frustrating that this event doesn't appear even in the `.on('all')` event and there seems to be a lack of documentation regarding this specific modal. Somewhat similarly to #3288, we would like to be able to fire this event from our own button and, _more importantly and urgently_, need to be able to control the visibility of our own custom overlays when this "modal" is visible.

jwplayer may want to alter their documentation that says this for `.on('all')`:
```
This singular API call can be used to gather all events from the player's API.
```
That statement is seemingly untrue, because the opening of a `jw-info-overlay` modal does not fire an event within the `.on('all')` API call. Not to mention no event is emitted on right-click, either.

Thank you in advance for any guidance.

**Comment by vseventer** [comment]
Hi @jaketrimble, 	

Most events the player emits are related to video playback, and not to user interactions. However, please fill out the Feature Request Template below and we will transfer this request to our internal backlog. Thanks!

```
# Feature Request Title (Clear and Descriptive)

## Problem Overview
This should be a general overview of the problem you're experiencing. It is important to note that this does not go into the solution you are proposing as that is relegated to a later section.

## Current Solutions or Workarounds
This should describe what current ways exist to get around the problem listed above.

## Proposed solution (optional)
Your idea for how to solve the above problem.

## Examples in the wild (optional)
List some other video players or applications where this feature exists.

## Additional Information (optional)
Anything else that does not fit into the above categories.
```

**Comment by karimMourra** [comment]
@jaketrimble sorry for the confusion. in the statement
> This singular API call can be used to gather all events from the player's API.

by `all events`, we mean all of the documented events that you could  register for. 
cc: @kcorneli201
