### ISSUE TITLE
toggling playback causes multiple simultaneous requests in safari

### ISSUE THREAD

**Issue by puckey** [jwplayer/jwplayer#3428]
### Expected Behavior

When I toggle between play and stop there should be a single request running in the network inspector

### Actual Behavior

In the safari web inspector I can see multiple requests running simultaneously (also the case for ios).

See this screen recording as demonstration of the issue: https://www.dropbox.com/s/4k7e817tmj2c62c/jwplayer-safari-issue.mov?dl=0

### Steps to reproduce

1. Use Safari (I am using OSX Mojave)
2. Go to the demo page at https://developer.jwplayer.com/jw-player/demos/toolbox/live-streaming/
3. Enter an mp3 stream into the url field - for example `http://cdn.nrjaudio.fm/audio1/fr/30201/mp3_128.mp3`
4. open the network inspector in safari and toggle between play and stop

### Environment

- *hardware | device* Macbook Pro 2018
- *operating system | version* Osx Mojave
- *browser | version* Safari 12.1.1
- *JW Player version | url* https://developer.jwplayer.com/jw-player/demos/toolbox/live-streaming/

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by vseventer** [comment]
Hi @puckey,

The network request behavior you are seeing in Safari is expected. Internally, on the HTML5 `<video>` tag, the player calls `load()` directly followed by `play()`, which causes the behavior you are seeing.

We do need to call `load()` to reset the media element so sources are re-requested since this is a live stream.

**Comment by puckey** [comment]
In the screen capture you are seeing multiple requests to the same live stream running side by side, while there should only be one. When the media element is reset, the request that belongs to it is not being destroyed.

**Comment by vseventer** [comment]
Hi @puckey,

I am able to reproduce in Safari on OSX Mojave. Strangely enough, on High Sierra the behavior is different as the previous request is destroyed and stops downloading.

However, the behavior you are seeing also appears when not using our player. For example, if you run the following snippet on an empty page, the same behavior can be observed (after roughly three seconds):

```js
const v = document.createElement('video');
v.src = 'http://cdn.nrjaudio.fm/audio1/fr/30201/mp3_128.mp3';
v.play();

setTimeout(() => {
    v.load(); 
}, 3000);
```

At this point, if you feel this is a bug in Safari, I'd recommend reporting the bug to Apple.

**Comment by puckey** [comment]
Yes, I checked and it was reported in 2017.. But seems a serious enough bug to warrant a workaround.. I have done so in my own codebase using iframes:

(Note that there is a bunch of pool related stuff here because I need to be able to switch audio tracks o mousemove.. )

```javascript
import * as loop from '../../loop';
import { isMobile } from '../../../utils/feature';

const pool = [];
const used = [];
let containerEl;

const silenceAudioData =
  'data:audio/wav;base64,UklGRigAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhAgAAAAEA';

export const isDepleted = () => pool.length < 2;

export const fill = () => {
  containerEl = document.createElement('div');
  containerEl.style.display = 'none';
  document.body.appendChild(containerEl);
  const fillPool = () => {
    const needed = 10 - pool.length;
    for (let i = 0; i < needed; i++) {
      const iframe = document.createElement('iframe');
      containerEl.appendChild(iframe);
      const audio = iframe.contentWindow.document.createElement('audio');
      audio.src = silenceAudioData;
      audio.play();
      pool.push([iframe, audio]);
    }
  };
  fillPool();
  document.addEventListener(isMobile ? 'touchstart' : 'mousedown', fillPool);
};

export const get = () => {
  if (!pool.length) {
    throw new Error('audio pool depleted');
  }
  const entry = pool.shift();
  used.push(entry);
  return entry[1];
};

export const release = audio => {
  loop.next(() => {
    const index = used.findIndex(([, usedAudio]) => usedAudio === audio);
    const [[iframe]] = used.splice(index, 1);
    iframe.parentNode.removeChild(iframe);
  });
};
```

**Comment by vseventer** [comment]
Thanks for your sharing your workaround. I added a ticket to our internal backlog and will update this ticket in the event the ticket is prioritized.

**Comment by jnatalzia** [comment]
Hi @puckey given this seems to be localized to mp3 and it was reported to Apple in 2017 (as it's ultimately an issue with their browser) we don't see this as a high priority for our dev team and as a result will not be moving forward with a fix. Apologies for any inconvenience this causes you, feel free to let me know if you have additional questions/concerns!
