### ISSUE TITLE
Safary subtitles

### ISSUE THREAD

**Issue by zordark** [jwplayer/jwplayer#3433]
### Expected Behavior

Subtitles not showing in Safari

### Actual Behavior

Subtitles should be shown

### Steps to reproduce

1. Open jwplayer stream tester (https://developer.jwplayer.com/tools/stream-tester/)
2. Open this stream https://videos.massiveaxis.com/content/sintel-hls/main_1min_all_inclusive.m3u8

In other browsers, like Chrome, Firefox, Opera provided stream works well

### Environment

- Jwplayer stream tester tool

**Comment by waxidiotic** [comment]
Hi @zordark. In Safari, we defer handling of HLS playback and captions rendering to Safari's native player. This means that the player is not responsible for rendering captions in that environment.

I also confirmed I am not seeing captions in Safari for desktop as well. I see the captions tracks listed but the captions do not render in the video.

I'm going to check to see if I can find another stream with a similar setup for in-manifest VTT captions and see if that works in Safari. I will let you know what I find.

**Comment by waxidiotic** [comment]
I found a stream with captions embedded in-manifest, similar to yours, and it is working properly in both Safari for iOS and Mac for me.

http://wowzaec2demo.streamlock.net/vod-multitrack/_definst_/smil:ElephantsDream/elephantsdream2.smil/playlist.m3u8

One thing I did notice in looking at your manifest is that it is missing some of the tags that are normally required in HLS manifests, such as `#EXT-X-VERSION`. Safari is a little more strict on HLS streams conforming to specification than we are when we are responsible for playback, so you may want to check how the manifest is being generated.
