### ISSUE TITLE
JW Player Making Request Head instead of GET

### ISSUE THREAD

**Issue by grandemestre** [jwplayer/jwplayer#3439]
### Expected Behavior

Play a video dash through CURL

### Actual Behavior

For some reason JWPlayer is sending a HEAD request instead of GET
Appearance error only happens with URL having "?"

### Steps to reproduce

1. Put a url that contains "?" as the source of the file and the type as "dash".
In my case:

"sources": [{"file": "http://localhost.com/curl/index.php?url=http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827 -manifest.mpd ",
     "type": "dash"
}]
2. 
My CURL does not seem to be the problem because it works with other players. The question seems to be the query in the url.
But it's like this:
```
<?php
$_url = $_GET['url'];
curl_init();
curl_setopt($ch, CURLOPT_URL, $_url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);

$return = curl_exec($ch);
curl_close($ch);
header('Content-Description: File Transfer');
header('content-type: attachment; application/octet-stream');
header('Content-Type: video/mp4');
header('accept-ranges: bytes');
header('access-control-allow-origin: *');
header('Content-Disposition: filename="car-20120827-manifest.mpd"');
header('Content-Transfer-Encoding: binary');
header('cache-control: public, max-age=3600');
header('access-control-expose-headers: origin, range');
header('age: 3128');
header('cache-control: public, max-age=3600');
header('content-language: en');
header('content-length: 3130');
header('etag: 48f4796b4eab7bc6ab60f624dcf0e00d');
echo $return;

?>
```

### Environment

- *Windows NT  6.2 build 9200 (Windows 8 Home Premium Edition) i586*
- *Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.15*
- *Google Chrome | Version 75.0.3770.100 64 bits*
- * JW Player version 8.9.0 | https://content.jwplatform.com/libraries/IDzF9Zmk.js*

**Comment by waxidiotic** [comment]
@grandemestre - Thanks for opening this issue. I know that 302 redirects from PHP to DASH streams work successfully, but I'll have to look in to the way you have things set up.

I'll let you know what I find out.

**Comment by waxidiotic** [comment]
@grandemestre - Perhaps it's an issue with the way the URL is encoded. Can you try with this config?

```
"sources": [{
     "file": "http://localhost.com/curl/index.php?url=http%3A%2F%2Fyt-dash-mse-test.commondatastorage.googleapis.com%2Fmedia%2Fcar-20120827-manifest.mpd",
     "type": "dash"
}]
```
