### ISSUE TITLE
JW Player JS 8.9.2's Chromecast does not work when Cast Tab is used, but does work when its own Chromecast button is clicked.

### ISSUE THREAD

**Issue by thomas-profitt** [jwplayer/jwplayer#3441]
### Expected Behavior

Either:
- The tab to be cast normally, with the video streamed to the device running Chrome, then compressed and streamed to the Chromecast, as is the case when JW Player does not load Chromecast support (e.g. HTTP, not HTTPS, pages)
- JW Player to successfully start casting properly, as it's trying to do, and as it does when the user clicks its Chromecast button themselves

### Actual Behavior

When the user is already casting the tab when JW Player loads, or "Cast Tab" is selected after JW Player loads, JW Player tries to begin casting properly, as if the user has clicked JW Player's Chromecast button themselves, but fails.

A black screen with the Chromecast logo in blue is shown on the Chromecast.

No HTTP requests from the Chromecast requesting the stream are received by our servers.

Choosing "Stop casting" from Chrome's UI, then clicking JW Player's cast button, starts casting properly.

I've reproduced this in the environment described below, and our users report it when using different environments.

### Steps to reproduce

1. Enable "Cast Tab" in Chrome.
2. In that tab, visit a JW Player page with Casting enabled, e.g. https://s3.amazonaws.com/qa.jwplayer.com/~abussey/demos/2017/nov/122156-cast.html
3. See that JW Player's Chromecast icon is lit up to indicate it's trying to cast.
4. Observe the above behavior

### Other information that may aid in debugging

- When I end the Cast Tab Chromecast session, in JS or in the browser's UI, then try to trigger JW Player's stream casting with `document.querySelector("google-cast-launcher").click()`, and click the browser Chromecast prompt as the user would, _the problem occurs_, but it doesn't occur when I click the icon, _with my bare hands_, as a user would.

### Environment

- Chromebook, MacBook Pro tested
- Chrome OS, macOS tested
- Chrome
- JW Player JS 8.9.2

**Comment by thomas-profitt** [comment]
I'd also like to know if there's a way to work around this:

Can I use the `cast` SDK loaded in and set up by JW Player to detect when the user visits the page with "Cast Tab" enabled, or starts a "Cast Tab" Chromecast session?

I'd like to listen for that, end the "Cast Tab" session, and prompt the user to use JW Player's Chromecast button.

**Comment by waxidiotic** [comment]
Hi @thomas-profitt - thanks for submitting this issue. I am able to reproduce. It looks like we're not listening for if the browser initiates the cast session.

I'm going to look more in to this and let you know what I find.

Thanks again.

**Comment by thomas-profitt** [comment]
2 minute turnaround, not bad!

Thanks, I'll keep listening!

**Comment by waxidiotic** [comment]
@thomas-profitt - Thank you for your patience. It looks like the Cast SDK used to have an API configuration to automatically join an existing cast session, but they no longer offer it since moving the cast sender from a Chrome extension to being baked in to Chrome itself.

Unfortunately, this means that it does not appear like we will be able to work around this behavior.

**Comment by thomas-profitt** [comment]
Does that mean that JW Player will have to let Cast Tab work as it normally does, stream requested and played by JW Player, and then compressed and streamed to the Chromecast?

Or will the current behavior continue?

**Comment by waxidiotic** [comment]
@thomas-profitt - After second look, I think I found a way to handle this so that casting the tab and then clicking Play will result in the content being played.

I'm going to open a Feature Request in our backlog and we will update you with the progress.

**Comment by thomas-profitt** [comment]
Cool!

In the meantime, being that coming to the page with JW Player on it while using Cast Tab causes the Chromecast and JW Player to both show black screens (or was it just the Chromecast?), is a bugfix possible?

Like having JW Player not try to start casting the stream, and just letting Cast Tab work as it would without JW Player's Chromecast support (the way it works when JW Player is loaded on non-HTTPS pages, with Cast Tab)?

**Comment by waxidiotic** [comment]
I'm pretty sure since we use Google's official chromecast web component button, that automatically ties in to the cast SDK in the browser and lets them know that they should expect a video. I'll look in to it, but I don't think there's a way.

**Comment by thomas-profitt** [comment]
Thanks again.

If your sleuthing has found a way that I might be able to use the Cast SDK set up by JW Player to detect that the problem is happening, or just that the Chromecast session is a Cast Tab session, and at least prompt users to use JW Player's own cast button, you would make me very happy!

**Comment by thomas-profitt** [comment]
@waxidiotic Has this been addressed in any JW Player updates since it was reported? (I don't have  a Chromecast nearby to test.)

I don't understand the tags `answered` and `feature-request`; this wasn't a question or a feature request, it was a bug report.

**Comment by waxidiotic** [comment]
@thomas-profitt - My apologies for the confusion. I added the Feature Request label since this is not a bug, as it is not currently within the scope of our casting integration. Unfortunately, I do not have an answer for whether or not this will be implemented in the player.

**Comment by moonseppel** [comment]
Any chances that there might be a fix soon? I'm victim of this on the user side, I guess :(

**Comment by iamakimmer** [comment]
> I'm pretty sure since we use Google's official chromecast web component button, that automatically ties in to the cast SDK in the browser and lets them know that they should expect a video. I'll look in to it, but I don't think there's a way.

Were you able to the cast api?
