### ISSUE TITLE
Player doesn't display under IE 11 if document.domain is set

### ISSUE THREAD

**Issue by privaloops** [jwplayer/jwplayer#3445]
### Expected Behavior

Play a video

### Actual Behavior

Player doesn't display anything

### Steps to reproduce

Create a simple demo page with basic jwplayer setup
before setting up jwplayer, set document.domain to a value (typically your domain name)

### Environment

- VirtualBox
- windows 8
- IE 11.0.9600.17031
- jwplayer > 8.3

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by DanFerrer** [comment]
Hi @privaloops , Can you provide any more detail on this (screenshot, video, etc)? Is this strictly on Virtual Box using a Windows 8 image? I tried reproducing the issue using Browserstack and the player sets up properly.

**Comment by robwalch** [comment]
@privaloops can you explain why you are setting `document.domain`

According to MDN this could affect the same-origin policy which could result in cross-domain requests from failing. Please take a look at the Network panel to see if requests to player assets are blocked as a result.

https://developer.mozilla.org/en-US/docs/Web/API/Document/domain

**Comment by privaloops** [comment]
@DanFerrer I can confirm it happens also on normal environnement.
@robwalch I set it because there is some communication between the page and an iframe in it

**Comment by robwalch** [comment]
@privaloops Can you provide a sample page that reproduces the issue? It would help to see a hosted issue with the domains in question. Ex: is the page on a subdomain (sub.top.com) and `document.domain` set to a top-level domain (top.com)?

In the interim you might put the player in an iFrame to avoid issues with changes made on the main page.

**Comment by privaloops** [comment]
@robwalch 
http://jsfiddle.net/d8q7tf54/2/ doesn't work
http://jsfiddle.net/d8q7tf54/1/ work
