### ISSUE TITLE
Android Chrome navigationUI full screen issue

### ISSUE THREAD

**Issue by axent1** [jwplayer/jwplayer#3446]
### Expected Behavior

While playing any video on chrome (android devices) using full screen, Navigation UI from android should be hidden. Like m.youtube site player etc..

### Actual Behavior

While playing any video on chrome (android devices) using full screen Navigation UI from android stays open. This is related to new chrome update: https://www.chromestatus.com/feature/5188650908254208

https://bugs.chromium.org/p/chromium/issues/detail?id=933436#c7

### Steps to reproduce

While requesting full screen mode, we need to pass {navigationUI: "hide"} or create some JWPlayer api for navigation, how to handle it for android devices on google chrome.

https://developer.mozilla.org/en-US/docs/Web/API/FullscreenOptions/navigationUI

### Environment

- *Any android device with NavigationUI controls | tested on samsung galaxy s9*
- *Android | 9.x*
- *Google Chrome | 75.03xxx*
- *JW Player 8.9.3 | from CDN*

----------------------------------------------------------------------------------------

**Comment by DanFerrer** [comment]
Thanks for bringing this to our attention @axent1. We've logged the issue internally and its now under review. You can follow the status of the issue on the wiki: 

https://github.com/jwplayer/jwplayer/wiki/Open-Bug-Reports.

**Comment by jnatalzia** [comment]
Hi @axent1 !

We've prioritized this bug for our upcoming patch which means the fix should be available in player version 8.11.3 when that releases in the next couple weeks. Thanks!
