### ISSUE TITLE
gapro.js MIME content-type is incorrect

### ISSUE THREAD

**Issue by nodanaonlyzuul** [jwplayer/jwplayer#3450]
_apologies is this isn't the correct repo - I tried looking for the gapro.js's repo but couldn't find it - I know gapro.js is not in this repo....I'm pretty sure that file comes in when you enable GA tracking on JwPlayer - many many apologies and much much egg on my face if I'm wrong._

### Expected Behavior

The content-type header of https://ssl.p.jwpcdn.com/player/plugins/gapro/v/2.1.5/gapro.js should be "text/javascript".

### Actual Behavior

It is "text/plain"

### Steps to reproduce

```
$ curl -I https://ssl.p.jwpcdn.com/player/plugins/gapro/v/2.1.5/gapro.js
HTTP/2 200
accept-ranges: bytes
access-control-allow-origin: *
cache-control: max-age=31536000, immutable
content-type: text/plain
date: Thu, 18 Jul 2019 18:28:45 GMT
etag: "e83d797922d8589456725338a81aa207"
last-modified: Fri, 26 Apr 2019 16:08:53 GMT
server: ECAcc (mic/9BE2)
x-cache: HIT
content-length: 2115
```
### Environment

Requested by JwPlayer 8.9.3.

**Comment by DanFerrer** [comment]
Hi @nodanaonlyzuul,

Thanks for bringing this up. We are talking to our internal ops team about this and will keep you posted on this issue.

**Comment by nodanaonlyzuul** [comment]
Thanks @DanFerrer 

To be clear - browsers (FF at least) still load the file, they just show a warning in the developer tools / network tab.

Thanks again!

**Comment by robwalch** [comment]
The content-type on gapro 2.1.4 and 2.1.5 have been updated to application/javascript:
```
access-control-allow-origin: *
cache-control: max-age=31536000, immutable
content-encoding: gzip
content-length: 952
content-type: application/javascript
date: Fri, 09 Aug 2019 22:44:01 GMT
etag: "e83d797922d8589456725338a81aa207+gzip"
last-modified: Fri, 09 Aug 2019 22:41:47 GMT
server: ECAcc (nya/79B9)
status: 200
vary: Accept-Encoding
x-cache: HIT
```

**Comment by nodanaonlyzuul** [comment]
Hey thanks!
