### ISSUE TITLE
playlist related videos only show 10 data

### ISSUE THREAD

**Issue by Sgemini** [jwplayer/jwplayer#3454]
I have a playlist of 13 videos.

This is my code
```
jwplayer().setup({
  playlist: mylist,
  related: { displayMode: "shelfWidget" }
})
```

Are there any settings missing?
Or i must define templates for more than 10 related videos?

### Expected Behavior
i should see all the 13 videos in ` <div class="jw-related-shelf-contents"></div> ` div tag.

### Actual Behavior
I only saw 10 videos on desktop and 4 videos on mobile,  I checked that the network response video count was correct.

### Environment
JW Player version 8.9.3
chrome version 75.0.3770.100

thx.

**Comment by DanFerrer** [comment]
Thanks for submitting this @Sgemini. I'm not able to reproduce the issue you're experiencing. The amount of items in the widget you see per page is based on your players width. Can you provide any screenshots or the setup config you are using if you're still seeing this problem?
