### ISSUE TITLE
Intercepting requests to HLS manifests and content, then rewrite their URL

### ISSUE THREAD

**Issue by BrightSoul** [jwplayer/jwplayer#3472]
Hello everyone! I'm hosting JWPlayer 8 on my server to play HLS videos that are hosted on AWS S3/CloudFront.
I load those videos by providing an HLS manifest to JWPlayer, such as this one:
```
https://my-cloudfront-host/dirname/index.m3u8?env=staging
```
As you can see, there's an `env=staging` that allows me to perform some statistics later, when I process access logs produced by AWS CloudFront.

Now, suppose the m3u8 manifest has this content. Really nothing out of the ordinary.
```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="program_audio_0",LANGUAGE="eng",NAME="Alternate Audio",AUTOSELECT=YES,DEFAULT=YES,URI="index-audio.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=2717477,AVERAGE-BANDWIDTH=2609992,VIDEO-RANGE=SDR,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=25.000,AUDIO="program_audio_0"
index-720p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1162714,AVERAGE-BANDWIDTH=1109168,VIDEO-RANGE=SDR,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=854x480,FRAME-RATE=25.000,AUDIO="program_audio_0"
index-480p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=887024,AVERAGE-BANDWIDTH=858528,VIDEO-RANGE=SDR,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=25.000,AUDIO="program_audio_0"
index-360p.m3u8
```
And let's suppose JWPlayer decides to play the video @ 360P, so it's making these two requests:
```
https://my-cloudfront-host/dirname/index-audio.m3u8
https://my-cloudfront-host/dirname/index-360p.m3u8
```
My `env=staging` parameter is now lost when making these requests and this is a problem in my scenario.

Can I, somehow, intercept those two requests before they're sent by JWPlayer, so I can append the `env=staging` parameter to their URL?
And the same goes for further requests JWPlayer will do to content files.

Please note that:
- I can't use cookies for this purpose - it has to happen in the querystring;
- HLS manifest can't be dynamically generated;
- I tried coding an XMLHttpRequest interceptor but it doesn't intercept requests made by JWPlayer.

Thank you,
Moreno

**Comment by BrightSoul** [comment]
Hi @waxidiotic, unfortunately I cannot use the `onXhrOpen` hook since the XMLHttpRequest has already been created and I can't change the URL of the request at that point. I can just add custom headers like you showed, but that's it.

In the meantime I solved my problem by sending a cookie instead of a query string variable. In fact, I noticed CloudFront can also log cookies sent with the request.

![cloudfront_logging_2](https://user-images.githubusercontent.com/1888641/64118121-46050280-cd97-11e9-924e-6ba357962a43.png)

Now I wonder if I should just close this because it would still be interesting to have one more hook such as `onXhrOpenING` which would allow to inspect and change the URL, method and payload of a request before the XMLHttpRequest object is actually created.

Thanks,
Moreno

**Comment by waxidiotic** [comment]
@BrightSoul - We actually use the open source hls.js provider for rendering HLS in browsers that do not natively support it, so they would have to implement that feature. I would recommend opening a feature request on their repo.

https://github.com/video-dev/hls.js/

**Comment by BrightSoul** [comment]
@waxidiotic 
Good, it seems hls.js does allow the interception of requests by using [xhrSetup](https://github.com/video-dev/hls.js/blob/master/docs/API.md#xhrsetup). It's explained in this issue:
https://github.com/video-dev/hls.js/issues/1588

Thanks you, bye.
Moreno
