### ISSUE TITLE
Expose the language attribute on tracks returned by `getCaptionsList()`

### ISSUE THREAD

**Issue by drewwyatt** [jwplayer/jwplayer#3474]
### Expected Behavior

Expose track `language` attribute along with `label` and `id` when calling `getCaptionsList()`.

### Actual Behavior

JWPlayer exposes only `label` and `id`.

- [documentation](https://developer.jwplayer.com/jw-player/docs/javascript-api-reference/#jwplayergetcaptionslist)
- [relevant code](https://github.com/jwplayer/jwplayer/blob/master/src/js/controller/captions.js#L98-L110)

### Motivation

`LANGUAGE` is [part of the HLS specification for alternate media](https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/adding_alternate_media_to_a_playlist) as an optional attribute used to "[identify] the primary language used in the media selection." This differs from `NAME` (returned as `label` by JWPlayer), which the HLS specification indicates is a "[description of] the primary language used in the media selection."

It’s generally good practice to be distinguish a display name (for user presentation) from a programatic identifier, so as to be able to vary these independently. The ability to do so via separate `name` (`label`) and `language` attributes corresponding to the HLS spec is common in video players (examples of some are provided below).

User presentation makes the `NAME` attribute an especially poor candidate for unique language identifiers (like locales) because even in instances where JWPlayer's default UI is being overridden, the `name` attribute will still be exposed to users when the media is played on devices not controlled by JWPlayer (e.g. iOS Safari's web player, Chromecast, AppleTV) where `NAME` is assumed to be user-facing (as the HLS specification suggests). 

### Examples

This behavior can be seen in the following players

- [Brightcove](https://docs.brightcove.com/brightcove-player/current-release/TextTrack.html) via `TextTrack`'s `language` property
- [AVFoundation (iOS/macOS/tvOS/watchOS)](https://developer.apple.com/documentation/avfoundation/avmediaselectionoption) via `AVMediaSelectionOption`'s `locale` property
- [ExoPlayer](https://github.com/google/ExoPlayer/blob/44293e8f45fc62ff918001b4425c44d0ded5ffc9/library/core/src/main/java/com/google/android/exoplayer2/Format.java#L160) via `TrackGroup` `Format`'s `language` property

**Comment by jnatalzia** [comment]
Hi Drew!

First off, thanks for the very detailed ticket; it makes our jobs a lot easier. I've added your feature request to our running list in the [wiki here](https://github.com/jwplayer/jwplayer/wiki/Open-Feature-Requests) and added a ticket to our internal backlong. You can follow along for updates there and I'll post a comment on the ticket if and when the feature get prioritized.

If you have any other questions please let me know. I'm going to mark this as answered as we prefer to track these requests on our internal JIRA board and try to use the issues section as a means for untriaged requests.

Thanks again!

**Comment by drewwyatt** [comment]
Thanks for responding! I opened a PR for this (I mentioned this issue in the description), but don’t have any experience with JWPlayer’s internals (yet). I’m happy to help in any way I can.

**Comment by jnatalzia** [comment]
Even better! Getting some eyes to review it/assess what it could impact. Thanks! Will continue conversation on the PR

**Comment by robwalch** [comment]
I merged the PR. No impact. `undefined` properties are filtered out of the event if language is undefined. Works great if you pass in your own captions tracks with `language`.
