### ISSUE TITLE
Missing DOCTYPE for VPAID ads

### ISSUE THREAD

**Issue by branks** [jwplayer/jwplayer#3500]
### Expected Behavior

When viewing a VPAID ad that renders using html5 standards, the styles on all browsers should be the same

### Actual Behavior

Styles are not displaying as expected as the DOCTYPE is missing so the browser does not know to render as html5

### Steps to reproduce

1. Use a VPAID tag that renders a custom HTML5 video player 
2. The iframe created does not have a DOCTYPE within it, so the inner content is not rendered correctly

**Comment by branks** [comment]
So in our case, the VPAID doesn't create an iframe itself, we just create our divs within the `slot` that is passed to us

If you go here https://developer.jwplayer.com/tools/ad-tester/ and select the VPAID 2 Tag example, click apply and inspect the preview, you can see a div is present with a class `jw-vpaid-wrapper` which contains an iframe. That iframe has no doctype. 

The example VPAID in this solution then creates another iframe within it, which is where the ad runs, but this seems like more of a workaround due to the missing doctype in the base iframe

**Comment by waxidiotic** [comment]
@branks - I see what you are talking about. However, we create that iFrame with `createElement` and then add the script to it with `document.write()`. I am not aware of any way to programmatically add or update the doctype on an iFrame that is created programmatically.

**Comment by branks** [comment]
Something like this would work?
https://stackoverflow.com/questions/14186070/javascript-create-an-iframe-with-strict-doctype

**Comment by waxidiotic** [comment]
@branks - We can take a look. In the meantime, can you provide a URL to a VPAID creative that's styling is being affected by this? It doesn't look like it's having any stylistic affect on the sample VPAID from our Ads Tester.

**Comment by branks** [comment]
I don't have a link I can share right now, however putting in a doctype makes the frame operate in html5 mode and not quirks mode, which means styling is consistent across all browsers, and things that use 100% height render correctly, as 100% of the parent and not 100% of the document size.

You can read more on quirks mode here - https://en.wikipedia.org/wiki/Quirks_mode

**Comment by waxidiotic** [comment]
Hi @branks. I would not be against creating a ticket in our backlog to address this but we would need an ad that exhibits the styling behavior. All of our VPAID test ads create iFrames with the correct DOCTYPE, so we cannot currently reproduce the behavior you are reporting.
