### ISSUE TITLE
Can't play hls stream

### ISSUE THREAD

**Issue by rharunzade** [jwplayer/jwplayer#3505]
Compiled latest version, but player doesn't play hls stream.
I see error: This video file cannot be played. (Error Code: 102630)
https://jsfiddle.net/cvypseoj/

**Comment by waxidiotic** [comment]
Hi @rharunzade - The open-source version of our player does not include the provider used to render HLS or DASH content. For that, you would need the commercial version of the player, available at https://www.jwplayer.com.
