### ISSUE TITLE
Unable to disable auto-pause

### ISSUE THREAD

**Issue by edorivai** [jwplayer/jwplayer#3507]
### Expected Behavior
Setting `autoPause.viewability` to `false` should result in the player continuing playback, despite the tab becoming inactive (i.e. switching to another tab).
```js
player.setup({
  ...
  autoPause: {
    viewability: false,
  }
})
```
Note: I tried setting `autoPause.pauseAds` as well, this doesn't have any effect (as is documented).

### Actual Behavior

Player pauses playback when switching to a different tab.

The player receives a `"pause"` event immediately when switching tabs:
```js
{
  newstate: "paused",
  oldstate: "playing",
  pauseReason: undefined,
  reason: "paused",
  type: "pause",
  viewable: 0
}
```

A current workaround is listening to this `pause` event, checking the `pauseReason`, and immediately invoke `player.play()` if `event.pauseReason !== 'interaction'`:

```js
player.on("pause", e => {
  if (e.pauseReason !== 'interaction') {
    player.play();
  }
});
```

### Steps to reproduce

1. Play any video
2. Switch to a different tab
3. Switch back to the tab with your JW Player
4. Player is now paused

### Environment

- Device type: Laptop/Desktop
- OS: `Linux 4.15.0-64-generic #73~16.04.1-Ubuntu SMP Fri Sep 13 09:56:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Google Chrome: Version 77.0.3865.90 (Official Build) (64-bit)
- JW Player version: `8.11.4`

**Comment by waxidiotic** [comment]
Hi @edorivai - Thanks for reporting this. I'm not seeing the same behavior in Chrome or Firefox on macOS. I'm going to check on Linux and let you know.

**Comment by waxidiotic** [comment]
Hi @edorivai - I just tried in Chrome in Ubuntu 18 and the behavior is not reproducing for me. The content continues to play in the background tab.

Can you provide a URL to the page you are seeing this behavior on?

**Comment by edorivai** [comment]
Hmmmmmmm, that's weird my colleagues are seeing the same behavior on their macs. The page isn't public, so I'll see if I can get a minimal reproduction repo up some time. One thing I can say already is that the player is embedded in a React app, so that might have something to do with it :man_shrugging:

**Comment by waxidiotic** [comment]
@edorivai - Can you try this page in Chrome?

https://waxidiotic.github.io/jw-sandbox/github/3507/

My only guess is that it has something to do with being embedded in React, but we have not heard of any issues before this.

**Comment by edorivai** [comment]
Epic video, yeah it seems to work - the video keeps playing in the background when I switch tabs. Seems like I have some digging to do in our configuration. Thanks @waxidiotic :)

**Comment by waxidiotic** [comment]
Not a problem. Let us know if you have any questions.

**Comment by ashishaugust22** [comment]
Hello @edorivai,
I am also facing the same issue with Vue3. Works fine with @waxidiotic link.
Did you able to figure out the issue?
