### ISSUE TITLE
Duplicate Closed Captions Entries when provided array with single "default" CC file.

### ISSUE THREAD

**Issue by adamellsworth** [jwplayer/jwplayer#3508]
### Expected Behavior

When given the following value for `tracks`, it is expected that the only visible/selectable CC track (assuming it's valid) is the one provided. 

```
tracks = [{
    'file': ourCaptionPath,
    'label': 'English',
    'kind': 'captions',
    'default': true
}]
```

### Actual Behavior

We are seeing two "English" tracks which both reference the same CC file provided:

![Screen Shot 2019-10-18 at 4 05 57 PM](https://user-images.githubusercontent.com/7034617/67133563-38c69a80-f1c2-11e9-9caf-306be85012ad.png)

<img width="748" alt="Screen Shot 2019-10-18 at 4 06 23 PM" src="https://user-images.githubusercontent.com/7034617/67133562-38c69a80-f1c2-11e9-9c90-c0eb110c45cb.png">

### Steps to reproduce

We're not sure if this only us, but to reproduce, you'd just give a config as above with an array of one default CC file, then check to see if more than one entry in the list shows up.

### Environment

- *OSX | 10.14.6*
- *Chrome | 77.0.3865.120, Firefox Dev edition | 71.0b2 (64-bit)*
- *JW Player | Self Hosted | 8.9.3+commercial_v8-9-3.329*

**Comment by waxidiotic** [comment]
Hi @adamellsworth - thanks for the report. Are you able to reproduce on the latest version of the player, currently 8.11.4 (although 8.11.5 may be released by the time you see this comment).

**Comment by adamellsworth** [comment]
@waxidiotic I'm afraid it did not. Still seeing the same behaviour for version `8.11.4+commercial_v8-11-4.360`

**Comment by adamellsworth** [comment]
I forgot to mention that the only way to currently "fix" this in production for us is to unwrap it from the array (below). However, this doesn't allow us to use multiple CC files should our client's need to.

e.g.
```js
tracks = {
    'file': ourCaptionPath,
    'label': 'English',
    'kind': 'captions',
    'default': true
}
```

**Comment by waxidiotic** [comment]
@adamellsworth - I am unable to reproduce this behavior for myself. Please see my test page at:

https://waxidiotic.github.io/jw-sandbox/github/3508/index.html

Would you be able to provide us with a link to a test page so we can see the behavior you are?

**Comment by adamellsworth** [comment]
After some debugging today we found that this is caused by some misconfiguration in our Fastly VCL. Thanks for checking this issue out; I'll close it.

**Comment by waxidiotic** [comment]
No problem, @adamellsworth. Feel free to reach out if you have any other questions.
