### ISSUE TITLE
Memoryleak on Long Running Stream (HLS.js?)

### ISSUE THREAD

**Issue by brudvik** [jwplayer/jwplayer#3510]
### Expected Behavior

Expected behaviour would be to be able to play a long running stream without the browser crashing.

### Actual Behavior

When playing a long-running stream (e.g. several hours) you'll notice that the memory will keep on raising during the entire lifespan of the stream. Eventually, some browsers will crash or be rendered more or less useless as the memory goes too high. HLS.js 0.12.0 introduced a feature (actually a bugfix) to be able to cope with this, but JWPlayer latest (8.11.5) includes HLS.js 0.9.1 according to https://ssl.p.jwpcdn.com/player/v/8.11.5/notice.txt.

Could it be to exposed events? I've seen the discussion in regards of players exposing the HLS.js events, and a potential memory leak. We use the events to trigger certain functions.

### Steps to reproduce

1. Setup JWPlayer, and configure it to attach to onTime.
2. Start a stream.
3. Watch the stream in JWPlayer.
4. Keep an eye on the memory usage.

### Environment

- All browsers affected.
- JWPlayer 8.11.5

**Comment by jnatalzia** [comment]
Hey @brudvik. JW Player relies on a custom fork of hls.js and we it looks like we are running the latest commit in master from that project based on the package.json of `8.11.5` (https://ssl.p.jwpcdn.com/player/v/8.11.5/package.json)

Master in our fork is up to date with v0.12.2 (and then some) so despite the notice we are actually on `0.12`. It looks like that notice is not updated with the new version of the dependency we are using, which is def something to look at. Thanks for the report!
