### ISSUE TITLE
Ability to upload a subtitle

### ISSUE THREAD

**Issue by sandorex** [jwplayer/jwplayer#3518]
I don't quite understand why this option is not already available but i would be quite happy to see it be implemented

**Comment by karimMourra** [comment]
Hi @sandorex could you please clarify what you mean ? We currently support side-loaded captions in the player. Do you mean the ability to upload subtitles to our Dashboard ? 
You can setup a player with captions by adding a tracks array to your playlist items.
i.e. 
```
playerInstance.setup({
    playlist: [{
        file: "/assets/sintel.mp4",
        image: "/assets/sintel.jpg",
        tracks: [{ 
            file: "/assets/captions-en.vtt", 
            label: "English",
            kind: "captions",
            "default": true 
        },{ 
            file: "/assets/captions-fr.vtt", 
            kind: "captions",
            label: "French"
        }]
    }]
});
```
for more info please read https://developer.jwplayer.com/jw-player/docs/javascript-api-reference/#playlist

The following document contains information on how to add captions in our dashboard, and additional ways to setup a player with captions https://support.jwplayer.com/articles/how-to-add-closed-captions
For information on how

**Comment by sandorex** [comment]
To clarify i meant user using the player uploading an additional subtitle, it seems like a feature that wouldn't hurt to include

**Comment by karimMourra** [comment]
@sandorex could you please describe what this interface would look like ? Do you expect an API which would take the file path of a caption file as an argument ?  i.e. `jwplayer.addSubtitle('http://myserver.com/caption.vtt');` 
Also what is the use case for this ? This seems to be a feature that would only benefit viewers who have enough javascript experience and video knowledge to open a debugger and add a captions file to a 3rd party website.

**Comment by 4getit** [comment]
> `jwplayer.addSubtitle('http://myserver.com/caption.vtt');`


Exactly that. Perhaps with a label & returns the new track ID.


Website owners can then write the logic of letting the viewer upload a .vtt/.srt and use above API call to load (and then set) the new track. 


From what I understand, JW Player caption tracks can only be set during the setup so it would help if there was a way to side-load caption tracks on-the-fly (like above).

**Comment by sandorex** [comment]
While api itself isn't a bad idea, why not also add option for uploading captions/subtitle in already existing menu just add `Upload` below `Off` maybe style a bit it so it attracts attention
![screenshot_20191108_170633](https://user-images.githubusercontent.com/18004075/68491045-65faeb80-024a-11ea-9148-8ce69e7b11cb.png)

**Comment by karimMourra** [comment]
@4getit and @sandorex thank you for your feedback! The value of this functionality is not significant enough for us to implement it in the near term. We will keep it in our backlog and consider it when we reevaluate our roadmap. Thank you!

**Comment by geetesh07** [comment]
> @4getit and @sandorex thank you for your feedback! The value of this functionality is not significant enough for us to implement it in the near term. We will keep it in our backlog and consider it when we reevaluate our roadmap. Thank you!

I do think you should implement it now!

**Comment by imperatormk** [comment]
Cmon do it already! Would you consider a PR if I submitted it?
