### ISSUE TITLE
Better handling of rate limiting

### ISSUE THREAD

**Issue by 4getit** [jwplayer/jwplayer#3524]
Since 18, the server is really hammered when viewers drag the timeline around. To keep things under control, rate-limiting by sending 429's (or 503's) would be the solution but the player isn't handling it nicely.

When there were too many 429's, JW Player just dies because it stops retrying.

It would be nice if the player holds off a bit when there was a 429 (or 503).  And perhaps even check for a 'retry-after' header. 

You can see it when you enable rate limiting (that returns 429's) on a HLS stream. Open the XHR requests in the developer console and drag the timeline slider around. At some point, JW Player just stops.

**Comment by vseventer** [comment]
Hi @4getit - could you fill out the template below? I would be interested to see a test page reproducing the behavior you're describing.

```
## Problem Overview
This should be a general overview of the problem you're experiencing. It is important to note that this does not go into the solution you are proposing as that is relegated to a later section.

## Current Solutions or Workarounds
This should describe what current ways exist to get around the problem listed above.

## Proposed solution (optional)
Your idea for how to solve the above problem.

## Examples in the wild (optional)
List some other video players or applications where this feature exists.

## Additional Information (optional)
Anything else that does not fit into the above categories.
```

**Comment by 4getit** [comment]
## Problem Overview
When streaming (HLS in my case) and the user scrubs the seekbar around, tons of requests to the server are fired causing an extremely high load on the server.

## Current Solutions or Workarounds
Enabling Nginx rate limiting prevents problems on the server. However, JW Player isn't properly handling the 429's or 503's coming back from the server. After some (random?) time JW Player just stops sending new requests if it has gotten too many 429's or 503's.

## Proposed solution (optional)
- When JW Player receives a 429 or 503, back off for at least 200(?)Ms before sending the next request. If the server returns a Retry-After header, properly pause the time that is set in that header.
- Another solution would be is to just wait with new requests until the user stopped scrubbing the seekbar.

## Examples in the wild (optional)
JW Player versions before version 8 didn't have this problem because it didn't fire requests like crazy when scrubbing the seekbar. I think it either had a build in delay between sending requests or it just reacted slower on seekbar changes.

## Additional Information (optional)
none
