### ISSUE TITLE
Fragment loop when change to full screen

### ISSUE THREAD

**Issue by viet1pro** [jwplayer/jwplayer#3532]
### Expected Behavior

HLS still play when change to full screen

### Actual Behavior

When change to full screen, the player will stuck loop loading 2 segments

### Environment

- Windows 10  v1903
- Google Chrome | 78.0.3904.97
- JW Player version: 8.11.7
- HLS segment duration: 0.5 seconds

Test M3U8 URL: https://anime.viet1.tk/3/3.m3u8

I think it have some similar with #2543 but in my case it only happen when change to full screen

**Comment by vseventer** [comment]
Hi @viet1pro, thank you for this bug report - I was able to reproduce and transferred the issue to our internal backlog. We will prioritize along with other work we are looking to get done.
