### ISSUE TITLE
Question: Bitrate Switching

### ISSUE THREAD

**Issue by Teranode** [jwplayer/jwplayer#3533]
Is it possible to limit the quality in which the bitrate will be selected. For instance, lets say that the hls m3u8 file contains: 1080p,720p,480p,360p

If I did this, then "visually" the 1080p option would be omitted:

```
jwplayer().on('levels', (e) => {
    if(e.levels[1].label === '1080p') {
         delete e.levels[1]
     }
})
```
however whatever method changes during the visualQuality will automatically select the "highest" quality available from the hls stream which would be the 1080p, completely bypassing the removal of the label.

**Comment by robwalch** [comment]
Hi @Teranode,

Deleting a level from an event object does not remove the stream rendition. In “auto” mode the player picks the best quality based on measured bandwidth, limited by the player’s size.

Renditions cannot be removed using the player API, but you can select a fixed level for playback with jwplayer().setCurrentQuality(index).
