### ISSUE TITLE
localization > liveBroadcast - text wrap on fullscreen 

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#3537]
### Expected Behavior

<img width="490" alt="ok" src="https://user-images.githubusercontent.com/9075761/69633695-0590ea00-1051-11ea-9144-f5a27e961f2e.png">

### Actual Behavior
Text wrapping in full-screen mode or on the large monitor.
<img width="520" alt="bad" src="https://user-images.githubusercontent.com/9075761/69633684-fdd14580-1050-11ea-8c3a-370fe6612179.png">

### Steps to reproduce

```
{
  "file": "https://wowzaec2demo.streamlock.net/live/bigbuckbunny/playlist.m3u8",
  "localization": {
    "liveBroadcast": "Lorem Ipsum is simply"
  }
}
```

### Environment
- *operating system | version* MacOs 10.15.1
- *browser | version* Chrome 78, Safari 13 
- *JW Player version* 8.11.8

**Comment by vseventer** [comment]
Hi @mtoczko, thanks for reporting this, I'm able to reproduce. I've transferred this ticket to our internal backlog and we will prioritize it together with all the other work we have planned.
