### ISSUE TITLE
JW Player has no means to start or stop embedded media at a time offset defined as URL parameter

### ISSUE THREAD

**Issue by idea--list** [jwplayer/jwplayer#3538]
### Expected Behavior

JW player should be able to start playing media content from 3rd party server from and to a time offset given in URL parameters when embedded in an iframe like that:
<iframe src="https://somecdn.com/embed/2448020?start=30&stop=55"></iframe>
This is really unique as any other media platform has that feature (like youtube, vimeo, etc.)

### Actual Behavior

The above scenario is not the same as described here:
https://www.jwplayer.com/developers/web-player-demos/linking-to-time-offset/#t=15
(As this scenario does only work on media that you host on your own server but is completely useless in case of media embedded with an iframe from a server that you can not control)

**Comment by vseventer** [comment]
Hi @idea--list - this idea is already in our internal backlog, and we will prioritize along with other work we are looking to get done.
