### ISSUE TITLE
HLS stop play when change quality

### ISSUE THREAD

**Issue by viet1pro** [jwplayer/jwplayer#3540]
### Expected Behavior
HLS still play when change quality
### Actual Behavior
When change quality, the player will stop loading.
### Environment

- Windows 10 v1903
- Google Chrome | 78.0.3904.108
- JW Player version: 8.11.10
- HLS segment duration: 0.5 seconds
- Config:
```
file: "https://anime.viet1.tk/3/3.m3u8",
preload: "auto",
aboutlink: "",
"cast": {}
```
Test M3U8 URL: https://anime.viet1.tk/3/3.m3u8

I noticed that I need to refresh page to make the player continue play with new quality.
I had tried on video-dev/hls.js and don't have this problem.

**Comment by zetagame** [comment]
I was able to reproduce this on video-dev/hls.js, in castr the stream doesn't play at all, in bitmovin it jumps and buffers every few seconds. Is it possible there's an issue with the manifest or encoding?

**Comment by viet1pro** [comment]
I just have problem with JWPlayer. 
Other HLS like "video-dev/hls.js" or "bitmovin" can still play.

**Comment by waxidiotic** [comment]
Hi @viet1pro - I am seeing the same behavior as @zetagame. When I switch the qualities when playing your stream on HLS.js's demo player, I also see the player stalling due to a low buffer.

I would recommend taking a look at the encoding of the stream.

**Comment by viet1pro** [comment]
My current fixing is just increase segments time from 1s to 6s.

**Comment by viet1pro** [comment]
But my goal is lower them

**Comment by waxidiotic** [comment]
That does make sense, but is not something I thought of because you originally said your segments were five seconds long, which is a good amount.

We are working on more improvements to support low-latency HLS streaming and CMAF, but nothing is finalized yet.
