### ISSUE TITLE
User views restricting setting

### ISSUE THREAD

**Issue by ashishhbh** [jwplayer/jwplayer#3546]
### Expected Behavior

*Describe expected behavior*

### Actual Behavior

*Describe actual behavior*

### Steps to reproduce

1.
2.
3.

### Environment

- *hardware | device*
- *operating system | version*
- *browser | version*
- *JW Player version | url*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by ashishhbh** [comment]
Hi , we are looking for someone who can help us in customization the settings of the Jw Player app. Let me share the complete requirement with you - Actually we are using a litmos platform ( Third Party Application) to host our training videos so litmos platform play our video in JW player app by default. We want to setup any setting through we can resctrict the  number of views on our single video by a single user. Currently a user can watch our video unlimited number of times so we want to restrcit this setting so that user can watch the single video only limited no of times like 3 or 4 times

I have talked with the JW player support team and tehy have to told me that "This would be something you would have to add on our end. For example, in our database, a user can be assigned a view count, and if their view count is > 3, you can choose to not embed the JW Player on the page"  . So this is the reason i am reaching out to you.


Please let us know if you can help us in this

**Comment by zetagame** [comment]
This isn't a feature out-of-the-box, but this could be achieved by utilizing localStorage and JWPlayer's API: https://developer.jwplayer.com/jwplayer/docs/jw8-javascript-api-reference
