### ISSUE TITLE
JWPlayer is not working on Chrome iOS Responsive Emulator and Android Emulator (Error Code: 102630)

### ISSUE THREAD

**Issue by dusan-l9** [jwplayer/jwplayer#3554]
### Actual Behavior

JWPlayer is not working when used in:

* Chrome Responsive Emulator - Any of the iOS devices (iPhone 5/SE, iPhone 6/7/8...)
* Android Emulator
* Maybe other places as well

We use it in a Ionic 4 mobile application, but the player doesn't even work on the **Stream Test** page.

### Steps to reproduce

1. Open the **JWPlayer Stream Test** page: https://www.jwplayer.com/developers/stream-tester/
2. Use the default **file URL**: https://content.jwplatform.com/manifests/yp34SRmf.m3u8
3. The stream works in normal conditions
4. Now, open the **Chrome Developer Tools**, activate the **Device Toolbar** and choose **iPhone 6/7/8** for example.
5. Refresh the page to re-start the stream.
6. Now it doesn't work and a generic, non-helpful error is displayed:

```
This video file cannot be played. (Error Code: 102630)
```

The same error happens on the Android Emulator as well.

### Environment

- *Lenovo ThinkPad L580*
- *Linux 4.15.0-72-generic #81-Ubuntu x86_64 GNU/Linux*
- *Chrome Browser (Responsive Emulator) - Version 79.0.3945.79 (Official Build) (64-bit)*
- *JW Player v8.11.10 | https://www.jwplayer.com/developers/stream-tester/*

### Screenshot:

<a href="https://ibb.co/PwdXQ5n"><img src="https://i.ibb.co/f4s6vC5/image.png"></a>

**Comment by zetagame** [comment]
Chrome Inspector changes the userAgent and the screen size, but you're still on the javascript engine of whatever browser you're using (Chrome). So the player might think you can use a specific browser API/feature based on the userAgent provided by the simulator, but it isn't available on the actual browser you're using.

I'd recommend using Xcode for simulating iOS devices/browsers, as it's much closer to an accurate simulation.
