### ISSUE TITLE
Player events beforePlay, onPlay, firstFrame doesn't work on HLS videos

### ISSUE THREAD

**Issue by chuxolatouz** [jwplayer/jwplayer#3584]
I'm using JWPlayer to reproduce a playlist with m3u8 format.
i have a console.log statement on each event handlers closer to play a video (in specific beforePlay, onPlay and firstFrame) using jwplayer API. 

i want to execute a seek function to set a specific time in the video (into the beforePlay event)
So as m3u8 format is streaming that functions are execute before the videos are loaded into the player. 

### Expected Behavior

Play any HLS video under m3u8 and player events to be executed as expected (beforePlay, onPlay, firstFrame)

- video is loaded
- beforePlay() -> seek(T) 
- onPlay() 
- video start from T time on realtime
- firstFrame()

### Actual Behavior

Player events like 'firstFrame' or 'onPlay' are executed before buffering and not as it's to be expected

runtime:
- beforePlay() -> seek(T)
- onPlay() 
- firstFrame()
- video is loaded
- video start from 0 time on realtime

### Steps to reproduce

1. Playlist with m3u8
2. Reproduce playlist
3. Show how HLS doesn't work as expected 

### Environment
- *High Sierra, Windows 10 and Ubuntu 18.04 | version*
- *Chrome, Safari and Firefox | version*
- *JW Player version | 7.12.13*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by mamaddox** [comment]
Hi @chuxolatouz 
I noticed that you were using version 7.12.13 of the player. 
This issue has been fixed in later versions so I would recommend upgrading your player if possible.
