### ISSUE TITLE
Buffering issues with DSL connection and quality set to auto

### ISSUE THREAD

**Issue by PascalThuet** [jwplayer/jwplayer#3587]
### Expected Behavior

Player should play adaptive HLS streaming without any buffering. When quality set to "auto', player should select the best quality depending on the available connectivity

### Actual Behavior

Player is buffering every 10 - 30 sec. By looking at the network under chrome developer tools, we can see that the same chunks are downloaded multiple times and that quality is always switching.

By switching to a given quality, including the highest available, the file is played without any buffering.

By opening the same file with Bitmovin / HLSJS Demo page, the stream is played without any buffering under the same network condition

### Steps to reproduce

1. Go to the JWPlyaer test player
2. Simulate bad network condition with Chrome Developper tools or have a DSL connection with approx 5-6 Mbps
3. Open this file https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/master.m3u8 
4. Set the quality to auto
5. File will be played with non stop buffering
6. Open the Chrome developer tools you will see multiple chunk downloaded multiple times

### Environment

- *hardware | device* : Macbook
- *operating system | version* : Chrome / Safari under MacOS
- *browser | version* Chrome latest
- *JW Player version | url* : JWPlayer latest on JWPlater test URL

![Capture d’écran 2020-01-26 à 22 10 20](https://user-images.githubusercontent.com/2512445/73306983-9d5faf80-421d-11ea-8edc-8941a1768f1d.png)

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
@PascalThuet This is an issue with hls.js, your stream and the connection you are testing onvideo-.

I suggest reporting this issue in hls.js https://github.com/video-dev/hls.js where the adaptive bitrate switching is implemented.

I ran your stream through Apple's `mediastreamvalidator` and it shows that the bandwidth estimates for the levels in your stream have a high margin of error. This will cause hls.js to adapt to levels it can't play, which is likely why you see segments getting re-downloaded. (See `--> Detail:  Measured: 1439.48 kb/s, Master playlist: 404.00 kb/s, Error: 256.31%`)


``
$ mediastreamvalidator https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/master.m3u8                                                 [ruby-2.1.3]
mediastreamvalidator: Version 1.2 (373.7-180828)
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/master.m3u8] Started root playlist download
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_1_av.m3u8] Started media playlist download
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_0_av.m3u8] Started media playlist download
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_a.m3u8] Started media playlist download
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_av.m3u8] Started media playlist download
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_2_av.m3u8] Started media playlist download
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_a.m3u8] parsed media segment count: 29, duration: 300.000
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_av.m3u8] parsed media segment count: 29, duration: 300.000
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_a.m3u8] parsed media segment count: 59, duration: 600.000
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_a.m3u8] All media files delivered and have end tag, stopping
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_2_av.m3u8] parsed media segment count: 29, duration: 300.000
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_av.m3u8] parsed media segment count: 59, duration: 600.000
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_0_av.m3u8] parsed media segment count: 29, duration: 300.000
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_av.m3u8] All media files delivered and have end tag, stopping
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_2_av.m3u8] parsed media segment count: 59, duration: 600.000
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_2_av.m3u8] All media files delivered and have end tag, stopping
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_0_av.m3u8] parsed media segment count: 59, duration: 600.000
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_1_av.m3u8] parsed media segment count: 29, duration: 300.000
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_0_av.m3u8] All media files delivered and have end tag, stopping
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_1_av.m3u8] parsed media segment count: 59, duration: 600.000
[/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_1_av.m3u8] All media files delivered and have end tag, stopping

--------------------------------------------------------------------------------
https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_1_av.m3u8
--------------------------------------------------------------------------------
Processed 68 out of 68 segments
Average segment duration: 9.943529
Total segment bitrates (all discontinuities): average: 2617.11 kb/s, max: 4048.02 kb/s
Playlist max bitrate: 2518.000000 kb/s


Discontinuity: sequence: 0, parsed segment count: 68 of 68, duration: 676.160 sec, average: 2617.11 kb/s, max: 4048.02 kb/s
Track ID: 1
Video Codec: avc1
Video profile: Main
Video level: 3.1
Video resolution: 1280x720
Video average IDR interval: 1.217946, Standard deviation: 0.291967
Video frame rate: 25.000
Track ID: 2
Audio Codec: AAC-LC
Audio sample rate: 48000 Hz
Audio channels: 2
Audio channel layout: Stereo (L R)

--------------------------------------------------------------------------------
https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_0_av.m3u8
--------------------------------------------------------------------------------
Processed 68 out of 68 segments
Average segment duration: 9.943529
Total segment bitrates (all discontinuities): average: 1824.06 kb/s, max: 2842.41 kb/s
Playlist max bitrate: 1742.000000 kb/s


Discontinuity: sequence: 0, parsed segment count: 68 of 68, duration: 676.160 sec, average: 1824.06 kb/s, max: 2842.41 kb/s
Track ID: 1
Video Codec: avc1
Video profile: Main
Video level: 3
Video resolution: 720x406
Video average IDR interval: 1.224565, Standard deviation: 0.280015
Video frame rate: 25.000
Track ID: 2
Audio Codec: AAC-LC
Audio sample rate: 48000 Hz
Audio channels: 2
Audio channel layout: Stereo (L R)

--------------------------------------------------------------------------------
https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_a.m3u8
--------------------------------------------------------------------------------
Processed 68 out of 68 segments
Average segment duration: 9.943529
Total segment bitrates (all discontinuities): average: 74.84 kb/s, max: 75.05 kb/s
Playlist max bitrate: 61.000000 kb/s


Discontinuity: sequence: 0, parsed segment count: 68 of 68, duration: 676.160 sec, average: 74.84 kb/s, max: 75.05 kb/s
Track ID: 1
Audio Codec: AAC-LC
Audio sample rate: 48000 Hz
Audio channels: 2
Audio channel layout: Stereo (L R)

--------------------------------------------------------------------------------
https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_av.m3u8
--------------------------------------------------------------------------------
Processed 68 out of 68 segments
Average segment duration: 9.943529
Total segment bitrates (all discontinuities): average: 452.57 kb/s, max: 1439.48 kb/s
Playlist max bitrate: 404.000000 kb/s


Discontinuity: sequence: 0, parsed segment count: 68 of 68, duration: 676.160 sec, average: 452.57 kb/s, max: 1439.48 kb/s
Track ID: 1
Video Codec: avc1
Video profile: Baseline
Video level: 1.3
Video resolution: 384x216
Video average IDR interval: 1.200639, Standard deviation: 0.307966
Video frame rate: 25.000
Track ID: 2
Audio Codec: AAC-LC
Audio sample rate: 48000 Hz
Audio channels: 2
Audio channel layout: Stereo (L R)

--------------------------------------------------------------------------------
https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_2_av.m3u8
--------------------------------------------------------------------------------
Processed 68 out of 68 segments
Average segment duration: 9.943529
Total segment bitrates (all discontinuities): average: 997.33 kb/s, max: 1427.15 kb/s
Playlist max bitrate: 933.000000 kb/s


Discontinuity: sequence: 0, parsed segment count: 68 of 68, duration: 676.160 sec, average: 997.33 kb/s, max: 1427.15 kb/s
Track ID: 1
Video Codec: avc1
Video profile: Main
Video level: 3.1
Video resolution: 640x360
Video average IDR interval: 1.220144, Standard deviation: 0.286941
Video frame rate: 25.000
Track ID: 2
Audio Codec: AAC-LC
Audio sample rate: 48000 Hz
Audio channels: 2
Audio channel layout: Stereo (L R)

--------------------------------------------------------------------------------
MUST fix issues
--------------------------------------------------------------------------------

Error: Measured peak bitrate compared to master playlist declared value exceeds error tolerance
--> Detail:  Measured: 4048.02 kb/s, Master playlist: 2518.00 kb/s, Error: 60.76%
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/master.m3u8
--> Compare: https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_1_av.m3u8

--> Detail:  Measured: 2842.41 kb/s, Master playlist: 1742.00 kb/s, Error: 63.17%
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/master.m3u8
--> Compare: https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_0_av.m3u8

--> Detail:  Measured: 75.05 kb/s, Master playlist: 61.00 kb/s, Error: 23.03%
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/master.m3u8
--> Compare: https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_a.m3u8

--> Detail:  Measured: 1439.48 kb/s, Master playlist: 404.00 kb/s, Error: 256.31%
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/master.m3u8
--> Compare: https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_av.m3u8

--> Detail:  Measured: 1427.15 kb/s, Master playlist: 933.00 kb/s, Error: 52.96%
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/master.m3u8
--> Compare: https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_2_av.m3u8

Error: Old codec format (RFC 4281) subelements found. Use format specified by RFC 6381
--> Detail:  Subelements: 77.30
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/master.m3u8
--> Compare: https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_0_av.m3u8

--> Detail:  Subelements: 77.30
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/master.m3u8
--> Compare: https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_1_av.m3u8

--> Detail:  Subelements: 77.30
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/master.m3u8
--> Compare: https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_2_av.m3u8

--> Detail:  Subelements: 66.30
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/master.m3u8
--> Compare: https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_av.m3u8

--------------------------------------------------------------------------------
SHOULD fix issues
--------------------------------------------------------------------------------

Warning: #EXT-X-ALLOW-CACHE has been deprecated
--> Detail:  Line: #EXT-X-ALLOW-CACHE:YES
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_1_av.m3u8

--> Detail:  Line: #EXT-X-ALLOW-CACHE:YES
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_0_av.m3u8

--> Detail:  Line: #EXT-X-ALLOW-CACHE:YES
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_a.m3u8

--> Detail:  Line: #EXT-X-ALLOW-CACHE:YES
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_3_av.m3u8

--> Detail:  Line: #EXT-X-ALLOW-CACHE:YES
--> Source:  https://arteconcert-vh.akamaihd.net/i/am/concert/093000/093100/093186-000-A_0_VO_AMM-CONCERT-NEXT_XQ.1Enmr17NVlm.smil/index_2_av.m3u8
```

**Comment by robwalch** [comment]
I'm also noticing something about the stream that is triggering "back tracking" in hls.js. This is likely because the segments do not start with keyframes. As a result, hls.js cannot switch on the next segment. It tries, but then has to back track to get a keyframe in the previous segment in order for the new quality to overlap with what was previously buffered.

```
[warn] > [stream-controller]: Fragment 3 of level 3 is missing 28 video frame(s); backtracking to find a keyframe
```

Because of this your stream requires even more bandwidth than advertised. This is not something we would be able to resolve. You should contact akamai about re-configuring and re-encoding this stream to address these issues as that will drastically improve performance in any environment (Safari, hls.js etc...)

**Comment by PascalThuet** [comment]
Many thanks for your answer. 
I will open an issue in HLSJS. But strangely on the HLS.JS Test player we do not experience the same issue as on JWPlayer. Are there any additional logic implemented on JWPlayer side that can explain the behavior differences ?

**Comment by robwalch** [comment]
I was able to reproduce the issue in hls.js. Perhaps you tested without automatic bitrate switching enabled? If you select a quality then all of the issues we’ve discussed are avoided.
