### ISSUE TITLE
 Unable to get property 'className' of undefined or null reference

### ISSUE THREAD

**Issue by esetnik** [jwplayer/jwplayer#3590]
### Expected Behavior
No crash on supported browser
Edge
Version: 18.18362

### Actual Behavior
Sentry reports an error `Unable to get property 'className' of undefined or null reference` in `{snip} turn t+(t.toString().indexOf("%")>0?"":"px")}function h(t){return Object(i.x)(t.className)?t.className.split(" "):[]}function v(t,e){e=Objec {snip}`

### Steps to reproduce
Unknown

### Environment
- *Windows 10*
- *Edge 18.18362*
- *v8.12.4*

Appears to be caused by an undefined or null reference passed to https://github.com/jwplayer/jwplayer/blob/2707d144d0682100379d4ab31d6027c272ed39c6/src/js/utils/dom.js#L85

Stacktrace:
```
TypeError: Unable to get property 'className' of undefined or null reference
  at h(/libraries/N0kKSNrZ.js:11:23014)
  at m(/libraries/N0kKSNrZ.js:11:23334)
  at value(/player/v/8.12.4/jwplayer.core.controls.html5.js:10:46439)
  at hideMenuHandler(/player/v/8.12.4/jwplayer.core.controls.html5.js:10:47125)
  at u(/static/js/2.857ca1be.chunk.js:1:270286)
```

**Comment by robwalch** [comment]
Thanks @esetnik. We'll have a look at that `hideMenuHandler`. These utils expect valid elements, and shouldn't be called with undefined arguments. cc @zetagame

**Comment by zetagame** [comment]
Hey @esetnik! Do you have any more info? Have a couple ideas of how this could surface, but steps to reproduce would be very helpful. Thanks!

**Comment by esetnik** [comment]
I haven’t identified str yet but I am using `micnews/react-jw-player` if it’s helpful information.

**Comment by zetagame** [comment]
Here's some more info for the time being:

The issue appears to be surfacing from rightclick.js:
![image](https://user-images.githubusercontent.com/2903955/74070753-ec50d600-49cf-11ea-98aa-eb46978d2e37.png)


Either the playerContainer or the right click menu isn't present at the time hideMenu is called, which is throwing the exception. Hope that helps scope the str for you :)
