### ISSUE TITLE
[Not an Issue] Taking on maintainer-ship of React-JW-Player!

### ISSUE THREAD

**Issue by danmakenoise** [jwplayer/jwplayer#3591]
Hey JW Player team!

I used to work for Mic, where we created the `react-jw-player` [library](https://github.com/micnews/react-jw-player) that has a some decent usage among your clients. I am no longer able to maintain that repository effectively, and am wondering if the JW Player team is interested in taking control. Let me know, and sorry for using Issues for this question, but it seemed the most effective way to get a conversation going.

**Comment by monibons** [comment]
Hey Dan,
Thanks for reaching out. We are big fans of your react web player component so hopefully we can preserve this as, we agree, it's very useful for other customers. We'll review internally and let you know if we need anything from you.

Thanks!

**Comment by danmakenoise** [comment]
@monibons any update on whether you all want to take this on or not? Just trying to find a solution for current users here!

**Comment by wsaun-edh** [comment]
Is anyone taking pull requests for this?

**Comment by robwalch** [comment]
@danmakenoise If the offer is still on the table I would be willing to take on a maintainer role in the project. Just send me an invite. Thanks!
