### ISSUE TITLE
How can I use AES on Safari?

### ISSUE THREAD

**Issue by viet1pro** [jwplayer/jwplayer#3611]
My videos encrypt with AES but I read that
![image](https://user-images.githubusercontent.com/29736874/74909884-ce319f80-53eb-11ea-9039-7a695c9d73e9.png)
So how can i use AES HLS on Safari?

**Comment by jnatalzia** [comment]
Hi @viet1pro! If I recall that portion of the docs correctly, that is in relation to the explicit `aestoken` config option. If your tokens are embedded in your HLS manifest as many are, safari parses that natively to my knowledge. What is not supported is passing your own token through JW's config
