### ISSUE TITLE
Whitelisting more Hls.js configs

### ISSUE THREAD

**Issue by mrbar42** [jwplayer/jwplayer#3612]
We would like to be able to better tune hls.js through its config.
At the moment only a subset of the configs are actually passed on to the `Hls` constructor most of which are around liveSync and other latency related knobs.

We would like to be able to override the [`loader` config](https://github.com/video-dev/hls.js/blob/12f2e164674b5466e23665183792c144af147c71/src/config.ts#L210) for the sake of interacting with the network stack of the player.

example:
```js
{
  hlsjsConfig: {
    loader: customLoader
  }
}
```

**Comment by robwalch** [comment]
@mrbar42 This should land in v8.14.0.
