### ISSUE TITLE
How to force hls.js usage on Amazon Echo Show (AlexaWebMediaPlayer)

### ISSUE THREAD

**Issue by kasty** [jwplayer/jwplayer#3621]
### Expected Behavior

I'm trying to use our video player based on jwplayer in a video skill on an Amazon Echo Show device. It's based on Android 5.1.1 and the userAgent is `AlexaWebMediaPlayer/1.0.201891.0 (Linux;Android 5.1.1)`. I want to play some HLS videos. Here's an example : https://arteptweb-vh.akamaihd.net/i/am/ptweb/089000/089000/089059-000-A_0_VF-STF_AMM-PTWEB_XQ.1IOPrEtPNs.smil/master.m3u8

### Actual Behavior

No matter what I try to set in the config it's "html5" provider that is used to decode the HLS file and it doesn't work well. No sound, image is freezing, the onTime event is not working correctly (triggered only once per 20 sec) etc.

How can I force the jwplayer to use hls.js provider ?

I tried this config :
```
androidhls: true,
hlsjsdefault: true,
hlshtml: false
```

=> The video is playing but with the problems explained above

and also 
```
androidhls: false,
hlsjsdefault: true,
hlshtml: false
```

=> SetupError #102630 ("This video file cannot be played.")

### Environment

- Amazon Echo Show 2nd gen
- Fire OS 5.5.3.6 (651614220)
- AlexaWebMediaPlayer/1.0.201891.0 (Linux;Android 5.1.1)
- jwplayer 8.11.5
- jwplayer().getEnvironnement() :
```
{
    "Browser": {
        "androidNative": true,
        "chrome": false,
        "edge": false,
        "facebook": false,
        "firefox": false,
        "ie": false,
        "msie": false,
        "safari": false,
        "version": {
            "version": undefined,
            "major": undefined,
            "minor": undefined
        }
    },
    "OS": {
        "android": true,
        "iOS": false,
        "mobile": true,
        "mac": false,
        "iPad": false,
        "iPhone": false,
        "windows": false,
        "version": {
            "version": "5.1.1",
            "major": 5,
            "minor": 1
        }
    },
    "Features": {
        "flash": false,
        "flashVersion": 0,
        "iframe": false,
        "passiveEvents": true,
        "backgroundLoading": true
    }
}
```

**Comment by privaloops** [comment]
@kasty can you post manifest URL ?

**Comment by robwalch** [comment]
@kasty Does hls.js standalone work and `Hls.isSupported()` return `true` on the device?

> I tried this config :
> ```
> androidhls: true,
> hlsjsdefault: true,
> hlshtml: false
> ```

You are on the right track, but the hls(.js) support check requires that MSE APIs be present in order for hls.js to work. If not, the API hls.js depends on are not present, and hls.js playback is not possible. This is generally the case with Android 5.

hls.js isSupported check:
https://github.com/video-dev/hls.js/blob/v0.13.2/src/is-supported.ts

jwplayer hlsjs provider supports check:
```js
function hlsSupports (source) {
    // hls.js does not support DRM
    if (source.drm) {
        return false;
    }

    const validExtension = source.file.indexOf('.m3u8') > -1;
    const validMediaType = source.type === 'hls' || source.type === 'm3u8';

    if (!validExtension && !validMediaType) {
        return false;
    }

    // hls.js is supported for Desktop Chrome, Firefox, IE11 & Edge by default.
    // Android Chrome & Desktop Safari are supported if the appropriate flag is set.
    const supportedBrowser = Browser.chrome || Browser.firefox || Browser.edge || (Browser.ie && Browser.version.major === 11);
    const disableAndroid = OS.android && (source.hlsjsdefault === false);
    const forceSafari = Browser.safari && !!source.safarihlsjs;

    // Used to check if MediaSource is supported with at least the most basic codecs
    const supportsTypes = supportsMediaTypes(source.mediaTypes || ['video/mp4;codecs="avc1.4d400d,mp4a.40.2"']);

    return supportsTypes && (supportedBrowser || forceSafari) && !disableAndroid;
}

function supportsMediaTypes(mediaTypes) {
    const mse = window.MediaSource;
    // returns true when mediaTypes is undefined or empty
    return all(mediaTypes, (type) => !!mse && !!mse.isTypeSupported && mse.isTypeSupported(type));
}
```

So if `window.MediaSource` and `MediaSource.isTypeSupported` are available, but is failing for `'video/mp4;codecs="avc1.4d400d,mp4a.40.2"'`, you could try setting playlist item source `mediaTypes` to a supported codec string that matches your stream and is supported by the device.

**Comment by kasty** [comment]
Hi @robwalch,

Well, I've run the tests you told on the Amazon device, here are my results :
```
Hls.isSupported() : true
typeof window.MediaSource : function
window.MediaSource.isTypeSupported('video/mp4;codecs="avc1.4d400d,mp4a.40.2"') : true
```
Playing the video with the standolone Hls.js is working perfectly.

Looking at your code from jwplayer I think the `hlsSupports()` returns `false` because of `supportedBrowser` that must be `false` (check at the jwplayer().getEnvironnement() in my first message)

Is there any chance that this browser might be supported soon ? 

Here are the details of the navigator :
```
window.navigator.userAgent : AlexaWebMediaPlayer/1.0.201891.0 (Linux;Android 5.1.1)
window.navigator.appName : Netscape
window.navigator.appCodeName : Mozilla
```

Thanks

**Comment by robwalch** [comment]
Thanks @kasty,

We can make a change so that `hlsjsdefault` opens up hls.js usage on more browsers. The idea of gating hls.js to major browsers is that we do not want it running on browsers we do not test on, and falling back to an mp4 source might be more reliable. That said we should let you run it at your own risk if that's what you want.

(I have a lot of Amazon Echos 🔈🎤 at home, but no Echo Show 📺 - Is it good?)

We plan to change this `hlsSupports` check to open up HLS playback on Tizen and improve support there. I don't have a timeline yet but stay tuned. It's not something we would ungate completely because then we end up with lots of support requests where mp4 fallback was working with our platform embeds, and suddenly would not on odd browsers.

**Comment by robwalch** [comment]
Closing since `hlsjsdefault: true` works when MSE is available. If the MSE check does not pass, hls.js is not supported.
