### ISSUE TITLE
HLS autoselect track should be selected

### ISSUE THREAD

**Issue by privaloops** [jwplayer/jwplayer#3629]
### Expected Behavior

Player should select the caption by default

### Actual Behavior

Caption is set to off

### Steps to reproduce

Load this manifest with jwplayer https://arte-cmafhls.akamaized.net/am/cmaf/091000/091100/091152-037-A/200226143143/091152-037-A_VOF-STMF_XQ.m3u8 . Subtitle track has AUTOSELECT attribute set to YES but it's not loaded, user has to choose it manually

### Environment

MacBookPro11,5 Quad-Core Intel Core i7
MacOS Catalina 10.15.3
Version 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
jwplayer 8.11.5

**Comment by robwalch** [comment]
Thanks for reporting an issue @privaloops.

Are you experiencing this in both Safari and Chrome, or just one of the two?

**Comment by robwalch** [comment]
What the HLS spec says
```
      DEFAULT

      The value is an enumerated-string; valid strings are YES and NO.
      If the value is YES, then the client SHOULD play this Rendition of
      the content in the absence of information from the user indicating
      a different choice.  This attribute is OPTIONAL.  Its absence
      indicates an implicit value of NO.

      AUTOSELECT

      The value is an enumerated-string; valid strings are YES and NO.
      This attribute is OPTIONAL.  Its absence indicates an implicit
      value of NO.  If the value is YES, then the client MAY choose to
      play this Rendition in the absence of explicit user preference
      because it matches the current playback environment, such as
      chosen system language.

      If the AUTOSELECT attribute is present, its value MUST be YES if
      the value of the DEFAULT attribute is YES.
```
One of the issues is, if you've used JW Player to watch content without captions we may have stored that as a preference.

If you want captions to be displayed when the user has never made a choice to view them, you should set both `DEFAULT` and  `AUTOSELECT` to `YES`. We would still want to verify that this results in the captions being displayed in Safari, where we don't have access to the manifest and depend on video tag behavior, before making changes to hls.js to do the same thing.
