### ISSUE TITLE
Wowza security token is not supported in the this opensource free edition?

### ISSUE THREAD

**Issue by openaspace** [jwplayer/jwplayer#3635]
Hi. 
I want to set WOWZA security token but i don't find the files and folders from the wowza guide.
https://www.wowza.com/docs/how-to-add-securetoken-protection-to-jw-player

This version don't support wowza security token?

Thank you.

**Comment by jnatalzia** [comment]
Hi @openaspace , the docs you linked state `For use with JW Player 6 and Wowza Streaming Engine™ media server software.` - are you trying this with the latest player version? Based on the fact that this references JW6, I'm inclined to think these docs are old and possibly out of date
