### ISSUE TITLE
Subtitle Settings - keyboard control

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#3645]
### Expected Behavior
After pressing esc I should go back to the previous menu.

### Actual Behavior

<img width="295" alt="Zrzut ekranu 2020-03-24 o 22 35 19" src="https://user-images.githubusercontent.com/9075761/77479320-da13e580-6e1f-11ea-8a5e-aa55a9826018.png">

### Steps to reproduce

1. https://www.jwplayer.com/developers/web-player-demos/closed-captions/
2.  `Setting > Closed Captions > [↓](settings) > [Enter] > [Enter](Font Color) > [ESC]`
3. `Setting > Quality> [↓] > [↓] (720p or 480p) > [Enter] ` 
4. `Setting > Quality> (720p or 480p)`  - Use mouse

### Environment

- *operating system | version* MacOS 10.15.3
- *browser | version* Chrome 80
- *JW Player version | url* 8.13.0

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by mamaddox** [comment]
Hi @mtoczko!
Thank you for the catch! I was able to recreate and this is definitely a bug. I created a bug ticket and added it to our internal backlog. I can't give an immediate estimate on when a fix will be in place, but we'll prioritize it with our other work.

**Comment by mtoczko** [comment]
Hi @mamaddox 
There are updates for this bug?

**Comment by mamaddox** [comment]
Hi @mtoczko,
Unfortunately, no updates yet. We currently don't have a fix version for this, but once we do, I'll tag this issue.

**Comment by mtoczko** [comment]
Hi @aliciahurst,
Can you look at this bug? The keyboard control is not working properly.

**Comment by mtoczko** [comment]
Hi @robwalch,  Could you check what status this bug has now?

**Comment by aliciahurst** [comment]
Hi @mtoczko sorry for taking so long to get back to you. We'll prioritize this fix for January. Note I've updated steps and actual/expected as I reproduced something different, which is to be expected given it's been some time.

Expected Behavior:
The settings menu is closed and I am focused on the settings icon in the control bar

Actual Behavior:
The settings menu closes but I lose focus (depends on the setup, could be lost to somewhere outside the video player, or the control bar hides and when you hit tab again you’re focused on the time slider)

Steps to Reproduce:
1. Navigate to any player, eg. http://stream-tester.jwplayer.com/
2. Press play
3. Use the tab key, navigate to and open the settings menu
4. Observe you are focused on an element in the settings menu
5. Hit escape key

Let me know if you're still seeing your original actual behavior.

**Comment by mamaddox** [comment]
Hi @mtoczko,

This issue should be fixed in the latest 8.18.4 release.
Here are the release notes: https://releases.jwplayer.com/jw-player/#v8.18.4

Thank you!

**Comment by mtoczko** [comment]
Hi @mamaddox 
Thank you for the information. But I see another issue ;)

https://www.jwplayer.com/developers/web-player-demos/closed-captions/
1. (use the keyboard) Setting > Closed Captions > [↓](settings) > [Enter] > [Enter](Font Color) > [ESC]
2. (use the keyboard) Setting > Closed Captions > [↓](German) > [Enter]

BTW: Font Opacity settings are missing the option: `50%`

**Comment by mtoczko** [comment]
Hi @mamaddox 
I tested version 8.19 and it doesn't work properly. I recommend testing the player (using only the keyboard). New bugs have appeared.

**Comment by mamaddox** [comment]
Hi @mtoczko!
Sorry for the delayed response. Thank you for bringing up the issues. However, I have not been able to reproduce either of them. 
For the first one I tried:
- Tab to the Settings Icon
- Press Enter
- Tab to the Captions Icon (Also tried using the arrow keys)
- Press down arrow (Also tried using Enter)
- Press Enter to show Font Color Menu
- Press Esc
I see the menu close as expected.

For the second one, I tried:
- Tab to the Settings Icon
- Press Enter
- Tab to the Captions Icon
- Press down arrow
- Press Enter to show Font Color Menu
I see the menu show as expected and the first option is highlighted.

Please let me know if I am missing something though.

**Comment by mtoczko** [comment]
Hi @mamaddox 
I made tests on the 8.20 version... 
I am sending a link to a video showing how it works.
`https://drive.google.com/file/d/1HlVvwl9fTpirE8VADVBDRacNAJaGV-OY/view?usp=sharing`

1. Focus is off the player when esc is pressed.
2. The menu is mixed between tabs.
3. By pressing an item in the menu, you are taken to the subtitle settings.
