### ISSUE TITLE
Support on youtube 

### ISSUE THREAD

**Issue by zhampu** [jwplayer/jwplayer#3653]
### Expected Behavior
Hello,
reading a bit on jwplayer I saw there is no youtube support but I stumble upon this website that uses it for youtube videos: [CCA](https://www.cca.qc.ca/en/events/63178/our-happy-life)

*Describe expected behavior*
Is this because is JW7? how can I do my own skin for a website im currently developping?

### Actual Behavior

*Describe actual behavior*

### Steps to reproduce

1.
2.
3.

### Environment

- *hardware | device*
- *operating system | version*
- *browser | version*
- *JW Player version | url*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by mamaddox** [comment]
Hi @zhampu!
So it does look like they are using JW7 and the complimentary skins that used to be offered with it have been deprecated. But you are still able to create custom skins for JW8!
The [JW8 Branding Docs](https://developer.jwplayer.com/jwplayer/docs/jw8-branding) will help you do so.

If you are using JW7, you can reference our [JW7 Legacy Docs](https://github.com/jwplayer/jwplayer-legacy-docs).
The legacy docs specific for creating skins are these:
- [Creating Custom Skins](https://github.com/jwplayer/jwplayer-legacy-docs/blob/master/legacy-docs/JW7/skins_creating.md)
- [Custom Icons and Fonts](https://github.com/jwplayer/jwplayer-legacy-docs/blob/master/legacy-docs/JW7/skins_fonts.md)
- [Example Skin](https://github.com/jwplayer/jwplayer-legacy-docs/blob/master/legacy-docs/JW7/skins_example.md)
- [CSS Skin Reference](https://github.com/jwplayer/jwplayer-legacy-docs/blob/master/legacy-docs/JW7/skins_reference.md)

Hope that helps!

**Comment by zhampu** [comment]
Thanks for the answer.
Is there support for youtube in JW8?

**Comment by mamaddox** [comment]
No. Youtube is not longer supported in JW8.

**Comment by zhampu** [comment]
Thanks for answering
