### ISSUE TITLE
JWPlayer error 330000 and 334001

### ISSUE THREAD

**Issue by x3inspire** [jwplayer/jwplayer#3658]
Hye, may i know what is this error?

jwplayer.js:10 JW Player Warning 330000. For more information see https://developer.jwplayer.com/jw-player/docs/developer-guide/api/errors-reference#33000
`

ee | @ | jwplayer.js:10
-- | -- | --
  | f | @ | jwplayer.js:10
  | t.trigger | @ | jwplayer.js:10
  | O.trigger | @ | jwplayer.core.controls.js:10
  | L | @ | jwplayer.core.controls.js:10
  | f | @ | jwplayer.js:10
  | t.trigger | @ | jwplayer.js:10
  | (anonymous) | @ | jwplayer.core.controls.js:10
  | f | @ | jwplayer.js:10
  | t.trigger | @ | jwplayer.js:10
  | t.forEach.e.<computed> | @ | jwplayer.js:10
  | (anonymous) | @ | jwplayer.core.controls.js:10
  | f | @ | jwplayer.js:10
  | t.trigger | @ | jwplayer.js:10
  | Z.trigger | @ | provider.hlsjs.js:10
  | e.<computed> | @ | provider.hlsjs.js:10
  | l.emit | @ | provider.hlsjs.js:10
  | e.trigger | @ | provider.hlsjs.js:10
  | t._tryNudgeBuffer | @ | provider.hlsjs.js:10
  | t._tryFixBufferStall | @ | provider.hlsjs.js:10
  | t.poll | @ | provider.hlsjs.js:10
  | e._checkBuffer | @ | provider.hlsjs.js:10
  | e.doTick | @ | provider.hlsjs.js:10
  | e.tick | @ | provider.hlsjs.js:10
  | e._checkAppendedParsed | @ | provider.hlsjs.js:10
  | e.onBufferAppended | @ | provider.hlsjs.js:10
  | t.onEventGeneric | @ | provider.hlsjs.js:10
  | t.onEvent | @ | provider.hlsjs.js:10
  | l.emit | @ | provider.hlsjs.js:10
  | e.trigger | @ | provider.hlsjs.js:10
  | e.onSBUpdateEnd | @ | provider.hlsjs.js:10

`

jwplayer.js:10 JW Player Warning 334001. For more information see https://developer.jwplayer.com/jw-player/docs/developer-guide/api/errors-reference#33400

`

ee | @ | jwplayer.js:10
-- | -- | --
  | f | @ | jwplayer.js:10
  | t.trigger | @ | jwplayer.js:10
  | O.trigger | @ | jwplayer.core.controls.js:10
  | L | @ | jwplayer.core.controls.js:10
  | f | @ | jwplayer.js:10
  | t.trigger | @ | jwplayer.js:10
  | (anonymous) | @ | jwplayer.core.controls.js:10
  | f | @ | jwplayer.js:10
  | t.trigger | @ | jwplayer.js:10
  | t.forEach.e.<computed> | @ | jwplayer.js:10
  | (anonymous) | @ | jwplayer.core.controls.js:10
  | f | @ | jwplayer.js:10
  | t.trigger | @ | jwplayer.js:10
  | Z.trigger | @ | provider.hlsjs.js:10
  | e.<computed> | @ | provider.hlsjs.js:10
  | l.emit | @ | provider.hlsjs.js:10
  | e.trigger | @ | provider.hlsjs.js:10
  | t._tryNudgeBuffer | @ | provider.hlsjs.js:10
  | t._tryFixBufferStall | @ | provider.hlsjs.js:10
  | t.poll | @ | provider.hlsjs.js:10
  | e._checkBuffer | @ | provider.hlsjs.js:10
  | e.doTick | @ | provider.hlsjs.js:10
  | e.tick | @ | provider.hlsjs.js:10
  | e._checkAppendedParsed | @ | provider.hlsjs.js:10
  | e.onBufferAppended | @ | provider.hlsjs.js:10
  | t.onEventGeneric | @ | provider.hlsjs.js:10
  | t.onEvent | @ | provider.hlsjs.js:10
  | l.emit | @ | provider.hlsjs.js:10
  | e.trigger | @ | provider.hlsjs.js:10
  | e.onSBUpdateEnd | @ | provider.hlsjs.js:10

`

**Comment by robwalch** [comment]
3XX,XXX codes are non-fatal warnings. They have the same meaning as their fatal 2XX,XXX error counterparts. 

In this case they came from hls.js but were not fatal. Since the player is still attempting to recover playback the 3x warnings were fired first before a fatal error indicating that playback could not start or continue.

```
230000	An unknown error occurred handling HLS media.	-	This video file cannot be played.
230001	Occurs when a live stream has stalled for more than 30 seconds. The timeout can be configured at setup using config.liveTimeout.	The live stream is either down or has ended	The live stream is either 
```
