### ISSUE TITLE
Error 102630 on valid RTMP URL in JW7

### ISSUE THREAD

**Issue by mgw-sbic** [jwplayer/jwplayer#3659]
### Expected Behavior

We are able to play a live RTMP feed in JW7.

### Actual Behavior

Get error 
102630
### Steps to reproduce

1. Try the following code when the RTMP stream is streaming:
<meta charset="UTF-8">
<html>
	<head>
		<meta charset="utf-8">
	        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<script src="https://cdn.jwplayer.com/libraries/[our library code].js"></script>
	</head>
	<body>
		 <div id="player1">
		    <script type="text/javascript">
			    jwplayer('player1').setup({
				    primary: "flash",
			      file: "rtmp://[our server]:1935/goliveIngest/kidmero",
			      height: 360,
			      width: 640,
			      autostart: true
			    });
		    </script>
		    </div>
	</body>
</html>
2.
3.

### Environment

- *hardware | device*
- *operating system | version*
- *browser | version*
- *JW Player version | url*

----------------------------------------------------------------------------------------

**Comment by robwalch** [comment]
RTMP in no longer supported in v8 and above. The Flash provider will be deprecated before the end of the year and is not part of this project.
