### ISSUE TITLE
Error after 35mn of play on mobile

### ISSUE THREAD

**Issue by frequeradio** [jwplayer/jwplayer#3665]
Hi

1. I play a stream (on this test page for example https://en-directo.frequence-radio.com/testflaix.php ) with this stream : https://flaixfm.streaming-pro.com:8001/flaixfm.mp3
2. After 35mn of play on a galaxy s8 with chrome, the stream stoppes and i have this error : _The live stream is either down or has ended.(Error Code: 220001)_   although the stream is nor done or endeded. Reproduce rate 100%.
So far i can't reproduce it with iphone X, the stream stoppes some seconds but start again.

JW Player version 8.13.4

I don't know if I can provide you more information, don't hesitate to ask

thanks

**Comment by jnatalzia** [comment]
Hi @frequeradio thanks for the bug report.

@robwalch have you seen any reports on this in the hls project (based on the environment specifics listed)

**Comment by robwalch** [comment]
@jnatalzia `"The live stream is either down or has ended"` error handling logic is part of our provider, not hls.js.

**Comment by jnatalzia** [comment]
Ahh thanks Rob, misread the extension on this.

**Comment by jnatalzia** [comment]
@frequeradio do you have any additional information about how this stream is served/encoded? Depending on the mechanisms in play it could help narrow down the problem.

**Comment by frequeradio** [comment]
Strangely I could not reproduce the issue today although it was 100% when i opened the ticket :/

I'm gonna run more tests and ask my users if they experience the issue.
Sorry for that.

**Comment by jnatalzia** [comment]
Interesting! Sounds good, thank you. I'll mark this as `answered` but feel free to reach out if you find it reproduce-able again.
