### ISSUE TITLE
jwplayer.remove() not preventing next up videos

### ISSUE THREAD

**Issue by nomve** [jwplayer/jwplayer#3666]
### Expected Behavior

Remove the player and prevent it from playing a video in all cases

### Actual Behavior

When destroying the player instance with e.g. `jwplayer().remove()` while on the "next up videos" screen that counts down from 10, the player gets removed but when the countdown is completed the next videos plays. It's not visible, but it can be heard.

### Steps to reproduce

1. Play a video that will have next videos coming up
2. play completely or skip until the end
3. wait for the next up screen to show up
4. call `jwplayer().remove()`
5. observe that the next video will eventually start to play

here an example https://jsfiddle.net/zhoa0836/

**Comment by jnatalzia** [comment]
Hi @nomve ,

Thanks for the bug report, I was able to reproduce on my end. I'll be adding a ticket to our internal backlog and will report back when it's been prioritized.

Really appreciate your contribution!

**Comment by nomve** [comment]
thanks a lot! keep us posted so I can remove some workarounds we use for this currently.

**Comment by robwalch** [comment]
Hi @nomve,

While I see @jnatalzia did create a ticket for us (JW8-11082) we haven't been able to prioritize it. If you reach out support@jwplayer.com to report the issue, that would help to get it into the queue on our end.

Thanks!

**Comment by aliciahurst** [comment]
Hi @nomve sorry it's taken us so long to respond. I retested this today and was unable to reproduce it anymore. I'm going to close this out but feel free to reopen if you can still see it happening. If so, please provide the configuration you're using so we can see it on our end.
