### ISSUE TITLE
Safari IOS show "This video cannot be played (Error Code: 224003)" when use blob as file url

### ISSUE THREAD

**Issue by hoangvietfreelancer** [jwplayer/jwplayer#3670]
### Expected Behavior
JWPlayer can play with file url as blob
### Actual Behavior
JWPlayer on Safari Mobile cannot play when file url is blob(But Safari on Mac can still play normal)
### Steps to reproduce

1. Make m3u8 file as blob string:
```
fileData = "m3u8 data"
URL = URL.createObjectURL(new Blob([fileData], { type: "vnd.apple.mpegURL" })); //It make something like blob:https://mysite.com/15a7d35c-fbde-4a7e-8169-286bea9ccddf
```
2. Add URL to JWPlayer:
```
player.setup({
	"sources": [{
		"file": URL,
		"type": "hls",
		"preload": "metadata",
	}],
	androidhls: "true",
	preload: "auto",
	width: "100%",
	aspectratio: "16:9",
	playbackRateControls: [0.75, 1, 1.5, 2],
	aboutlink: "",
	"cast": {}
});
```

### Environment

- *Iphone 6*
- *IOS | 12.4.6*
- *Safari IOS*
- *JWPlayer 8.13.3*

I create M3U8 using blob to add my hotlink protection to M3U8 file. I tested on MACOS and it can play normal but on IOS/IpadOS it can't play.

**Comment by robwalch** [comment]
We don't support blob urls as sources.

**Comment by hoangvietfreelancer** [comment]
Is there anyways that I can modify request to add my hotlink protection (like from ```https://mysite.com/myvideo/mysegment.ts``` to ```https://mysite.com/hotlink protection hash/myvideo/mysegment.ts``` that I need to generate "hotlink protection hash" with user's current time)

**Comment by robwalch** [comment]
Safari on iOS handles HLS playback and segment requests. Our player cannot modify these requests. You would need to register a [ServiceWorker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) on your site to make modifications to those requests.
