### ISSUE TITLE
Problem to load the player on IE 11 

### ISSUE THREAD

**Issue by frequeradio** [jwplayer/jwplayer#3671]
Hello

One of my user can't load the player on IE 11
Here is a picture of his console : https://ibb.co/kcLpybk

As the error are in spanish here is the translation : 
SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.
And 
SEC7121: Wildcard in Access-Control-Allow-Origin not allowed when credentials flag is set to true.

The issue does not occur with other players. 

thanks

**Comment by mamaddox** [comment]
Hi @frequeradio!

Based on the error, this looks like it's most likely a CORS issue. If you are trying to load a resources from a different domain, it could be causing this error, which is preventing the player from loading.
I would suggest looking at how you have CORS configured.

This might be a useful reference: https://support.jwplayer.com/articles/cross-domain-file-loading-reference

Hope that helps!
