### ISSUE TITLE
M3U8 containing m4s segments or segments other than ts causes jwplayer to flag the video with the class "jw-flag-media-audio"

### ISSUE THREAD

**Issue by Teranode** [jwplayer/jwplayer#3673]
Encode any video with something like ffmpeg with hls options. The streams get segmented to m4s files and output to m3u8. Upon importing as an external url jwplayer treats the video as an audio source.

**Comment by jnatalzia** [comment]
Hi @Teranode , thanks for the report. Could you please provide us with a test stream and reproduction steps for this issue?
