### ISSUE TITLE
Safari/Chrome IOS show "This video cannot be played (Error Code: 224003)"

### ISSUE THREAD

**Issue by natilux2** [jwplayer/jwplayer#3678]
### Expected Behavior

The player can play video

### Actual Behavior

The player got an error and show "This video cannot be played (Error Code: 224003)"

### Environment
- IphoneX - iOS 11,12
- JWPlayer 8.12
- mp4 video file

---------
It seems the cookies-thing is not being updated
#3056

**Comment by jnatalzia** [comment]
Could you provide us the mp4 file you used to reproduce please?

**Comment by natilux2** [comment]
@jnatalzia 
https://video.vtcnew.com.vn/video/2020/5/5/658D74278FCF6D0520C822C1C19AAEF6/658D74278FCF6D0520C822C1C19AAEF6.mp4
Here's my sample URL

**Comment by robwalch** [comment]
This error code indicates that the browser tried to play the stream, but encountered an error.
https://developer.jwplayer.com/jwplayer/docs/jw8-player-errors-reference#224003
> Failed to play the associated resource because it is not supported by this browser. Equivalent to the HTML5 MEDIA_ERR_SRC_NOT_SUPPORTED mediaError

If I paste the stream URL into Safari it will not play. If the browser cannot play the stream then neither can our player.

**Comment by natilux2** [comment]
@robwalch  Thanks for your response
It seems a CloudFlare issue, I will inspect more about this


I put this link to anyone who gets issue can check around
https://community.cloudflare.com/t/mp4-wont-load-in-safari-using-cloudflare/10587/49
