### ISSUE TITLE
On buffer does not detect buffer on advertisments

### ISSUE THREAD

**Issue by Surbhi77** [jwplayer/jwplayer#3679]
When an advertisment is buffering a on("buffer") should detect it but no advertisment buffering is detected
Is their any way to detect it?

**Comment by robwalch** [comment]
The "buffer" event indicates that the player state changed to buffering during normal playback. "bufferChange" events, like "time" events, only apply to progress for the main content. While we do have "adTime" events for tracking the currentTime of an ad, we do not expose `on("adBuffer")` `on("adBufferChange")` events for ads.
