### ISSUE TITLE
Playback affected by non-existing subtitles (Error Code: 241415)

### ISSUE THREAD

**Issue by dagwieers** [jwplayer/jwplayer#3680]
### Expected Behavior
So we have a stream from a live radio station that has subtitles available, but doesn't offer them currently. The reason why there is a subtitle track according to the VOD provider is that they can offer them when they are available without reloading the stream.

Fetching the subtitle track returns a HTTP 415 Unsupported Media Type, which causes playback to fail.

The stream is: https://live-radio-cf.lwc.vrtcdn.be/groupa/live/d6fdec5d-5d67-4cc3-9f8c-e3e8993c8ee4/live.isml/.mpd

### Actual Behavior
Video playback stops almost immediately with error: **This video file cannot be played.(Error Code: 241415)**

### Steps to reproduce

1. Go to: https://www.jwplayer.com/developers/stream-tester/
2. Open the stream: https://live-radio-cf.lwc.vrtcdn.be/groupa/live/d6fdec5d-5d67-4cc3-9f8c-e3e8993c8ee4/live.isml/.mpd
3. Get the error: **This video file cannot be played.(Error Code: 241415)**

### Environment
- CentOS-7
- Chrome 80.0.3987.163 (Official Build) (64-bit)
- https://www.jwplayer.com/developers/stream-tester/

### Alternative players
We did a study on how other players handle this and made an overview here:
https://github.com/peak3d/inputstream.adaptive/issues/433#issuecomment-626994942

THEOplayer seems to handle this best. It never retries on failure, but keeps getting the next segment, so if subtitles (re)appear they would work immediately.

You can try out this stream and behaviour of THEOplayer from the VOD provider's website: https://radio1.be/kijk-live (You will have to enable subtitles by pressing the square on the lower-right)

**Comment by dagwieers** [comment]
A summary of this issue is offered in https://github.com/peak3d/inputstream.adaptive/pull/446

**Comment by robwalch** [comment]
@dagwieers 

We use shaka-player to handle dash streams, and when shaka attempts to load your subtitle tracks and receives a 415 response, it emits a fatal error event that is not recoverable. Now maybe the context for that from shaka's perspective is that the track loading mechanism failed and will not recover, but the rest of the stream will play on, but our player has no way of determining this currently. So we treat fatal errors as fatal.

I would recommend that you return empty subs instead of 415'ing as that would work in all players.

If your stream says it has subtitles, then we assume that content is essential for viewers who rely on those subtitles. For this reason I do not think it's good to fail gracefully here. The error is caused by your stream missing an essential track that is provides an endpoint for.

**Comment by dagwieers** [comment]
@robwalch It is not us unfortunately. We noticed this practice in the field, and looked how different players handle this situation. Shaka player handles this best (even though it emits an error) it retries once, and then continues with the next fragment. This makes sense because an unavailable fragment could also mean the fragment is not yet available.

It does this for all errors, not just 415.

The question here is whether a subtitle is an essential track to fail playback.

Thanks for your answer.

**Comment by robwalch** [comment]
> The question here is whether a subtitle is an essential track to fail playback. Shaka's online player doesn't think so, but also doesn't give up on the subtitles.

It reties once for each file, but keeps the subtitle track alive?

Thanks for the issue and comparison @dagwieers. I hope I don't sound too defensive. My team would like to know if this behavior blocks you from using JW Player, and how we can better work with the streaming provider you are using.

We could handle the shaka error event more gracefully, but need to figure how to interpret the context from shaka that the request for a segment was fatal, but not overall playback.

**Comment by dagwieers** [comment]
No, I am not using JW Player myself. I was just reporting this after comparing online players. The streaming provider (software vendor) here is Unified Streaming (Unified Origin).

I did my duty by reporting, I'll leave it up to you to decide whether this is something worth fixing.

**Comment by dagwieers** [comment]
The original stream no longer includes the (missing) subtitle track. So cannot be used for testing this particular problem.
