### ISSUE TITLE
Cardboard Icon / View

### ISSUE THREAD

**Issue by mosane** [jwplayer/jwplayer#3681]
### Expected Behavior

1. I have stereoscopic videos uploaded on JW player with the right modes selected. I want to be able to play them in the cardboard view on my browser. 
2. I was not able to figure out how to enable gyroscope movement. 

### Actual Behavior

1. Playback happens in 360 / VR mode but I never get the split screen cardboard view. 
2. Gyroscope movement doesn't work. 

### Environment

- *hardware | device*
iOS / Desktop 
- *operating system | version*
- *browser | version*
Chrome (81.0.4044.138) / Firefox (76.0.1)
- *JW Player version | url*
8 https://jwp.io/s/IuYpjvcL

**Comment by robwalch** [comment]
Duplicates #3663

Gyroscope functionality relies on [WebVR](https://github.com/immersive-web/webvr-polyfill) which is no longer maintained and which no longer provides orientation data in newer versions of Chrome. We are looking to port over to [WebXR](https://github.com/immersive-web/webxr-polyfill) but the rendering stack, and device selection are completely upended, and orientation (gyro) access is much more restricted.

We have a ticket internally to track this work but no estimate on when it will be completed.
