### ISSUE TITLE
I need to play video link like youtube url using jwplayer. is it possible?

### ISSUE THREAD

**Issue by mosvict** [jwplayer/jwplayer#3682]
Hello.  How are you?
I implement to play video file using jwplayer.
but I need to play video link like youtube using it.
Is it possible?
If it is possible, then how to implement it?
I hope to help me. :)

**Comment by robwalch** [comment]
JW Player no longer supports playback of Youtube links.

**Comment by mosvict** [comment]
If so, jwplayer support othere video link(no video file)?
for example, http://www.xxx.xxx/abcde21828374
