### ISSUE TITLE
Playlist function broken on Sony devices

### ISSUE THREAD

**Issue by StoneyEagle** [jwplayer/jwplayer#3689]
### Expected Behavior

Next video starts playing from the playlist after the video has ended.

### Actual Behavior

On Playstation 4's and Sony Linux tv's the video stops playing with 3 seconds remaining, with both the open source and licensed version of JW player.
The player is still fully functional, but it's stuck in the playing state. 
The player requires a pause and play request to finish the last 3 seconds, and then correctly proceeds to the next video.

Both browsers lack a console to debug, so i don't have any specific error.
This issue does NOT occur on any other browser/device i have tested.

### Steps to reproduce

1. Load a playlist with multiple files in mp4 or m3u8 HLS, title, description and other, example below.
2. Watch a video till the end or skip to 5 seconds remaining.

### Environment

- PS4 & Sony KD-49XE7096
- Linux
- Not sure
- 8.15.0+local.2020-06-02-02-40-35-559 / 8.15.0

```json
[
    {
        "id": 15015,
        "title": "American Dad S01E01 Pilot ",
        "description": "Stan Smith uses his CIA skills to h.....",
        "image": "https://image.tmdb.org/t/p/original/4KiwE5neX9CkoIoA3Birbia1bvv.jpg",
        "language": null,
        "quality": "['SDDVD']",
        "duration": "00:20:59",
        "date": "2005-02-06",
        "video_type": "tv",
        "tmdbid": 1433,
        "season": 1,
        "episode": 1,
        "season_id": 3811,
        "episode_id": 65903,
        "vote_average": "3.75",
        "vote_count": 2,
        "file": "***.mp4",
        "uid": "1433381165903",
        "tracks": [
            {
                "file": "***.vtt",
                "kind": "thumbnails"
            },
            {
                "file": null,
                "kind": "chapters"
            },
            {
                "file": "***.vtt",
                "name": "Dutch",
                "language": "dut",
                "kind": "captions"
            }
        ]
    },
    {
        "id": 15016,
        "title": "American Dad S01E02 Threat Levels ",
        "description": "Stan Smith is mad because a....",
        "image": "https://image.tmdb.org/t/p/original/cCFXv71PLaMHhg3uPloj5zGNsIP.jpg",
        "language": null,
        "quality": "['SDDVD']",
        "duration": "00:21:11",
        "date": "2005-05-01",
        "video_type": "tv",
        "tmdbid": 1433,
        "season": 1,
        "episode": 2,
        "season_id": 3811,
        "episode_id": 65906,
        "vote_average": "6",
        "vote_count": 1,
        "file": "***.mp4",
        "uid": "1433381165906",
        "tracks": [
            {
                "file": "***.vtt",
                "kind": "thumbnails"
            },
            {
                "file": null,
                "kind": "chapters"
            },
            {
                "file": "***.vtt",
                "name": "Dutch",
                "language": "dut",
                "kind": "captions"
            }
        ]
    }
]

```

This playlist structure is dynamically crated and filled with a database query.
I use the extra meta to build dynamic item cards and allow for magic sauce 😉
[Codepen](https://codepen.io/Stoney_Eagle/pen/wvMxzVg)

**Comment by husenLogicwind** [comment]
exact same thing happens with me but the difference is 
1) i have a react native android app.
2) scenario generate when chromecast is started.

**Comment by robwalch** [comment]
This sounds like an issue with the browser not supporting preload and playback across multiple video tags at the same time. Try disabling 'backgroundLoading`. That will force the player to use a single video element for playback across playlist items.

```js
jwplayer(id).setup({
    backgroundLoading: false,
    playlist: // etc...
});

**Comment by StoneyEagle** [comment]
> This sounds like an issue with the browser not supporting preload and playback across multiple video tags at the same time. Try disabling 'backgroundLoading`. That will force the player to use a single video element for playback across playlist items.
> 
> ```js
> jwplayer(id).setup({
>     backgroundLoading: false,
>     playlist: // etc...
> });
> ```

Thanks for your time to reply, Setting this option works.
Is there a performance benefit to use multiple video elements? 

I had a workaround that might help others where this does not fix this issue.

```js

let upnext = false;
jwplayer().on("time", (e) => {
    if((jwplayer().getDuration() - jwplayer().getPosition()) <= 5.5){
        if(upnext == false){
            next = setTimeout(() => {
                next(); 
                upnext = false;
            }, 5000);
            upnext = true;
        }
    }
});

function next() {
    if (jwplayer().getPlaylistIndex() != jwplayer().getPlaylistIndex().length) {
        jwplayer().playlistItem(jwplayer().getPlaylistIndex() + 1);
    } 
};

```

**Comment by robwalch** [comment]
> Is there a performance benefit to use multiple video elements?

In browsers that support it, yes. The next video is preloaded before it's played making the transition between playlist items seamless. There are also benefits when playing ads.

You don't get this benefit is you skip ahead like in your workaround. Don't use the workaround. Just disable background loading in browsers that do not support it. We automatically disable it in Safari and Samsung Tizen TV browser. 

Can you share the user-agent of the browser you experienced this issue in?

**Comment by StoneyEagle** [comment]
Sure, Hope i didn't make a typo.

TV: "Mozilla/5.0 (Linux armv71) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36 OPR/36.0.2128.0 OMI/4.8.0.129.PIXEL_UNICORN2.21"

PS4: "Mozilla/5.0 (PlayStation 4 7.51) AppleWebkit/605.1.15 (KHTML, like Gecko)"

I used my "workaround" before to skip intro's and outro's of episodes, can't say i notice any difference on modern browsers.

**Comment by robwalch** [comment]
Thanks @StoneyEagle,

> I used my "workaround" before to skip intro's and outro's of episodes, can't say i notice any difference on modern browsers.

That makes perfect sense as a feature. `backgroundLoading` doesn't make a difference when you skip ahead. It's at that T-5s mark where preloading kicks in. It also keeps the main content paused in the background during ads playback, rather than sharing the one video element for ad playback and reloading everything. So, I recommend you keep it enabled. To disable it based on additional UAs, you could do this. This sets it to the player's preference, but also disables it on Playstation and TV or other Chrome 49 based browsers.

```js
const supportsBackgroundLoading = jwplayer(id).getEnvironment().Features.backgroundLoading &&
    !(/Playstation|Chrome\/49/).test(navigator.userAgent);
jwplayer(id).setup({
    backgroundLoading: supportsBackgroundLoading
```ll

This is something we may do automatically in a future release. ideally based on feature detection rather than UA, but this is fast and will work if these devices are important to you.

**Comment by StoneyEagle** [comment]
You are my hero, your'e hired 😂
You only made a typo on "PlayStation" but this is a prefect solution.
Would it be possible to mention or comment when this fix is implemented?
I really appreciate your help and info so thanks again!

You got to love those outdated browsers... at least i can have my binge-watching sessions.
PS. If you're curious [preview](https://nomercy.tv/preview) (its behind on my main app but its still a work in progress)
