### ISSUE TITLE
JWPlayer adds overflow-y:hidden style to body when activating PiP in Safari 13

### ISSUE THREAD

**Issue by mzipagang** [jwplayer/jwplayer#3693]
### Expected Behavior

*When picture-in-picture is activated in Safari, jwplayer should not style the body with overflow-y: hidden since this style is only for fullscreen*

### Actual Behavior

*In Safari, jwplayer detects a fullscreen event when activating picture-in-picture and styles the body with overflow-y: hidden*

### Steps to reproduce

1. Using Safari, play the video on this page: https://jwp.io/s/vemmUvSe
2. Activate PiP (https://www.idownloadblog.com/2019/10/25/enable-use-picture-in-picture-safari-mac/)
3. Inspect the body element and see that an overflow-y: hidden style has been added.

### Environment

- *MacBook Pro (15-inch, 2019)*
- *Catalina 10.15.3*
- *Safari Version 13.0.5 (15608.5.11)*
- *JW Player version 8.15.1*

----------------------------------------------------------------------------------------

**Comment by robwalch** [comment]
Hi @mzipagang,

We have plans to officially support PIP, until then, the player is unable to distinguish between fullscreen and PIP modes. I recommend addressing this with CSS, or by appending the `disablepictureinpicture` attribute to the video element for the time being.

**Comment by aliciahurst** [comment]
Hi @mzipagang. We have plans to add support for PiP around late June/early July, which as Rob mentioned should fix this issue. I'm going to close this issue for now, but stay tuned for a future release.

**Comment by aliciahurst** [comment]
@mzipagang Can you check to see if this issue is resolved with 8.21.0? It's now on the preview channel and will be on the latest channel tomorrow!
