### ISSUE TITLE
Does Jwplayer support with Ionic Framework?

### ISSUE THREAD

**Issue by kvmoondra** [jwplayer/jwplayer#3706]
Hello there,
Hope you are doing well.

With regards, we are developing a hybrid video news android app(from our app: we are going to distribute the hyperlocal video news feed to end-users, only video content).

For the above, we are looking to integrate Jwplayer Android SDK(https://www.jwplayer.com/mobile-sdk/android/) and the technologies we are using to develop the Hybrid Android App are:
Ionic, Angular JS, Node JS & MySQL

**My question is: Does Jwplayer support with Ionic Framework & other technologies we are using?**

Will wait to hear from you

Thanks & Regards
Kumar Vansh Moondra

**Comment by robwalch** [comment]
Please contact support for questions regarding the Android SDK. This project is for question regarding the web player JavaScript library.
