### ISSUE TITLE
While event.playReason is 'autostart' and the player status is also 'playing', still it is actually not playing.

### ISSUE THREAD

**Issue by RaviAtTTN** [jwplayer/jwplayer#3709]
### Expected Behavior

If the jwplayer(playerId).getState() is "playing", then the video must actually be playing.

### Actual Behavior

Video is not playing

### Environment

- Laptop and Mobile devices
- Ubuntu 18.04
- Chrome and Opera
- JW Player Ver. 7.12.13

### Screenshot
![imageedit_10_6751768564](https://user-images.githubusercontent.com/56861974/86768718-9c079e00-c06b-11ea-9725-106007f74414.png)

**Comment by robwalch** [comment]
HI @RaviAtTTN,

The latest version of JW Player v8.16.0. We are no longer patching issues such as this for v7. Please upgrade to the latest version.
