### ISSUE TITLE
Inconsistent type definition for VolumeParam.volume

### ISSUE THREAD

**Issue by BrightSoul** [jwplayer/jwplayer#3715]
Hello there, I think there's a small typo in the type definition from the npm package `@types/jwplayer`.
The [documentation here says](https://developer.jwplayer.com/jwplayer/docs/jw8-javascript-api-reference#section-jwplayer-on-volume) the `volume` event will provide an object with a `volume` property of type `Number`.

The npm package, however, reports `volume` to be `Boolean`.
![image](https://user-images.githubusercontent.com/1888641/87449325-56b01700-c5fd-11ea-8663-97791ad48ec4.png)

In fact, here's what I've found inside `node_modules/@types/jwplayer/index.d.ts` at line 179;
```
    interface VolumeParam {
        volume: boolean;
    }
```

Version of `@types/jwplayer` I'm using is 8.2.2 (latest available).

**Comment by robwalch** [comment]
`@types/jwplayer` (https://www.npmjs.com/package/@types/jwplayer) comes from https://github.com/DefinitelyTyped/DefinitelyTyped, not this project. Please open an issue there.

**Comment by BrightSoul** [comment]
Right, done.
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46078
