### ISSUE TITLE
How to develop a custom provider over shaka provider for mpeg-dash

### ISSUE THREAD

**Issue by Niharika098** [jwplayer/jwplayer#3731]
### Expected Behavior

Way to extend shaka provider for mpeg-dash

### Actual Behavior

Shaka provider code not available

### Steps to reproduce

NA

### Environment

Any

Hi
I want to extend the internal shaka provider to add extra functionality on top of it but couldn't find any resources on how that could be done. I found a provider for hls with jwplayer here https://github.com/hola/jwplayer-hlsjs/. Is there any such similar thing available for shaka player. If not what would be the right way to proceed

One more question is where is the source code for internal hlsjs or shaka provider available. I could see only basic html5 provider and timer provider.
----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
We do not offer a way to extend internal providers. You can create custom providers. There is an example and test harness here:

https://github.com/jwplayer/jwplayer/blob/master/test/manual/events/custom-provider.html
https://github.com/jwplayer/jwplayer/blob/master/test/manual/events/src/providers/video-element-provider.ts

demo: https://jwplayer.github.io/jwplayer/test/manual/events/custom-provider.html

You are on your own adapting shaka-player.
