### ISSUE TITLE
Setting a New `repeat` Config Breaks Playlist Functionality

### ISSUE THREAD

**Issue by ggwicz** [jwplayer/jwplayer#3733]
### Expected Behavior

- When a player instance has been created with `repeat: true` passed in its initial `.setup()` call,
- If I then call `.setConfig()` and specify `repeat: false`,
- The existing playlist of videos should continue playing,
- Until it reaches the end of the last video in the playlist,
- Where it should then end and fire the `playlistComplete` event

### Actual Behavior

- When a player instance has been created with `repeat: true` passed in its initial `.setup()` call,
- If I then call `.setConfig()` and specify `repeat: false`,
- The next video in the playlist will finish playing,
- And fire a `playlistComplete` event prematurely,
- Ending the play sequence and not playing the rest of the videos in the playlist as intended

### Steps to reproduce

1. Create a very basic player with a playlist, like the following:
```
var playerInstance = jwplayer('player').setup({
    playlist: [
        {
            file: "https://stream.mux.com/csOj7oB4RdpYlLfgfQQySQm7RL91hf00yL7TqkcWBsnM.m3u8",
            title: "fall"
        },
        {
            file: "https://stream.mux.com/9JPUB01VsYML02kbQuTPgemt01WJxVpwPGIi1fNvjYZISk.m3u8",
            title: "clouds"
        },
        {
            file: "https://stream.mux.com/ne9U5iZm600F7VyayeT3Sza3QXE9T7Thg02r2cYxVE0184.m3u8",
            title: "trees"
        }
    ],
    autostart: true,
    controls: true,
    repeat: true
});
```
2. Observe how the generated player plays the playlist as desired: it automatically goes from one video to the next, looping back to the first video in the playlist indefinitely.

3. Now add a bit of code like the following to set `repeat: false` on the `playerInstance` (in this example, it just happens after a 4-second `setTimeout` delay):

```
window.setTimeout( function() {
    playerInstance.setConfig({
        repeat: false
    } );
}, 4000 );
```

I'd also recommend adding a simple callback to the `playlistComplete` event like this one:

```
playerInstance.on( 'playlistComplete', function() {
    console.log( 'playlistComplete event fired' );
    console.log( 'playerInstance playlist', playerInstance.getPlaylist() );
} );
```

4. Observe that once the `setConfig()` call happens, the playlist no longer behaves as desired. The first video will end, and the playlist will fire the `playlistComplete` event and stop playing any video.

5. **Important:** Note that just adding a `playerInstance.play()` call after the `setConfig()` does **not** rectify this. 

For example, you can try something like this:
```
var fired = false;

playerInstance.on( 'playlistComplete', function() {
    if ( ! fired ) {
        playerInstance.play();
        fired = true;
    }
} );
```
↑ This code _will_ make the first item in the playlist play again, but then once it reaches the end of the video, it stops again instead of proceeding to the next item in the playlist.

### Environment

```
{
	"Browser": {
		"androidNative": false,
		"chrome": false,
		"edge": false,
		"facebook": false,
		"firefox": true,
		"ie": false,
		"msie": false,
		"safari": false,
		"version": {
			"version": "79.0",
			"major": 79,
			"minor": 0
		}
	},
	"OS": {
		"android": false,
		"iOS": false,
		"mobile": false,
		"mac": true,
		"iPad": false,
		"iPhone": false,
		"windows": false,
		"tizen": false,
		"version": {
			"version": "10.15",
			"major": 10,
			"minor": 15
		}
	},
	"Features": {
		"flash": false,
		"flashVersion": 0,
		"iframe": false,
		"passiveEvents": true,
		"backgroundLoading": true
	}
}
```

**Comment by robwalch** [comment]
Hi @ggwicz,

The bug is caused by logic in our complete handler that checks if the player `shouldAutoAdvance`:

```js
        function _completeHandler() {
            if (_this.completeCancelled()) {
                return;
            }

            _actionOnAttach = _this.completeHandler;

            if (!_this.shouldAutoAdvance()) {
                if (_model.get('repeat')) {
                    _next({ reason: 'repeat' });
                } else {
                    // Exit fullscreen on IOS so that our overlays show to the user
                    if (OS.iOS) {
                        _setFullscreen(false);
                    }
                    // Autoplay/pause no longer needed since there's no more media to play
                    // This prevents media from replaying when a completed video scrolls into view
                    _model.set('playOnViewable', false);
                    _model.set('state', STATE_COMPLETE);
                    _this.trigger(PLAYLIST_COMPLETE, {});
                }
                return;
            }

            _this.nextItem();
        }
```

That method is overrided in our "related" recommendations plugin: 
```js
        this.shouldAutoAdvance = function() {
            let relatedConfig = model.get('related');
            let nextUpItem = model.get('nextUp');
            // If the next item is not recs, lets the OS controller handle it
            if (nextUpItem && nextUpItem.mode === 'playlist' && relatedConfig.shouldAutoAdvance) {
                return true;
            }

            return false;
        };
```

Which is configured with `shouldAutoAdvance` set to `false` at setup when `repeat` is true:

```js
export function normalizeRelated(config) {
    const supports = Edition(config.edition);

    // Related
    const relatedOptions = config.related;
    const disableRelated = !supports('discovery') || (relatedOptions !== Object(relatedOptions));
    const showButton = !relatedOptions || relatedOptions.displayMode !== 'none';

    // We should always have autoplay options in the related config, normalize here
    let relatedOptionsWFallback = (relatedOptions || {});
    let oncomplete = typeof relatedOptionsWFallback.oncomplete === 'undefined' ? 'none' : relatedOptionsWFallback.oncomplete;
    let autoplaytimer = relatedOptionsWFallback.autoplaytimer;
    if (oncomplete === false || config.repeat) {
        oncomplete = 'hide';
    } else if (oncomplete === 'none') {
        // If we want to immediately advance on complete
        // Set the autotimer appropriately for the recs case
        autoplaytimer = 0;
    }

    let shouldAutoAdvance = (oncomplete === 'autoplay' && autoplaytimer <= 0) || oncomplete === 'none';

    return Object.assign({}, relatedOptions, {
        disableRelated,
        showButton,
        oncomplete,
        autoplaytimer,
        shouldAutoAdvance
    });
}
```

The fix on our end will be to update this `shouldAutoAdvance` flag when you update `repeat` or find a way to remove the flag and/or it's side-effect.

In the meantime you could try either:
1. Add `related: { oncomplete: 'none' }` to your config. This will set the flag to true removing the side-effect.
1. remove `repeat: true` from your config (or set it to false in the config), and then call `setConfig({ repeat: true })` on "ready". That will prevent the flag from flipping on setup. You can then call `setConfig({ repeat: false })` and repeat will work as expected.

**Comment by ggwicz** [comment]
@robwalch Thank you for the response! And for these tips. We had trouble getting things to work as desired by just passing `related: { oncomplete: 'none' }`, but your second tip has been really useful and we have a temporary workaround for now.

**Comment by ggwicz** [comment]
@robwalch Can you please remove the `answered` tag from this issue? It does not seem like this issue been fixed, even though a (very helpful and appreciated!) workaround answer was provided here. 

If you will keep this issue issue closed, can you provide any insight as to the status of the bug that is mentioned here? Is that captured internally for the JWPlayer team to hit, and if so, any general ETA for the proper fix?

**Comment by aliciahurst** [comment]
Hi @torgospizza, I'm the product manager of the player, and wanted to say that I'm sorry we're taking so long to reply to you. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible, which is why I'm going to close out this issue, and ask that if it still persists, you please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team. You'll be in great hands with them, and get a reply and support within a few business days, and we have a system there to follow up more effectively when issues are resolved. Thanks for submitting!
