### ISSUE TITLE
JW Player not working with Angular Custom Elements

### ISSUE THREAD

**Issue by djdmorrison** [jwplayer/jwplayer#3742]
### Expected Behavior

We expect to be able to add JW Player to an Angular custom element and it work the same as if it was not. 

### Actual Behavior

Turning on the custom element's encapsulation so that it's in a closed shadow-root breaks JW Player as it can't find the supplied element ID on setup. Explained here: https://stackoverflow.com/questions/51778063/jwplayer-doesnt-play-well-in-angular-elements

We can achieve a half working solution by grabbing the element itself with javascript and supplying that to the JW Player setup but it seems to fail to apply the CSS styling and causes a number of issues.

### Steps to reproduce

1. Create an angular custom element (https://angular.io/guide/elements) with jw player implemented.
2. Embed the custom element inside another webpage
3. JW player fails to setup correctly as it can't find the player ID within the custom element.

### Environment

- Any device/ latest JW Player version.

**Comment by aliciahurst** [comment]
Hi @djdmorrison I'm the product manager of the player, and wanted to say that I'm sorry we're taking so long to reply to you. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible. While we don't support Angular, and don't test player compatibility with custom elements, if you'd like to follow up on this issue further, please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team. You'll be in great hands with them, and get a reply and support within a few business days. Thanks for submitting!
