### ISSUE TITLE
Write a proxy over jwplayer

### ISSUE THREAD

**Issue by Niharika098** [jwplayer/jwplayer#3745]
### Expected Behavior

Write a proxy over jwplayer

### Actual Behavior

Unable to find relevant information

### Steps to reproduce

NA

### Environment

Any

Hi
I want to know what is the approach to write a proxy over jwplayer. 

I am planning to implement a mid-stream CDN switcher to use the best CDN based on performance and for this the approach I thought would be to intercept the request from jwplayer using a proxy, fetch the content from cdn of my choice and give the response back to jwplayer. 

Would love to know if there are any inbuilt methods in jwplayer which facilitate above kind of approach. If not can I use any open source solutions to implement the same ? Would love to get your feedback.

Thanks for your time.

**Comment by robwalch** [comment]
This is not a feature of JW Player. Our player aims to play streams (HLS/DASH/MP4) seamlessly across all browsers. Intercepting network requests is not possible in all environments.

We only expose a few helpers from hls.js and shaka-player for filtering certain requests (look for references to "XHR" in https://developer.jwplayer.com/jwplayer/docs/jw8-player-configuration-reference). That code is not part of this project and out of scope of the level of support we can provide here. This project implements media playback through HTML5. Your best option to proxy requests within your site's domain is to use Service Workers https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API
