### ISSUE TITLE
"Broken ARIA menu" errors if settings menu is empty. 

### ISSUE THREAD

**Issue by dalin-** [jwplayer/jwplayer#3748]
### Expected Behaviour

JWPlayer passes automated accessibility checking tools. 

### Actual Behaviour

Broken ARIA menus reported by WAVE (and other checkers).

### Steps to reproduce

1.  Run the audio player through the WAVE web accessibility evaluation tool:
https://wave.webaim.org/report#/https://www.jwplayer.com/developers/web-player-demos/audio-metadata/

Most of those errors about the other stuff on the page.  

### Environment

- all

### Technical Details

Here's the offending markup

```html
<div id="jw-settings-menu" class="jw-reset jw-settings-menu" role="menu" aria-expanded="false"><div class="jw-reset jw-settings-topbar" role="menubar">
  <div class="jw-reset jw-settings-topbar-text" tabindex="0"></div>
    <div class="jw-reset jw-settings-topbar-buttons">
      <div class="jw-icon jw-icon-inline jw-button-color jw-reset jw-settings-close" role="button" tabindex="0" aria-label="Close" style="">
        <svg xmlns="http://www.w3.org/2000/svg" class="jw-svg-icon jw-svg-icon-close" viewBox="0 0 240 240" focusable="false"><path d="M134.8,120l48.6-48.6c2-1.9,2.1-5.2,0.2-7.2c0,0-0.1-0.1-0.2-0.2l-7.4-7.4c-1.9-2-5.2-2.1-7.2-0.2c0,0-0.1,0.1-0.2,0.2L120,105.2L71.4,56.6c-1.9-2-5.2-2.1-7.2-0.2c0,0-0.1,0.1-0.2,0.2L56.6,64c-2,1.9-2.1,5.2-0.2,7.2c0,0,0.1,0.1,0.2,0.2l48.6,48.7l-48.6,48.6c-2,1.9-2.1,5.2-0.2,7.2c0,0,0.1,0.1,0.2,0.2l7.4,7.4c1.9,2,5.2,2.1,7.2,0.2c0,0,0.1-0.1,0.2-0.2l48.7-48.6l48.6,48.6c1.9,2,5.2,2.1,7.2,0.2c0,0,0.1-0.1,0.2-0.2l7.4-7.4c2-1.9,2.1-5.2,0.2-7.2c0,0-0.1-0.1-0.2-0.2L134.8,120z"></path></svg>
      </div>
    </div>
  </div>
</div>
```

WAVE's summary of the problem:

> ## Why It Matters
> ARIA menus are application menus (like those used in software menu) with a specific keyboard interactions. They are NOT for navigation links on a web site and must contain at least one `menuitem`, `menuitemcheckbox`, or `menuitemradio` element.
>
> ## What To Do
> Ensure that the menu is an application menu and has the appropriate keyboard interactions (menu items are navigated via the arrow keys, not via the Tab key) and internal menu items, otherwise remove the menu role.
>
> ## The Algorithm... in English
> An element with `role="menu"` does not contain at least one element with `role="menuitem"`, `role="menuitemcheckbox"`, or `role="menuitemradio"`.

It looks like this isn't specific to the audio player, but happens whenever the settings menu is empty.  In this case it should not even appear in the DOM.

**Comment by aliciahurst** [comment]
Hi @dalin- 

I'm the product manager of the player and wanted to thank you for writing in! I filed this issue as a bug in our backlog. We're prioritizing accessibility initiatives in the second half of 2021 so I hope to get it to it soon. I'm going to close this issue in the meantime so it doesn't remain open forever. I think the good news here is while it may be flagged in WAVE, the empty menu isn't an element that the user can interact with, so it's not going to get read by a screen reader. 

I'm sorry it took us so long to respond. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible. In the future, can you please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team. You'll be in great hands with them. Thanks for submitting!
