### ISSUE TITLE
A way to disable drag on floating player

### ISSUE THREAD

**Issue by tcarlsen** [jwplayer/jwplayer#3753]
Is there a way to disable the feature of dragging the floating player around?

**Comment by robwalch** [comment]
Hi @tcarlsen,

There is no way to disable dragging of the floating player. It is [enabled automatically when the player is not in an iFrame and not playing ads](https://github.com/jwplayer/jwplayer/blob/e081e30410ab8f321877c1b822b82acc1b508156/src/js/view/view.js#L824).
