### ISSUE TITLE
HLS stream is not working into Version 8.17.7

### ISSUE THREAD

**Issue by deep-ego** [jwplayer/jwplayer#3754]
### Expected Behavior

*Having a HLS stream to be played into jwplayer V8*

### Actual Behavior

That HLS stream is playable over [http://stream-tester.jwplayer.com/](http://stream-tester.jwplayer.com/) with player 8 and 7, And also playable using cdn of V7 in the application but when i change the cdn from V7 to V8. Player starts infinite loading and getting this error later of a warning.

**Warning** : *JW Player Warning 339000. For more information see https://developer.jwplayer.com/jw-player/docs/developer-guide/api/errors-reference#339000*

**Error** : *Uncaught TypeError: self.setInterval is not a function*

Do i need to pass any extra flag in set-up or options?

**Comment by robwalch** [comment]
Hi @deep-ego,

`self` should be the same as `window` on your page. If it is not, then something has polluted the global space of your page's JavaScript environment. Make sure you are not overriding the global `self`.
