### ISSUE TITLE
Video Replay is not working properly in JW8

### ISSUE THREAD

**Issue by uc-asv** [jwplayer/jwplayer#3755]
Replaying the video in the playlist playing the first video in the playlist automatically.

I have a playlist of 5-7 videos and suppose if I am at 5th play index and the video completes then if I am clicking on the replay button the video automatically starts playing the video which is at 0 indexes.

**Comment by robwalch** [comment]
When video completes, if there are more items in the playlist, the next video will automatically be played. We don't show the replay button until you are on the last item.
