### ISSUE TITLE
Not Showing Quality Button in apple products (iphone , ipad, etc)

### ISSUE THREAD

**Issue by MehdiAghighi** [jwplayer/jwplayer#3775]
### Actual Behavior

when i am playing the hls video in iphone or ipad when i tap settings there is no where to change quality of video , but in windows or android there is that button !
in iphone there is only the caption and playback speed rate controls but no quality change

**Comment by djdmorrison** [comment]
Hey @MehdiAghighi, (I'm not with the jwplayer team but run into the same issue recently) - iPhones/iPads use Apple's native implementation of HLS which doesn't give you the option to adjust the quality hence why jwplayer doesn't show the option. 

I haven't tested but if you force the use of hls.js with `safarihlsjs: true` in your setup config then it may appear on iPad as that will use a different implementation. This option doesn't help with iPhone though as it's missing certain things that hls.js requires.

**Comment by robwalch** [comment]
Thanks @djdmorrison. That is correct. We play HLS natively in Safari which does not allow quality selection.

**Comment by MehdiAghighi** [comment]
@robwalch So is there a way that i can set a default quality for safari browser ?

**Comment by robwalch** [comment]
> @robwalch So is there a way that i can set a default quality for safari browser ?

Safari select the HLS quality to be played. See `EXT-X-STREAM-INF` and "Variant Stream" in the [HLS spec](https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-08) for guidelines. In general most players will start playback using the first `EXT-X-STREAM-INF` listed in your parent manifest ("Master Playlist"). The only way to limit which variants Safari can select is by delivering a limited set of variants to the browser in the stream. The browser does not have any options the player can set to control quality in Safari.

HLS spec: https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-08
