### ISSUE TITLE
Request - Hook into a "before cast" to change the m3u8 location

### ISSUE THREAD

**Issue by iamakimmer** [jwplayer/jwplayer#3781]
### Expected Behavior

Ability to play 5.1 AAC on the computer, but switch to another codec/hlf feed entirely right before casting

### Actual Behavior

I don't see a way to hook into some type of "before cast". The reason I want to switch over the m3u8 file is because the browser can all play 5.1 AAC at 4k But this codec is not able to be cast over Google cast (AAC supported ,but AAC 5.1 is not). 4k Also doesn't work either as the H264 Profile must be Main in some devices, and Main doesn't go over 1080p. So I was hoping to figure out some way to have 2 videos, one at the optimum browser level and one for casting and be able to swap out if they decide to cast. Is something like this possible?

### Steps to reproduce

1. https://developer-tools.jwplayer.com/stream-tester/
2. Use https://www2.iis.fraunhofer.de/AAC/ChID-BLITS-EBU.mp4 as the file URL
3. Attempt to cast on a 4k Chromecast Ultra (Non 4k Cast devices may or may not work depending on the firmware, as they removed 5.1 AAC on updated firmware)

**Comment by robwalch** [comment]
hls.js/shaka/Safari can all select a variant that the player is capable of playing if your HLS stream contains multiple variants with details in the EXT-INF CODECS attribute. We do not support stream url switching when casting.

**Comment by iamakimmer** [comment]
Okay. We're waiting for the ability for Jwplayer Enterprise to be able to upload multiple audio tracks in different codecs 🙏 but hoping to have some way to switch Urls in the meantime.
