### ISSUE TITLE
JW Player Error 102630 for Live Streams using Chrome Developer Tools for certain device user-agents

### ISSUE THREAD

**Issue by talkshoplivedev** [jwplayer/jwplayer#3786]
### Expected Behavior
Using Chrome Developer Tools, enable toggle Device Toolbar and select built-in devices to test responsive layouts for a player

### Actual Behavior
For **m3u8/live streams only**, this is the behavior:
- Player presents error: ```JW Player Error 102630. For more information see https://developer.jwplayer.com/jw-player/docs/developer-guide/api/errors-reference#102630```
- Also, the player never even throws `'error'`
- This seems to happen indiscriminately between Android and iOS user agents, but in all cases is not working for iOS devices that we tested

Working User Agent Examples:
- Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 8.0; Pixel 2 Build/OPD3.170816.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36

**Not working** User Agent Examples:
- Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1
- Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1
- Mozilla/5.0 (Linux; U; Android 4.3; en-us; SM-N900T Build/JSS15J) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
- Mozilla/5.0 (Linux; U; en-us; KFAPWI Build/JDQ39) AppleWebKit/535.19 (KHTML, like Gecko) Silk/3.13 Safari/535.19 Silk-Accelerated=true
- Mozilla/5.0 (Linux; U; Android 4.1; en-us; GT-N7100 Build/JRO03C) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
- Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1

### Steps to reproduce

1. In a Chrome Browser, go to https://developer-tools.jwplayer.com/stream-tester/
2. Open Chrome Developer Tools and toggle on the device/responsive mode
3. Choose any iOS built-in device user agent from the device selector, such as an iPad
4. Refresh the page so the new user-agent is detected
5. You will now see error in player

Note: We used the JWPlayer site as a quick way to reproduce, but we can reproduce this in our own project as well.

### Environment

- Mac and PC
- MacOS and Windows
- Chrome | 87.0.4280.88 (Official Build) (64-bit) AND 86.0.4240.198 (Official Build) (x86_64)
- https://developer-tools.jwplayer.com/stream-tester/

<img width="1456" alt="Screen Shot 2020-12-09 at 9 56 46 AM" src="https://user-images.githubusercontent.com/32524539/101674495-335b8d80-3a1e-11eb-8bac-d106fbe95631.png">
<img width="1312" alt="Screen Shot 2020-12-09 at 12 58 40 PM" src="https://user-images.githubusercontent.com/32524539/101674583-4a9a7b00-3a1e-11eb-8489-1ac90284afde.png">

**Comment by robwalch** [comment]
Hi @talkshoplivedev,

I recommend that you test responsive layouts without changing the user agent. The dev tools in chrome allow you to do this. The reason you are getting a setup error when changing the UA to iOS, is because this causes jwplayer to attempt to use HTML5 playback of HLS streams. Chrome does not support this so the items are filtered out of the playlist and you get error 102630. Test using an mp4 video source if you want to change the UA, or simply change the simulated display settings without changing the UA.

**Comment by talkshoplivedev** [comment]
@robwalch thanks for the info and that makes perfect sense now. It's just that this seemed to our team to be a new issue.
