### ISSUE TITLE
Stops buffering when movie plays

### ISSUE THREAD

**Issue by Latchplug** [jwplayer/jwplayer#3788]
### Expected Behavior
I am just a movie viewer.  I could not find the movie anywhere but here.  I expect the movie to play in firefox with few interruptions.

### Actual Behavior

The movie seems to start out ok.  Then it stops for a 1 or 1&1/2 minutes.  Then movie starts again.  The frequency of this increases.  I noticed that the movie stops.  The modem data lights flash downloading additional parts of the movie.  When the movie continues the modem data lights stop flashing.  Then the movie stops.  Modem data lights begin to flash.  Movie continues and modem data lights stop.  This is the cycle through the movie.  
There is a message at the tip “Help: If player is buffering please pause and wait 1-3 minutes and then play again ! It should fix issue, do not reload player. Thanks.”.  this is not true.  It just does the buffering cycle I describe above.  

### Steps to reproduce

Watch the movie.  https://gomovie.ms/movie/the-seventh-page-2018/watching/?ep=7
Using firefox built-in information tools the movie is coming from Vidoo.tv or streamango.to.  I know you have no control over the gomovie.ms website or the source of the movie.  I have to believe the jwplayer has control over the data.  Why does the jwplayer in firefox stop downloading or stop buffering the movie when the movie plays?
I use firefox because other browsers I have little control over the junk on the site.  Other browsers it is all or nothing.  Firefox I can allow what I want and block popups, flashing ads, redirects, obscene links, etc.  
I used this web site because it is the only place I could find this movie to stream.  Then I find out it is a worthless boring movie.  Hoping there would be some substance to the movie I stayed with it too long before ending it.  

### Environment
centurylink 40mb internet service
- *hardware | device*  
I run i7-4770 Haswell midtower, 15GB memory, 500GB SSD, 2GB video card 
- *operating system | version*
Windows 10 Pro 2004
- *browser | version*
- firefox 84.0   64bit
- *JW Player version | url*  I do not know
----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by robwalch** [comment]
Hi @Latchplug,

The page at gomovie.ms is using a fake JW Player license. They are essentially stealing a commercial product.
