### ISSUE TITLE
MultipleAudioRenditions broken on 8.18.3 

### ISSUE THREAD

**Issue by adinapoli** [jwplayer/jwplayer#3793]
### Expected Behavior

When JW is fed with a [MultipleAudioRendition](https://support.jwplayer.com/articles/multiple-audio-renditions-reference) HLS playlist, it should offer the user the ability to switch audio tracks. Calling `getAudioTracks` should return a non-null array. 

### Actual Behavior

`getAudioTracks()` returns `[]` for the same video. Compare **8.18.2** :

<img width="833" alt="Screenshot 2021-01-06 at 11 24 56" src="https://user-images.githubusercontent.com/442035/103758843-0eedd380-5013-11eb-9544-5a57da8d62f9.png">

With **8.18.3** :

<img width="380" alt="Screenshot 2021-01-06 at 11 02 42" src="https://user-images.githubusercontent.com/442035/103758855-14e3b480-5013-11eb-91d6-eb9688a57895.png">

This is an example of a MAR HLS `index.m3u8` playlist we have in our systems, which worked just fine for older versions of the player:

```
#EXTM3U
#EXT-X-VERSION:3


#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="Primary Audio",DEFAULT=NO,AUTOSELECT=NO,URI="audio_2/f012957f4423d7d3dd9f1cc87b332777c8ee59caef36024dec656997821a316e.m3u8"

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="Secondary Audio",DEFAULT=NO,AUTOSELECT=NO,URI="audio_1/f012957f4423d7d3dd9f1cc87b332777c8ee59caef36024dec656997821a316e.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1200000,RESOLUTION=640x480,NAME="Main",CODECS="avc1.66.30",AUDIO="aac"
1200/f012957f4423d7d3dd9f1cc87b332777c8ee59caef36024dec656997821a316e.m3u8
```

Where `audio_1/f012957f4423d7d3dd9f1cc87b332777c8ee59caef36024dec656997821a316e.m3u8` and `1200/f012957f4423d7d3dd9f1cc87b332777c8ee59caef36024dec656997821a316e.m3u8` lives in the same directory of `index.m3u8` on S3, like so:

![this](https://user-images.githubusercontent.com/442035/102595248-9385ba00-4117-11eb-8acb-57f5a52cffca.png)

### Steps to reproduce

1. Setup JW **>= 8.18.3** on a multiple audio rendition HLS video.
2. Call `jwplayer(domSelector).getAudioTracks()`
3. Observe the return array is null, and there is no option to switch between audio tracks.

### Environment

- Not relevant, but I am on a MacBook Pro (13-inch, 2017).
- Not relevant, but I am on a macOS Catalina 10.15.7
- Google Chrome Version 87.0.4280.88 (Official Build) (x86_64)
- JW Version 8.18.3, as downloaded from the JW dashboard (we are on a commercial support subscription).

**Comment by robwalch** [comment]
Hi @adinapoli,

Thanks for filing an issue. We are tracking this issue internally as it has already been reported to our support engineers. It appears to be unique to streams with only one quality level (like the single `STREAM-INF` in your manifest example). We'll have a fix for it in an upcoming release.
