### ISSUE TITLE
FloatingCloseButton

### ISSUE THREAD

**Issue by MohammadHerzalla** [jwplayer/jwplayer#3806]
How can I listen to the Floating Close Button,  wich this floating button appear after the user scroll down,
how can I know that the user closed the floating video, and there is no event that is called after the floating video was closed like,

for example u can do this
 ```
 jwplayer("myElement").on('complete', function(){
    alert("Complete fired - Your content has completed!");
  });
```  

is there an option where 
 ```
 jwplayer("myElement").on('close', function(){
    alert(" video was closed ");
  });
```  
or something

**Comment by robwalch** [comment]
> how can I know that the user closed the floating video

Check out the 'float' event:

```js
jwplayer().on('float', function(event) {
  console.log(event.floating); // true | false
  jwplayer().getFloating(); // true | false
});

**Comment by crispipear** [comment]
> > how can I know that the user closed the floating video
> 
> Check out the 'float' event:
> 
> ```js
> jwplayer().on('float', function(event) {
>   console.log(event.floating); // true | false
>   this.getFloating(); // true | false
> });
> ```

Is there a way to know if the floating player has been dismissed forever? The floating player no longer floats after it was dismissed with the close button.
