### ISSUE TITLE
Future Requests: audioTracks button in controlbar.

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#3808]
I would add the option to enable a button to select the audio track in the control bar . Customers have commented that they can't find where to change it or didn't know that additional audio tracks were available.  Possibility to enable such option in configuration, I understand that not everyone needs such functionality.  

<img width="262" alt="Zrzut ekranu 2021-01-27 o 21 02 31" src="https://user-images.githubusercontent.com/9075761/106049165-238b2c00-60e6-11eb-994b-ab3bb7711fbd.png">

@aliciahurst  
You can consider my request, I don't like to write to support  :)

**Comment by aliciahurst** [comment]
Hi @mtoczko! Thanks for the idea! We may do this in a future major release of the player, but not at this time. For now, tracks can be found in the settings menu, and you can add a shortcut to it like you're showing there.

**Comment by mtoczko** [comment]
Hi @aliciahurst 
Question for 100 points, how to open a submenu for audio track selection using api?  If it was trivial, I wouldn't have asked this question.

**Comment by aliciahurst** [comment]
Good question @mtoczko! I might be missing a class or two here but I'm seeing on click you could 
add .jw-settings-open to the .jw-controls div 
and add .jw-settings-submenu-active to #jw-settings-submenu-audioTracks
and toggle aria-expanded to "true"
Pretty sure that should work.

**Comment by mtoczko** [comment]
@aliciahurst I call such solutions "prostheses".
The player is out of sync with the DOM. And there are these problems
<img width="299" alt="Zrzut ekranu 2021-04-21 o 00 28 06" src="https://user-images.githubusercontent.com/9075761/115471773-ce6c3b80-a238-11eb-888d-652d7c776243.png">

The problems I see with this solution:

- KeyListener `esc` not working.
- You have to set the focus additionally 
- The menu will not close if you click on another object

**Comment by aliciahurst** [comment]
Ah, you may be right about that, and that adding it yourself is not a great suggestion. 
At this point though with JW8 being so many years old, I am not a fan of the shortcut in the control bar, and in a future version, I don't think we'd have it at all. That's why I'm not inclined to add any more of them. What I'd rather see us do is:
1. Closed captions (with an updated icon that's not CC) button in the control bar would simply toggle them on/off, a la YouTube; changing the track would be available via a settings/kebab menu.
2. Perhaps we could have an optional Netflix-like menu combining subtitle and captions tracks for those who have that kind of experience.

**Comment by mtoczko** [comment]
Hi @aliciahurst 
I will show one example, based on youtube
[https://www.youtube.com/watch?v=WaOKSUlf4TM](https://www.youtube.com/watch?v=WaOKSUlf4TM)
This video has 2 audio tracks, this is not indicated by the interface.  Most people will not notice that such an option is available. I bet not many people check the settings for each video. Although this menu is easier to read because you can see all the options on one click.  Compared to the icon in the menu.

>Perhaps we could have an optional Netflix-like menu combining subtitle and captions tracks for those who have that kind of experience.

Apple does it in a similar style:  [https://www.apple.com/apple-events/april-2021/](https://www.apple.com/apple-events/april-2021/).
For me, this is a better solution
