### ISSUE TITLE
Future Requests: Ability to resume playback after an error 

### ISSUE THREAD

**Issue by mtoczko** [jwplayer/jwplayer#3809]
Hi @aliciahurst 

I would consider the option of trying to play the stream again one more time. The problematic situation is when the stream hasn't started yet, people get an error message and have to reload the entire page to try again. 
A more convenient solution would be to add a play button above the message or to restore the player after some time to the initial state.

**Comment by robwalch** [comment]
This is a great suggestion @mtoczko and one we've discussed internally.

It's worth noting that we used to display errors that occur during preload. For the last handful of minor releases, errors preloading a stream are surfaced as non-fatal "warnings", and clicking play will reload the stream from scratch.

I'll bring it up again with the team as this can be useful for rejoining live streams, or maybe selecting a secondary source if available and compatible. Can't promise anything so I'd encourage you to implement this by adding UI on "error" over the player that calls `load(playlistItemIndex)` to reload the current item without changing anything else about the setup.

**Comment by mtoczko** [comment]
Hi @robwalch.

> Can't promise anything so I'd encourage you to implement this by adding UI on "error" over the player that calls load(playlistItemIndex) to reload the current item without changing anything else about the setup.

I prefer to avoid adding external controllers to check status and display additional interface.

A good alternative would be to be able to add a custom UI in a commercial version. Just like you add plugins to the player.  
Going back to displayed errors, vimeo has it solved well.  By adding the ability to reload under the link.

<img width="499" alt="Zrzut ekranu 2021-03-31 o 08 53 28" src="https://user-images.githubusercontent.com/9075761/113425480-35cd6300-93d2-11eb-8b38-e7af02ba4541.png">

**Comment by aliciahurst** [comment]
Thanks for this idea, it is indeed something we've considered before, but didn't do for a few reasons. For now, I can leave it open here, but due to our network wide low error rates won't be prioritizing it very soon.
