### ISSUE TITLE
Add cast feature to custom controller via sdk

### ISSUE THREAD

**Issue by maximeroma** [jwplayer/jwplayer#3810]
### Expected Behavior

It'll be great to expose a method to launch chromecast/airplay from custom control.  

### Actual Behavior

When i click google-cast-launcher in my custom control the chrome cast is launched. I select my device android tv in the dropdown. Then the jwplayer 'cast' event is fired with castActivated = true and deviceName = "Android tv" and after nothing happens the video is never loaded. Though, when i do the same action with the google-cast-laucher of the default control it works perfectly.

**Comment by robwalch** [comment]
We don't have plans to support such a feature, as these are 3rd party APIs exposed to developers, and we expose the playlist and video element via our API and support joining active sessions.
