### ISSUE TITLE
SubRip file being parsed incorrectly

### ISSUE THREAD

**Issue by juangl** [jwplayer/jwplayer#3812]
### Actual Behavior

we have a customer who sent us a .srt file that contains a mix of Windows (`\r\n`) and Unix (`\n`) newlines sequences:

```
"1\r\n00:00:01,800 --> 00:00:02,500\r\nLorem Ipsum is simply dummy text of\n\r\n2\r\n00:00:02,600 --> 00:00:05,500\r\nthe printing and typesetting industry.\n\r\n3\r\n00:00:06,000 --> 00:00:09,900\r\nLorem Ipsum has been the industry\'s standard dummy"
```

This gets parsed incorrectly by the [JWPlayer srt parser](https://github.com/jwplayer/jwplayer/blob/7ba8e4faf1917702304bdf7ca0004d90edbc8bf5/src/js/parsers/captions/srt.ts):

```javascript
[ { begin: 1.8,
    end: 2.5,
    text:
     'Lorem Ipsum is simply dummy text of\n\r\n2\r\n00:00:02,600 --> 00:00:05,500\r\nthe printing and typesetting industry.\n\r\n3\r\n00:00:06,000 --> 00:00:09,900\r\nLorem Ipsum has been the industry\'s standard dummy' } ]
```

This can potentially be fixed by changing this part from the parser: 
https://github.com/jwplayer/jwplayer/blob/7ba8e4faf1917702304bdf7ca0004d90edbc8bf5/src/js/parsers/captions/srt.ts#L10-L13

to: 
```javascript
let list = data.split(/\r?\n\r?\n/);
```

### Environment

- JWPlayer 8.11.5

**Comment by juangl** [comment]
@robwalch I just updated the issue with new information that we found. I hope it helps to have this problem fixed easier

**Comment by robwalch** [comment]
Hi @juangl,

We recommend switching to WebVTT or correcting the line breaks in your SRT files. We don't have plans to update the parser at this time.
