### ISSUE TITLE
player failed

### ISSUE THREAD

**Issue by dluffymonkey** [jwplayer/jwplayer#3814]
JS error from executing '(function(){playerInstance.playlistItem(0);return true;})();',
	 resule = (null), 
	error = Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: playerInstance, WKJavaScriptExceptionColumnNumber=27, WKJavaScriptExceptionSourceURL=undefined, NSLocalizedDescription=A JavaScript exception occurred}

初始化的Player是全局变量

### Environment

iOS SDK   Swift

- *hardware | device*
- *operating system | version*
- *browser | version*
- *JW Player version | url*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by dluffymonkey** [comment]
JS error from executing '(function(){jwTriggerEvent('error', 'id-0', 'The operation could not be completed');return true;})();',
	 resule = (null), 
	error = Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=3, WKJavaScriptExceptionMessage=TypeError: undefined is not an object (evaluating 'r.toString'), WKJavaScriptExceptionColumnNumber=2178, WKJavaScriptExceptionSourceURL=file:///private/var/mobile/Containers/Data/Application/4A13F397-0113-4387-9951-2E4C66B700A4/tmp/54B6A1A4-56A1-4DD8-A638-8E6F20FB3BE4/jwplayer.js, NSLocalizedDescription=A JavaScript exception occurred}

**Comment by dluffymonkey** [comment]
**** DEBUG ERROR **** An uncaught JS Error was thrown: {
    message = "Script error.";
    source =     {
        isTrusted = 1;
    };
    type = error;
}

**Comment by robwalch** [comment]
Hi @dluffymonkey,

This project is not the forum for iOS SDK support. You can access support for that product at https://support.jwplayer.com/articles/android-and-ios-sdk-reference by submitting a Support Case.
