### ISSUE TITLE
renderCaptionsNatively doesn't work on 8.18.4

### ISSUE THREAD

**Issue by maximeroma** [jwplayer/jwplayer#3818]
### Expected Behavior
Have an empty captions list on Safari.

### Actual Behavior

On Safari i get this [{id: "off", label: "Off"}, {id: "nativecaptions0", label: "Unknown CC", language: ""}] on my captionList but i have set renderCaptionsNatively false in my setup method.

**Comment by robwalch** [comment]
What you have is an HLS stream with 608 captions or a manifest that doesn't include `CLOSED-CAPTIONS=NONE` on the renditions. That automatically adds an "Unknown CC" text track during playback which the player will not ignore.

`renderCaptionsNatively` does not ignore tracks, it only determines how they are rendered. Add  `CLOSED-CAPTIONS=NONE` to your manifest variants to explicitly disable 608 captions channels.

https://developer.apple.com/library/archive/qa/qa1801/_index.html
