### ISSUE TITLE
Loading new playlist while casting interrupts playback

### ISSUE THREAD

**Issue by AeonFr** [jwplayer/jwplayer#3830]
### Expected Behavior

- If we change the playlist while the player is casting, all controls should update and the play/pause controls should continue working.
- When setting a playlist item's `starttime`, that value should be respected when casting the media.

### Actual Behavior

When loading a playlist (e.g. calling `player.load()`) while a cast session is in progress:

1. The `starttime` param is not respected
2. The player enters a state in which it becomes impossible to interact with the media. \*

<img width="640" alt="Player in the 'invalid' state" src="https://user-images.githubusercontent.com/11742754/111176630-cbcb5600-85a9-11eb-88eb-5c002c15e861.png">

(\* In the code sample provided below, we set no captions to the initial playlist, and loaded a new playlist with captions while casting. It suddenly becomes impossible to change captions, but also to play or pause the player).

### Steps to reproduce

1. Save the following code in an HTML file:

```html
<!doctype html>
<html>
  <head>
    <script src="https://cdn.jwplayer.com/libraries/KEMSOowL.js"></script>
  </head>
  <body>


    <div id="player"></div>

    <script type="text/javascript">


      let player = jwplayer("player").setup({
        "playlist": [
          {
            "file": "https://cdn.jwplayer.com/manifests/wYBsqRfI.m3u8",
            "starttime": 10
          }
        ]
      });

      player.on("ready", () => {
        player.on("cast", (event)=> {
          if (!event.active) return;

          console.log("playlist loaded");
          player.load([{
            "file": "https://cdn.jwplayer.com/manifests/wYBsqRfI.m3u8",
            "starttime": 30,
            "tracks": [{
              "kind": "captions",
              "file": "https://content.jwplatform.com/tracks/d91HZQsb.vtt",
              "label": "English"
            },{
              "kind": "captions",
              "file": "https://content.jwplatform.com/tracks/zvoWJa7V.vtt",
              "label": "German"  
            }
            ]
          }]);

        });
      });

    </script> 
  </body>
</html>
```

2. Serve the file in a webserver, for example, by using [http-server](https://www.npmjs.com/package/http-server) (`npx http-server ./`)
3. Serve your webserver in a real url using [ngrok](https://ngrok.com/) or similar tool. (`npx ngrok http 8080`)
4. Load the provided URL (must be HTTPS) in a chrome tab. A chromecast device should be available to cast.
5. Play the video and watch how the player "disconnects" from the casted video (play/pause control breaks, no way to set subtitles, etc).

<img width="640" alt="Player in the 'invalid' state" src="https://user-images.githubusercontent.com/11742754/111176630-cbcb5600-85a9-11eb-88eb-5c002c15e861.png">

### Environment

- MacBook Pro (13-inch, M1, 2020) + Google Chromecast (third generation)
- MacOs Big Sur
- Chrome 89 (latest)
- https://cdn.jwplayer.com/libraries/KEMSOowL.js

**Comment by aliciahurst** [comment]
Hi @AeonFr, I'm the product manager of the player, and wanted to say that I'm sorry we're taking so long to reply to you. In fact, we recognize it often takes us _too long_ to reply here in github. I want you to get the help you need as fast as possible, which is why I'm going to close out this ticket and ask that you please [submit your issue](https://support.jwplayer.com/submit-support-case) to our fabulous technical support team, led by @SageBrushes. You'll be in great hands with them. Thanks for submitting!

**Comment by AeonFr** [comment]
Thanks for the reply @aliciahurst. I understand some issues might take time. I'll send the issue through technical support then.

**Comment by jhemmmm** [comment]
> Thanks for the reply @aliciahurst. I understand some issues might take time. I'll send the issue through technical support then.

Any news regarding to this?.
