### ISSUE TITLE
Can I use the repo to download unknown format live stream?

### ISSUE THREAD

**Issue by zydjohnHotmail** [jwplayer/jwplayer#3939]
Hello:
I can login to watch some live sports games from one small video web site. But there is no customer service, I don’t know how to set up a customer account.
However, I found that the web site uses JWPlayer to play live videos, and from the web site JavaScript, I found the HLS source seems to be available for all browser without login. It is working for Google Chrome, Microsoft Edge, and Firfox without login.
The following is one of such URL, which I can watch live sport game:
https://bingsport.com/1proxy.php?id=g_1
Other examples like:
https://bingsport.com/1proxy.php?id=g_2
https://bingsport.com/1proxy.php?id=g_3
......
https://bingsport.com/1proxy.php?id=g_20

Depend on what time you try, in the European nights, there are always some live sports games.
I tried to use Youtube-DL.exe to download it, but I got error message:
[generic] 1proxy: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1proxy: Downloading webpage
[generic] 1proxy: Extracting information
ERROR: Unsupported URL: https://bingsport.com/1proxy.php?id=g_1
I want to know what type of live stream this URL is using, and how I can download it?
For example, if I want to download this type of live stream and save as an MP4 file in my local disk using this library, what I should do?
Thanks,

**Comment by aliciahurst** [comment]
Hi, we do not provide guidance on how to download videos.

**Comment by mazznoer** [comment]
```
youtube_dl <HLS_URL>
```
