### ISSUE TITLE
custom cue points don`t  appear on the time slider

### ISSUE THREAD

**Issue by siarhei-tutejshy** [jwplayer/jwplayer#4017]
### Expected Behavior

*CUstomized cue points shold appear*

### Actual Behavior

*When we try to use custom cue points nothing happens: no changes are made in DOM, no cue points appear on  the time slider, respectively no customisation using class selectors as described in the documentation. Changing the player version to previous version using requestly extension, everything starts working as before*

### Environment

- *Laptop*
- *Windows, Linux, Mac*
- *Chrome, Edge*
- *8.26.9*

**Comment by zoeyim** [comment]
The `custom` cue point type has been deprecated with the new time slider. You can either switch to using the `chapters` cue type, or use the legacy time slider with:
```
"timeSlider" : {
  "legacy": true
}
```
