### ISSUE TITLE
I want the video to fit the screen perfectly how can I do it?

### ISSUE THREAD

**Issue by kaganzdmr58** [jwplayer/jwplayer#4026]
I am developing applications on ios and android platforms with JWPlayer, I want the videos to fit the screen exactly, but when the video ratio and the screen ratio do not match, there are gaps on the sides or on the top, how do I prevent this?

When I test it on different devices, these rates can decrease or increase, and even go up and down. I want it to fit the screen perfectly, leaving  no gaps. I'm waiting for your help.

![Screenshot_1686145274](https://github.com/jwplayer/jwplayer/assets/58965229/2f2e610b-5ab6-40cd-93e3-82e015f6281a)

**Comment by zoeyim** [comment]
You can achieve this with the `stretching` player configuration option: https://docs.jwplayer.com/players/reference/setup-options#appearance

> `stretching` string
> Resize images and video to fit player dimensions
> Possible values:
> - `uniform`: (Default) Fits JWP player dimensions while maintaining aspect ratio
> - `exactfit`: Will fit JWP player dimensions without maintaining aspect ratio
> - `fill`: Will zoom and crop video to fill dimensions, maintaining aspect ratio
> - `none`: Displays the actual size of the video file with black borders
