### ISSUE TITLE
how to make fullscreen icon disable

### ISSUE THREAD

**Issue by kaganzdmr58** [jwplayer/jwplayer#4027]
I have a problem, I make disable fullscreen mode but icon is not disable, it is show here.

![Screenshot_1687032316](https://github.com/jwplayer/jwplayer/assets/58965229/9cfaf93e-b987-40b3-908a-dd8cb7680a94)

**Comment by zoeyim** [comment]
You can remove buttons using CSS: https://docs.jwplayer.com/players/reference/css-skin-reference#button-container

For fullscreen, this is the `.jw-icon-fullscreen` class. 

I'd suggest using `display: none`.
