### ISSUE TITLE
jwplayer7.0.1+flash doesn't work.(bug?)

### ISSUE THREAD

**Issue by shucreaml0117** [jwplayer/jwplayer#681]
Hello.

I updated jwplayer from v6.x to v7.0.1
Since then, there has been something wrong with playing videos with "flash".(setup option `primary: 'flash'`)
It stops with "buffering" status and never becomes "play".

-- my environment --
pc: mac(yosemite)
browser: chrome
flash player: version 18,0,0,232 installed 
\-\-\-\-

Incidentally, in FireFox and Safari, "html5" is automatically used instead of "flash" in spite of  this setting → `primary: 'flash'`. (and it works.)

if using version 6.x, this problem doesn't occur.

please instruct me if you have some solution :pray:

**Comment by robwalch** [comment]
@shucreaml0117 which version(s) of Chrome are you seeing this in?

As mentioned in #679 [Chrome power saving](http://www.jwplayer.com/blog/chrome-power-saving/) may be blocking the Flash player from starting. You could try hosting the swf yourself to see if that prevents blocking, or if that doesn't seem to be the issue, please share a url so that we can have a look at the media you're trying to play.

**Comment by shucreaml0117** [comment]
@robwalch 

Thank you for replying :smile: 

Latest version(44.0.2403.157 (64-bit)) Chrome is installed.
And, this is a url I'm trying to play. → `http://dl01.twitcasting.tv/unachanman/download/173011802?embed=e91585cc`

I created a repository as example that shows the problem.
→ https://github.com/shucreaml0117/JWPlayer_issue_example
Please clone, and open `index.html` after inputting `jwplayer.key` on line 16.

**Comment by robwalch** [comment]
This is a case of Chrome blocking Flash content. We recommend you not set primary: 'flash' on your streams. We will be working on improving the experience when Flash content is blocked, but the user will  need to initiate playback with a click. Autostart will not be possible with Flash in Chrome. Eventually it is very likely that we will deprecate primary setup option as well.

Is there any reason that you need to set primary: 'flash' ? Ads?

**Comment by chrisdeely** [comment]
@robwalch I would encourage you to not remove the ```primary``` config option. We have use cases where we need to use the Flash rendering for HLS, even on Safari.

Specifically, we have custom metadata in our HLS streams that needs to be read at runtime, and the HTML5 implementation never fires the ```meta``` event for ID3 or other timed metadata on desktops.

**Comment by robwalch** [comment]
Good to know @chrisdeely. "very likely" is strong language - considering it. If you need autoplay, more than our HLS functionality or Flash ad support than be wary. That's the message we're working on. Soon Flash in Chrome with "Detect and run important plugin content" power save feature will behave like click to start video on iOS.

**Comment by shucreaml0117** [comment]
@robwalch 

I'm sorry for being late. :sob:
For a reason, it is better to use flash.
But, this time, I tried with html5 player and it went well!

Thank you.
