### ISSUE TITLE
Do not attempt to load chunk files from CDN in open-source builds

### ISSUE THREAD

**Issue by ping** [jwplayer/jwplayer#700]
I've no problems building 7.0.1 but noticed some odd changes with 7.0.2/7.0.3

Below is the build outputs for 7.0.1 and 7.0.3.

```
$ ls jwplayer-7.0.1/bin-release
jwplayer.09c66dd58cf6fdcbe348.map	jwplayer.flash.swf			jwplayer.js

$ ls jwplayer-7.0.3/bin-release
1.1.js						jwplayer.f966f8df54d94c1842ba.map		provider.youtube.f966f8df54d94c1842ba.map
1.f966f8df54d94c1842ba.map			jwplayer.flash.swf
2.provider.youtube.js				jwplayer.js
```

Also, when testing 7.0.2/3, the page attempts to load "http://p.jwpcdn.com/player/v/7.0.3/2.provider.youtube.js" (which returns a 404).

I did not have these problems with the 7.0.1 build.

Any idea what's wrong?

**Comment by robwalch** [comment]
Hi @ping,

We split out the youtube provider as well as a btoa polyfill for ie9 (1.js) into separate files in 7.0.2.

http://p.jwpcdn.com/player/v/7.0.3/provider.youtube.js
http://p.jwpcdn.com/player/v/7.0.3/1.js

It should be provider.youtube.js not 2.provider.youtube.js. Maybe this is a problem with the open-source gruntfile that is not an issue in our commercial project.

**Comment by ping** [comment]
@robwalch Perhaps I'm reading this wrongly, but why is the main script loading anything from http://p.jwpcdn.com in the first place? Since this is the open-source version, I'd expect it to stand on it's own. This dependency makes it impossible to self-host in my opinion.

Also, the problem with the wrong filenames doesn't seem like an issue if the main script would load from current directory instead of http://p.jwpcdn.com.

**Comment by robwalch** [comment]
@ping 

Release builds will attempt to load webpack chunks from the CDN. You can avoid this by setting `base` to '.' in your setup when self hosting.

`__webpack_public_path__`
https://github.com/jwplayer/jwplayer/blob/master/src/js/jwplayer.js#L7

is set to `config.base` (script location)
https://github.com/jwplayer/jwplayer/blob/master/src/js/api/config.js#L46

 or `utils.loadFrom()`
https://github.com/jwplayer/jwplayer/blob/master/src/js/utils/playerutils.js#L37

Only release builds will work with the webpack chunks on the CDN. This feature simplifies setup of the commercial releases. If should not be in open-source (this project) to prevent users like yourself from running into this issue.

**Comment by ping** [comment]
@robwalch Thanks for the info. Wished that the change was better documented though.

Verified that the 2c271bd commit fixed the filename issue.
