### ISSUE TITLE
[7.0.3] playing mp4(radio movie) with firefox

### ISSUE THREAD

**Issue by shucream0117** [jwplayer/jwplayer#709]
#### Problem
When a mp4 movie is composed of still image(2fps) and audio, Firefox can't play the movie correctly.
like this ↓
![sep 08 2015 20 46](https://cloud.githubusercontent.com/assets/13616781/9733996/b63a936a-566a-11e5-9259-13a4bc3329ae.gif)

#### my environment
- mac(yosemite)
- firefox 40.0.3(latest)
(it occurs only with firefox)

#### Please check this
1. clone this → https://github.com/shucreaml0117/JWPlayer_issue_example
2. input your license key in `index.html` line 15.
3. open `index.html` with latest version of Firefox.

:pray:

**Comment by robwalch** [comment]
The player thinks your movie is stalling because of slow time updates. If the video tag can provide src fps we can investigate a fix.

**Comment by shucreaml0117** [comment]
@robwalch 

>If the video tag can provide src fps

Sorry, I couldn't understand this sentence...😭
(I think, maybe video tag doesn't provide any options for fps.)

If I use previous version of JWPlayer(v6), the probrem doesn't occur.
Is it difficult for JWPlayer7 to play video whose fps is extremely low?

**Comment by donato** [comment]
This is occurring due to the stall check handler, look here : https://github.com/jwplayer/jwplayer/blob/master/src/js/providers/html5.js#L513

**Comment by robwalch** [comment]
@shucreaml0117 yes, unfortunately there is not method to get media fps from the video tag. So we can't adjust the stall check handler that way. Only option I can think of for now would be to disable it in Firefox, or ask mozilla to provide more frequent time events based on audio playback and not video frame rendering.

**Comment by shucream0117** [comment]
@robwalch 

ok, I decided to use previous version of JWPlayer in Firefox.
Thank you.
