### ISSUE TITLE
7.0.3 calling getDuration following the initial on('play') returns 0

### ISSUE THREAD

**Issue by jakedahm** [jwplayer/jwplayer#717]
I am writing an analytics plug-in, and have that found calling getDuration after the on('play') event is dispatched the first time returns 0. It is not until the first on('time') event that you receive the correct duration.

```javascript
(function(jwplayer) {
    jwplayer().registerPlugin('playerAnalytics', '7', function(player, options, element) {
        var trackHandler = function(e) {
            var video = player.getPlaylistItem();
            var video_meta = {
                duration: parseInt(player.getDuration()),
                player_name: options.player_name || 'JW Player',
                title: video.title || video.file
            };
            console.log(video_meta); // video_meta.duration = 0
        };
        player.on('play', trackHandler);
        player.on('pause', trackHandler);
        player.on('complete', trackHandler);
        player.on('time', trackHandler);
    });
}(window.jwplayer));
```

**Comment by robwalch** [comment]
Hi @jakedahm,

This is a known issue. I'll see if we can get a fix for it with html5 and Flash playback in our 7.1.1 release.

The player's model doesn't get duration from the current video provider until the first time event so that's why you are seeing this behavior:

https://github.com/jwplayer/jwplayer/blob/master/src/js/controller/model.js#L93

The plan so far is to add this data to "bufferChange" events so that it can be set before playback when media is buffering (or preloading in v7.1.1:tada:).

**Comment by jakedahm** [comment]
Thanks @robwalch!

Can you give me an idea of when 7.1.1 will be released? I know you are still at 7.1.0-beta, but I am wanting to cut over to 7 from 6 ASAP.

**Comment by robwalch** [comment]
@jakedahm We're shooting for end of the month based on our current 2 week cycle.

This is an issue we deal with in our own analytics product. We require four events to fire before all the playback data is available (and we could probably ignore play the more I think about it).

- 'play' (video tag or provider indicated that playback has begun)
- 'meta' (usually where duration, width and height are provided)
- 'levels' (usually before play when we know what qualities are available)
- 'firstFrame' (new in 7. Fired either when the first frame is rendered or first time event, depending on provider)

Keep in mind that this developed for the course of 6.x to 7.x. Our analytics plugin has to work across multiple versions of the same major release so it works around the short comings of previous releases.

Keep in mind that this developed for the course of 6.8 to 7.x. Our analytics plugin has to work across multiple versions of the same major releases.

We can reopen this issue if you want to get a notification when we've made a change internally. I hope with preloading we can also provide duration in some instances before play is even called.

**Comment by jakedahm** [comment]
I think it should be alright. I just found out that 'meta' is fired before 'play', and contains the duration in the event payload.

Thanks
