### ISSUE TITLE
Thumbnail background images not loading

### ISSUE THREAD

**Issue by matb33** [jwplayer/jwplayer#725]
The line found at https://github.com/jwplayer/jwplayer/blob/master/src/js/view/components/thumbnails.mixin.js#L81

should change from: `style.backgroundImage = url;`
to: `style.backgroundImage = 'url(' + url + ')';`

**Comment by robwalch** [comment]
In which browser? Works in latest Chrome.

We'll make it `'url("' + url + '")';` the double quotes take care of anyone careless enough to include apos in their urls (it's happened).

**Comment by matb33** [comment]
For myself it was Chrome, though I'm on beta (46.0.2490.22). I also thought it strange it wouldn't work without the `url()` syntax. If it helps, my URL was fully qualified and I was working from the minified version of jwplayer.js.
