### ISSUE TITLE
DASH stream with presentationTimeOffset fails

### ISSUE THREAD

**Issue by mattcoz** [jwplayer/jwplayer#752]
This is a bug in Shaka 1.4.x and is fixed in 1.5.0 which was released on September 17.

https://github.com/google/shaka-player/issues/143

The bug refers to live streams, but it affects on-demand stream clips as well.

**Comment by donato** [comment]
Shaka 1.5 looks like a great release, we can't wait to get it in! We do have a responsibility to thoroughly vet it before pushing it out, we should have time over the next few weeks to get it in though :+1: 

I think ultimately we should allow publishers the freedom to select which version of Shaka to use with the player, or use a default which we can guarantee has been tested extensively.

Ultimately versioning the providers independently from the player would be a pretty slick enhancement.

**Comment by donato** [comment]
@mattcoz - this will be going into v7.2.0

**Comment by donato** [comment]
@mattcoz - player v7.2.3 has been released to our beta channel
