### ISSUE TITLE
[7.x] Youtube Quality toggle doesn't indicate active option nor does it seem to have an effect

### ISSUE THREAD

**Issue by ping** [jwplayer/jwplayer#756]
The quality setting doesn't indicate which option has been selected. Also, changing the quality setting does not seem to have an effect. I tested by setting it to the worst / best possible setting. It appears to be stuck on auto.

![image](https://cloud.githubusercontent.com/assets/104607/10037909/5f89bea2-61ef-11e5-89c6-a665a098ee77.png)

Demo link: https://rawgit.com/ping/60587ee7132458733ebe/raw/e99a1b60b5907bd298bc1ffe0659dfbd3eb384eb/jwplayer-71x-youtube-test.html

**Comment by donato** [comment]
Good find. If I had the time I would try debugging this method : https://github.com/jwplayer/jwplayer/blob/master/src/js/providers/youtube.js#L594

I bet something screwy is going on in there!

**Comment by ping** [comment]
The only way I managed to force a quality change is to stop the video (pause doesn't work), setting the quality, and playing video again.

https://github.com/jwplayer/jwplayer/blob/master/src/js/providers/youtube.js#L602

```
_youtubePlayer.stopVideo();
_youtubePlayer.setPlaybackQuality(ytQuality);
_youtubePlayer.playVideo();
```
Is there code actually updating the selected quality in UI? The UI still doesn't update with the selected quality even though actual playback quality has changed.

**Comment by robwalch** [comment]
According to Google's docs this is expected https://developers.google.com/youtube/iframe_api_reference#setPlaybackQuality

> This function sets the suggested video quality for the current video. The function causes the video to reload at its current position in the new quality. If the playback quality does change, it will only change for the video being played. Calling this function does not guarantee that the playback quality will actually change.

**Comment by eye8** [comment]
@robwalch thanks for pointing to the YouTube player api. I understand it's the expected behavior with the YouTube player. But @ping 's code actually proved to work for me. Will you consider revising the `setCurrentQuality` method in the YouTube provider?

```
        this.setCurrentQuality = function(quality) {
            if (!_youtubePlayer) {
                return;
            }
            if (_youtubePlayer.getAvailableQualityLevels) {
                var ytLevels = _youtubePlayer.getAvailableQualityLevels();
                if (ytLevels.length) {
                    var ytQuality = ytLevels[ytLevels.length - quality - 1];
                    var currentTime = _youtubePlayer.getCurrentTime();
                    _youtubePlayer.stopVideo();
                    _youtubePlayer.setPlaybackQuality(ytQuality);
                    _youtubePlayer.seekTo(currentTime);
                }
            }
        };
```

Thanks.
