### ISSUE TITLE
error build

### ISSUE THREAD

**Issue by ahmedlotfey** [jwplayer/jwplayer#757]
Running "flash:debug" (flash) task
C:\AIRSDK_Compiler/bin/mxmlc -compiler.source-path=src/flash -compiler.library-p
ath+=C:\AIRSDK_Compiler/frameworks/libs -default-background-color=0x000000 -defa
ult-frame-rate=30 -target-player=11.2 -swf-version=15 -use-network=true -show-mu
ltiple-definition-warnings=true -compiler.inline=true -compiler.remove-dead-code
=true -define+=JWPLAYER::"version,'7.2.0-alpha.0'" -output=bin-debug/jwplayer.fl
ash.swf src/flash/com/longtailvideo/jwplayer/player/Player.as -link-report=bin-d
ebug/jwplayer.flashlink.xml -size-report=bin-debug/jwplayer.flashsize.xml -stric
t=true -debug=true -define+=CONFIG::debugging,true
Fatal error: spawn C:\AIRSDK_Compiler\bin\mxmlc ENOENT

**Comment by ahmedlotfey** [comment]
windows 7 64bit

**Comment by donato** [comment]
This means the file isn't found (or the shell doesn't have permissions for it), try setting an environment variable for $AIR_HOME that matches your install directory

**Comment by ahmedlotfey** [comment]
Hi I already do this and same problem , is there any one try to build with windows7 64bit 

cheers

**Comment by donato** [comment]
You are right, the flash compiler does not support windows!

We will need some toggling to add ".bat" to the end of all binaries (ie all the strings which go /bin/___) in this project:

https://github.com/jwplayer/grunt-flash-compiler

**Comment by ahmedlotfey** [comment]
is there any way to compile it on ubuntu using flex cause air not supported any more on Linux 

regards

**Comment by donato** [comment]
yup, we do just that for our jenkins builds!

Just make sure you have FLEX_HOME set, and that AIR_HOME is *not* set

Relevant code is here : https://github.com/jwplayer/jwplayer/blob/master/Gruntfile.js#L277

**Comment by ahmedlotfey** [comment]
Thanks for Help , i will try and feedback :)

**Comment by ahmedlotfey** [comment]
after try i get this error after npm install

C:\jwplayer>npm install
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (curre
nt: {"node":"4.1.1","npm":"2.14.4"})
npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN optional dep failed, continuing fsevents@1.0.0

> phantomjs@1.9.18 install C:\jwplayer\node_modules\phantomjs
> node install.js

Download already available at C:\Users\Devloper\AppData\Local\Temp\phantomjs\pha
ntomjs-1.9.8-windows.zip
Extracting zip contents
Removing C:\jwplayer\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\Devloper\AppData\Local\Temp\phantomjs\phantomj
s-1.9.8-windows.zip-extract-1443115153993\phantomjs-1.9.8-windows -> C:\jwplayer
\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\jwplayer\node_modules\phantomjs\lib\phant
om\phantomjs.exe
npm WARN optional dep failed, continuing fsevents@1.0.0
/
> ws@0.4.32 install C:\jwplayer\node_modules\karma\node_modules\socket.io\node_m
odules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\jwplayer\node_modules\karma\node_modules\socket.io\node_modules\socket.io-cli
ent\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files\n
odejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gy
p.js" rebuild )  else (node  rebuild )
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path C:\Users\Devloper\AppData\Roaming\npm-cache\wrappy\1.0.1\package\p
ackage.json.ca831dbf8e860038eecd6ec18dfec0e3
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Devloper\AppDat
a\Roaming\npm-cache\wrappy\1.0.1\package\package.json.ca831dbf8e860038eecd6ec18d
fec0e3' -> 'C:\Users\Devloper\AppData\Roaming\npm-cache\wrappy\1.0.1\package\pac
kage.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\Devloper\Ap
pData\Roaming\npm-cache\wrappy\1.0.1\package\package.json.ca831dbf8e860038eecd6e
c18dfec0e3' -> 'C:\Users\Devloper\AppData\Roaming\npm-cache\wrappy\1.0.1\package
\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\Devloper\\AppData\\Roaming\\npm-cache\\wrappy\\1.0.
1\\package\\package.json.ca831dbf8e860038eecd6ec18dfec0e3',
npm ERR!   dest: 'C:\\Users\\Devloper\\AppData\\Roaming\\npm-cache\\wrappy\\1.0.
1\\package\\package.json',
npm ERR!   parent: 'once' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\jwplayer\npm-debug.log

**Comment by robwalch** [comment]
You might want to give `npm cache clear` a try. Then `npm update -g` to update to the latest npm.

**Comment by ahmedlotfey** [comment]
another error

Running "flash:debug" (flash) task
C:\AIRSDK_Compiler/bin/mxmlc -compiler.source-path=src/flash -compiler.library-p
ath+=C:\AIRSDK_Compiler/frameworks/libs -default-background-color=0x000000 -defa
ult-frame-rate=30 -target-player=11.2 -swf-version=15 -use-network=true -show-mu
ltiple-definition-warnings=true -compiler.inline=true -compiler.remove-dead-code
=true -define+=JWPLAYER::"version,'7.2.0-alpha.0'" -output=bin-debug/jwplayer.fl
ash.swf src/flash/com/longtailvideo/jwplayer/player/Player.as -link-report=bin-d
ebug/jwplayer.flashlink.xml -size-report=bin-debug/jwplayer.flashsize.xml -stric
t=true -debug=true -define+=CONFIG::debugging,true
Fatal error: spawn C:\AIRSDK_Compiler\bin\mxmlc ENOENT

**Comment by ahmedlotfey** [comment]
finally my error was i need to create folder C:\AIRSDK_Compiler\frameworks\libs\player\11.1 and copy the file  playerglobal.swc on it


PhantomJS 1.9.8 (Windows 7 0.0.0): Executed 77 of 77 SUCCESS (0.541 secs / 0.433
 secs)

Done, without errors.

C:\jwplayer>

**Comment by donato** [comment]
No problem! Feel free to update the documentation if you think it could be better.

**Comment by chengshengru** [comment]
same error
Running "flash:debug" (flash) task
F:\IdeaProjects\jwplayer\node_modules\jwplayer-flex-sdk\lib\flex_sdk/bin/mxmlc.b
at -compiler.source-path=src/flash -compiler.library-path+=F:\IdeaProjects\jwpla
yer\node_modules\jwplayer-flex-sdk\lib\flex_sdk/frameworks/libs -compiler.extern
al-library-path=F:\IdeaProjects\jwplayer\node_modules\jwplayer-flex-sdk\lib\flex
_sdk/frameworks/libs/player/11.2/playerglobal.swc -default-background-color=0x00
0000 -default-frame-rate=30 -target-player=11.2 -swf-version=15 -use-network=tru
e -static-link-runtime-shared-libraries=true -define+=JWPLAYER::"version,'7.8.6'
" -output=bin-debug/jwplayer.flash.swf src/flash/com/longtailvideo/jwplayer/play
er/Player.as -link-report=bin-debug/jwplayer.flashlink.xml -size-report=bin-debu
g/jwplayer.flashsize.xml -strict=true -debug=true -define+=CONFIG::debugging,tru
e
Fatal error: spawn F:\IdeaProjects\jwplayer\node_modules\jwplayer-flex-sdk\lib\f
lex_sdk\bin\mxmlc.bat ENOENT

**Comment by robwalch** [comment]
Maybe windows doesn't like the mix of forward and backward slashes in the mxmlc command. Have a look at Grunfile.js and https://github.com/jwplayer/jwplayer-flex-sdk/

We have no interest in supporting Windows for building the player but will gladly look at any PR that adds support.

**Comment by johnBartos** [comment]
@chengshengru What shell are you using? I've built on Windows before with git-bash and that seemed to work. You can ignore the flash errors with `grunt --force` if you're just working on the html5 project
