### ISSUE TITLE
jwplayer README.md says it's open source, but license doesn't meet Open Source Definition

### ISSUE THREAD

**Issue by gerv** [jwplayer/jwplayer#763]
By far the most commonly-used definition of "open source" is the one from the Open Source Initiative (OSI): http://opensource.org/osd .

The very first item in that definition is:

"1. Free Redistribution. The license shall not restrict any party from selling or giving away the software as a component of an aggregate software distribution containing programs from several different sources. The license shall not require a royalty or other fee for such sale."

Selling the software, whether on its own or in aggregate, is not permitted by JWPlayer's license, CC-BY-NC-SA, because that license has a non-commercial restriction. So, JWPlayer is not open source using the standard definition, and the README.md and other docs and websites should be updated to remove that claim, because it will cause confusion and upset.

**Comment by donato** [comment]
Thank you for the feedback, I think it'd be cool to use a more modern license, but it would require a fair amount of business research/planning first.

In order to avoid confusion for people, we have a section on the front page of our github:
https://github.com/jwplayer/jwplayer#software-license

**Comment by gerv** [comment]
It would indeed be cool to use a better license :-), but that is not what this bug is about. In the readme section you link, it says this is "JW Player Open Source edition". My point is that you should not call it "open source" when it's not open source. This term has a widely-understood definition in the industry, and your license doesn't meet it because of the non-commercial restriction. So I am say that (pending any license change you may or may not do) you should update your documentation to be clear that, at the moment, JWPlayer is not open source.

I have spent a lot of time doing licensing stuff; if you need some help and advice in choosing a true open source licence for JWPlayer which also meets your business goals, I am very happy to help. :-)

**Comment by gerv** [comment]
Hey. Thanks for fixing that instance, but it's not the only place the player is referred to as "open source". 

Top of README.md:
JW Player is -the- open source solution for making video playback seamless

Let me know if you'd prefer a new bug to be opened.
