### ISSUE TITLE
can not build jwplayer

### ISSUE THREAD

**Issue by elibushehri** [jwplayer/jwplayer#774]
hi
I have already installed node.js and JAVA and Adobe air SDK. I also installed air SDK by using npm. and when I use npm install in my jwplayer directory I got this error
![capture](https://cloud.githubusercontent.com/assets/12871462/10122743/93a6b0fe-652e-11e5-9b12-e879be63c7d4.PNG)
please help to solve that

**Comment by robwalch** [comment]
This looks like a problem installing phantomas with your install of npm. Try updating npm to the latest and try again:

`npm update -g`

**Comment by elibushehri** [comment]
![capture](https://cloud.githubusercontent.com/assets/12871462/10128033/50da54f2-65b9-11e5-9514-5697f421d960.PNG)
I still have problem with that. registry error, unexpected token and etc!

**Comment by elibushehri** [comment]
can I use flex sdk and ant with adobe flash builder?

**Comment by elibushehri** [comment]
some how I solved that problem. now I have this problem that
[image: Inline image 1]

problem with installing bower! I cant install it at all.
thanks

**Comment by elibushehri** [comment]
it's done! I should first of all install -g grunt and then install and finally grunt.

**Comment by donato** [comment]
great thanks for the feedback!
