### ISSUE TITLE
appearing jwplayer on different browsers

### ISSUE THREAD

**Issue by elibushehri** [jwplayer/jwplayer#781]
hi again. sorry I'm new with jwplayer specially 7 versions and their changes.
As I said before I build Jwplayer version 7.1.0 but still I have some problems to deal with.
My jwplayer only appears on chrome, although if I link the file to an url, it will be wait on loading and do nothing (no problem with audios that load from PC or URL (net) and videos from PC). also jwplayer does not show up on mozilla firefox and IE (opera and the other browsers have not been tested yet :)).
 in build process I got no html.js file in my bin release, I just have swf and js. is that normal?! 
and one last thing is we should script jwplayer.js from bin release or debug release?
 would you mind help me to solve these problems?
thanks

**Comment by robwalch** [comment]
> in build process I got no html.js file in my bin release, I just have swf and js. is that normal?! 

Yes this is normal. In 7, the functionality that was present in jwplayer.html5.js with version 6 is now incorporated in jwplayer.js.

Please provide a test page and steps to reproduce the issues you are having.

**Comment by donato** [comment]
When testing use bin-debug, when releasing use bin-release :) Best of luck, I will close this until you provide a test page to show your issue.
