### ISSUE TITLE
Mootools 1.4.5 breaks JWPlayer7

### ISSUE THREAD

**Issue by roisag** [jwplayer/jwplayer#822]
I noticed that mootools 1.4.5 core library stops jwplayer7 from working with errors:
Uncaught TypeError: Cannot read property 'css' of undefined
Uncaught ReferenceError: jwplayer is not defined
Uncaught ReferenceError: jwplayer is not defined

**Comment by robwalch** [comment]
[Mootools breaks ES5's `bind()`](https://github.com/mootools/mootools-core/issues/2707) which breaks many other things, in this case WebPack's style loader. Maybe give Mootools 1.5.x a try?
