### ISSUE TITLE
Add support for Windows Surface IE10+

### ISSUE THREAD

**Issue by bhargavshah** [jwplayer/jwplayer#844]
Right now, JWPlayer works on Windows Surface IE10 in mouse mode even though it is a touch device. This makes it unusable for some features. For example,
* Trying to change the volume - Tapping on volume, it mutes/unmutes. The volume slider does not stay   because JWPlayer thinks it is a desktop mouse enabled device and expects a mouseover event to show the volume slider. (IE has pointer events which are a unification of touch and mouse events)
* Trying to change the subtitle language - Tapping on 'CC' the language list does not stay for the same reason as above.

**Comment by donato** [comment]
This is really interesting feedback, thank you! @jw-kaurand - any idea why this is happening?

**Comment by jw-kaurand** [comment]
This is likely related to how PointerEvents are handled in IE 10.  What version of JWPlayer are you having this issue with?  We support devices and browsers which use PointerEvents in JWPlayer 7.

**Comment by bhargavshah** [comment]
I'm using JW 6.8.4616. Can you add support for the version I'm using?

**Comment by robwalch** [comment]
No. We released 6.8 in early 2014.

JW Player 7 features a modern UI with support for MS Pointer Events. Can you upgrade?

**Comment by robwalch** [comment]
Let us know your experience with controlbar menus in v7+. Our understanding is that this issue has long been resolved.

**Comment by bhargavshah** [comment]
I'm trying it out right now. Thanks for the response.
Btw, JW7 is really sleek. Kudos!
