### ISSUE TITLE
bower installable binary release?

### ISSUE THREAD

**Issue by peterzen** [jwplayer/jwplayer#851]
Is there an available compiled distribution that can be installed with bower without compiling?

**Comment by robwalch** [comment]
There are several unofficial mirrors with builds of 6 and 7 that seem to be of the commercial variety.

How important is this to your project?

Which version of jwplayer do you use now?

**Comment by peterzen** [comment]
Thanks for the answer @robwalch .

Currently I use v6 from itnok/jwplayer-mirror, but would like to upgrade to 7 and stay on the latest releases.  I've successfully built v7 but ideally would like to leave the build out of my own build process as I'm not likely to customize it in any way, a 'stock' build that's always up to date would be of great help as my build could then always pick up the latest release and be in sync with the upstream.

So the benefit would be convenience, mostly – however as long as v7 is still quite fluid and has frequent releases I imagine I could take some guesswork out of the process of debugging.

Thanks again.

**Comment by anthonygreco** [comment]
👍

**Comment by gjchung** [comment]
When is this feature going to be available?

**Comment by johnBartos** [comment]
@gjchung Probably never unless there's quite a lot of demand for it. I can see the case for NPM but not bower.

**Comment by robwalch** [comment]
Sign up for an account. Under the tools section you can get a url to a cloud hosted player library. This url is always up to date and licensed for use. https://www.jwplayer.com/sign-up/
