### ISSUE TITLE
JW7 Providers - Backbone events

### ISSUE THREAD

**Issue by shaharmor** [jwplayer/jwplayer#857]
Hi,

I'm looking to write a provider for JW7, but i can't seem to find how to extend my provider with the backbone events you are using like here: https://github.com/jwplayer/jwplayer/blob/master/src/js/providers/html5.js#L61

Any help will be appreciated.

**Comment by robwalch** [comment]
Hi @shaharmor,

`backbone.events` is available via the player instance (`jwplayer().Events`). In your provider's constructor, use the player id to query the current player instance. That will also give you access to underscore which you can use to extend the provider.

```javascript
function MyProvider(playerId, playerConfig) {
    var player = jwplayer(playerId);
    player._.extend(this, player.Events);
```

**Comment by shaharmor** [comment]
Great! Thanks a lot.

Btw, underscore is also available at `jwplayer._`
