### ISSUE TITLE
HLS support

### ISSUE THREAD

**Issue by j-norwood-young** [jwplayer/jwplayer#884]
Hi guys

Does the open source player support HLS? I've been trying to get it to play HLS on Android, and although the stream does start playing, I get a setup error, and now events are fired. I've also tried a plain-Jane test on Chrome and HLS doesn't seem to want to play there either.

Thanks
J

**Comment by robwalch** [comment]
It should work on browsers with native support (iOS, Safari, Edge, maybe Android) but to play HLS on platforms without it like Chrome you'd need aliveness commercial jwplayer.

**Comment by esboyd** [comment]
*aliveness = "licensed" commercial player
