### ISSUE TITLE
About IDE

### ISSUE THREAD

**Issue by daiyanbao** [jwplayer/jwplayer#892]
Thanks for your product
jwplayer is very powerful 

i want know which ide your use

i build then in grunt and Atom

but i don't know how to debug the source code

**Comment by robwalch** [comment]
Most of the team at JW Player use [IntelliJ](https://www.jetbrains.com/idea/whatsnew/?mail=news&mkt_tok=3RkMMJWWfF9wsRojsqnNZKXonjHpfsX56eUpX6Swg4kz2EFye%2BLIHETpodcMRMFgNa%2BTFAwTG5toziV8R7THKs1xzNEQWhDm). We do most of our debugging in the browser with Chrome's dev tools.

**Comment by daiyanbao** [comment]
I means action script 

maybe IntelliJ debug flash is not a best solution

**Comment by robwalch** [comment]
IntelliJ is great for debugging ActionScript.  Just install the debug NPAPI Flash player and launch your page in Firefox.
