### ISSUE TITLE
Controlling Timeout for ads

### ISSUE THREAD

**Issue by eranbrill** [jwplayer/jwplayer#894]
Hi ,
Is there a way to control or modify the timeout of the player for preroll ads playing?

**Comment by donato** [comment]
This isn't currently possible, but we have discussed adding this feature.

How would you like to use it? For just prerolls, or for midrolls as well? What type of ads? Would you set it higher or lower than the current default?

**Comment by eranbrill** [comment]
mostly prerolls, and I would want to have control over it, and change it according to setup:
- making it shorter for better UX, sometimes.
- Making it longer and giving engought time fir the adserver to respond. - this is something I am dealing with right now.

- What is currently the default timeout set?
- can You point me where in the code, so I can make my own custom version, and perhaps contribute my changes as well?

**Comment by robwalch** [comment]
Hi @eranbrill,

The VAST plugin source is not public. There is a 5 second timeout on VMAP schedule requests and a 5 second timeout on ad tag (including wrapped tag) requests.

We've considered making this configurable. There is not a recommendation as to how should be done by the IAB in the VAST spec. They basically say it's "defined by the video player".

If we did do it, it would probably be another option like `skipOffset`, and we would have to constrain it to something within reason like 1-30 seconds.

**Comment by christopherosko** [comment]
Very interested in this feature too.
Ideally, there should be one timeout for the vast tag and one for the vast media, just as IMA is doing.
Are you still considering making this configurable ?
I'd do it by myself but the source isn't public :(

**Comment by robwalch** [comment]
We're working on a feature now allows configuration of ad request and ad creative start timeouts...

**Comment by robwalch** [comment]
Hi @eranbrill @christopherosko,

It's been a while!

Two options have been implemented that allow setting the timeouts of ad tag and ad creative requests: `requestTimeout` and `creativeTimeout`.

https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/#Advertising

**Comment by christopherosko** [comment]
Good news, thanks 👍
