### ISSUE TITLE
Buffering in adaptive multi-bitrate live streams

### ISSUE THREAD

**Issue by lomenl** [jwplayer/jwplayer#895]
Hello,
We are using JW Player 7.14 Ads Edition and found that many times the player can not perform well when the available download bandwidth suddenly decreases. I made a short video (and uploaded to our CDN:  http://httphu-service01.connectmedia.hu/6136/JW_buffering_1.mov) where I simply set the download speed to 1 Mbit/s with Network Link Conditioner and I got a lot of buffering sign on the screen. As you can see in the video, I have not set any other "problem" like packed drop or delay. The profile bitrates are: 3, 1.5, 1, 0.8, 0.4 Mb/s with 64 kb/s audio.
My questions: Do you know about this issue? Is there any improvement in progress regarding this issue?
Can I provide more details which can help you to analize this issue more deeply?
Thanks in advance,
Laszlo

**Comment by robwalch** [comment]
Have you considered upgrading to JW Player 7? It can maintain playback of videos which have a bitrate less than or equal to the rate at which the media file can be accessed.

We do not support JW Player 4. This repo contains the public portions of JW Player back to version 6.

**Comment by lomenl** [comment]
Hi,
sorry, it was a typo, the version number is 7.14.
Regards,
Laszlo

**Comment by robwalch** [comment]
We're about to release 7.2. Please give it a try. We've introduced the ability to preload which may help with your situation.

The most helpful thing would be to post the url of the page you're having trouble with, or create a new page that duplicates the issue.

**Comment by lomenl** [comment]
Thanks! The url is: http://web12.connectmedia.hu/jw7/jw7.html. You can easily simulate the issue with Network Link Conditioner or other bandwidth limiter tool.
Can you please tell me the download source of release 7.2?

**Comment by robwalch** [comment]
Hi @lomenl,

I was able to see the behavior you described. We haven't made any changes to adaptive streaming in v7.2 so updating the player won't help in this case. For your reference I post links in the [releases section](https://github.com/jwplayer/jwplayer/releases).

The problem boils down to the quality levels of your stream, their bitrates and distance to each other and the available bandwidth.

I ran Apple's `mediastreamvalidator` and it reported that every level exceeded it's target rate by 10-20%. JW Player must be naive in that it assumes the bitrate's in the manifest are the max speed of each adaption. When that is not true, and the connection can't deliver the stream at the speed advertised we drop to a lower quality. Since the lowest quality is half the bitrate and delivered with time to space, the player tries to go back to quality that should work, but because it's 10% larger than advertised it cannot be sustained. The "auto" switching is expensive and resulting in under buffering.

Here's some of the output from `mediastreamvalidator`:

```
media_w1140145017_b400000_22545.ts:
	WARNING: Media segment bandwidth exceeded target playlist bandwidth
	--> Bandwidth exceeded by 21 % (484.29 kbits/sec vs 400.00 kbits/sec, limit is 10 %)

Average segment duration: 10.00 seconds
Playlist target bitrate: Max: 400.00 kbits/sec
Segment bitrate: Average: 493.48 kbits/sec (exceeds target by 23.37 %), Max: 504.44 kbits/sec (exceeds target by 26.11 %)
Average segment structural overhead: 49.05 kbits/sec (9.94 %)
...
media_w1140145017_b800000_22545.ts:
	WARNING: Media segment bandwidth exceeded target playlist bandwidth
	--> Bandwidth exceeded by 11 % (884.20 kbits/sec vs 800.00 kbits/sec, limit is 10 %)

Playlist target bitrate: Max: 800.00 kbits/sec
Segment bitrate: Average: 902.40 kbits/sec (exceeds target by 12.80 %), Max: 927.22 kbits/sec (exceeds target by 15.90 %)
Average segment structural overhead: 57.98 kbits/sec (6.43 %)
...

media_w1140145017_b1200000_22544.ts:
	WARNING: Media segment bandwidth exceeded target playlist bandwidth
	--> Bandwidth exceeded by 12 % ( 1.34 Mbits/sec vs  1.20 Mbits/sec, limit is 10 %)

Playlist target bitrate: Max:  1.20 Mbits/sec
Segment bitrate: Average:  1.31 Mbits/sec, Max:  1.35 Mbits/sec (exceeds target by 12.56 %)
Average segment structural overhead: 66.76 kbits/sec (5.09 %)
...

media_w1140145017_b1600000_22544.ts:
	WARNING: Media segment bandwidth exceeded target playlist bandwidth
	--> Bandwidth exceeded by 10 % ( 1.76 Mbits/sec vs  1.60 Mbits/sec, limit is 10 %)

Playlist target bitrate: Max:  1.60 Mbits/sec
Segment bitrate: Average:  1.72 Mbits/sec, Max:  1.77 Mbits/sec (exceeds target by 10.84 %)
Average segment structural overhead: 75.50 kbits/sec (4.39 %)
```

I don't think you're the only person who's experiencing this. We've seen similar problems with multi-bitrate live HLS. Can you give us any more info about the live stream? Which streaming providers or CDNs you use?

**Comment by lomenl** [comment]
Hi robwalch,

Thanks for the mediastreamvalidator tool, we are now checking all of our CDN's outputs. The url I have sent you before belongs to Wowza CDN. You can find more streams from the live platform, here: http://www.mediaklikk.hu/m1-elo/ , http://www.mediaklikk.hu/m2-elo/ , http://www.mediaklikk.hu/m4-elo/
(The player here is an older version v6.12, but it also acts like I mentioned before.)

Our other CDN's output seems flawless testing it with mediastreamvalidator, but I can see problems when I test it with bandwidth limiter tool. You can find it here: http://web12.connectmedia.hu/jw7/jw7x.html
The situation is slightly better but the sound mutes, and sometimes I can see the buffering icon on the screen during profile changing. Would you please confirm that you can see the same? Thanks!

**Comment by lomenl** [comment]
Hi robwalch,

I suppose that it is not so easy to fix this issue without deep modifications in the code which need more time, so I was thinking that maybe there is a way for us to deliver a solution to our customer.
My question: Is there any way to use special - maybe not public - parameters which can force the player to go to higher profile only if the available bitrate a bit (20%) higher than the bandwidth which indicates the profile's bandwidth?
Our customer is desperated to have a solution to eliminate this issue.
Thanks,
Waiting for your kind opinion,
Laszlo

**Comment by robwalch** [comment]
If this is still an issue in v7.10, let us know. At this point we expect that you are playing back HLS with html5/hls.js in the player (do not set "primary: flash") for over 90% of plays. Flash is only used for HLS in IE11 and lower and includes several improvements since v7.2.
