### ISSUE TITLE
Remove flash

### ISSUE THREAD

**Issue by jimmywarting** [jwplayer/jwplayer#899]
I have had enough of flash and you guys are the root cause to all the eval why all website still use flash on there webpages still till this day! 

Html5 video element is [supported in all browser](http://caniuse.com/#search=video) long time ago

Flash is only a burden. You have to maintain 2 players now... The only thing i see flash is used for today is flash banners and video streaming. So it makes since why tusens of ppl use click-to-flash to ignore all the banners and only enables them when they want to see movies. But that is not the only reason ppl block flash. Flash for Mac has a bug where CPU goes to the roof. There is a reason why there is many users has installed flash block addons. Flash also has many security issues that has needed hot-fixes. The extra flash player just brings frustation to users and extra payload in terms of size and compilation by browsers VM where non mobile browser even supports flash. Flash also drains alot battery life. You can save 1000 of man hours on building one awesome html5 player instead of maintaining 2.

One more thing that is fucking annoying is that even if the video format is supported in both html5 and flash player in my browser you still stick to the flash player by default and dosen't use flash as a fallback witch leads to this ugly frame on all websites over the web
![skarmavbild 2015-11-15 kl 02 36 03](https://cloud.githubusercontent.com/assets/1148376/11166705/ee936b54-8b41-11e5-8e5f-fbc68b601b87.png)

The built in click-to-flash dosen't cut it. It still enables javascript to detect if flash is installed so thats make it OKEY to use flash first. The `navigator.plugins["Shockwave Flash"]` shouldn't even be exposed to javascript to be a successful flash blocker to make it switch to html5 mode. That + security, performance and battery is why i have disabled flash in my browsers.

The only way to truly force the web to embrace modern open standards is to invalidate old technology.

**Comment by FloridaStream** [comment]
I'm using flash.

**Comment by jimmywarting** [comment]
@FloridaStream Why? Do you think Flash is better then html5? Dose flash has something html5 dose not?

**Comment by jimmywarting** [comment]
There is a lot of talk going on with HTTP live streaming and being adaptive to clients view size and network.
But we don't need flash to support HLS! We have [hls.js](https://github.com/dailymotion/hls.js) to cover this. But you shouldn't have to come to that point as you should provide a at least more then 1 video source to support more devices. That is what `<source>` is meant for. try the first one, if it isn't supported use the next

We have web workers and that can handle decoding a video codec that isn't supported, we shouldn't have to relay on flash to play our video as flash won't always be there for us but html5 video will!

**Comment by FloridaStream** [comment]
I'm using flash. I need it because i use a custom actionscript client-side -> client-side -> server-side -> client-side function. I cant use this in html or any javascript, only in flash client. FOR ME, flash is the unique way.

**Comment by robwalch** [comment]
Thanks. We're working on it.
