### ISSUE TITLE
jwplayer 7 & require.js

### ISSUE THREAD

**Issue by mdbrennan** [jwplayer/jwplayer#900]
I can't seem to get jwplayer 7 to work with require .js version 6 was working fine.

It seems that window.jwplayer is not set, and as a result 'ReferenceError: jwplayer is not defined' 

Creating a shim with require.js has no effect either. I can see the file physically being called, but not declaring the jwplayer variable.

When I inspect my Window cars, I have this reference 'webpackJsonpjwplayer' and that's about it.

Obviously, when I don't use require.js everything works, but unfortunately that's not an option for my project as we're trying to upgrade to jwplayer 7.

**Comment by robwalch** [comment]
See #741. This issue duplicates it.

@mdbrennan let us know if you're unable to work around the issue by setting `window.jwplayer`.
