### ISSUE TITLE
JW7 - Primary isn't working when using multiple providers

### ISSUE THREAD

**Issue by shaharmor** [jwplayer/jwplayer#901]
Hello,

I have two providers, one for flash playback and one for html5 playback.
They are named (In the provider name context) "flashp" &"html5p".

I'm trying to switch between the playback of them by using the primary property in the player config as such:
```
// registering html5p provider here
jwplayer.api.registerProvider(Html5Provider);

// load player
jwplayer('player').setup({
        playlist: [{
            file: 'link-to-stream,
            provider: 'link-to-flash-provider'
        }],
        primary: 'flashp'
    });
```

Correct me if i'm wrong, but to set the flash providers name i need to use `super('flashp');` in the providers actionscript code in the constructor right?

If thats true, then i expect that using `primary: 'flashp'` will play with the flash provider, and if i change it to `primary: 'html5p'` it will use the html5 provider. However it does not work.

When debugging and going over the listed providers here: https://github.com/jwplayer/jwplayer/blob/8779a339ecc8d527eb983ea40e6a9a90786d3d46/src/js/providers/providers.js#L9 i don't see the flash provider name, but i do see the html5 one.

If i rename the html5 provider to "html5" it overrides the default html5 playback and then if i use `primary: 'flash'` it will swap them here: https://github.com/jwplayer/jwplayer/blob/8779a339ecc8d527eb983ea40e6a9a90786d3d46/src/js/providers/providers.js#L13 and then it will work and use my flash provider, .
But obviously i don't want to override the default playback, just create an additional one.

So how can i choose between which provider to use?

**Comment by robwalch** [comment]
The "primary" option accepts only two values, "html5" (default) and "flash". These apply to jwplayer's providers. They have no affect on custom JS providers.

When you register a custom JS provider, that provider will be checked before html5 and flash. If that provider is not supported, playback will fall-through to html5 and flash (flash first if "primary" "flash" is set).

The playlist item's Flash provider will only be used if the JW Player flash provider is used. If your JS provider always reports that it can play the item, then Flash will never be selected. You need to allow you JS provider to fall-through by modifying it's `supports` method, or not register your JS provider and set "primary" to "flash".

**Comment by donato** [comment]
The name for built-in providers is set here : https://github.com/jwplayer/jwplayer/blob/8779a339ecc8d527eb983ea40e6a9a90786d3d46/src/js/providers/providers-supported.js#L28

For a newly registered provider it is set using it's getName method : https://github.com/jwplayer/jwplayer/blob/8779a339ecc8d527eb983ea40e6a9a90786d3d46/src/js/api/global-api.js#L73

Like Rob said, the "primary" toggle in JWPlayer only affects built-in html5 versus built-in flash. Any custom providers will ALWAYS have priority over the built-in providers. Priority dependent upon the order they were registered.

**Comment by robwalch** [comment]
A "hybrid" js provider that can use either technology could be ideal, but we have not developed such an example. Flash provider support remains a legacy feature we've kept around from version 6 "as-is".

What I would do is only specify the source "provider" with the "link-to-flash-provider" if you want to use Flash. Then you can modify your JavaScript provider's supports method as follows:

```
Html5Provider.supports = function(source) {
     if (!!source.provider) {
        // If a custom Flash provider is specified, do not use custom JS provider
        return false;
    }
    ...
};

// registering html5p provider here
jwplayer.api.registerProvider(Html5Provider);

// load player
jwplayer('player').setup({
        playlist: [{
            file: 'link-to-stream,
            provider: 'link-to-flash-provider'
        }],
        primary: 'flash'
    });
```

You could also use a different config property in the source if you prefer. Setting primary to "flash" means that if the custom JS provider is not used, Flash will be used and it will load your custom Flash provider.

**Comment by donato** [comment]
@shaharmor - please re-open if you have further questions
