### ISSUE TITLE
no Firefox 31 support

### ISSUE THREAD

**Issue by freshfx** [jwplayer/jwplayer#902]
JW 7 doesn't work on Firefox 31. After click on play button the loading spinner is visible and the video is never loaded. (Firefox 42 works)

Tested on Saucelabs:
Firefox 31
OS X Mavericks

Is there a way to detect the support for used browser?

**Comment by robwalch** [comment]
Please provide an example of the player setup that causes this behavior and the version of jwplayer you are using. Do you have a sample url? I'll reopen after an example with steps to reproduce are given.

**Comment by freshfx** [comment]
http://support.jwplayer.com/customer/portal/articles/1406723-basic-video-embed
even the implementation on the jwplayer support page doesn't work in Firefox 31.

I'm using the version "7.0.1+commercial_v7-0-1.39.commercial.33dee3.jwplayer.6b17f5.analytics.af35ed.vast.7e8ed7.googima.51f628.plugins.73d5ab"

**Comment by robwalch** [comment]
Firefox 31 accounts for %0.08 of global traffic according to caniuse.com and is not even an option for live testing in BrowserStack. The latest version of Firefox is 42. My recommendation would be to upgrade Firefox.

**Comment by freshfx** [comment]
+1
