### ISSUE TITLE
IE9 issue.

### ISSUE THREAD

**Issue by losywee** [jwplayer/jwplayer#906]
SCRIPT5007: Unable to get property "call" values: the object is null or undefined
polyfills.promise.js, Line 1 Character 1
SCRIPT5007: Unable to get property "call" values: the object is null or undefined
polyfills.base64.js, Line 1 Character 1

**Comment by dannyfinks** [comment]
Hi @losywee can you provide us some reproducible steps for this issue? Which player version are you currently using? JW Player 7.2.1 (current master branch) has a lot of new updates that may potentially resolve your problem.

**Comment by losywee** [comment]
@dannyfinks  Yes, currently, I had reproduced the JW Player 7.2.1. In Chrome browser, it shows right, but it wrong when I open it in IE9.0.44.

**Comment by robwalch** [comment]
@losywee can you share the url where is is happening? We use a promise polyfill for older browsers like IE9. We need to see where promises are being hit on your page to see exactly what the issue is.

**Comment by losywee** [comment]
@robwalch  Thanks, but I test it in my localhost Webserver. Ok, please wait, I will upload it to Internet.

**Comment by donato** [comment]
@losywee - are you still seeing this problem?

**Comment by losywee** [comment]
Not yet, I had replaced it by Jwplayer 6. Thanks.
