### ISSUE TITLE
Fetch and AJAX utils

### ISSUE THREAD

**Issue by robwalch** [jwplayer/jwplayer#908]
Our AJAX utils are geared toward xml loading and not well suited to loading JSON (getting better #904). We should consider using/polyfilling Fetch, and make sure the util(s) allows us to specify the type of content we're requesting to optimize response handling.

**Comment by donato** [comment]
var fetchPromise = utils.fetch('playlist.rss');
fetchPromise.then(handleRSS);

**Comment by robwalch** [comment]
#### Fetch API Streaming Response Sample (Available in Chrome 43+)
https://googlechrome.github.io/samples/fetch-api/fetch-response-stream.html
```
        fetch(url).then(function (res) {
          var contentLength = res.headers.get('Content-Length');
          var reader = res.body.getReader();
          reader.read().then(function (result) {
          if (result.done) {
            // handle complete
            return;
          }
          // handle progress
          // cancel fetch
          reader.cancel();
        })
        .catch(function (e) {
          // handle error
        });
```
XHR pseudo-streaming `xhr.addEventListener('progress', ...)` could be a fallback for text only content.

**Comment by robwalch** [comment]
Ajax refactor is complete. Fetch util could use more work but isn't required for anything at this point.
