### ISSUE TITLE
Playlist thumbnails with special characters in URL are mutated

### ISSUE THREAD

**Issue by erikdonohoo** [jwplayer/jwplayer#919]
All of our thumbnail URLs are broken because of this line...

https://github.com/jwplayer/jwplayer/blob/eacf851cafe407edcbc91d5117804ee2ff804161/src/js/view/preview.js#L24

We have urls to thumbnails in S3 that have a signature and key in them with special characters that are there by design, that `encodeUri()` destroys.  Any workaround for this?

**Comment by donato** [comment]
Can you give us an example? Which special characters?

**Comment by erikdonohoo** [comment]
A '%' symbol gets turned into '%25' even though the '%' was intentional as part of the S3 signature

**Comment by donato** [comment]
@erikdonohoo if you have a specific example we can include it in our tests, otherwise we will just be guessing what you mean.

**Comment by erikdonohoo** [comment]
Ok, for example:

`https://someurl.amazonaws.com/image.jpg?AWSAccessKeyId=SKIAJTKJN7H35T4LHI6Q&Expires=1449608325&Signature=Br6oJPAOa1Pf5ZDWv5l6DuxpOCE%3D`

becomes

`https://someurl.amazonaws.com/image.jpg?AWSAccessKeyId=SKIAJTKJN7H35T4LHI6Q&Expires=1449608325&Signature=Br6oJPAOa1Pf5ZDWv5l6DuxpOCE%253D`

**Comment by michelegera** [comment]
+1

I’m working around this by calling `decodeURIComponent` on the thumbnail URL, but I agree with @erikdonohoo that it should be my responsibility to pass a well-formed URL and the player should not make any assumptions on it.

**Comment by erikdonohoo** [comment]
@donato Any update on this?  Did you understand my example?

**Comment by donato** [comment]
@erikdonohoo @michelegera - thanks for the examples, I totally agree.

**Comment by donato** [comment]
This is targeted for jwplayer v7.3.0
