### ISSUE TITLE
Sharing close button conflict with logo link

### ISSUE THREAD

**Issue by Andries-Smit** [jwplayer/jwplayer#924]
- When have a logo with link and a sharing button.

- A user select the sharing button, and the overlay is shown.

- However the z-index of the overlay is not set. So when the logo is place over the close button of the sharing overlay.

Suggested fix; is to add

    .jw-plugin-sharing .jw-sharing-container {
        z-index: 10;
    }

**Comment by robwalch** [comment]
This duplicates #912. There is a fix in v7.2.3.
