### ISSUE TITLE
Undetected stalls in RTMP audio streams

### ISSUE THREAD

**Issue by chrisdeely** [jwplayer/jwplayer#929]
An audio-only live stream (via RTMP) does not report nor recover from stalls due to bad network conditions

Please see the example here:
http://plnkr.co/Gj9z0E

When using the network link conditioner on OSX I can cause a playing audio stream to stall and the audio playback to cease. These stalls are either not detected by the player or not surfaced via events.

```time``` events continue to fire, but the playback ```position``` remains at the last known time.

Since there is no concrete event surfaced for this condition, we cannot easily detect the stalls and attempt to reconnect or message the user.

Also, when conditions improve, the connection is often not reestablished.

**Comment by robwalch** [comment]
Hi @chrisdeely,
The example is throwing an invalid license key. Is there a particular AS3 NetStream event you're expecting?

Maybe there's a listener missing in the status handler or client object:

https://github.com/jwplayer/jwplayer/blob/master/src/flash/com/longtailvideo/jwplayer/media/RTMPMediaProvider.as#L617

https://github.com/jwplayer/jwplayer/blob/8779a339ecc8d527eb983ea40e6a9a90786d3d46/src/flash/com/longtailvideo/jwplayer/utils/NetClient.as

**Comment by chrisdeely** [comment]
I purposefully left my commercial license key out of the demo, sorry I didn't call that out in the instructions. I've updated the instructions in the plunker.

I'll review the source files you mentioned and let you know if I find anything.

**Comment by chrisdeely** [comment]
The attached change to ```RTMPMediaProvider``` sends buffer events when they occur on the ```NetStream```.

I'm wondering if the ```PlayerState``` should also be set to ```BUFFERING``` or if any other actions should be taken here?
