### ISSUE TITLE
Update README for developer.jwplayer.com landing

### ISSUE THREAD

**Issue by robwalch** [jwplayer/jwplayer#944]
Include links to http://developer.jwplayer.com and other public projects in our org that may be of interest to developers coming here from our developer portal.

**Comment by robwalch** [comment]
@donato @ganondalf @esboyd @justiniso What do you guys think? The README covers building the player, but as a landing page for developers we could link to the portal, and add more info for folks coming from the portal.

Media Services may have some resources to share too.

**Comment by justiniso** [comment]
:+1: 

The developer portal will link to Platform docs though. Maybe keep that as the hub so we won't have to update the player readme as things on the platform side change.

**Comment by robwalch** [comment]
Yep. The dev portal "github" link goes here, so some other links in the README might be helpful here if this is the "jwplayer github hub" :)

**Comment by ganondalf** [comment]
@robwalch Love this idea. Maybe we should update the readme when the updated player demo section goes live on Dec. 18th? If we want to start directing people to the developer site, I want to make sure the necessary resources are ready for developers.

**Comment by robwalch** [comment]
Let's add the link to http://developer.jwplayer.com then. That and other PRs to the README are welcome anytime.

It's good that the doc covers this project and how to build it. I'd like to see links to other public repos and a little blurb about how this is a component of our video platform and services - either in the README or the project description.

**Comment by johnBartos** [comment]
Looks like this was added already - closing
