### ISSUE TITLE
Youtube related videos are not disabled

### ISSUE THREAD

**Issue by lihaosky** [jwplayer/jwplayer#950]
Hi,

I'm try to embed a youtube video and somehow the annotations in youtube is not disabled. Below is my code:

    var playerInstance = jwplayer("myElement");
    playerInstance.setup({
        file: 'http://youtu.be/76VOFvFpF-g',
        width: '100%',
        height: '100%',
        controls: true,
        // visualplaylist: false
        abouttext: false,
        aboutlink: false,
        displaytitle: false,
        displaydescription: false,
        primary: 'html5'
    });

Also getVideoData().video_id doesn't seem to work, it always give an error

Thanks.

**Comment by lihaosky** [comment]
It's actually working. My bad...

**Comment by lihaosky** [comment]
I think that's the reason. Can you add iv_load_policy:3 or expose a flag to set it?

**Comment by lihaosky** [comment]
Also, I chose self-hosting my library, files like provider.youtube.js are still got from jwplayer website instead of my directory. Any way to configure that?

**Comment by robwalch** [comment]
@lihaosky, you can use the `base` and `flashplayer` config parameters:
```
jwplayer().setup({
    base: './jwplayer-assets/',
    flashplayer: './jwplayer-assets/jwplayer.flash.swf',
});
```

It sounds like you want to be able to pass Youtube Player configuration parameters through our player. Can you update this issue or submit a new one describing this request? https://developers.google.com/youtube/player_parameters?hl=en#iv_load_policy

**Comment by lihaosky** [comment]
Thanks. I will submit a new one describing this.
