### ISSUE TITLE
Pass youtube configurations through setup

### ISSUE THREAD

**Issue by lihaosky** [jwplayer/jwplayer#954]
Hi,

I would like to pass some youtube iframe configuration through setup like iv_load_policty. Can you expose some parameters in setup to configure that?

**Comment by lihaosky** [comment]
Also, there's no "html5:1" parameters in https://developers.google.com/youtube/player_parameters?hl=en#fs

**Comment by donato** [comment]
@lihaosky - This is an option, can you open a pull request showing how you would like this done?

**Comment by robwalch** [comment]
We are not adding additional features to Youtube playback support at this time.
