### ISSUE TITLE
Volume knob margins (top and bottom) are not even

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#962]
Volume knob is moved little bit up because there is no negative margin for it. To fix this you need to add margin-bottom: -0.3em (as on pct below)
![image](https://cloud.githubusercontent.com/assets/2443904/11867129/6ef8b700-a4af-11e5-9fa3-2ef1759cf39c.png)

Cheers

**Comment by donato** [comment]
Thanks @artur-michalak- I don't see this problem, are you hosting this somewhere that I can verify it?

**Comment by donato** [comment]
Closing until we have a hosted example.

**Comment by artur-michalak** [comment]
Hi, sorry for not giving any response - holidays :)

I just checked it again on latest version 7.2.4 with skin seven.

See attached screenshots

1. 
![image](https://cloud.githubusercontent.com/assets/2443904/12112089/7abb0ae4-b39a-11e5-83da-703045bcb750.png)

2. 
![image](https://cloud.githubusercontent.com/assets/2443904/12112094/8692d266-b39a-11e5-8b9f-67050a5938ca.png)


Basically knob is wrongly positioned. It goes to far up on track (image 1  - 100% of volume) and not enough to bottom on (0% vol -  picture 2)

To reproduce this you need to use a simplest config. I don't want to post example due to exposing of license key.
