### ISSUE TITLE
Please remove "open source" from README.md

### ISSUE THREAD

**Issue by Flimm** [jwplayer/jwplayer#967]
The top of README.md says:

> JW Player is -the- open source solution for making video playback seamless across browsers and file types. It empowers the developer to interact with video programmatically to create unique and awesome user experiences.

However, the license of JW Player is CC-BY-NC-SA, which makes it not open source, according to the OSI definition which everybody uses:

> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

This license specifically prohibits commercial use. Please remove this misleading part of the sentence from the README.md.

**Comment by robwalch** [comment]
Thanks @Flimm. This has been brought up before in #763. In order to avoid confusion about our license I'll update the readme.

**Comment by Flimm** [comment]
Excellent! Thanks.
