### ISSUE TITLE
Could add beforeSeek event please

### ISSUE THREAD

**Issue by leixu2txtek** [jwplayer/jwplayer#977]
First of all, thx to all Contributors.

in my project , we need check user permission to seek the video

but if we do sth on time event,that cause some bugs.

So i want add beforeSeek event .. However, because of the limited my ability.

So I hope that we can solve the problem together.

thx!

**Comment by robwalch** [comment]
The "seek" event is fired before a seek is performed, "seeked" is fired after the position has changed.

**Comment by leixu2txtek** [comment]
@robwalch  yeah, but  i want stop user to seek xx position ..

**Comment by robwalch** [comment]
Hi @leixu2txtek,

We're not going to add this as a feature to the player, but you can prevent seeking with custom JavaScript. What you need to do is override the seek method of your player instance:

```
var player = jwplayer('container').setup({ file: 'video.mp4'});
player.on('ready', function() {
    var seek = this.seek;
    this.seek = function(position) {
        // for this test we will only allow seeking after the first 10 seconds has played
        var seekIsAllowed = this.getPosition() > 10;
        if (seekIsAllowed) {
            seek.apply(this, [position]);
        }
    };
});
``` 

In the future I think we should consider implementing events using the web Event class where one could call `event.preventDefault()` to cancel the event. That way we wouldn't need to add a beforeSeek event, you could just cancel seek. The seek event could event be the seek event from the video tag if that event is actually cancelable.

**Comment by leixu2txtek** [comment]
@robwalch  Great...Thank you very much..

**Comment by jonhermansen** [comment]
@robwalch Your code snippet no longer works for me after upgrading to version v8.9.0, any idea why? I checked that it works on v8.8.6, so something must have changed between then.

**Comment by robwalch** [comment]
@jonhermansen we no longer allow overwritten methods on the public api to affect internals. You can get access to the private API by defining a plugin:

jwplayer().registerPlugin('seekLimit', '8.0', function(api, pluginConfig) {
    console.log('seekLimit on for player #' + api.id + ' plugin config: ' + pluginConfig);
    const playerSeek = this.seek;
    this.seek = function(position) {
        // for this test we will only allow seeking after the first 10 seconds has played
        var seekIsAllowed = this.getPosition() > pluginConfig.maxPos;
        if (seekIsAllowed) {
            playerSeek.apply(this, [position]);
        }
    };
});
jwplayer().setup({
	file: '//video',
	autostart: true,
	width: '100%',
	aspectratio: '16:9',
	plugins: {
	    seekLimit: {
                maxPos: 30
            }
	}
});

**Comment by jonhermansen** [comment]
@robwalch Totally was not expecting such a fast response, thank you very much for the support!

**Comment by robwalch** [comment]
I just provided a similar example for someone last week that disables the fullscreen button, and we were just having an internal meeting about player plugins, so good timing! Hope it works out.
