### ISSUE TITLE
on ready & idle BROKEN

### ISSUE THREAD

**Issue by sleepychild** [jwplayer/jwplayer#979]
//Object Definition
	var Projector = function(div){
		this.div = div;
		this.labelIcon = document.getElementById('uploadIcon').cloneNode();
			
		this.display = new Image();
		this.display.id = div+"_display";
		this.display.classList.add(div);
		
		this.fileInput = document.createElement("input");
		this.fileInput.setAttribute("id",this.div+"_file");
		this.fileInput.setAttribute("type","file");
		this.fileInput.setAttribute("style","display.none");
		this.fileInput.onchange = function(){
			console.log("FILE CHANGED");
		};
		
		this.label = document.createElement("label");
		this.label.setAttribute("for", this.div+"_file");
		
		this.instance = jwplayer(this.div);
		this.instance.setup({playlist:[{image:"image/"+this.div+".png",sources:[{file:"video/"+this.div+".mp4"},{file:"video/"+this.div+".webm"}]}],controls:false,width:640,height:480});
		this.instance.on("ready", function(event){
			console.log(event);
			console.log(this.instance.getContainer());
			console.log(this.instance.getState());
		});
		this.instance.on("idle", function(event){
			console.log(event);
			console.log(this.instance.getContainer());
			console.log(this.instance.getState());
		});
	};

when on ready and on idle hit nothing happens
the browser logs "Object {setupTime: 13943, type: "ready"}"

it doesn't log the idle event thus idle doesn't fire
and it doesn't log .getContainer or .getStatus thus when ready fires the player is in fact not actually ready.

both events broken

**Comment by robwalch** [comment]
Hi @sleepychild. The ready event is working as expected. There is no initial idle event. You can expect the player state to be idle initially. `getState()` returns `"idle"` on ready.

```
var player = jwplayer('container').setup({
    file: 'video.mp4'
});
player.on('ready', function(e) {
    console.log(e);                   // Object {setupTime: 174, type: "ready"}
    console.log(this.getContainer()); // <div>...</div>
    console.log(this.getState());     // idle
});
```

**Comment by sleepychild** [comment]
getContainer in on ready callback returns <div id="player"></div>... Non jwplayer initialized div tag, so any jwplayer specific actions don't work at that point. I had to window.onload {getContainer} and then & there do any fancy init I wanted to do. Could it be a browser specific issue???

**Comment by robwalch** [comment]
What version of JW Player are you using (`console.log(jwplayer.version)`)? 

Which browser(s) are you seeing this behavior on (OS, browser name, version)?

Can you provide a sample page?
