### ISSUE TITLE
primary:html5 doesn't work with multiple sources

### ISSUE THREAD

**Issue by shaharmor** [jwplayer/jwplayer#982]
```javascript
jwplayer('player').setup({
    primary: 'html5',
    playlist: [{
        sources: [{
            file: 'http://playertest.longtailvideo.com/adaptive/bbbfull/bbbfull.m3u8',
        }, {
            file: 'http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_50mb.mp4'
        }]
    }]
});
```

The above snippet plays the HLS stream using flash even though its explicitly asking for html5.
The expected result would be to play the mp4 video in html5 and skip the HLS one.

**Comment by shaharmor** [comment]
btw, `default: true` on the MP4 video doesn't help here either

**Comment by robwalch** [comment]
We prioritize first source over first provider. The first provider that can play the first source is the one that is selected, not the source that can be played in the first provider.

**Comment by robwalch** [comment]
If you want to ensure html5 playback, only include an mp4 source, unless you first verify that a videotag in the browser canplay m3u8 files. We are working on a javascript hls provider.
