### ISSUE TITLE
Allow to choose which provider will play which source explicitly

### ISSUE THREAD

**Issue by shaharmor** [jwplayer/jwplayer#983]
Something like this:

```javascript
jwplayer('player').setup({
    playlist: [{
        sources: [{
            file: 'http://playertest.longtailvideo.com/adaptive/bbbfull/bbbfull.m3u8',
            primary: 'myhlsprovider'
        }, {
            file: 'http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_50mb.mp4',
            primary: 'mymp4provider'
        }]
    }]
});
```

and if the provider can't play the source than it should automatically **skip to the next source** and not try other plugins

**Comment by robwalch** [comment]
Custom providers are given the opportunity to play media sources before flash/html5. You can add whatever properties you want to sources and filter on these within your provider. primary is used only for the prioritizing the built in html5 and flash providers.

Given your example above, your provider's "supports" method can return true when `source.primary === "myhlsprovider"`.
