### ISSUE TITLE
Autostart with related plugin

### ISSUE THREAD

**Issue by artur-michalak** [jwplayer/jwplayer#984]
With given configuraiton:

```javascript
{
[..]
"related": {"file": "http://localhost:3001/related.xml", "oncomplete": "autoplay", "autoplaytimer": 3},
"autostart": true,
}
```

Player won't autostart related video. Here is call stack
![image](https://cloud.githubusercontent.com/assets/2443904/12112310/18f627ba-b39c-11e5-82b3-b3209c219c53.png)

If i remove autostart then everything works well (except video doesn't autostart ;))

**Comment by robwalch** [comment]
Please include a sample page so we can see the complete config, related file, and debug ourselves. Seeing the middle of the call stack provides some context but not the end where the exception occurs if there is one.

Thanks!

**Comment by robwalch** [comment]
@artur-michalak 7.3.0-beta.2 is available. If this issue persists in the latest version and you can provide a sample we'll reopen the issue and might be able to address it before the release.
