### ISSUE TITLE
VTT caption time markers display in HLS stream

### ISSUE THREAD

**Issue by mattcoz** [jwplayer/jwplayer#990]
Example VTT file:

    WEBVTT
    X-TIMESTAMP-MAP=MPEGTS:000000,LOCAL:00:00:00.000
    00:00:00.000 --> 10:00:00.000
    Caption text

Should display:

    Caption text

Instead it displays:

    00:00:00.000 --> 10:00:00.000
    Caption text

This only happens with an HLS stream with embedded VTT. When the same VTT file is instead set in the tracks property, I get an Invalid SRT error even though it's VTT not SRT. When I remove the X-TIMESTAMP-MAP header, it displays correctly. But, that header is required according to the standard:

http://tools.ietf.org/html/draft-pantos-http-live-streaming-09#page-19

**Comment by robwalch** [comment]
Hi @mattcoz do you have a sample stream and player setup we can look at?

We have a few HLS streams with embedded VTT working just fine that include X-TIMESTAMP-MAP info. That header is required when the VTT is part of your HLS stream. It should not be present in side loaded VTT or VTT in text tracks. We don't support the loading and parsing of files with those headers outside of an HLS stream.

**Comment by mattcoz** [comment]
Sorry about this, apparently I didn't read the standard close enough and it requires a blank line between the header and the cue. It displays correctly after adding the blank line.

**Comment by robwalch** [comment]
Thanks for the update @mattcoz. Good to know!
