### ISSUE TITLE
unable to access file mxml-cli.jar

### ISSUE THREAD

**Issue by StriverBoy** [jwplayer/jwplayer#991]
I got an error 'unable to access file mxml-cli.jar' when build jwplayer7.2.4. In the folder 'Adobe Flash Builder 4.7\sdks\4.6.0\lib', I can see file mxml.jar Can you help me?Please!

**Comment by robwalch** [comment]
I recommend using the Adobe AIR SDK rather than FLEX library included in Flash Builder. See our [build instructions](https://github.com/jwplayer/jwplayer#build-instructions).
